### ISSUE TITLE
Zigbee radio options

### ISSUE THREAD

**Issue by gigawatts** [diyhue/diyHue#10]
Are any other zigbee radios supported? I have one of these and would love to use it with this project: https://www.tindie.com/products/Elelabs/elelabs-zigbee-raspberry-pi-shield/

I planned to use that radio to control some Ikea lamps (I don't have the Ikea gateway).

I'm willing to help test whatever to try and get this working if it's not currently supported.

**Comment by mariusmotea** [comment]
Hi,

I will take a closer look, my concern is that not all devices will work because i know Deconz is doing some workarounds in order to have IKEA remotes paired. So i'm a little afraid that with this device i will not be able to pair the IKEA remotes.

**Comment by ryancasler** [comment]
I'm using this one and it seems to work so far. https://www.amazon.com/gp/product/B01FDWOIHK/ref=oh_aui_detailpage_o01_s01?ie=UTF8&psc=1

**Comment by mariusmotea** [comment]
That is officially suported. Basically ConBee is nothing else than the Rasbee module + USB to serial adapter packed in one USB stick case. I read the api from [here](https://www.silabs.com/documents/public/user-guides/ug101-uart-gateway-protocol-reference.pdf) and to add support to this device you need to understand very well how ZigBee works.

**Comment by cheesemarathon** [comment]
Ok, I will close this then but add it to a project board as it is a bit outside of the scope of the project for now, but maybe something that can be worked on by others or in the future.

**Comment by gigawatts** [comment]
Sure, let me know if I can help test anything.
