### ISSUE TITLE
Add Virtual Bulbs for Testing and Debugging

### ISSUE THREAD

**Issue by rkkoszewski** [diyhue/diyHue#100]
It would be great if it would be possible to use a virtual bulbs for testing  the integration of diyHue with existing devices and how it all behaves (Without having to own any of the bulbs). It would also allow to quickly fire up diyHue and test or debug Hue apps without having to own the real hardware (Also useful when you're on the go and don't have the real bulbs at hand).

Is there something like this already possible with diyHue?

**Comment by arachnetech** [comment]
In case it's any use/interest, I wrote a very simple Node.js script which emulates a light while testing diyHue:
https://github.com/arachnetech/fakehue
