### ISSUE TITLE
Hue Sync not working with Yeelight

### ISSUE THREAD

**Issue by JonathanJhon55** [diyhue/diyHue#101]
So basically everything works, besides the Entertaintment thing. It shows my bulb but when doing the Test Synchronization thing the colors don't change they stay just static. 
Also when using Hue Sync PC app, it connects and then the button goes from stop to start so the service shuts down or anything. And the lights also don't change.

How to fix this? Also the debug file doesn't say anything suspicious. Actually nothing when I do --debug

**Comment by mariusmotea** [comment]
Hi,

What Yeelight bulb are you using?

**Comment by JonathanJhon55** [comment]
Hi

I am using as well the Yeelight Color Bulb V1.0 and the Yeelight Light strip. Both have the same problem.

**Comment by mariusmotea** [comment]
Probably i create an issue when i migrate the entertainment to dedicated py file. I will check it.

**Comment by JonathanJhon55** [comment]
Alright. Thanks! Looking forward for an update.

**Comment by mariusmotea** [comment]
I found the issue, i will fix it but i'm not sure today i will be able to do it. Maybe tomorrow.

**Comment by mariusmotea** [comment]
i made a very big commit to fix this. Please check this.

**Comment by mariusmotea** [comment]
Closing as no feedback. @JonathanJhon55 feel free to reopen this in case you still face problems.
