### ISSUE TITLE
Apache

### ISSUE THREAD

**Issue by Ryan911199** [diyhue/diyHue#102]
After installing Apache on a pi you are unable to access the hue emulate. 
Example:

(ip address )/hue
 
Response:

The requested URL /hue was not found on this server.

**Comment by Mevel** [comment]
Apache is blocking port 80 used by emulator web ui. You can remap the ports used by apache. See apache documentation

**Comment by mariusmotea** [comment]
Stop apache service and it will work again

**Comment by eskimos2000** [comment]
I have similar problem, installed diyHue docker image in host mode as in the manual.  But I can to see it running when I get docker stats command, and I have error when I have tried to `http://192.168.0.250/hue/linkbutton`
Error:

`Object not found!
The requested URL was not found on this server. If you entered the URL manually please check your spelling and try again.

If you think this is a server error, please contact the webmaster.

Error 404`

I have apache installed on my Arch Linux so it seems that they no go well together.

**Comment by eskimos2000** [comment]
Hmmm I have moved apache port to 8082, restarted diyHue container but it still not working, and I can not see it after docker stats, why ?

**Comment by eskimos2000** [comment]
I have checked docker container ls -a

and I see that container is exited, so it starts and stops because probably some clash with other containers, I have on that docker hassio with home assistant, sonarr, radarr, nzbget.  A bit of frustration as I am a noob and can't solve that by myself.

**Comment by cheesemarathon** [comment]
Run `docker port <container_name>` to list ports in use by each container. Make sure there are no conflicts. Also run `docker logs diyHue` and post the output here

**Comment by eskimos2000** [comment]
Hi,
Here you have logs:
`Using Host IP of 10.8.8.11
Docker Setup Initiated
Restoring Certificate
Certificate Restored
Restoring config
Config restored
Docker Setup Complete
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 303, in <module>
    bridge_config["config"]["mac"] = mac[0] + mac[1] + ":" + mac[2] + mac[3] + ":" + mac[4] + mac[5] + ":" + mac[6] + mac[7] + ":" + mac[8] + mac[9] + ":" + mac[10] + mac[11]
IndexError: string index out of range`

I have done port checks but as I can not get it to start I only see that my other containers do not have port conflicts. I have homeassistant, hassio, radarr, sonarr, nzbget only on that machine. Can they have conflicts with diyHue?
