### ISSUE TITLE
DIYHUE won't pair (with any App, incl native Hue app)

### ISSUE THREAD

**Issue by alexio70** [diyhue/diyHue#1027]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

made a fresh install of DIYhue add-on, from the add-on store. Got rid of certicates, Got the mac right and started the add-on. DIYHue can find lights (through MQTT service), pairing with any other apps is the issue

### Errorlog:

The (error) debug log file can be downloaded as instructed but the diyhue_log.TAR file can't be unzipped and in a text editor shows 0000 0000 0000 0000 (10kB)

### Steps to reproduce

installed in http and https environment with and without no_serve_https; Rebooted home assistant several times; made sure got the date/time right to Europe/Amsterdam. started the app after cert. delete and got the mac address right; leave the default port settings

### Please enter your operating system details here

OS: Linux
Architecture: x86_64
os_version: '#1 SMP PREEMPT_DYNAMIC Tue Jun 18 13:51:59 UTC 2024'
os_release: 6.6.33-haos
Hue-Emulator Version: '2024-07-17 19:34:15.000000000'
WebUI Version: '2024-07-17 19:38:54.000000000'

### Upload debug tar

```
This can be downloaded from the webUI.
DiyHue > Bridge > Brdige Control > Download debug > Full debug
Do not upload from Force config dump, Force config dump contains sensitive information
``
[config_debug.tar.zip](https://github.com/user-attachments/files/16273004/config_debug.tar.zip)


### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
Hi, Can you provide log via the normal way? In HA this can be found on the diyhue addon page on the top right.

**Comment by alexio70** [comment]
Yes it is possible but the actual history has disappeared. It seems rather useless maybe if I can't capture the "pairing issue"? I will try to replicate and see what can be found...

**Comment by alexio70** [comment]
2024-07-18 08:45:22,413 - werkzeug - INFO - 192.168.2.6 - - [18/Jul/2024 08:45:22] "GET /api/01ef27b0446611ef8db7021132240a60/config HTTP/1.1" 200 -
2024-07-18 08:45:22,432 - flaskUI.restful - DEBUG - [{'success': {'/config/linkbutton': {'lastlinkbuttonpushed': 1721285122}}}]
2024-07-18 08:45:22,443 - configManager.configHandler - DEBUG - Dump config file /config/diyhue/config.yaml
2024-07-18 08:45:22,445 - werkzeug - INFO - 192.168.2.6 - - [18/Jul/2024 08:45:22] "PUT /api/01ef27b0446611ef8db7021132240a60/config HTTP/1.1" 200 -
2024-07-18 08:45:22,462 - services.ssdp - DEBUG - Sending M-Search response to 192.168.2.47
2024-07-18 08:45:22,775 - werkzeug - INFO - 192.168.2.6 - - [18/Jul/2024 08:45:22] "GET /api/01ef27b0446611ef8db7021132240a60/config/swupdate2 HTTP/1.1" 200 -
2024-07-18 08:45:22,779 - werkzeug - INFO - 192.168.2.6 - - [18/Jul/2024 08:45:22] "GET /api/01ef27b0446611ef8db7021132240a60/groups/0 HTTP/1.1" 200 -
2024-07-18 08:45:23,156 - services.mqtt - DEBUG - MQTT: got state message on zigbee2mqtt/Aqara plug 3
2024-07-18 08:45:23,157 - services.mqtt - DEBUG - b'{"auto_off":false,"button_lock":null,"consumer_connected":null,"current":null,"device_temperature":27,"elapsed":5090,"energy":419.06,"led_disabled_night":false,"linkquality":108,"overload_protection":2299,"power":0,"power_outage_memory":null,"state":"OFF","update":{"installed_version":41,"latest_version":32,"state":"idle"},"update_available":null,"voltage":null}'
2024-07-18 08:45:23,157 - services.mqtt - DEBUG - Device not found for Aqara plug 3
2024-07-18 08:45:23,157 - services.mqtt - DEBUG - MQTT: got state message on zigbee2mqtt/Aqara plug 3
2024-07-18 08:45:23,158 - services.mqtt - DEBUG - {
    "auto_off": false,
    "button_lock": null,
    "consumer_connected": null,
    "current": null,
    "device_temperature": 27,
    "elapsed": 5090,
    "energy": 419.06,
    "led_disabled_night": false,
    "linkquality": 108,
    "overload_protection": 2299,
    "power": 0,
    "power_outage_memory": null,
    "state": "OFF",
    "update": {
        "installed_version": 41,
        "latest_version": 32,
        "state": "idle"
    },
    "update_available": null,
    "voltage": null
}
2024-07-18 08:45:23,565 - services.ssdp - DEBUG - Sending M-Search response to 192.168.2.47

**Comment by alexio70** [comment]
> Hi, Can you provide log via the normal way? In HA this can be found on the diyhue addon page on the top right.

Thanks for your help

**Comment by hendriksen-mark** [comment]
I dont see anything wrong in the logs, you can use portainer to see the full log. Via the webui in diyhue>bridge>bridge control>show advanced config>restart python you can restart the python code so you can monitor the log from the start with portainer. In the hue app, does the app find the bridge? And does the app give a prompt to push the link button?

**Comment by alexio70** [comment]
In the native HUE App the bridge is found and indicating the prompt to push the link button. I followed your instruction to restart python and captured the log from the Add-on log tab (for as much as possible) while pressing the link button again. How to use portioner is a unclear to me; I am not using a docker container but the HA Add-on instead.
[2024-07-18 10:35:24,783 - services.mqtt - DEBUG -.zip](https://github.com/user-attachments/files/16280311/2024-07-18.10.35.24.783.-.services.mqtt.-.DEBUG.-.zip)

**Comment by alexio70** [comment]
your help is much appreciated (I heavily rely on this to get it working)

**Comment by hendriksen-mark** [comment]
Ha addon is running in a docker container.

**Comment by alexio70** [comment]
I see; how can I apply portainer to capture the full log?
![IMG_61D047C8187F-1](https://github.com/user-attachments/assets/46b2d4f2-9d04-46d3-b291-e59d07b2f0e9)

**Comment by alexio70** [comment]
To my great surprise the Hue Essentials App has now linked to my DiY HUE

**Comment by alexio70** [comment]
and immediately gave a disconnect, error on my Mobile device (that I could not capture) and crashed the App.

**Comment by hendriksen-mark** [comment]
can you check the https certificate as described [here](https://diyhue.readthedocs.io/en/latest/AddFuncts/debug.html#https-certificate-check)?

**Comment by alexio70** [comment]
For 127.0.0.1 should I use the IP of the host? 

*   Trying 127.0.0.1:443...
* connect to 127.0.0.1 port 443 from 127.0.0.1 port 46320 failed: Connection refused
* Failed to connect to 127.0.0.1 port 443 after 0 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to 127.0.0.1 port 443 after 0 ms: Couldn't connect to server
➜  ~

**Comment by hendriksen-mark** [comment]
this is [portainer](https://community.home-assistant.io/t/home-assistant-community-add-on-portainer/68836)

**Comment by hendriksen-mark** [comment]
yes replace 127.0.0.1 with your bridge IP

**Comment by alexio70** [comment]
> yes replace 127.0.0.1 with your bridge IP

*   Trying 192.168.2.33:443...
* connect to 192.168.2.33 port 443 from 192.168.2.33 port 59446 failed: Connection refused
* Failed to connect to 192.168.2.33 port 443 after 0 ms: Couldn't connect to server
* Closing connection
curl: (7) Failed to connect to 192.168.2.33 port 443 after 0 ms: Couldn't connect to server
➜  ~

**Comment by hendriksen-mark** [comment]
That is not good,
How do you run HA? Via HAOS or as a docker container?

**Comment by alexio70** [comment]
HAOS on VM (SynologyNas)

**Comment by hendriksen-mark** [comment]
If you go to https://192.168.2.33 what do you get? This is httpS not http.

**Comment by alexio70** [comment]
my Home assistant instance (with a security warning) I am using DuckDNS with port forwarding 443 & 8123

**Comment by hendriksen-mark** [comment]
That is the problem, port 80 and 443 are used bij hue and can not use a different port, so http and https need to return the webui of diyhue

**Comment by alexio70** [comment]
meaning that DiY Hue can't run in https environment if DuckDNS is port forwarding 443?
should I simply use another port for DuckDNS or alternatively I can run DIYHue on a dedicated RPi4 in http but I face the same issues (maybe because of port 443 being forwarded from any IP to my HAOS instance)?

**Comment by alexio70** [comment]
Thanks, it's clearly a port forwarding issue rather than a DiYhue issue; I will try to resolve and get back to you with the results ;-)

**Comment by alexio70** [comment]
seems we have found the root cause ;-)

**Comment by antoniozh** [comment]
You can run diyhue behind a reverse proxy. It worked for my NAS

**Comment by alexio70** [comment]
> You can run diyhue behind a reverse proxy. It worked for my NAS

Would you mind sharing the details of that reverse proxy to me?

**Comment by hendriksen-mark** [comment]
yes it can work but how to setup reverse proxy with duckdns i dont know, the hue app looks at port 80 and 443, if those ports cant be reach or does not return the right stuff it wont work.

**Comment by alexio70** [comment]
> yes it can work but how to setup reverse proxy with duckdns i dont know, the hue app looks at port 80 and 443, if those ports cant be reach or does not return the right stuff it wont work.

in the DIYhue config there is adoption to alter the ports. is it possible to change port 443 specifically?

**Comment by hendriksen-mark** [comment]
in HA you can do it in the addon config page of diyhue.

**Comment by antoniozh** [comment]
```
upstream hue {
        server 127.0.0.1:2000;
}

server {
        listen 80;
        listen 443 ssl;

        server_name 192.168.1.2 diyhue.local;
        # allow anyone in 192.168.1.0/24
        allow   192.168.1.0/24;
        # drop rest of the world
        deny    all;
        ssl_certificate /apps/docker/diyhue/cert.pem;
        ssl_certificate_key /apps/docker/diyhue/cert.pem;
        location / {
          proxy_set_header    X-Forwarded-By       $server_addr:$server_port;
          proxy_set_header    X-Forwarded-For      $remote_addr;
          proxy_set_header    X-Forwarded-Proto    $scheme;
          proxy_set_header    Host                 $host;
          proxy_set_header    X-Real-IP            $remote_addr;
          proxy_pass https://hue;       
        }
}
```

Change the upstream as needed

**Comment by alexio70** [comment]
> ```
> upstream hue {
>         server 127.0.0.1:2000;
> }
> 
> server {
>         listen 80;
>         listen 443 ssl;
> 
>         server_name 192.168.1.2 diyhue.local;
>         # allow anyone in 192.168.1.0/24
>         allow   192.168.1.0/24;
>         # drop rest of the world
>         deny    all;
>         ssl_certificate /apps/docker/diyhue/cert.pem;
>         ssl_certificate_key /apps/docker/diyhue/cert.pem;
>         location / {
>           proxy_set_header    X-Forwarded-By       $server_addr:$server_port;
>           proxy_set_header    X-Forwarded-For      $remote_addr;
>           proxy_set_header    X-Forwarded-Proto    $scheme;
>           proxy_set_header    Host                 $host;
>           proxy_set_header    X-Real-IP            $remote_addr;
>           proxy_pass https://hue;       
>         }
> }
> ```
> 
> Change the variables such as server_name, upstream and cert location as needed

and where would you put such a code?

**Comment by antoniozh** [comment]
Set up nginx, let nginx handle your HTTP/HTTPs ports and insert this config to funnel the diyhue requests

**Comment by alexio70** [comment]
> in HA you can do it in the addon config page of diyhue.

Setting another port didn't work and DiYhue is now running on a dedicated RPI4, with HA OS add on. No pairing though!! Although No duckDNS anymore and the certificate seem allright: 

[core-ssh ~]$ curl https://192.168.2.38/api/nouser/config -v -k
*   Trying 192.168.2.38:443...
* Connected to 192.168.2.38 (192.168.2.38) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / prime256v1 / id-ecPublicKey
* ALPN: server did not agree on a protocol. Uses default.
* Server certificate:
*  subject: C=NL; O=Philips Hue; CN=e45f01fffe0e5c44
*  start date: Jul 23 16:40:54 2024 GMT
*  expire date: Jul 23 16:40:54 2045 GMT
*  issuer: C=NL; O=Philips Hue; CN=e45f01fffe0e5c44
*  SSL certificate verify result: self-signed certificate (18), continuing anyway.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA256
* using HTTP/1.x
> GET /api/nouser/config HTTP/1.1
> Host: 192.168.2.38
> User-Agent: curl/8.5.0
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/1.1 200 OK
< Content-Type: application/json
< Content-Length: 252
< Access-Control-Allow-Origin: *
< Server: Werkzeug/2.0.3 Python/3.8.6
< Date: Tue, 23 Jul 2024 17:13:00 GMT
< 
{"name": "DiyHue Bridge", "datastoreversion": "126", "swversion": "1965111030", "apiversion": "1.65.0", "mac": "e4:5f:01:0e:5c:44", "bridgeid": "E45F01FFFE0E5C44", "factorynew": false, "replacesbridgeid": null, "modelid": "BSB002", "starterkitid": ""}
* Connection #0 to host 192.168.2.38 left intact
[core-ssh ~]$ 
 *1  [bash]                                                                                                                                                                                                                        Tue 07-23 19:20

Seems to me that the CN value of the certificate = the same as the bridgeid key from the json output AND also represent the mac address of the main interface with fffe in the middle.

HELP :-)

**Comment by alexio70** [comment]
> good luck, if you want to talk in dutch you can also find me on slack.

Hallo Mark, couldn't find you on Slack. Mvg Alexio Bowie

**Comment by hendriksen-mark** [comment]
Oke strange, how did you install HAOS? Via the respberry pi imager? And diyhue with the repository url from github? And before you press run you changed the mac adress?
I will make a test setup with HAOS like above and see if i can pair.

On slack you can find me on almost every thread.
If you are on the wright slack channel. https://diyhue.slack.com/
On that name i also can not find you on slack.

**Comment by hendriksen-mark** [comment]
Also do you have a original philips hue bridge on your network? If so this will also couse problems, try turning off the original bridge and pair again.

**Comment by alexio70** [comment]
> Oke strange, how did you install HAOS? Via the respberry pi imager? And diyhue with the repository url from github? And before you press run you changed the mac adress? I will make a test setup with HAOS like above and see if i can pair.
> 
> On slack you can find me on almost every thread. If you are on the wright slack channel. https://diyhue.slack.com/ On that name i also can not find you on slack.
> 
> > **[Slack](https://diyhue.slack.com/)**

Indeed installed HAOS via Raspberry imager and DIYhue through Add-on store; check the MAC address and changed this; first tried a different port than 443 (didn't work), changed it to 443, rebooted, configured the lights in diyhue.local (with MQTT broker), and they appear nicely... than tried to link the HUE App (didn't work), verified that HUE Esssentials had the same issue (with was the case/ didn't link either);

Unfortunately I do not have an original bridge

**Comment by alexio70** [comment]
Mark, My DiYhue addon shows a 2 hour offset in my log. 2024-07-24 08:22:05,241 - werkzeug - INFO - 192.168.2.6 - - [24/Jul/2024 08:22:05] "GET /api/87aa9d52491211efadb9e45f010e5c44/groups/0 HTTP/1.1" 200 -
[s6-finish] sending all processes the TERM signal.

Maybe this can cause the issue

Alexio

**Comment by alexio70** [comment]
After Debug logging disabled, it moves 2 hour
2024-07-24 10:24:35,944 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2024-07-24 10:24:35,953 - configManager.argumentHandler - INFO - Debug logging disabled!
2024-07-24 08:24:37,085 - configManager.configHandler - INFO - Config loaded
2024-07-24 08:24:37,612 - services.updateManager - INFO - no swversion number update from Philips

**Comment by alexio70** [comment]
Bridge config in DiYhue.local is (and was) set to CET - which should be correct

**Comment by hendriksen-mark** [comment]
I did some tests and found some things that is not good.
1 of those thins is on the webui the local time is not representing the local time that the bridge have.
The date/time in the log is the local time that diyhue is set to, so if that is not good please change your time zone setting.
I suggest that you pick your timezone with region/county.
If there is a time differential of 2 hours with the bridge and the phone running the app then it will not pair.

I will change the webui local time on the next release.

**Comment by alexio70** [comment]
> I did some tests and found some things that is not good. 1 of those thins is on the webui the local time is not representing the local time that the bridge have. The date/time in the log is the local time that diyhue is set to, so if that is not good please change your time zone setting. I suggest that you pick your timezone with region/county. If there is a time differential of 2 hours with the bridge and the phone running the app then it will not pair.
> 
> I will change the webui local time on the next release.

My Web UI has CET as local time (same as my Phone) - and still give the 2 hour difference
Until the fix is there can you advise on tweaking the web UI setting to get in sync with the Phone?

**Comment by alexio70** [comment]
@hendriksen-mark Tried to tweak the system by setting my iPhone to the altered time (with -2 hour difference to CET), kept Web UI in CET, that did not do the trick...

2024-07-25 13:04:19,634 - flaskUI.restful - INFO - {'devicetype': 'Hue#iPhone', 'generateclientkey': True}
2024-07-25 13:04:19,638 - werkzeug - INFO - 192.168.2.11 - - [25/Jul/2024 13:04:19] "POST /api HTTP/1.1" 200 -

No linking either

**Comment by alexio70** [comment]
@hendriksen-mark pairing is allowed for 30 seconds, so I tried 10-15 seconds before searching the bridge as well as after the bridge was found; alternatively also tried to set my iPhone time 2 hours ahead in time, just to make sure it links; but it doesn't. Do you have more suggestions please how to get it working? Hartelijk dank!!

**Comment by alexio70** [comment]
in the add-on Log I can't find the notification of Link button press, I keep refreshing forever (after Link button is pressed). The config_debug.tar file doesn't present any readable data after unzipping it gives me all the .yaml but one thing interesting is that config_debug.yaml shows:

bridgeid: E45F01FFFE0E5C44
localtime: '2024-07-24T08:43:18'

**Comment by alexio70** [comment]
ps: unzipping diyhue_log.tar doesn't work (so the UI log is my only resource, excluding history and 1 page only displayed)

**Comment by hendriksen-mark** [comment]
No logs in HA are different then docker and host spript, i found the issue and in the next release it wil be fixt.

**Comment by hendriksen-mark** [comment]
The problem was that the time zone was not set to the wright setting.
Also the local time on the webui did not represent the diyhue time but the browser time, this is fixed now.
If encountering this problem please set to region/country and try again and check the local time on the webui to the real time.
