### ISSUE TITLE
Link device not working anymore

### ISSUE THREAD

**Issue by pluypen** [diyhue/diyHue#103]
A couple of days ago I setup my raspberry pi 3 to work as a Hue-emulator. Got it to link with my phone Hue app and all. I connected some lights to it and was able to control them without issue.

Then I wanted to controll the lights via the windows Hue entertainment app. I tried connecting the Hue-emulator to. It found the bridge but I could not connect it because the app did not see the pushlink-button being pushed while I did do this via the web-app. I went to: Link device
Then pressed: activate
The app could not connect to the bridge. It just timed out.

I restarted the raspberry and the lights. Tried again but the app could't see the pushlink being activated.

Then I went to the Hue app on my phone and deleted the Hue-emulator bridge
Let the app search for a new bridge. I found one and I tried to connect to it again. This time however, the app too, did not see the pushlink button being pushed.

I uninstalled the Hue-emulator service from the raspberry. As I had used the host installation I used this command:
_curl -s https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_uninstall.sh | sudo bash /dev/stdin_ 

After that I checked that the /opt/hue-emulator folder had been removed.

Then, just to check, I let the Hue app on my phone search again for a bridge. It didn't find one as expected.

I installed diyHue again using:
_curl -s https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_install.sh | sudo bash /dev/stdin_

I let the phone app search for a new bridge. It found one again but when I tried connecting, it did not see the link button being pushed.

What am I doing wrong here?

**Comment by mariusmotea** [comment]
On installation there is a certificate generation process. This certificate is cached by the hue app and the only way to remove it is to reinstall/wipe Hue app data. When you reinstall hue emulator a new certificate was generated but hue app know is not legit certificate because it compare it with previews one. Raspberry pi 3 has one wired interfaces and one wifi. Ensure you connect just one. I recommend the wired one for stable operation, the wifi has very poor performance even on 5Ghz frequency.

**Comment by pluypen** [comment]
Ok, I wanted to run diyHue on a raspberry pi 2 I had laying around anyway so I installed diyHue on it. Connected it to the hue app on my phone without issue. 
Connected some lamps
Rebooted the raspberry pi 2
Made an entertainment room
Setup the lights for the entertainment room. All seems to work great
Then I went to my Win 10 pc on which I have Phillips Hue Sync installed
Let the Hue Sync app search for a new bridge. It found one
Tried connecting it
Pressing the activate button in the web-ui for diyHue was not seen by the Hue Sync app. That did work just minutes ago with the Hue phone app.

What am I doing wrong here?

**Comment by mariusmotea** [comment]
Hue Sync don't pair if hue entertainment protocol was started by an app like Hue app and it did not stop it. Try to pair Hue Sync right after a new restart of your pi 2

**Comment by pluypen** [comment]
That didn't work I'm affraid.

What I did was:

1. On my phone Hue app, switched to my original Hue bridge so it had no connection to the diyHue bridge
2. Rebooted my raspberry pi 2
3. Launched Hue Sync once the pi 2 had rebooted
4. Let Hue Sync look for a new bridge. It found one
5. Told Hue Sync to connect to it. It tells me to press the pushlink button
6. Went to the ip-adress of my pi2 in a browser.
7. Clicked on Link device
8. Log in using user: Hue and password: Hue
9. Press: Activate
10. Hue Sync just times out.

**Comment by pluypen** [comment]
Ah, found out there is a debug mode. 

As soon as I click on: link device and login using user: Hue and password Hue, the Linkbutton page appears.  In the terminal I get this error at that exact time:

`Exception happened during processing of request from ('192.168.178.75', 40700)
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 424, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 390, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
192.168.178.75 - - [03/Mar/2019 22:47:23] "GET /hue/linkbutton HTTP/1.1" 200 -
`


Any idea what causes this error?
