### ISSUE TITLE
KeyError: "`GroupedLight.owner` of type `<class 'aiohue.v2.models.resource.ResourceIdentifier'>` is required."

### ISSUE THREAD

**Issue by Ro4cHii** [diyhue/diyHue#1032]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

Hello all,

today in the morning I noticed that my hue lights stopped working. 
I updated diyHue to the newest version in hopes it would solve the problem but unfortunately it didn't.
The error remains the same after updating diyHue, deleting the Hue integration and readding diyHue bridge in HA.
I use watchtower to automatically update my HA docker container. Since 2024.7.4 has been released yesterday, it might be related to the update.

```
Logger: homeassistant.components.hue.bridge
Quelle: components/hue/bridge.py:78
Integration: Philips Hue (Dokumentation, Probleme)
Erstmals aufgetreten: 14:14:01 (1 Vorkommnisse)
Zuletzt protokolliert: 14:14:01

Unknown error connecting to Hue bridge
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 78, in async_initialize_bridge
    await self.api.initialize()
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/__init__.py", line 108, in initialize
    await self.fetch_full_state()
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/__init__.py", line 252, in fetch_full_state
    await asyncio.gather(
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 336, in initialize
    await resource_control.initialize(initial_data)
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 80, in initialize
    await self._handle_event(EventType.RESOURCE_ADDED, item)
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 209, in _handle_event
    raise exc
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohue/util.py", line 244, in dataclass_from_dict
    field.name: _parse_value(
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohue/util.py", line 202, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`GroupedLight.owner` of type `<class 'aiohue.v2.models.resource.ResourceIdentifier'>` is required."
```

### Errorlog:

[diyhue.log](https://github.com/user-attachments/files/16441854/diyhue.log)

### Steps to reproduce

Add diyHue bridge in the philips hue integration.

### Please enter your operating system details here

Hue-Emulator Version: 2024-07-29 08:12:08.000000000 +0200
WebUI Version: 2024-07-27 21:16:38.000000000 +0200
Architecture: aarch64
OS: Linux
Linux version: #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023
Linux release: 6.1.21-v8+
Hardware: %Hardware%

### Upload debug tar

[config_debug.zip](https://github.com/user-attachments/files/16441884/config_debug.zip)

### What DiyHue version(branch) are you using?

master (latest)

**Comment by ummetcivi** [comment]
Same for me. It started after latest Homeassistant update

**Comment by hendriksen-mark** [comment]
update of home assistant or diyhue addon?

**Comment by ummetcivi** [comment]
Docker image of Homeassistant updated, I'm not sure if Hue addon or Homeassistant updated.

**Comment by Ro4cHii** [comment]
> Hi your `groups.yaml` file is empty. Also you have debug logging disabled, to enable this you have to go to the config page of diyhue in HA and flip the debug switch. I have no experience with `aiohue`. All the logs in diyhue looks good, only `tasmota` is unreachable. If you had groups configured you can look in the backup folder for the previous `groups.yaml` maybe that contains the previous info.

As far as I know, I have never configured any groups. I use diyHue only for connecting my DIY lights (and original Hue lights via official hue bridge) to Home Assistant.

Im regards to `aiohue`: I don't even know what that is to be honest.

In regards to debug logging: I'll have to check tomorrow if I can switch it on and receive any more information out of it.

**Comment by hendriksen-mark** [comment]
the logs you show in the description are not from diyhue but from aiohue.
the log from diyhue are in the file and on the addon page of diyhue.

**Comment by hendriksen-mark** [comment]
found some interesting things about this.
please take a look an this.
https://github.com/home-assistant/core/issues/66900
https://www.home-assistant.io/integrations/hue#lights-for-hue-zones-and-rooms

**Comment by Ro4cHii** [comment]
As said, I have no idea what aiohue is.
This is the error message that Home Assistant shows me when I try to add the diyHue bridge in the HA hue integration.

**Comment by hendriksen-mark** [comment]
aiohue is used to connect to philips hue, is a component of HA.

**Comment by Ro4cHii** [comment]
> found some interesting things about this. please take a look an this. [home-assistant/core#66900](https://github.com/home-assistant/core/issues/66900) https://www.home-assistant.io/integrations/hue#lights-for-hue-zones-and-rooms
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/65efc35b57ba1c9628f13e06c8795d8367d749f1000c6d1b8209715a9c11158d/68747470733a2f2f7777772e686f6d652d617373697374616e742e696f2f696d616765732f64656661756c742d736f6369616c2e706e67"><img alt="" height="14" src="/images/favicon-192x192.png"> Home Assistant**[Philips Hue](https://www.home-assistant.io/integrations/hue/)**Instructions on setting up Philips Hue within Home Assistant.

I may have grouped some of my original hue lights in groups and zones back when I have not been using Home Assistant yet.
My diyHue lights however have never been grouped or anything.

**Comment by macfly92** [comment]
Hi,
Same here after a HA docker upgrade to 2024.7.4.
I'm using groups and my groups.yaml isn't empty.

**Comment by hendriksen-mark** [comment]
I have to look into this, this takes some time because i need to see if i can replicate this issue and see what aiohue is missing.

**Comment by hendriksen-mark** [comment]
It has something to do with this.
https://github.com/home-assistant-libs/aiohue/commit/eff93f31ba3f6f3c9830082c4077de64499f3972

**Comment by hendriksen-mark** [comment]
I think I know what to do, whem im home I will make the changes.

**Comment by macfly92** [comment]
thanks a lot to have a look into this !

**Comment by hendriksen-mark** [comment]
it should be fixed now.
Please check if everything works and give feedback.

**Comment by ummetcivi** [comment]
It works, thanks!

**Comment by hendriksen-mark** [comment]
thank you for the fast feedback.
if @Ro4cHii with his empty groups.yaml also does not have the error this issue can be closed.

**Comment by Ro4cHii** [comment]
Sorry, I didn't understand before that you were talking about Home Assistant groups.
Indeed, I have one entry in my groups.yaml but it is completely unrelated to diyhue.

The fix is also working for me. Thank you so much for fixing it so quickly!

Feel free to close the issue. In case you want me to test it with a completely empty groups.yaml first to be sure, I can do it, but only sometime on Sunday. Just let me know.

Cheers!

**Comment by hendriksen-mark** [comment]
the groups.yaml i was talking about is the one from diyhue, so if you have rooms/zones in the hue app it will be in there.
if HA also have a groups.yaml this is separate from the diyhue one.

**Comment by Ro4cHii** [comment]
Okay I see, sorry for the confusion.
Indeed, I don't have any groups in diyhue. So it's also working in this scenario.

Thanks again! :)

**Comment by macfly92** [comment]
Same here, works like a charm. Merci beaucoup !

**Comment by csprocket777** [comment]
I’m confused. I’m running into this right now. What was the solution?

**Comment by hendriksen-mark** [comment]
Hi, what version of diyhue are running?

**Comment by csprocket777** [comment]
I just recently installed it at the beginning of August.

**Comment by hendriksen-mark** [comment]
When im home i will check this, can you share the logs from HA and the config_debuf.tar from diyhue

**Comment by csprocket777** [comment]
I'm not sure how to get at the `config_debuf.tar` file from diyhue, I'm running it in a container using portainer.

Here is the contents of the log from HomeAssistant for this:
```
Logger: homeassistant.components.hue.bridge
Source: components/hue/bridge.py:78
integration: Philips Hue (documentation, issues)
First occurred: August 27, 2024 at 8:35:20 PM (2 occurrences)
Last logged: August 27, 2024 at 8:35:20 PM

Unknown error connecting to Hue bridge
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hue/bridge.py", line 78, in async_initialize_bridge
    await self.api.initialize()
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/__init__.py", line 108, in initialize
    await self.fetch_full_state()
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/__init__.py", line 252, in fetch_full_state
    await asyncio.gather(
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 336, in initialize
    await resource_control.initialize(initial_data)
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 80, in initialize
    await self._handle_event(EventType.RESOURCE_ADDED, item)
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 209, in _handle_event
    raise exc
  File "/usr/local/lib/python3.12/site-packages/aiohue/v2/controllers/base.py", line 200, in _handle_event
    cur_item = self._items[item_id] = dataclass_from_dict(
                                      ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohue/util.py", line 244, in dataclass_from_dict
    field.name: _parse_value(
                ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohue/util.py", line 202, in _parse_value
    raise KeyError(f"`{name}` of type `{value_type}` is required.")
KeyError: "`GroupedLight.owner` of type `<class 'aiohue.v2.models.resource.ResourceIdentifier'>` is required."
```

**Comment by hendriksen-mark** [comment]
You can find the config_debuf.tar on the webui of diyhue under diyhue>bridge>bridge control>full debug

**Comment by csprocket777** [comment]
[config_debug.zip](https://github.com/user-attachments/files/16785699/config_debug.zip)

Had to recompress it to zip because github doesn't like tar files.

**Comment by hendriksen-mark** [comment]
you do not have the latest diyhue version, your version is from `2024-07-29` and the newest is from `2024-08-16`
the fix for this in implemented in the version of `2024-08-10`
please update/rebuild diyhue in HA

**Comment by csprocket777** [comment]
I'm confused. I'm not running DiyHue inside of Home Assistant. I have a standalone instance of the DiyHue hub running in portainer and a separate standalone instance of HomeAssistant running along side it in portainer. I just recreated the HomeAssistant instance, re-pulling the image just last night.

**Comment by csprocket777** [comment]
Ahhh I see. I just recreated (re-pulling) the container for DiyHue and it magically worked. :) Thanks.

**Comment by hendriksen-mark** [comment]
ow sorry then i misinterpreting that part of HA.
still you have a old version of diyhue and need to update diyhue

**Comment by jaspervanisterdael** [comment]
I'm running version 2.0.15. The problem still occurs at my side when I add entertainment area's to the DiyHue hub.

**Comment by hendriksen-mark** [comment]
Hi, i will test this when im home. The hue apiv2 does not specify a owner for the entertainment groups. If you add this to the groups.yaml it will not be used because it is not needed. Also if you add it and then restart with save it is overwritten. If you want to edit the config files shutdown diyhue and then edit the files and start diyhue

**Comment by hendriksen-mark** [comment]
I made a update, please update and give feedback

**Comment by jaspervanisterdael** [comment]
After updating and rebuilding, it is now working. Thank you for the quick fix.
