### ISSUE TITLE
Support for LCG002

### ISSUE THREAD

**Issue by ummetcivi** [diyhue/diyHue#1033]
### Feature does not already exist?

I searched and did not find an existing feature request

### Summarize feature

Hey all,

I have Philips GU10 Color lights.  In Zigbee2MQTT it's identified as LCG002. But I can't find LCG002 in diyHue.

Is it possible to add support?

Thanks.
![Ekran görüntüsü 2024-07-31 203552](https://github.com/user-attachments/assets/c99f0ee1-7488-4763-9bf2-1a8ad3c8a18a)

**Comment by hendriksen-mark** [comment]
Hi, not all the hue lights are included, this is because there are allot of different lights.
What you need to do is chose 1 of the provided light types that have the same capabilities as your light.
This list is not on the readthedocs yet but this is the list.
```
* LCT001 Hue Color Bulb #1
    capabilities: on, bri, hue, sat, xy, ct
* LCT015 Hue Color Bulb #2
    capabilities: on, bri, hue, sat, xy, ct
* LST002 Hue Lightstrip Plus
    capabilities: on, bri, hue, sat, xy, ct
* LCA005 Hue White and Color Ambiance A19 800 Lumen
    capabilities: on, bri, hue, sat, xy, ct
* LWB010 Dimmable Hue Bulb
    capabilities: on, bri
* LTW001 Controlt Temp Hue Bulb
    capabilities: on, bri, ct
* LCX002 Hue Gradient TV Lightstrip
    capabilities: on, bri, hue, sat, xy, ct
* 915005987201 Hue Signe Gradient
    capabilities: on, bri, hue, sat, xy, ct
* LCX004 Hue Gradient Lightstrip
    capabilities: on, bri, hue, sat, xy, ct
* LCX006 Hue Play Lightstrip
    capabilities: on, bri, hue, sat, xy, ct
* LOM001 Hue Plug
    capabilities: on
* LOM004 Hue Plug
    capabilities: on
* LOM010 Hue Plug
    capabilities: on
```

**Comment by ummetcivi** [comment]
Hey Mark, 

Thank you for quick reply, I tried LCA005 and it works as expected. 

Not related to this topic but some weird stuff happening with areas. I have one room, 6 lights. I divided the room into two areas. When I turn off one area, the other area is shown off as well (other way around as well).  Is it a known issue?

**Comment by hendriksen-mark** [comment]
How do you divide a room into areas?

**Comment by ummetcivi** [comment]
Sorry, zones not areas.
![IMG_1740](https://github.com/user-attachments/assets/cb398a37-298f-4083-bb23-39425c26c994)

**Comment by hendriksen-mark** [comment]
If you do this and restart the app is the on status still not good?
It can happen that the app does not register all the changes in diyhue.
On start up the app looks at the state of the bridge.
If the app is open it looks for eventstreams, if the eventstream is not there or is not what the app expects then it will not register properly.

**Comment by ummetcivi** [comment]
When I restart, it's still the same. It's not only app tho, 

I tried it in the diyHue UI and it's the same.

**Comment by hendriksen-mark** [comment]
can you provide the config_debug.tar from the webui?
with my setup i dont see this behavior.

**Comment by ummetcivi** [comment]
Sure, there you go. 
[config_debug_2.zip](https://github.com/user-attachments/files/16446074/config_debug_2.zip)

Can it be related to exposed ports? I only expose 443,2100 and 1982 ports.

**Comment by hendriksen-mark** [comment]
I have take a look at your log/config.
Strange thing is that the groups are changed multiple times in less than 1 second, this happens every time you change the on state.
If you change the zone it also changes the room, this should not be happening.
Maybe this is something with home assistant or MQTT, i need to test this but i dont have time to do this because i dont daily drive home assistant and MQTT.
For the ports the hue app needs port 80 and 443 to communicate, port 1900 is used for ssdp, port 2100 is used for the entertainment protocol.

**Comment by ummetcivi** [comment]
I opened 80 port and now it’s shown correctly when I restart the Hue App. Right now diyHue can’t restore light states when restarted but I guess it’s not related to this issue.

**Comment by hendriksen-mark** [comment]
If you use mqtt the lights are not pulled if you restart diyhue, mqtt works on push messages.
