### ISSUE TITLE
No longer able to connect to Hue App

### ISSUE THREAD

**Issue by egore** [diyhue/diyHue#1036]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

A recent update of the Hue App caused it to loose its connection to the diyHue-based bridge. Trying to add it back lets the app find the bridge, clicking the link button signals the app that bridging is successful, but the next screen informs the user, that no Hue bridge was found.

I assume it is either a fault on my side (though I've tried reinstalling the addon, wiping the data from /config, creating a new certificate), or it is a measure of the app to prevent "counterfeit" hue bridges.

### Errorlog:

No longer available due to many reinstallations / repair attempts.

### Steps to reproduce

1. Perform a new installation of the diyHue addon and configure it (optionally add lights)
2. Download the latest Hue app from Play Store or iTunes
3. Try to register the bridge with the app using an Hue-account

### Please enter your operating system details here

If diyHue does not star use "uname -mrs"
Hue-Emulator Version:  2.0.15 (and 2.0.14)
Architecture: aarch64
OS: hassio
Os version: 2024.8.0
Hardware: RPi4

### Upload debug tar

No longer available due to many reinstallations / repair attempts.

### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
Hi, diyhue can not work with a philips hue cloud.
you have to activate the app without a philips hue account.
also make sure that your local time zone is correct.

**Comment by egore** [comment]
Ok, I will retry in the next days with a local-only account. Closing until tested.
