### ISSUE TITLE
Crash over ZeroDivisionError

### ISSUE THREAD

**Issue by azukaar** [diyhue/diyHue#1048]
### Issue does not already exist?

No, I did not search

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

The hue bridge is very slow to "wake up" - if  I dont access it for a while, the mobile app will take a minute to actually connect. At first I thought it was because of #1043 (which you have fixed, thanks again!) but it did not solve the issue and there is now another crash in the log which hopefully is related.

### Errorlog:

```
[2024-09-25 17:15:33,352] ERROR in app: Exception on /clip/v2/resource [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/v2restapi.py", line 290, in get
    data.append(group.getV2GroupedLight())
  File "/opt/hue-emulator/HueObjects/Group.py", line 296, in getV2GroupedLight
    result["dimming"] = {"brightness": self.update_state()["avr_bri"]}
  File "/opt/hue-emulator/HueObjects/Group.py", line 142, in update_state
    bri = (((bri/lights_on)/254)*100)
ZeroDivisionError: division by zero
```

### Steps to reproduce

-

### Please enter your operating system details here

Hue-Emulator Version: 2024-09-21 14:00:03.000000000
WebUI Version: 2024-09-21 14:00:04.000000000
Architecture: aarch64
OS: Linux
Linux version: #1 SMP PREEMPT Tue Jun 18 13:49:00 UTC 2024
Linux release: 6.6.33-haos
Hardware: %Hardware%

### Upload debug tar

[Debug.zip](https://github.com/user-attachments/files/17134744/Debug.zip)

### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
Hi, it is strange that with 0 brightness the light is still on?
i made a change to fix this.
please update and give feedback.

**Comment by azukaar** [comment]
CI failed for ARM sorry havent been able to update

**Comment by hendriksen-mark** [comment]
Yes there were some deprecated stuff. This one is succes https://github.com/diyhue/diyHue/actions/runs/11039805818

**Comment by azukaar** [comment]
Does that include all the docker images? It's weird my home assistant does not see this update
![image](https://github.com/user-attachments/assets/0e9eba65-b209-4b7d-8093-95ac3dcce676)

**Comment by hendriksen-mark** [comment]
HA does not follow the main repo. To push a update to HA we have to do it separately. When im home i will make a update to HA addon

**Comment by azukaar** [comment]
Ah makes sense, thanks a bunch!

**Comment by azukaar** [comment]
It works perfectly now, thanks you!
