### ISSUE TITLE
Can't update from .20 to .24

### ISSUE THREAD

**Issue by NOTORIOUSVR** [diyhue/diyHue#1052]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

Unable to update to latest version (from 2.0.20 to .24)

error:

The command '/bin/bash -o pipefail -c cp -r dist/index.html /opt/hue-emulator/flaskUI/templates/' returned a non-zero code: 1

### Errorlog:

```
This can be downloaded from the webUI.
DiyHue > Bridge > Brdige Control > Download debug > Log tar
This is also included in Full debug
If diyHue does not start upload from normal log
```

### Steps to reproduce

Click update in HA for DIYHUIE

### Please enter your operating system details here

If diyHue does not star use "uname -mrs"
Hue-Emulator Version:
Architecture:
OS:
Os version:
Os release:
Hardware:

### Upload debug tar

```
This can be downloaded from the webUI.
DiyHue > Bridge > Brdige Control > Download debug > Full debug
Do not upload from Force config dump, Force config dump contains sensitive information
``


### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
https://github.com/diyhue/hassio-addon/issues/44
