### ISSUE TITLE
Link Button not working

### ISSUE THREAD

**Issue by xeberth** [diyhue/diyHue#1054]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

Yes

### Description

After last Add-on update I'm getting an error when Pulse the "Link App" Button from UI 

Error Says: `Error occurred: Request failed with status code 500`

By checking Add-on Logs in Home Assistant I found this entry every time I pulse the button:

`AttributeError: 'bool' object has no attribute 'update'
2024-11-21 14:01:32,606 - werkzeug - 225 - INFO - 172.30.33.1 - - [21/Nov/2024 14:01:32] "PUT /api/afafd3b0a53a11ef84a920f83b00997b/config HTTP/1.1" 500 -`

This happens in both: with `no-serve-https` `true `and `false`

![imagen](https://github.com/user-attachments/assets/a8141c6f-d01d-425f-b1d2-500f3fec7ef3)

### Errorlog:

From UI: `Error occurred: Request failed with status code 500`

From Add-on Logs in HA: `AttributeError: 'bool' object has no attribute 'update'
2024-11-21 14:01:32,606 - werkzeug - 225 - INFO - 172.30.33.1 - - [21/Nov/2024 14:01:32] "PUT /api/afafd3b0a53a11ef84a920f83b00997b/config HTTP/1.1" 500 -`

### Steps to reproduce

After last Add-on update I'm getting an error when Pulse the "Link App" Button from UI 

Error Says: `Error occurred: Request failed with status code 500`

### Please enter your operating system details here

Hue-Emulator Version: 2024-11-19 13:41:35.000000000
WebUI Version: 2024-11-19 13:41:45.000000000
Architecture: aarch64
OS: Linux
Linux version: #1 SMP PREEMPT Tue Oct 15 12:37:42 UTC 2024
Linux release: 6.6.54-haos
Hardware: HomeAssistant Green
Home Assistant: Core 2024.11.2 - Supervisor 2024.11.4 - Operating System 13.2 

### Upload debug tar

[config_debug.zip](https://github.com/user-attachments/files/17851590/config_debug.zip)

### What DiyHue version(branch) are you using?

master (latest)

**Comment by hendriksen-mark** [comment]
Hi, please check out this and try this fix.
https://diyhue.discourse.group/t/link-button-returns-500-throws-python-exception/499

**Comment by xeberth** [comment]
> Hi, please check out this and try this fix. https://diyhue.discourse.group/t/link-button-returns-500-throws-python-exception/499
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/9323a0544786d89ad2f98105efa18270ef6c4b84f2f828f848178fd69b2bc94e/68747470733a2f2f63616e616461312e646973636f757273652d63646e2e636f6d2f66726565312f75706c6f6164732f6469796875652f6f726967696e616c2f31582f346533376562383635666162313137656430333539306165393438393239386336303333616234392e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/56dca1be674bbb8322c1974b92ec7c169f5a57b31d7cced75b48f69ab6b77260/68747470733a2f2f63616e616461312e646973636f757273652d63646e2e636f6d2f66726565312f75706c6f6164732f6469796875652f6f7074696d697a65642f31582f346533376562383635666162313137656430333539306165393438393239386336303333616234395f325f33327833322e706e67"> diyHue**[Link Button returns 500 / throws python exception](https://diyhue.discourse.group/t/link-button-returns-500-throws-python-exception/499)**Hi,  I have my diyHue instance running in Docker on my Pi 4 over a macvlan network. The Container is connected to my IOT Vlan so it has direct access to my HA instance and potentially other “Smart” things. Now if i try to connect either HueEssentials or the official Hue App to diyHue with clicking the “Link App” Button just throws a big red error toast.  Container log snippet (same output whether or not being in debug mode):  [2022-07-29 15:14:17,682] ERROR in app: Exception on /api/570df1040cc8...

Excellent, by adding that lines in diyhue config.yaml and restart the addon the Link Button worked again.

Thanks!
