### ISSUE TITLE
It wont work on arch linux?

### ISSUE THREAD

**Issue by eskimos2000** [diyhue/diyHue#106]
I can not get it to work on my Arch Linux on Odroid HC2.

**To Reproduce**
1. Get arch linux on odroid HC2, 
2. Install docker
3. Install Home assistant, hassio, sonarr, radarr, nzbget
4. Run as described:
docker run -d --name "diyHue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' diyhue/core:latest

**Expected behavior**
Running diyHue container

**Logs**
`Using Host IP of 10.8.8.11
Docker Setup Initiated
Restoring Certificate
Certificate Restored
Restoring config
Config restored
Docker Setup Complete
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 303, in <module>
    bridge_config["config"]["mac"] = mac[0] + mac[1] + ":" + mac[2] + mac[3] + ":" + mac[4] + mac[5] + ":" + mac[6] + mac[7] + ":" + mac[8] + mac[9] + ":" + mac[10] + mac[11]
IndexError: string index out of range`

Container is exited

So how to get this to work?

**Comment by mariusmotea** [comment]
Hi,

Is mandatory to provide host mac and ip address as parameters to docker container, please check wiki for details.

**Comment by eskimos2000** [comment]
I did not know that, here https://diyhue.readthedocs.io/ there is mentioned that Mac and iPhone only in bridge mode is necessary. So this manual is not correct?.

**Comment by sh3d2** [comment]
@eskimos2000 actually the MAC adds in the docker-compose file is too short ;) add :xx at the end and you're good to go
