### ISSUE TITLE
Using Wemos D1 Mini as Switch or Light with original Hue Bridge?

### ISSUE THREAD

**Issue by Wolle62** [diyhue/diyHue#109]
Im reading a lot of Hue Emulator, thats great,  but i have a original Hue Bridge.
Now i want to connect a self made Hue Light with wemos d1 mini direct to it ?
I flashed one of the examples from here in the wemos d1 mini. That worked. (Arduino IDE 1.8.5)
I can call the IP in a Browser an switch the connected LED on and off.
But the Hue App dont find  the Wemos.
Must i use the Emulator or work this with the original Bridge?
What i made wrong? Must i uncommend anything in the Arduino Sketch?
Thanks!

EDIT1:
I made the Emulator with my Rasberry Pi3, can connecting it with the Hue App, 
but there will no Lamps find , like on original Hue Bridge.
Something is wrong with my Arduino Sketch?

**Comment by Mevel** [comment]
Hello Wolle62

Original Hue Bridge uses Zigbee Radio (Frequency) != Wifi 2,4Ghz.
For diyHue Lights you need the Hue Emulator within your Network.

Search for Lights within app - multiple times. Close app and restart app. Discovery sometimes takes a bit.

For further help, you can join Slack Group at [https://joinslack.diyhue.org/](https://joinslack.diyhue.org)

If you are German and need German Support write to me in PN.

**Comment by Wolle62** [comment]
Yes i am German...  Thanks for reply.
Ok i need this Emulator . The original Hue Bridge is useless for connecting a Wemos D1 mini
and i can disconnect it?
I will try it with the Emulator again. Cross Fingers...
How i can write a PN to you ?

**Comment by Mevel** [comment]
Solved in slack: flash correct firmware from repo was the solution.
