### ISSUE TITLE
Hue Sync not connecting with Emulated Bridge

### ISSUE THREAD

**Issue by TripleCore21** [diyhue/diyHue#112]
The Emulated Bridge and lights are working perfectly on my iPad and the app seems to auto-discover the Emulated Bridge. I was able to make an entertainment area within the Hue app so i could try Hue Sync. When i started Hue Sync on my PC it was only able to detect my original Hue bridge. Also within the Razer Synapse software it showed the same problem. With a third party Hue app from the Microsoft Store called 'Huetro for Hue' it also couldn't find it but i was able to fill in the manual IP, but sadly Hue Sync doesn't support manual IP's 

How can i solve this?

**Comment by mariusmotea** [comment]
Give more details, what installation are you using? Try a hue emulator restart and connect again Hue Sync. If you reinstall the software you will need to reinstall Hue Sync because of previews certificate beying cached.

**Comment by TripleCore21** [comment]
@mariusmotea i’m using HueEmulator3.py on a Raspberry Pi 3B+ running Linux Ubuntu Mate 1.16.1 
I tried restarting it but it didn’t help

**Comment by CoinDuckling369** [comment]
@mariusmotea ?

**Comment by cheesemarathon** [comment]
@TripleCore21 have you tried reinstalling HueSync? Can you post the diyHue logs here when you try and search for the bridge in HueSync

**Comment by mariusmotea** [comment]
@CoinDuckling369 start the script in debug mode and show output during pair process in order to understand what is going on.

**Comment by timbru31** [comment]
Hue Sync isn't working for me either :( - my Philips TV seems to ignore the Hue Entertainment API, too.
Lightbulbs are running firmware 1.46.13_r26312, running diyHue on a Raspi 3B+ with commit https://github.com/diyhue/diyHue/commit/12a1c11d62cf7eccae7b2d0b0d01a346ca1db965  
Debug log: https://pastebin.com/QMubzCPH

Any advices?

**Comment by timbru31** [comment]
Update: complete deinstallation of diyHue (`rm -rf /opt/hue-emulator`) and reconfiguration results in the same error (even with the Hue app when testing the entertainment area)

**Comment by mariusmotea** [comment]
Philips tv don't use entertainment but the http hue api. Original hue bulbs work with delay on diyhue because deconz don't know this protocol.

@timbru31 reinstalling the diyhue will require reinstallation of all other hue applications because of the old certificate beying cached.

**Comment by timbru31** [comment]
@mariusmotea - wow, thanks for shining some led on this! Now I feel dumb 😂 - didn't knew that the Hue Entertainment is actually some sort of custom Zigbee protocol (or custom Clusters? Will dig deeper into this). This explains why my TV refuses to be awesome.

---

Regarding the Hue Sync crash: only macOS seems affected at least on Windows the connection is not immediately terminated.

**Comment by mariusmotea** [comment]
I test Hue Sync in general on MacOS and i don't have any issues. I use it with esp8266 devices because are working like the original hue bulbs at high frame rates. With Deconz i limit the request to ~1 per second. Your TV may send data in xy format, not RGB and i did not had any app to test this. I think here may be an issue.
