### ISSUE TITLE
Spoof other Bulbs(Tradrfi) as Hue Bulb

### ISSUE THREAD

**Issue by AlexKusnezov** [diyhue/diyHue#114]
**Is your feature request related to a problem? Please describe.**
Is there a way to create entertainment areas with Tradrfi or somehow spoof the bulb, so they get recognized as genuine Hue bulbs?

I have two Tradrfi bulbs paired with usb ConBee stick, which is connected with deconz to diyhue

**Describe the solution you'd like**
It would je awesome, if you could edit lights within the diyhue interface, how the would be recognized and how up in the app, to be able to use Hue Snyc on PC or Mac

**Describe alternatives you've considered**
An ability to create entertainment areas in the diyhue interface.

Is there a way to achieve this?

**Comment by Mevel** [comment]
This is not possible as original hue uses a special zigbee protocol to achieve fast data transfer. It won't work as smooth as original. You can use Diy Lights with esp8266.

**Comment by AlexKusnezov** [comment]
@Mevel ok thanks, got it. Also diyhue always disconnects when i try to start light sync with Hue Sync. Am I doing something wrong, or Hue Sync doesn't work with diyhue in general?

**Comment by Mevel** [comment]
I know the problem you describing. My problem was the esp8266 (wemos) not beeing connected stable enough to the local wifi (even close to the router) I switched wemos board, flashed (ws2512 sketch) again and it worked. In general: diyLights and Hue Emulator work very good with Hue Sync.

**Comment by AlexKusnezov** [comment]
@mevel thanks for the info. Maybe I have this problem, because I'm running diyhue in VM :). I'll will try hat without, when I have my rpi hardware. Do you know good RGB bulbs, which work with diyhue and hue sync out of the box?

**Comment by Mevel** [comment]
Hue sync (entertainment) works only when using diyhue firmware in combination with the hue emulator. You need to reflash the bulb

**Comment by AlexKusnezov** [comment]
@Mevel ok got it. Sorry for the dumb question, but where can I get the diyhue firmware for ESP8266 bulbs and can I flash them via OTA? Only thing I found is in here, but there's no .bin file https://github.com/mariusmotea/diyHue/tree/master/Lights

**Comment by Mevel** [comment]
diyHue Firmware for ESP8266 based diyLights can be found here

> diyHue Lights Firmware Repo - [HERE](https://github.com/diyhue/Lights)

Firmware is Initially Flashed via Arduino IDE and can be Updated via `http://IPofESP/update`

compiled `myFirmware.bin` can be uploaded there. Also you can fully configure the diyLight via WEB UI

**Comment by AlexKusnezov** [comment]
@mevel thanks that is what I was looking for. So just to clarify: To be able to flash a bulb, like this one: http://www.milight.com/milight-5w-rgbw-e14-screw-iphone-ios-android-controlled-light/ I have to connect it to an Arduino Controller (soldering), right?

**Comment by Mevel** [comment]
Milight uses 2.4Ghz Wireless connection but it is NOT WiFi you know from your daily use of Smartphone etc. In addition it uses a propiatary protocoll. You need to replace the main LED Controller with a ESP8266 and flash the firmware. As far as i know there are no such Bulbs available that are ready for diyHue out of the box. After all, it is a DIY project.

To answer the question: Yes, you need to hack the Bulb and solder.

**Comment by AlexKusnezov** [comment]
@mevel thanks for you answers and your patience. Would it be possible to create a gateway emulator:https://blog.christophermullins.com/2017/02/11/milight-wifi-gateway-emulator-on-an-esp8266/ out of single esp8266, connect multiple bulbs to it, and then connect the esp8266 to diyhue as a gateway to pass through the connected bulbs? Just like it is with deconz?

**Comment by mariusmotea** [comment]
There are some ESP based bulbs named ColorDream that can be flashed directly. But the best wifi bulbs i have are MiLight FUT15 converted to ESP-M3

**Comment by AlexKusnezov** [comment]
@Mevel awesome, thanks. 
>MiLight FUT15 converted to ESP-M3

Is there a guide for this particular combination?

**Comment by mariusmotea** [comment]
There is an old image that i don't recommend anymore. https://github.com/diyhue/ReadTheDocs/blob/master/source/_static/images/MiLight_RGB_CCT_converted_to_ESP-12S.jpg

The proper way to convert this bulb to ESP is to use a step down power 3.3v power supply because the onboard regulator output just 30mA (is working also with this by adding extra capacitor). I use these micro power supply https://www.aliexpress.com/item/3pcs-1A-DC-5V-6V-9V-12V-24V-to-3-3V-DC-DC-Step-Down-Buck/32765853201.html?spm=a2g0s.9042311.0.0.27424c4dPNF3SF

Here i made a dedicated board for this project, you can just look to the schematic https://easyeda.com/marius.motea/MiLight_ESP-M2 . The transistors with the resistors are already present on the board. You need to remove the original microcontroller because will enter in conflict with ESP.

**Comment by AlexKusnezov** [comment]
@mariusmotea thanks, this is awesome. So what I need for conversion, besides the bulb, is:
 - **ESP-M3**
 - **3.3v Step-Down Converter**
 - **your custom board**
right?

**Comment by AlexKusnezov** [comment]
@mariusmotea cool I'll definitely try that. But bsck to the initial topic, I just edited the config file and swapped out from tradfri to hue specs and it works in hue Snyc now:
![Screenshot_20190415-120238__01](https://user-images.githubusercontent.com/33514406/56124420-e5576380-5f76-11e9-9df2-9bcbf5db0766.jpg)

Tradfri bulbs are just really slow:(

**Comment by mariusmotea** [comment]
Yes, nothing can be done to increase the speed unfortunatelly
