### ISSUE TITLE
deCONZ on other hosts broken

### ISSUE THREAD

**Issue by timbru31** [diyhue/diyHue#117]
**Describe the bug**
The deCONZ arg is not respected and does not work anymore.

**To Reproduce**
1. Start with `--deconz` arg
2. Try to connect to deconz
3. Observe error: 
```
2019-04-18 20:53:21,170 - root - INFO - registration fail, is the link button pressed?
```

**Expected behavior**
deCONZ arg is recognized.

**Logs**
n/a

**Additional context**
The following commit broke the deconz_ip variable: https://github.com/diyhue/diyHue/commit/6163affb171e33b3c33be3009a4cd17c33cce21a#diff-1b10137c36e6d146dc0dd0cdab499229R737

**Comment by mariusmotea** [comment]
Ensure you enable app pair in deconz and also the port that deconz run is the same from config.json file (edit manually in case not)

Default values:
```
 "deconz":{
      "enabled":false,
      "lights":{

      },
      "port":8080,
      "sensors":{
```

**Comment by timbru31** [comment]
That's not the issue ;) - the deCONZ host is hardcoded to `127.0.0.1` it used to work with PR #98 but with the linked commit above (6163aff) the `deconz_ip` value was overriden (again) with `127.0.0.1`

**Comment by mariusmotea** [comment]
You are right, i made a mistake with a big commit. I will fix this in few minutes.

**Comment by mariusmotea** [comment]
Please check now.

**Comment by timbru31** [comment]
LGTM - I'm going to test this change later today when I'm home. If it works, I'll just close this issue then 👍
