### ISSUE TITLE
Milight bulbs - color temp shown in hue app reset to 400 or so after some seconds

### ISSUE THREAD

**Issue by huongminh** [diyhue/diyHue#118]
**Describe the bug**
Every time I change the color temp of miglight bulbs to cold white (like energize scene) with color temp around 150-160 and return to the room view of the app, just 3-5 seconds the color temp will get reset to around 400 or above (warm white). However, the real bulb color temp still glow with the right color temp set. So there is a discrepancy between real color temp on the bulbs and the color temp shown in the app. It is a minor issue I found right the time I first installed hue emulator in mid 2018. Since the color set still works and status of lights as on/off is still correct, I can live with it. But it is definitely a bug so I report here.
Other lights like real philips Hue (set up via hue emulator) do not reset color temp. Only milight bulbs.

**To Reproduce**
1. Go to a room or individual light
2. Turn on and set color temp manually or via a scene (energize) to the colder white. If seen in the setting screen, the color temp will show correctly and the real  bulbs show correct color temp.
3. return back to the room view, color temp will change back to  temp some where between the READ scene and the Concentrate scene (warm white). But the change is in the app view only, real bulb still show correct temp. Turn the bulbs off and back on, bulbs still keep correct color temp but app shows wrong color temp as described.

**Logs**
Log does not show any change when the temp color changes in the app view.

**Comment by mariusmotea** [comment]
I need output from the milight hub right after you change the color temp. The flow is like this:

- Hue emulator receive the command, convert the parameters and forward to milight hue.
- Hue Emulator fetch the milight hub to get the light status (between 15 seconds and 5 minutes). Here i understand there is the problem and i don't use milight hub to replicate this.

**Comment by mariusmotea** [comment]
With the last changes from Milight Hub i don't know if is better to just disable milight hue light status fetch.
