### ISSUE TITLE
Wake up schedule not smoothly transitioning

### ISSUE THREAD

**Issue by hexEF** [diyhue/diyHue#119]
**Describe the bug**
A 'wake up' routine/schedule has a transition time (10/20/30 minutes) in which it smoothly fades from brightness `1` to `254`. However, diyHue does not adhere to the `transitiontime` and therefore goes to brightness `254` after 1 minute has passed.

**To Reproduce**
Perhaps relevant: I'm running diyHue _and_ the official bridge, so diyHue instructs the official bridge what to do instead of having the lights directly connected to diyHue.

1. Set up 'wake up' routine at 9:00 with 10 minute transition time and to turn off at 10:00
2. Wait until 8:50, see lights turn on at brightness `1`
3. Wait until 8:51, see lights turn to brightness `254`

**Expected behavior**
A smooth transition between 8:50 and 9:00 from brightness `1` to `254`. Effectively adhering to the `"transitiontime": 5400` property inside the scene.

**Additional context**
I've tried to figure out how the 'wake up' routine functions in the official bridge and the emulator in order to perhaps already find the pain point. However, I'm also creating this issue because maybe there's a simple known reason why this has never been implemented or why this can never be implemented.

The app saves the following (names are simplified for ease of reference to explain how everything is tied together):
- `schedule_1` which is configured to start at `wake_up_time - transition_time` and will toggle `sensor_1`'s `flag` to `true`. This schedule is `enabled`
- `schedule_2` which is configured to enable `scene_2` after a timer of `1` minute expires. This schedule is `disabled`
- `rule_1` which triggers when `sensor_1`'s `flag` is set to `true` and performs two actions:
  - Enable `scene_1` (low brightness scene)
  - Enable `schedule_2` (start scene transition after `1` minute)
- `rule_2` which triggers when `sensor_1`'s `flag` is set to `true` and the last time it has changed (`ddx` `operator`) is `turn_off_time - wake_up_time - transition_time` ago and performs two actions:
  - Turn off the lights
  - Set `sensor_1`'s `flag` back to `false`
- `scene_1` is configured to be at brightness `1`
- `scene_2` is configured to be at brightness `254` with a `transitiontime` of `transition_time - one_minute`

It looks like when applying `scene_2` it is simply ignoring the `transitiontime` and therefore straight away going to `254` brightness. I've tried to comment out [line 915-916](https://github.com/diyhue/diyHue/blob/12a1c11d62cf7eccae7b2d0b0d01a346ca1db965/BridgeEmulator/HueEmulator3.py#L915-L916) since that had a high chance of being the issue. However, the behavior stayed the same unfortunately.

**Desired outcome**
I'd love to hear whether this is something which has worked in the past, or whether it should work if I connect the bulbs straight to diyHue instead of via the official bridge. Because I'm willing to debug along :) Or whether this is something which has never worked and will never work due to certain limitations I'm unaware of at the moment. 

Thanks in advance for your time :)

**Comment by mariusmotea** [comment]
Hi,

Very important is the type of light you are using. Do you flash the light with a recent version? If you send the arguments from scene directly to the light with any http tool like curl, it has same behavior?

The lines you mention had nothing to do, i delete transitiontime there because it must not be stored in light state key. If you check the code, the state was already passed to the light.

**Comment by hexEF** [comment]
Thanks for your quick reply :)!

I am using an innr E14 light, which does support transitioning. If I manually create a routine to simply transition the light over a set period of time, it does this just fine. I tested this via the official bridge as well as via diyHue. Both ways work fine. So, there must be a slight difference between the way the app sets up the scenes for these two scenarios.

I'll have a look at the configuration differences and get back to you about it. Then we can probably determine whether it's an issue with diyHue, or that the official Hue app is doing something weird and send them a bugreport.

--

While testing this, I figured I can of course just skip the whole 'wake up' feature and set up one of the simpler routines. Since the simpler routines seem to function just fine, but I'll have a look at the differences anyway :ok_hand:

**Comment by mariusmotea** [comment]
Is complicated with ZigBee lighs and hue scenes. Hue bulbs have unique customization to accept color + brightness + transitiontime in one request. Other bulbs accept just bri + transitiontime and color in separate requst. I have one ZIgBee controller that want all in separate requests.
If you want to debug this just add print commands to code in this file to see the requests differences:

https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/functions/lightRequest.py 

lines for Deconz are:
```
           elif addresses[light]["protocol"] in ["hue", "deconz"]:
                color = {}
                if "xy" in payload:
                    color["xy"] = payload["xy"]
                    del(payload["xy"])
                elif "ct" in payload:
                    color["ct"] = payload["ct"]
                    del(payload["ct"])
                elif "hue" in payload:
                    color["hue"] = payload["hue"]
                    del(payload["hue"])
                elif "sat" in payload:
                    color["sat"] = payload["sat"]
                    del(payload["sat"])
                if len(payload) != 0:
                    sendRequest(url, method, json.dumps(payload))
                    if addresses[light]["protocol"] == "deconz":
                        sleep(0.7)
                if len(color) != 0:
                    sendRequest(url, method, json.dumps(color))
            else:
                sendRequest(url, method, json.dumps(payload))

```

**Comment by hexEF** [comment]
The innr bulb is indeed showing strange behavior compared to performing the same operations on an original hue bulb, which is unfortunate. However, that makes it an innr issue and not a diyHue issue, so I'll close it and contact them instead :ok_hand:

In case you're curious, I did the following tests with both the innr bulb and the hue bulb:
- Create a wake up schedule and figure out which sensor it created to manually `PUT` the `flag` to `true` instead of having to wait for it to trigger each time
- Set the light to about half brightness
- Turn off the light
- Update the sensor
- Light turns on with `1` brightness
- Wait a minute
- Second part of the 'wake up' triggers
- Then the bulbs behave differently:
  - The innr bulb jumps back to half brightness and starts transitioning from there to `254`
  - The hue bulb starts transitioning from `1` to `254`

Since I initially had the bulb on full brightness when turning it off, it looked like the `transitiontime` was ignored since it jumped to full brightness all the way, causing me to create this (non-)issue :)

**Comment by mariusmotea** [comment]
You use deconz or hue bridge for zigbee communication?

**Comment by hexEF** [comment]
The Hue bridge. I even tried it directly on the Hue bridge and it shows the same behavior with the innr bulb, so I contacted them :)
