### ISSUE TITLE
Can't Add Lights After App Update

### ISSUE THREAD

**Issue by ryancasler** [diyhue/diyHue#12]
After the latest app update, there is a prompt in the Hue app to update the software of the hub.  This of course, fails.  But when it does, it prevents you from accessing most of the functions of the Hue app, even ones that worked before.  Are you planning on updating diyHue to at least let us use the functions that were working before, even if the new ones like power on memory, are not supported?  Even if the app was tricked into thinking the hub was updated, I would think the old functionality would still work.

**Comment by cheesemarathon** [comment]
An update is being worked on right now to support the new features and to trick the app into thinking the bridge is running the latest software version. Please bear with us.

**Comment by chrisdata** [comment]
Nice! It works now after I perform the easy install script again.

**Comment by chrisdata** [comment]
Oh it prompt for update bridge again after I reinstall the app, and it's not successful.

**Comment by chrisdata** [comment]
Also unable to add lights

**Comment by ryancasler** [comment]
You can download the old version of the app from apk mirror if you're on android.  Just remember to disable automatic updates in the play store first.  I'm assuming this will be re-opened then?

**Comment by FlorianJa** [comment]
Same Issue here. I updated the emulator and also reinstalled the hue app.
