### ISSUE TITLE
Unable to connect Hue lights and Hue dimmer switch via Deconz tab in Hue Emulator

### ISSUE THREAD

**Issue by DarkCruncher** [diyhue/diyHue#120]
After some back and forth i finally got diyHue working on my Raspberry Pi 3b+ with Deconz and Phoscon. I had trouble with the ports and now the Hue emulator is now running on port 80 and Deconz on 8090. 

My problem occured when i tried to import my Hue GU10 Lights into Hue emulator by firstly adding them to Phoscon (I've got the ConBee USB dongle for that) and then secondly trying to add them to Hue emulator via the "Deconz" tab as stated in the documentation.

I was finally able to add my light through the import from bridge tab by adding the port 8090 to the end of the Pi's IP-Address running Phoscon. However this does not work too well.

Another problem i had was not being able to add the Hue Dimmer Switch to the Emulator in any way even though i have it connected to Phoscon. I have even tried to connect it via the Hue application which did not work either. 

<img width="563" alt="Unbenannt" src="https://user-images.githubusercontent.com/37043598/56611997-7b445b80-6613-11e9-9a47-380422317b05.PNG">

I have attached a picture of the interface i see as i suspect that there are some options that are not being shown properly.

Thanks in advance!

**Comment by Mevel** [comment]
Hey! You tried Adding light from web ui with the phoscon port if I understand correct. 

Phoscon does emulate a bridge itself, alongside the websocket for populating state changes. 

You need to activate deconz in `config.json` of hue emulator. Also add the `websocket port` of  the deconz service you set up in the deconz configuration. Not the web Ui port! 

After that, diyhue should be able to receive state changes of the dimmer switch (already connected to deconz) aswell as control zigbee lights connected to deconz. 

The  ui in the picture will fill with Infos once diyhue can fetch the data from deconz websocket.

**Comment by mariusmotea** [comment]
Please check the Wiki because we specify there the changes that need to be made on systemd file in order to move Deconz to ports 8080 and 8081.
