### ISSUE TITLE
Official Hue app does not pair anymore

### ISSUE THREAD

**Issue by abnd90** [diyhue/diyHue#127]
I had to re-pair my bridge with the official hue app today and pairing does not seem to work. The app briefly discovers the bridge before showing "No bridge found". Here is the debug output:

192.168.1.102 - - [20/May/2019 06:22:00] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.238 - - [20/May/2019 06:22:11] "GET /description.xml HTTP/1.1" 200 -
192.168.1.238 - - [20/May/2019 06:22:11] "GET /description.xml HTTP/1.1" 200 -
192.168.1.238 - - [20/May/2019 06:22:11] "GET /description.xml HTTP/1.1" 200 -
192.168.1.238 - - [20/May/2019 06:24:23] "GET /description.xml HTTP/1.1" 200 -
192.168.1.238 - - [20/May/2019 06:24:23] "GET /description.xml HTTP/1.1" 200 -
192.168.1.238 - - [20/May/2019 06:24:23] "GET /description.xml HTTP/1.1" 200 -

Pairing works fine from Hue essentials but hue essentials cannot create and entertainment area, it wants to update the firmware on my ws2812 light strip. I'm using the latest firmware in this repo on the strip.

**Comment by cad435** [comment]
Same problem here, right now I'm stuck with a House full of not working switches, can't do anything...

Also any 3rd-party app seems to crash when trying to pair with the hue...

**Comment by mariusmotea** [comment]
Did you tried to reinstall the hue app on your phone?

**Comment by cad435** [comment]
For me, yes...
Several times...

**Comment by mariusmotea** [comment]
Can you provide pastebin link with your config file?

**Comment by cad435** [comment]
Hey,

I can do this when I'm at home again, but for now:
It also happens with a fresh Install via the Curl command (Automatic install, No Docker)

cad435

**Comment by abnd90** [comment]
Here's my config after a fresh curl install adding my light strip: https://termbin.com/ifj5

**Comment by cad435** [comment]
This is my config right now:

https://pastebin.com/Hj1uZ9M2

I can switch lights on and off via Hue website. Nothing else.
Tap Switches don't work either after the update


cad435

**Comment by mariusmotea** [comment]
I believe the issue is the uniqueid of the switches. are too short, need to be longer. Replace them with some values found on google.
```
"uniqueid": "18:fe:34:fb:ff:6f"
```

**Comment by cad435** [comment]
> I believe the issue is the uniqueid of the switches. are too short, need to be longer. Replace them with some values found on google.
> 
> ```
> "uniqueid": "18:fe:34:fb:ff:6f"
> ```
Did that, turns out I get the following Console log:
`192.168.178.78 - - [23/May/2019 22:53:15] "GET /switch?mac=18:fe:34:fc:7:c9&button=16 HTTP/1.1" 200 -`

But sadly won't trigger a Light turn on/off...

cad435

**Comment by mariusmotea** [comment]
@cad435 are you using recent version of hue emulator? I don't understand why you have the switch registered (i see in "sensors" there are entries) but in emulator key there is nothing. Look like a serious issue.
```
    "emulator": {
        "lights": {},
        "sensors": {}
    },
```

according to registration function, you need to have a big uniqueid generated for the sensor:
```
def addHueSwitch(uniqueid, sensorsType):
    new_sensor_id = nextFreeId(bridge_config, "sensors")
    if uniqueid == "":
        uniqueid = "00:17:88:01:02:"
        if len(new_sensor_id) == 1:
            uniqueid += "0" + new_sensor_id + ":4d:c6-02-fc00"
        else:
            uniqueid += new_sensor_id + ":4d:c6-02-fc00"
    bridge_config["sensors"][new_sensor_id] = {"state": {"buttonevent": 0, "lastupdated": "none"}, "config": {"on": True, "battery": 100, "reachable": True}, "name": "Dimmer Switch" if sensorsType == "ZLLSwitch" else "Tap Switch", "type": sensorsType, "modelid": "RWL021" if sensorsType == "ZLLSwitch" else "ZGPSWITCH", "manufacturername": "Philips", "swversion": "5.45.1.17846" if sensorsType == "ZLLSwitch" else "", "uniqueid": uniqueid}
    return(new_sensor_id)
```

**Comment by mariusmotea** [comment]
On a simple test for me the it was working. Try to upgrade the hue emulator, delete the already registered sensor(s) from hue app and add them back.
```
   "emulator": {
        "lights": {},
        "sensors": {
            "18:fe:34:fc:7:c9": {
                "bridgeId": "26"
            },
            "60:1:94:83:1c:6d": {
                "bridgeId": "32"
            }
        }
    },
```


```
192.168.0.241 - - [24/May/2019 11:01:02] "GET /switch?mac=18:fe:34:fc:7:c9&devicetype=ZGPSwitch HTTP/1.1" 200 -
2019-05-24 11:01:02,860 - root - INFO - {
    "devicetype": [
        "ZGPSwitch"
    ],
    "mac": [
        "18:fe:34:fc:7:c9"
    ]
}
2019-05-24 11:01:02,860 - root - INFO - registering new sensor ZGPSwitch
2019-05-24 11:01:02,860 - root - INFO - ZGPSwitch
```

**Comment by cad435** [comment]
Allright, quite a lot to answer:

So, yes I did run the Latest wich you can install with `curl -s https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_install.sh | sudo bash /dev/stdin`

And I can't connect Hue App to bridge, it always shows the behaviour wich abnd90 stated:

> The app briefly discovers the bridge before showing "No bridge found"


so, Im forced to do all config edit manually, upload them via putty, start the emulator, test it, etc - wich is why I seem to be so lost right now... 
Also Im not into Phyton, wich is why i have only a limited understanding of the script you made...

So I checked HueEmulator3.py Line 1211 and folliwing wich made me editing my config to the following:

`        "sensors": {
            "18:fe:34:fc:7:c9": {
                "bridgeId": "1"
            },
            "18:fe:34:fb:ff:6f": {
                "bridgeId": "2"
            }`

So I guess (!!) that "bridgeId" is the same Id wich is read to select the Sensor from "sensors".

Sich seemes to be working, the switches started triggering things again, a Lamp is switching from blue to green... so I guess i have to tweak the "rules" and "scenes" section to get it running...



I would REALLY appreciating if I can pair my Hue-App with my bridge again... You might Imagine that...



greetings cad435

**Comment by cad435** [comment]
Allright, I had it resolved, did a lot of manual editing, but for now I can use my Light-Switches again... Thx Marius for pointing me in the right direction!

this is my config now:
https://pastebin.com/n1Kf9AAx


But, the Root-Case of not beeing able to pair the Bridge is not resolved...
If I can give you anything to debug the case, please let me know... 

I might also do a Wireshark-Protocol analysis If you tell me what I should looking for. (I'd not used thes tool in a while now, but I can get familiar with it again if its necessary)


greetings cad435

**Comment by abnd90** [comment]
I was able to resolve the app no pairing by reinstalling the Android app.
Also when searching for bridges, I disconnected my real hue bridge from the
network.

If this is the only issue left, I'm fine with closing this. Thanks!

**Comment by cad435** [comment]
Actually, after fixing the config and reinstalling hue app I can pair (had to reinstall it 3 times, suddenly it worked, no idea why...). it gives me a error that I should update my bridge though...

**Comment by abnd90** [comment]
Great! I wonder if I can just backup this state somehow and not let the hue
app auto update. I don't care for new features as long as it's stable.
*Sigh*

**Comment by cad435** [comment]
actually yes, you can:

Go in your App-Store, open the app-Page
Then on the top right, klick on the three vertical buttons and disable "automatic updates"


that should do the trick...
