### ISSUE TITLE
Home Assistant Lights

### ISSUE THREAD

**Issue by Jeroendeeerste** [diyhue/diyHue#128]
Would it be possible to add any light from home assistant using the Home assistant API? Home Assistant is compatible with a whole range of smart bulbs. 

For instance, i would prefer to add my milights to home Assistant, and then add the Home Assistant light entities to diyHUE. This way i can manage my hardware in one place (Home assistant), en use the HUE futures with all home assistant compatible hardware. 

It would largely increase the amount of hardware compatible with diyHUE trough Home Assistant. 

https://developers.home-assistant.io/docs/en/external_api_rest.html

**Comment by mariusmotea** [comment]
Do you have output example with curl request that display the lights and lights status?

**Comment by Jeroendeeerste** [comment]
I really lack the knowledge to help implement this. So disregard it if its a hassle. 

But i think these commands can be found in the docs:

Get the state: 

$ curl -X GET -H "Authorization: Bearer ABCDEFGH" \
       -H "Content-Type: application/json" \
       http://localhost:8123/api/states/light.kitchen


Update the state: 

$ curl -X POST -H "Authorization: Bearer ABCDEFGH" \
       -H "Content-Type: application/json" \
       -d '{"state": "on", "attributes": {"brightness": "25"}}' \
       http://localhost:8123/api/states/light.kitchen

Does that help?

**Comment by mariusmotea** [comment]
i need sample output to see how the lights are displayed.

**Comment by tube0013** [comment]
I used the HomeAssistant Emulated Hue component to add the lights to dyihue to attempt to get some ios hue apps working. seems to work pretty well.

**Comment by VitanyLTD** [comment]
HomeAssistant Emulated Hue lacks compatibility with devices like the ambilight tv. 
i'd like to see this feature too since all my lights (except the hue playbar behind the tv) are directly controlled by Homeassistant.

**Comment by Mace404** [comment]
If you use the Home Assistant Emulated Hue to import Hue lights into diyHue it goes nuts when you want to change color of a light. (and even makes the official Hue app/Hue Essentials crash)
Just toggling on/off works fine.

I would also like to control Home Assistant lights using diyHue.
Some more info on the rest api: https://developers.home-assistant.io/docs/en/external_api_rest.html
(or zigbee2mqtt support and I move all my lights to diyHue :))

**Comment by VitanyLTD** [comment]
I had the same issue, this is because the emulated hue of home assistant is outdated and it does not support anything else than a dimmable light :/

**Comment by VitanyLTD** [comment]
> 
> 
> If you use the Home Assistant Emulated Hue to import Hue lights into diyHue it goes nuts when you want to change color of a light. (and even makes the official Hue app/Hue Essentials crash)
> Just toggling on/off works fine.
> 
> I would also like to control Home Assistant lights using diyHue.
> Some more info on the rest api: https://developers.home-assistant.io/docs/en/external_api_rest.html
> (or zigbee2mqtt/CC2531 support and I move all my lights to diyHue :))
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/c555fca1d53c35e05e7b89c827194c8023cdf107/68747470733a2f2f646576656c6f706572732e686f6d652d617373697374616e742e696f2f696d672f64656661756c742d736f6369616c2e706e67">**[REST API · Home Assistant dev docs](https://developers.home-assistant.io/index.html)**Home Assistant provides a RESTful API on the same port as the web frontend. (default port is port 8123).

I had the same issue, this is because the emulated hue of home assistant is outdated and it does not support anything else than a dimmable light :/

**Comment by Hukuma1** [comment]
Any chance of a revisit? I just stumbled upon this repo in hopes of using my HomeKit-enabled lights from Home Assistant in Hue Entertainment Zone/Razer Chroma. I see someone else had asked for a native hassio addon before (https://community.home-assistant.io/t/diyhue-addon-hue-emulator/62737) but it didn't get traction because people didn't realize why it would be good (read: Hue Entertainment/Razer Chroma sync).

I'm not a coder, but I have some of the hardware and would eagerly help anyone test this feature to be added. HA is a giant platform so I would imagine it would only drive more traffic to diyHue once people realized they can pair non-Hue bulbs to the best features of the Hue ecosystem.
