### ISSUE TITLE
Linkbutton not working on some browsers

### ISSUE THREAD

**Issue by roel80** [diyhue/diyHue#129]
**Describe the bug**
Due to a double ending of the headers when using linkbutton, some browsers fail to successfully open this page. The Content-Size is never correctly received (as body rather as a header), due to a to early close of the HTTP response header.

**To Reproduce**
Steps to reproduce the behavior (1):
1. Go to 'hue/linkbutton' using Edge or IE
2. Authenticate
3. Page will most of the time not successfully load.

Steps to reproduce the behavior (2):
1. Go to 'hue/linkbutton' using Edge or IE
2. click Cancel
3. Page will display part of the header (Content-Size).

**Analysis**
This is due to the code calling ending the headers twice (self.end_headers)
This is ending in performed both in _set_AUTHHEAD(self) and _set_end_headers(self, data):
All failing pages functions first call _set_AUTHHEAD and then _set_end_headers.

**Proposed Fix**
Removing\disabling self.end_headers() on line 1011 fixes this behavior and is resulting in only a single call to end_headers()

**Comment by mariusmotea** [comment]
Wow! Very rare it happen to get such details. I will fix this according to your suggestion.

Thanks.
