### ISSUE TITLE
2 second delay before SK6812 turns lights on

### ISSUE THREAD

**Issue by sneak-thief** [diyhue/diyHue#132]
**Describe the bug**
When an SK6812 light strip is turned powered on from a mains light switch, it now takes almost 2 seconds for the light to go on. This used to be about 0.3 seconds with the older firmware that supported OTA updates.

**To Reproduce**
1. Load latest firmware to Wemos D1 mini
2. Turn power on to Wemos and SK6812 strip 

**Expected behavior**
When using power supplies connected to light switches, I expect them to turn on quicker than 2 seconds. It's unnerving to flip a light switch and wait so long.  I finally updated all my strips to the latest firmware and was surprised at how much longer it now takes to go on.

**Comment by mariusmotea** [comment]
I will check for a way to improve this. Extra delay is added because the config is loaded from spiffs then it look to see the last state of the light.

**Comment by mariusmotea** [comment]
I found in setup phase there is one second delay `delay(1000);`. Not sure if there is really needed a delay, but for sure one second is too much.

**Comment by sneak-thief** [comment]
Thanks - I'll try commenting that line out and let you know if I encounter any issues.

**Comment by sneak-thief** [comment]
OK, that works great so far. No problems at all when commenting it out like this:

`void setup() {
  //Serial.begin(115200);
  //Serial.println();
  // delay(1000);
`
