### ISSUE TITLE
can't compilate on arduino.ino....

### ISSUE THREAD

**Issue by estebangmn** [diyhue/diyHue#138]
hello,first of all thank you for all the work and upload here the files,i have several and infinite problems to compilate the .ino in my arduino,im always getting infinite errors when arduino ide try to include the libraries and compilate,is the first time i have so much and i could say infinite problems to compile some file .ino,i have tried everything,different libraries of the same kind,change the location,install a new version of IDE arduino and nothing,it's impossible make this .ino sketchs to build,

im trying to compile a simple sktech to activate a new led strip of ws2812b type in my raspberry with the hue bridge already running,this is one example but i have several errors in every librarie included at the begining of the code

Arduino\libraries\WiFiManager/WiFiManager.h:19:18: fatal error: memory: No such file or directory

i dont understand what happend because i add to the libraries several times and arduino ide can't find the files in the most of the cases,

please can you help me?????...

**Comment by mariusmotea** [comment]
Hi,

You need to open Arduino library manager and install following libraries:

WiFiManager by tzapu
NeoPixelBus by Makuna.
Also ensure that you have installed ESP8266 library and you selected under boards the ESP board you use.

**Comment by estebangmn** [comment]
just working on¡i'll tell you about it,thank you very much for the fast response,im very noob still and i didn't got that i need to choose first ESP board before compile

one more question please,wich library would you choose to avoid problems with the rest of libraries included on your lights sketch via wifi?

#include <ESP8266WiFi.h>
#include <ESP8266mDNS.h>
#include <WiFiUdp.h>
#include <ArduinoOTA.h>
#include <ESP8266WebServer.h>
#include <EEPROM.h>

and another question more sorry,would be possible to plug the led strip directly to the raspberry gpio pins and avoid the wifi modules? i dont need it because i have everything on my desktop together
