### ISSUE TITLE
Issue with HUE SYNC (Latest Version)

### ISSUE THREAD

**Issue by MopheusDG** [diyhue/diyHue#140]
I was able after some fighting to get my RPi3 Bridge working (Using Docker image on RPi3) and also tried just installing on the RPi3 via Autoinstall (Without luck there), but the Docker works fine. I can see now the IP of the Bridge, my ESP8266 lamp and everything works fine except from HUE SYNC from my PC.

What I can see:

The Bridge via web shows the Entertainment Area lights fine, they even switch colors inside the web.
The Hue Sync syncs with no problem, the color match what I can see on the bridge lamp colors.
But:

The Wemos ESP8266 light does not mimic the colors, just does nothing. I can change the color via the Philips HUE App on my cell, i can change the color via the webpage of the Lamp, but does not sync with HUE Sync for some reason.
Any ideas ? I can provide logs with some assistance.

Thanks.

**Comment by mariusmotea** [comment]
Hi,

Hue Sync use UDP protocol, in your case HUE api protocol that is http based is working fine. Did you map the UDP port 2100 to docker container? Also, be aware that new installation will generate new certificates and hue app cache the old certificate for this reason is required to reinstall all hue app's

**Comment by MopheusDG** [comment]
Hu @mariusmotea , thanks for your answer. I just followed the readmedocs to install Docker host image, like this:

docker run -d --name "diyHue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' diyhue/core:latest

Should I add something else to that ? Is it better to run the manual install on the RPi3 without using Docker maybe ?

Thanks for your help.

**Comment by mariusmotea** [comment]
I sugest to try host install in an ubuntu virtual machine. You cand made it with VirtualBox. The reason is to have different mac address in order to look like a new Hue Bridge. I forget one thing, did you try to stop/start the container? There are some startup funtions made to fix bridge emulator configuration problems.

**Comment by MopheusDG** [comment]
Let me try first the Ubuntu VM (Was already on it but too tired yesterday) and running the DIYHUE bridge on my PC will be faster and exactly what I neeed.

Would be great if diyhue could run as a windows app or service, that would be amazing for esp lights and gaming using HueSync.

Will let you know after installing the VM later. Thanks @mariusmotea .

**Comment by MopheusDG** [comment]
Fresh ubunt, installed Host Install via curl auto-install. Again same problem, I can see the Bridge, configure the lights, etc.... I can change the lights color from HUE official APP and HUE Essentials, but when HUE SYNC is active, lights do not change, even if the web access of the bridge show the lights and the enterainment area changing color acordingly.

So close yet so far away... lol !

Any idea for debug this issue ? Maybe the ESP SPiFFS is a problem ? (Just a shot in the dark).

Thanks again @mariusmotea. Great job with the emulator, page, etc.... is amazing anyway.

**Comment by mariusmotea** [comment]
@MopheusDG tell me on what OS you use HUE SYNC (Mac/Windows). Is the last version? What type of lights you are using from Lights repo (Ex: Generic WS2812 Strip). Did you try also with a smaller amount of lights in entertainment area (i test with max 5, not sure below if there are problems).

**Comment by mariusmotea** [comment]
I just test with latest Hue Sync for Mac and one WS2812 strip (2 virtual lights), it is working fine. I also test with Hue Essentials that has some entertainment functions (not sure in free version) and it is also working fine.

**Comment by MopheusDG** [comment]
Hi @mariusmotea I'm using "WS2812BHueRing" and Windows for Hue Sync (latests version of Hue Sync installed). I have configured my light as 2 lights with 4 leds each one.

Do you think I should try the WS2812 strip instead ? Or changing the amount of lights maybe... it's really weird because I can even turn on and off the lights from the HUE Sync app on Windows, it's just the Start Sync that doesn't work, the lights just stay on.

**Comment by mariusmotea** [comment]
That is the issue. I looked now in the code, the entertainment function was not implemented in WS2812BHueRing. Please use `strip` version, if is not a very big problem...

**Comment by MopheusDG** [comment]
Lol... well, that was actually the problem ! It works now but take me a bit to make the Strip work on my device, do you think there's chance to add Entertainment to the 2812B Ring ? Was perfect, just needed the code for entertainment. I tried to implement it but I'm not skilled enough.

By the way, on the WS2012_Strip, how should I setup the code if I have only 8 leds and want 2 lights of 4 leds each one ?

Thanks @mariusmotea ! Amazing job with DIYHUE.

**Comment by mariusmotea** [comment]
The WS2012_Strip is new version with configuration of the light from webgui. Don't change the code, just ensure you flash the firmware with 1MB or 2MB SPIFFS and access the configuration page of the light. From there choose 8 leds with 2 lights and 0 transition leds.
