### ISSUE TITLE
Refactoring help wanted?

### ISSUE THREAD

**Issue by zwegner** [diyhue/diyHue#143]
Hey everybody! First off, a huge thanks for this project, it's super useful!

I'm working with a small company, ATX-LED, that's interested in improving the project. We've been working with it internally for a few weeks now, adding the "native" protocol to our lights so they can be controlled by the Hue app. So far, we've fixed a few small bugs and cleaned up a few pieces of code, mostly related to configuration and scanning for lights. I pushed our changes up to https://github.com/atx-led-open-source/diyHue (I can make a pull request if you want). 

There is some refactoring we'd like to do to make the codebase more maintainable, but it might be fairly invasive to the code base, and so I'd like to see if you're open to it before we proceed:

* Add variables to access sub-dictionaries of the bridge_config. All over the codebase there's long dictionary lookups like `bridge_config["sensors"][light_sensor]["state"]["lightlevel"]` that are IMO pretty hard to read, and lead to really long lines of code. I've done this in a couple places in our current fork, like the changes to `updateConfig()` in [this commit](https://github.com/atx-led-open-source/diyHue/commit/983712db9b416bd9eb2958f4aa2a7eaf6bc052c7).

* Is there any reason to keep `bridge_config['lights']` and `bridge_config['lights_address']` separate? If not, it would make sense to put the address for each light inside the `bridge_config['lights']` entry.

* Move all protocol-specific code to the files in BridgeEmulator/protocols/. The light-scanning code would move to the appropriate protocol file (if it's not already there, like it is for yeelight and tasmota).

* Add an automated test suite. There's a lot of different pieces of code in this project, supporting many different types of lights, most of which we don't have. It would be very helpful to have a test suite that can test all these code paths to make sure they continue to work. One possibility is to use a network-mocking library to record the web requests sent and received when interacting with the lights. Then, during tests, all the web requests would use data from these recordings to simulate the lights, and verify that we send out the same data each time. I've successfully used [VCR.py](https://github.com/kevin1024/vcrpy) in the past for this, but it only supports HTTP, and there's some lights that use raw sockets/UDP to communicate. The library [Mocket](https://github.com/mindflayer/python-mocket) looks like it supports this, though.

* Add validation for the various web APIs using jsonschema. This would help for ensuring correctness, and also for documentation.

* Use a web framework such as Flask instead of the http.server module. IMO using the URL parsing/routing in Flask is much more readable/maintainable than the big nested `if`s inside `do_GET` etc.

**Comment by mariusmotea** [comment]
@zwegner this software was created as hobby so most contributors (including me) are not daily programmers. If you can improve it, why not?
I have only one remark, if we add the values from `'lights_address'` into `'lights'`` these will be exposed to hue app's and are not in the hue api. Currently i don't believe it is a problem, but in the future it might be.

**Comment by zwegner** [comment]
@mariusmotea Awesome! It might take a while to get through all the things I mentioned (I have plenty of other work to do too), but we're happy to help out. I'll make pull requests whenever I have a good chunk of work done.

I see what you're saying about lights/lights_address, that's good to know. It probably makes sense to consolidate them, and then only send the necessary parts of the light state to the Hue app.
