### ISSUE TITLE
Slack Link Not Working

### ISSUE THREAD

**Issue by Chirishman** [diyhue/diyHue#146]
**Describe the bug**
The site at https://slackinvite.squishedmooo.com is not responding

**To Reproduce**
1. Go to https://slackinvite.squishedmooo.com

**Additional context**

I'm trying to get in in the first place because despite setting pixelCount to 9 all 9 LEDs are still being treated as light 1. (LOLIN D1 mini running Generic_WS2812_Strip.ino)

**Comment by mariusmotea** [comment]
The url is https://diyhue.slack.com. I will try to fix the issue.

**Comment by Chirishman** [comment]
Thanks, though going directly to that site doesn't allow me to sign up, I still need an invitation. If you could send one to my username at gmail I'd appreciate it!

**Comment by Chirishman** [comment]
For anyone who might run across this in future, you apparently need to erase the entire flash contents when changing the lights count, LED counts, transitional pixel counts etc via `Tools>Erase Flash>All Flash Contents`

Erasing/reflashing the sketch only will not actually change these values unless you erase all.

**Comment by Mevel** [comment]
Slack link was updated commit 1e9aef970a75598152f7763a7269d9aafbcdb3be

Since you solved the problem you are invited to help if you want.
