### ISSUE TITLE
Install Python Astral error

### ISSUE THREAD

**Issue by dobby5** [diyhue/diyHue#148]
**Describe the bug**
Hello,

I always get this error during the installation (manual and automatic).

 Installing Python Astral.
Traceback (most recent call last):
  File "setup.py", line 5, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

I tried it with and without root right.
The installation was tried on a Raspberry 2 and 3B+. Raspian Buster.

**Comment by mariusmotea** [comment]
The automatic installation script execute following line :
`apt-get install -y unzip nmap python3 python3-requests python3-ws4py python3-setuptools`

for some reasons in your case it fail to install python3-setuptools. Can you execute `sudo apt update` and then run automatic installation script?

**Comment by dobby5** [comment]
Thank you, but unfortunately it didn't work.

I was able to fix the problem with a manual installation of python3-ws4py.

This package was necessary under buster.

https://apt.opmu.se/debian-buster/pool/main/p/python3-ws4py/ 

> The automatic installation script execute following line :
> `apt-get install -y unzip nmap python3 python3-requests python3-ws4py python3-setuptools`
> 
> for some reasons in your case it fail to install python3-setuptools. Can you execute `sudo apt update` and then run automatic installation script?
