### ISSUE TITLE
Crash when scanning unknown device

### ISSUE THREAD

**Issue by Fienberber** [diyhue/diyHue#149]
Hi, 

When scanning the network, if a device doesn't return a json it crashes. 

In the function `scan_for_lights():` in the file HueEmulator3.py : 
It crashed because of the `raise`.  (line 702)

**Comment by mariusmotea** [comment]
Probably that line can be removed. Can you check if everything is working fine if raise line is commented/removed?

**Comment by Fienberber** [comment]
I removed it and it's working perfectly, adding removing devices, no problem
