### ISSUE TITLE
python3-ws4py is incompatible to Buster

### ISSUE THREAD

**Issue by dobby5** [diyhue/diyHue#150]
Hello,

since I installed the latest version of Raspian (Buster). The entertainment function is no longer available. 

During the installation python3-ws4py is always specified as error.

**Comment by mariusmotea** [comment]
What error you receive when you try to manually install the python3-ws4py package?

`sudo apt install python3-ws4py`

**Comment by dobby5** [comment]
The package isnt available for Buster.

Log:
sudo apt install python3-ws4py
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python3-ws4py : Depends: python3:any (>= 3.3.2-2~)
E: Unable to correct problems, you have held broken packages.


Its possible change to this package? Its included ws4py

https://packages.debian.org/buster/python3-wsaccel

**Comment by mariusmotea** [comment]
`sudo apt install python3` ?

**Comment by dobby5** [comment]
python3 is already installed ;)

**Comment by dobby5** [comment]
All of this are installed

unzip nmap python3 python3-requests python3-setuptoo

**Comment by mduerager** [comment]
just install it by typing: 'sudo pip3 install ws4py'

**Comment by dobby5** [comment]
Es funktioniert nicht

> just install it by typing: 'sudo pip3 install ws4py'
