### ISSUE TITLE
diyHue + harmony Hub + Sonoff

### ISSUE THREAD

**Issue by avglas** [diyhue/diyHue#154]
Hi Guys!

I have no experience in programing and in Raspberry using - so I apologize if I ask basic questions.

I would like to connect a Harmony Hub to diyHue and Sonoff Basic switches. The Sonoffs switching ordinary GU10 LED-s. I've choosed this way because the Harmony Hub isn't connecting to Sonoff/eWelink)

I have a Raspberry Pi 3 (since a week), and installed the diyHue on it and managed that the Philips Hue app discovered the diyHue and they are connected. And here I've stopped.

My problem is 
- I couldn't add the sonoff switches to the diyHue 
- and couldn't connect the Logitech Harmony Hub to the diyHue

How can I solve this problem?

Thank you for Your kind answer in advance!

**Comment by mariusmotea** [comment]
Hi,

Please look on another recently opened issue regarding Harmony.

**Comment by avglas** [comment]
Thank you. So at the moment the only solution us to install ha-bridge, am I right?

Is there a way to connect the sonoff switches somehow to the chain (as a light bulb for example)?

**Comment by mariusmotea** [comment]
For Sonoff you can use Tasmota firmware that has support in diyhue (emulated as on/off device). Once imported you can create a group.
