### ISSUE TITLE
Milight Bulbs don´t mix rgb and white leds 

### ISSUE THREAD

**Issue by mduerager** [diyhue/diyHue#155]
Yesterday i set up the milight hub (big thx to sidoh!) and connected two CCT and two RGBW GU10 bulbs. The CCT ones are working fine, but the RGBW ones cannot mix colors (just the white leds or the rgb leds are lighting up, but never together). With the Milight FUT 092 control, you can ajust it (pastel tones, etc.)

Also, if anyone here has more then 4 Milight bulbs connected with the milight hub, do your lights turn on and off at the same time? Cause mine turn on and off with 1-2 seconds delay between the first and last bulb.

**Comment by mariusmotea** [comment]
If Milight bulbs are not set with same id and room then are controlled individually by hue emulator. You can try to decrese the delay between requests but the milight hub my be overloaded and miss some requests. Regarding the mix of rgb and wite leds i don't know how are done. Maybe support for this request is missing in mylight hub.

**Comment by mduerager** [comment]
They are in the same room, but every bulb has it´s own id. Can i set the same id for more then one bulb? 
 Have to look into the color issue once again today evening because now im not quite sure if the bulbs are even able to mix colors. Maybe thats the fault, have to try.

**Comment by mariusmotea** [comment]
Normally white leds are more powerful than color ones and turning them on will make color leds barelly visible. Probably if you want to achive brighter light with a small percent of color then this is useful.
