### ISSUE TITLE
Compatibility diyHue with Deconz

### ISSUE THREAD

**Issue by Toubster** [diyhue/diyHue#156]
Hi,

whatever I try, the Hue Emulator doesn't work with Deconz.
Both of them run in a Docker Container on a RaspberryPi 3b+.
Hue Emulator runs with the default Ports and the deconz container runs on the specified ports as in the description(http-port=8080 & ws-port=8081).
The lights are already added in the Descon.
I see with the integrated network analysis of Firefox the sent "GET" packets. There I saw that the wrong http port is used, not port 8080 as in the description rather port 80.

![grafik](https://user-images.githubusercontent.com/53408989/62411795-0e206900-b5f9-11e9-8fa3-d7d0efd55b89.png)

Then I enter the URL with the right Port, again an error.

![grafik](https://user-images.githubusercontent.com/53408989/62411820-5fc8f380-b5f9-11e9-9e0d-46259cf9de96.png)

Then I change the API Key and it works in the webpage.

![grafik](https://user-images.githubusercontent.com/53408989/62411728-f98fa100-b5f7-11e9-848b-5511844bf823.png)

Now my question. Have I made a mistake when starting the container or have I to do something else.
Thanks in advance.

**Comment by Mevel** [comment]
Make sure you have enabled deconz in config.json of hue emulator aswell as a valid api key with the specified web socket port 8081. For in depth and live support (also in German) join slack group via the invite link on the main page of the repo.

**Comment by Toubster** [comment]
Where can I change the specified Web Socket Port in the config.json?

That is deconz sector from my config.json:
![grafik](https://user-images.githubusercontent.com/53408989/62422894-fd83f780-b6b9-11e9-86c5-2ce689d2d37e.png)

I run the docker with the following command: sudo docker run -d --name "diyHue" --network="bridge" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' -p 80:80/tcp -p 443:443/tcp -p 1900:1900/udp -p 2100:2100/udp -p 1982:1982/udp -e 'DECONZ=192.168.0.5' diyhue/core:latest

**Comment by Toubster** [comment]
This Issue isn't resolved now. The Problem is still there.
