### ISSUE TITLE
Compatibility diyHue with Deconz #156

### ISSUE THREAD

**Issue by Toubster** [diyhue/diyHue#158]
Old Issue has been closed even though it hasn't been fixed yet.
#156

----
Toubster:
Hi,

whatever I try, the Hue Emulator doesn't work with Deconz.
Both of them run in a Docker Container on a RaspberryPi 3b+.
Hue Emulator runs with the default Ports and the deconz container runs on the specified ports as in the description(http-port=8080 & ws-port=8081).
The lights are already added in the Descon.
I see with the integrated network analysis of Firefox the sent "GET" packets. There I saw that the wrong http port is used, not port 8080 as in the description rather port 80.

![grafik](https://user-images.githubusercontent.com/53408989/62411795-0e206900-b5f9-11e9-8fa3-d7d0efd55b89.png)

Then I enter the URL with the right Port, again an error.

![grafik](https://user-images.githubusercontent.com/53408989/62411820-5fc8f380-b5f9-11e9-9e0d-46259cf9de96.png)

Then I change the API Key and it works in the webpage.

![grafik](https://user-images.githubusercontent.com/53408989/62411728-f98fa100-b5f7-11e9-848b-5511844bf823.png)

Now my question. Have I made a mistake when starting the container or have I to do something else.
Thanks in advance.

----
Mevel:

Make sure you have enabled deconz in config.json of hue emulator aswell as a valid api key with the specified web socket port 8081. For in depth and live support (also in German) join slack group via the invite link on the main page of the repo.

----
Toubster:

Where can I change the specified Web Socket Port in the config.json?

That is deconz sector from my config.json:
![grafik](https://user-images.githubusercontent.com/53408989/62422894-fd83f780-b6b9-11e9-86c5-2ce689d2d37e.png)

I run the docker with the following command: sudo docker run -d --name "diyHue" --network="bridge" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' -p 80:80/tcp -p 443:443/tcp -p 1900:1900/udp -p 2100:2100/udp -p 1982:1982/udp -e 'DECONZ=192.168.0.5' diyhue/core:latest

----
Toubster:
This Issue isn't resolved now. The Problem is still there.

**Comment by Toubster** [comment]
Waiting...

**Comment by mariusmotea** [comment]
You need to perform some low level debugging from diyhue container to deconz container. I believe the issue is made by broken communication between these two. In container output what do you see during pair process?

**Comment by Toubster** [comment]
Which pairing process do you mean? I thought the "pairing process" is automatic and then I can see the found devices in the /deconz path or have I misunderstood the description?  
That is the output from the Container log.(diyHue):  
![grafik](https://user-images.githubusercontent.com/53408989/63882415-3d48b100-c9d2-11e9-8454-11c16cf407f7.png)

How should the data exchange work? Deconz to diyHue or vice versa?

**Comment by mariusmotea** [comment]
No, is automatically. What lights do you have paired with deconz? Diyhue do raw import of the lights from Deconz, if there are wired values the hue app may ignore the lights. Also the lights are not displayed in weg ui if are not added to a group.

**Comment by Toubster** [comment]
I use the OSRAM Candle E14 and the OSRAM Classic E27 Dimmable.  
I tried both, with groups and without groups, it is nothing displayed in the web ui.  
Where is the import from Deconz coded? Could I overwrite that?

**Comment by mariusmotea** [comment]
I recommend you to force the import again by removing the devices from config.json file => deconz => lights. Delete everything from there and start again hue emulator

**Comment by Toubster** [comment]
I'm working on it. I will write here if I know more...

**Comment by Mevel** [comment]
a user has deconz running with this commands.

```
docker run -d \
   --name=deconz \
   --net=host \
   --restart=always \
   -v /etc/localtime:/etc/localtime:ro \
   -v /home/USERNAME/dockerStuff/deconz/deCONZ:/root/.local/share/dresden-elektronik/deCONZ \
   --device=/dev/ttyAMA0 \
   -e DECONZ_UPNP=0 \
   -e DECONZ_WEB_PORT=8080 \
   -e DECONZ_WS_PORT=8081 \
   marthoc/deconz

```

 - enable deconz in diyhue config
 - pair with diyhue  (unlock gateway --> App Verbinden) Gateway-->Advanced Options
 - restart diyhue (optionally with ```--debug```) and check the logs.

**Comment by Zappelphilipp** [comment]
i do have the exact same issue. i get curl from the diyHue container to the deconz container on :8080 like <deconzip>:8080/api/<apikey>/lights and i get a proper response.
