### ISSUE TITLE
Resetting DIYHue does not work

### ISSUE THREAD

**Issue by mplogas** [diyhue/diyHue#167]
**Describe the bug**
I would like to completly reset my DIYHue installation, as it seems to have some hiccups with changed/removed lights from deconz. For that, I was expecting to shut down the service, delete my existing config.json and start from scratch again. That is not the case, DIYHue "remembers" deconz auth and pulls all lights and sensors from the deconz upon restart.

**To Reproduce**
1. Install Deconz/RaspBee on a Pi
2. Install DIYHue on a Pi using easy_install script
3. Bind to Deconz, import some lights
4. Shut down DIYHue service
5. Replace config with default-config.json (check in editor that deconz is **NOT** enabled and not set up)
6. Start DIYHue service
7. DIYHue is pulling all lights and sensors from Deconz

**Expected behavior**
I would have expected to start from scratch again with the "naked" config.

**Additional context**
I tried to work around it by uninstalling, rebooting and reinstalling the app. I did not clean up any additional packages, however the connection to deconz remains. Eh?

**Comment by mariusmotea** [comment]
Hi,

Just grab the config.json from main repo and replace it in /opt/hue-emulator. Is important to preserve the certificate from that directory to not request data wipe on hue applications.

**Comment by mplogas** [comment]
It seems this is a Deconz issue, not a DIYHue issue. Feel free to close this issue.
