### ISSUE TITLE
Alexa Color change support

### ISSUE THREAD

**Issue by xPowerCode** [diyhue/diyHue#17]
Somehow i managed to add a light to my alexa so i can control the lights & dimm & color, and it did work. I was able to change the **color** & brightness!
But i needed to reinstall the bridge on my pi so they are now gone. 
If i now try to add a Light from the Bridge its only accessable as a dimmable light.
Any solution?
Why did it work last time? i thought the color controll options were only accessable over the cloud?

**Comment by mariusmotea** [comment]
Please note that i made some changes and now the firmware version exposed the last one. You can try to play with the swversion field of the lights in config.json file. The older firmware versions are public but i don't have now the url.

**Comment by Death111** [comment]
I just speak for the WS2812B example:
I found that the current modelid (LST002) used in the bridge is a "Extended Color Light", not a "Color Light".
see https://developers.meethue.com/develop/hue-api/supported-devices/
I'm not yet sure, if this is a problem. Just noticed, as I have the same problem that I cannot change color with alex.a

**Comment by Death111** [comment]
If https://github.com/mariusmotea/diyHue/issues/189 is still current, it is not supported without the skill.

**Comment by xPowerCode** [comment]
https://imgur.com/a/gyMYInd thats how it looked

**Comment by Death111** [comment]
@xPowerCode do you know when you installed it the last time? So we can go back in time and check what versions were used then. Also, you don't happen to have the old config - right?
I already tried some older versions but had no luck with them.

**Comment by xPowerCode** [comment]
Nope cant remember @Death111

**Comment by Nikfinn99** [comment]
Alexa does not support any color change on phillips hue without skill in the current version.
It would require the Hue skill but that in turn requires the remote API that is not supported by diyHue.

**Comment by xPowerCode** [comment]
@Nikfinn99 it did work, Alexa does support the Hue lights somehow...

**Comment by xPowerCode** [comment]
I couldnt believe it too, but it did work with experimenting with the version and the model

**Comment by xPowerCode** [comment]
i accidentally closed it whopsy

**Comment by mnoeth93** [comment]
Has anybody found out what version number to use?

**Comment by mnoeth93** [comment]
I compared all the request from the original bridge with diyHue. There were serveral things that differed. I modified my version so that all responses are identical. But so far no luck that alexa will recognize the color.

Any ideas what else this could be?

**Comment by xPowerCode** [comment]
When alexa scanned the lights with the color, i set the brightness to 2% or 1% then Alexa recognized the lights with color. I dont know if thats something associated with the scanning devices thingy but idk

**Comment by xPowerCode** [comment]
My Alexa discovered the lights with Colorchange support this version!

**Comment by Death111** [comment]
Works for me too :) I documented with screenshots:
![image](https://user-images.githubusercontent.com/5772511/51791278-e4493e00-21a0-11e9-95c6-66d8be996fba.png)
Latest commit on master was: https://github.com/diyhue/diyHue/commit/1f64fbef58d9395a09714ad12fabe8128b94833e

**Comment by braini1511** [comment]
Which revision do you use?

**Comment by Death111** [comment]
> Which revision do you use?

what u mean? I posted used commit in my post before if you mean that.

**Comment by mariusmotea** [comment]
I'm not aware of any fix regarding Alexa. Maybe the fix was done on Alexa?

**Comment by shbatm** [comment]
Do you have the Philips Hue Skill enabled in Alexa? I've read elsewhere that the native Hue support that Amazon provides without the Skill enabled doesn't support color change, but the Skill does.

**Comment by xPowerCode** [comment]
Nope skill isnt enabled
