### ISSUE TITLE
Light always shows reachable even when offline

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#176]
**Describe the bug**
Lights are toggled to unreachable but then immediately changed back to reachable.

**To Reproduce**

Unplug a light. Try to see if it shows unreachable.

**Expected behavior**
Light shows unreachable.
**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.

**Additional context**
Seems to be related to the try in the syncwithlights function. Under protocols, there is a try that catches all errors, however, if it does error (when the light is offline), it still continues down the code and hits the line to switch it back to reachable. See line 224-227 and 283 in lightrequest.py.

**Comment by mariusmotea** [comment]
Hi,

You are referring to esp8266 lights?

**Comment by alexyao2015** [comment]
Its happening with all lights now. I think I've fixed it. I'll issue a pull request soon.
