### ISSUE TITLE
Entertainment: interrupted by SIGTERM (in net_accept())

### ISSUE THREAD

**Issue by andyman1222** [diyhue/diyHue#179]
Alright so for the past few days I've been trying to get diyhue back working on my rpi 3. With the latest updates Python 3.4 is no longer supported (might want to note that), so I painstakingly tried installing Python 3.7 and finally settled on  3.6.9 (nice).

Anyways, I'm trying to get it connected back with Razer Synapse, which it has been able to do in the past successfully. However when I go thru the setup in Synapse it ends on "update required." I updated `config.json` so all the version numbers can match with `default-config.json` from the repo. I'd prefer to not use `check-updates.sh` to try to fix problems because I modified `entertainment.py` so my own program can handle entertainment instead. (Maybe there's something wrong here when it comes to authentication?)

Here's the debug output:

![Capturere](https://user-images.githubusercontent.com/14265340/64149099-11269900-cdf3-11e9-9e25-a9ad2ab5ff2e.PNG)

**Comment by mariusmotea** [comment]
The entertainment dtls server is c++ independent application and it is stopped with SIGTERM. This is triggered by PPUT request steam => active: false. Sinapse don't like something from a GET request
