### ISSUE TITLE
keeps crashing

### ISSUE THREAD

**Issue by camatthew** [diyhue/diyHue#18]
after a few minutes the prograsm no longer works and a reinstall is needed

**Comment by mariusmotea** [comment]
If you provide the crush log we can fix this. If not you may end with same error when same configuration is done.

**Comment by camatthew** [comment]
if i make a command script with plhue that changes the lights to red and green every seond it stops working after a couple minutes

**Comment by cheesemarathon** [comment]
Can you post this script and the output logs from diyHue until it crashes?
