### ISSUE TITLE
Yeelight get state of current light

### ISSUE THREAD

**Issue by betonishard** [diyhue/diyHue#185]
**Describe the bug**
When the Hue app is closed, and it is opened again turning a yeelight on will always show the same color (in the banner, in my case red) although  the color of the bulb is different.

**To Reproduce**
1.Add a yeelight to your Hue APp
2. Verify that it works, switching colors etc,etc this works. set it to blue for instance
3. Turn off the yeelight
4. Switch off the app
5, Open the app
6. turn on the yeelight.
7. You will see that the light turns on (nblue), however the color in the hue app is differnet (in my case always red.

**Expected behavior**
REspresent the color that the bulb is.

**Logs**
Only thing that i saw what was relted to the yeelight was this.

` File "/opt/hue-emulator/functions/lightRequest.py", line 192, in syncWithLights
    light_state = protocol.get_light_state(addresses[light], lights[light])
  File "/opt/hue-emulator/protocols/yeelight.py", line 122, in get_light_state
    tcp_socket.connect((address["ip"], int(55443)))
OSError: [Errno 113] No route to host`

So I looked up the code and manually added the ip.. Just to check. The error message was gone, however bot the expected behaviour.

**Additional context**

**Comment by alexyao2015** [comment]
Duplicate of #181

**Comment by betonishard** [comment]
Sorry for the inconvenience I will close
