### ISSUE TITLE
Slow reaction time when changing brightness / color when using with deconz.

### ISSUE THREAD

**Issue by vandalon** [diyhue/diyHue#186]
**Describe the bug**
When changing brightness or color from a hue app the reaction time is slow. It takes up to 5 seconds before all the lights in my living room (6) are dimmers/changed. 
I'm using deconz on a raspberry pi 4 on which I also run diyHue
I have a total 30 lights in deconz. 

Is there something I missed to speed things up? :)

**Logs**
The logs don't show anything out of the ordinary. What I do notice though is that every change to every light is happening 1 second after the other:

```
192.168.1.202 - - [09/Sep/2019 15:23:59] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/17/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:00] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/28/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:01] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/26/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:02] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/9/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:03] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/13/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:03] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/22/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:04] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/17/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:05] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/28/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:06] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/26/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:07] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/9/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:08] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/13/state/ HTTP/1.1" 200 -
192.168.1.202 - - [09/Sep/2019 15:24:09] "PUT /api/83a83a3876c64c33f66f33c54f1869ed/lights/22/state/ HTTP/1.1" 200 -
```

Any help would be much appreciated :)

**Comment by mariusmotea** [comment]
It can be something normal because currently i need to send the status of every light in separate requests with a 0.7 seconds delay. Try move the lights om a zigbee channel outside the wifi channels from your home.

**Comment by vandalon** [comment]
6 lights , every 0.7 seconds is close to 5 seconds :) Is it not possible to lower that to 0.1?

**Comment by mariusmotea** [comment]
on my side yes, on deconz side it may stop responding. Is more easy to throw data than to receive it and to process it. The only current option is to replicate the groups and the scenes from DiyHue in Deconz, but this require lot of work.

**Comment by vandalon** [comment]
Ok. Are you using websockets with deconz or just rest api?

**Comment by mariusmotea** [comment]
rest api. Webdocket is used just to receive events from Deconz.
