### ISSUE TITLE
Hue original Dimmer and Motion Sensor ? 

### ISSUE THREAD

**Issue by Scotty-89** [diyhue/diyHue#187]
hello,

I have a question ^^ is it possible to use the original Dimmer and motion Sensor also?
Sorry maybe stupid but I don’t find anything about that…
 At the moment I tri out the system with a Raspberry and all is looking god at the moment, the only thing is that the hue emulation doesn’t find the dimmers a motion sensor ^^ is that normal? Because this is one big feature, I need so that I can combine the Wemos d1 lights with some motion 😉

**Comment by Mevel** [comment]
Welcome!

You can use original Hue Dimmer and Sensors. Those use the Zigbee protocoll therefore you have to use a extra Dongle to include them into the diyHue ecosystem.

This can be done by using Deconz (Software) and the Conbee Dongle (Hardware).

If you have that extra Hardware, you can also use Sensors and Dimmers from Ikea, Xiaomi etc.

**Comment by Scotty-89** [comment]
hey,

thx i will take an closer look at this...
So but than i do not need the original Hue Brige any more or ??

**Comment by Mevel** [comment]
No you dont need a Bridge if you have the Hardware Dongle.
If you have one, you can import the Lights from existing Bridge and control them BUT no sensors.

**Comment by Scotty-89** [comment]
ok tihs is what i have right know ^^  so i will take an closer look at the HW Dongel an Deconz (Software)... maybe i can switch up to tihs and remove the original bride 
any helpful links ?
