### ISSUE TITLE
Issues when installing on OpenWRT using easy_openwrt.sh (wget)

### ISSUE THREAD

**Issue by tarneeb** [diyhue/diyHue#188]
**Describe the bug**
OpenWrt 18.06.4 r7808-ef686b7292 on Netgear R6220 with 16GB of storage added to overlay

uhttpd and lighthttp configured to use port 82, can access router interface fine

easy_openwrt.sh errors:

```
easy_openwrt.sh: line 10: pip3: not found
easy_openwrt.sh: line 12: pip3: not found

cp: can't stat 'config.json': No such file or directory
chmod: /opt/hue-emulator/config.json: No such file or directory

/etc/rc.common: /etc/init.d/hueemulatorWrt-service: line 16: can't create /sys/class/leds//trigger: Permission denied
/etc/rc.common: /etc/init.d/hueemulatorWrt-service: line 17: can't create /sys/class/leds//brightness: Permission denied
```

**To Reproduce**
1. ssh into router
2. 
```
wget --no-check-certificate https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_openwrt.sh && sh easy_openwrt.sh
```

3. all packages & dependencies install fine
4. see error

**Expected behavior**
The service would start

**Additional context**
package python3-pip is installed, but I don't know about pip3.

**Comment by tarneeb** [comment]
Update: pip3 problem was just that my package uses `pip` instead of `pip3`

The rest is still the same

**Comment by juanesf** [comment]
Hello, as soon as I can, I will watch the script, but as far as I can see, the configuration of a system LED is failing to see if the service is running and the name of the json file is different, I have entered a correction attempt at main repository

**Comment by tarneeb** [comment]
Thank you. Yes, I eventually realized the naming issue with the json file.

Please excuse my ignorance, but how do I test your correction attempt?

**Comment by juanesf** [comment]
I have entered a functional correction to the main repository, try the following:

wget --no-check-certificate https://raw.githubusercontent.com/juanesf/diyHue/master/BridgeEmulator/easy_openwrt.sh && sh easy_openwrt.sh

**Comment by tarneeb** [comment]
Thank you, it installed now. (btw I had to run the python commands in python 2.7 because I can't get pip to work with python 3 for some reason, but that shouldn't matter, right?).

Still, the service is not running properly. I don't get any error messages with `/etc/init.d/hueemulatorWrt-service start` or `reload` or `restart`, but when I do `python3 /opt/hue-emulator/HueEmulator3.py` I get:
`Traceback (most recent call last):
  File "HueEmulator3.py", line 11, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

**Comment by juanesf** [comment]
The emulator was migrated from python2.7 to python3, so the openwrt installation of python3 is in the installation script itself. I recommend you to reformat the external memory and make /overlay clean and then run the installer

**Comment by tarneeb** [comment]
It installed fine after a reboot. But I noticed that in HueEmulator3.py the server_address line is set to host ip (which I guess would be x.x.x.x:82 since that's what we changed uhttpd and lighthttpd to?) so I changed it to 80, but I still get some errors when running HueEmulator3.py:
```
# python3 /opt/hue-emulator/HueEmulator3.py
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/threading.py", line 916, in _bootstrap_inner
  File "/threading.py", line 864, in run
  File "/opt/hue-emulator/functions/entertainment.py", line 9, in entertainmentService
    serverSocket.bind(('127.0.0.1', 2101))
OSError: [Errno 125] Address in use

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/threading.py", line 916, in _bootstrap_inner
  File "/threading.py", line 864, in run
  File "/opt/hue-emulator/HueEmulator3.py", line 1704, in run
    httpd = server_class(server_address, handler_class)
  File "/socketserver.py", line 456, in __init__
  File "/server.py", line 136, in server_bind
  File "/socketserver.py", line 470, in server_bind
OSError: [Errno 125] Address in use

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/threading.py", line 916, in _bootstrap_inner
  File "/threading.py", line 864, in run
  File "/opt/hue-emulator/HueEmulator3.py", line 1717, in run
    httpd = server_class(server_address, handler_class)
  File "/socketserver.py", line 456, in __init__
  File "/server.py", line 136, in server_bind
  File "/socketserver.py", line 470, in server_bind
OSError: [Errno 125] Address in use
```
similar error to the one that made me change the ports to 80 and 443, but I'm not sure what to do with this one? Thanks for your patience.

**Comment by juanesf** [comment]
I tell you, diyhue needs to use port 80 otherwise it would not be detectable by the other services, the change to port 80 to 82 is to access the OpenWrt configuration (192.168.x.1: 82 / cgi-bin / luci) since when accessing 192.168.x.1 the emulator page appears where the linkbutton is among others, once you leave port 80 on uhttpd and lighthttp you just have to restart, the service runs diyhue when you turn on the router

**Comment by juanesf** [comment]
To manually run HueEmulator, the service must be disabled (/etc/init.d/hueemulatorWrt-service disable) and restart, once it is switched on it can be executed: python3 /opt/hue-emulator/HueEmulator3.py

**Comment by tarneeb** [comment]
> I tell you, diyhue needs to use port 80 otherwise it would not be detectable by the other services, the change to port 80 to 82 is to access the OpenWrt configuration 

Yes I know, I thought that since in HueEmulator.py it said host ip that it might use whatever the router is using (82) because that's what we specified for the 'host'. My misunderstanding. I didn't mean to change the port for diyhue, in fact I changed it _to_ 80 because I thought it might have been accidentally set to 82.

> that error occurs because HueEmulator is already running

I see. However it is still not working. 
I re-ran the install script, it installed fine, checked correct config for lighthttpd and uhttpd, can connect fine to luci web interface on port 82, but no diyhue when I go to 192.168.1.1 (on port 80 ofc) - see [this pic](https://i.imgur.com/urwTm5e.png) for what happens: it downloads luci.bin from the router... so no web server.

After this I did what you said, stopped and disabled the service, restarted it, and ran Hueemulator3.py - this is the output, same error msg as before:
```
# python3 /opt/hue-emulator/HueEmulator3.py
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/threading.py", line 916, in _bootstrap_inner
  File "/threading.py", line 864, in run
  File "/opt/hue-emulator/functions/entertainment.py", line 9, in entertainmentService
    serverSocket.bind(('127.0.0.1', 2101))
OSError: [Errno 125] Address in use

Exception in thread Thread-7:
Traceback (most recent call last):
  File "/threading.py", line 916, in _bootstrap_inner
  File "/threading.py", line 864, in run
  File "/opt/hue-emulator/HueEmulator3.py", line 1717, in run
    httpd = server_class(server_address, handler_class)
  File "/socketserver.py", line 456, in __init__
  File "/server.py", line 136, in server_bind
  File "/socketserver.py", line 470, in server_bind
OSError: [Errno 125] Address in use

Exception in thread Thread-8:
Traceback (most recent call last):
  File "/threading.py", line 916, in _bootstrap_inner
  File "/threading.py", line 864, in run
  File "/opt/hue-emulator/HueEmulator3.py", line 1704, in run
    httpd = server_class(server_address, handler_class)
  File "/socketserver.py", line 456, in __init__
  File "/server.py", line 136, in server_bind
  File "/socketserver.py", line 470, in server_bind
OSError: [Errno 125] Address in use
```
Sorry for all the trouble and thanks again for your patience.

**Comment by juanesf** [comment]
Is port 2101 being used by another service?

**Comment by tarneeb** [comment]
And when I try this: disable the service, reboot router, and execute the script, I get this:

```
# python3 /opt/hue-emulator/HueEmulator3.py
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/threading.py", line 916, in _bootstrap_inner
  File "/threading.py", line 864, in run
  File "/opt/hue-emulator/HueEmulator3.py", line 1717, in run
    httpd = server_class(server_address, handler_class)                                                
  File "/socketserver.py", line 456, in __init__                                                       
  File "/server.py", line 136, in server_bind                                                          
  File "/socketserver.py", line 470, in server_bind                                                    
OSError: [Errno 125] Address in use   
```

**Comment by tarneeb** [comment]
> Is port 2101 being used by another service?

Oh that's a good question. On the router itself, no, because I did a clean install recently and haven't grabbed any packages really. How can I check? 

But I have some other devices on my network that might be using it I guess? I'm not exactly a networking wiz as you can see, but that shouldn't interfere, right? e.g have tested diyhue on a raspi (in docker and I set it up with non-default ports (8080 and 4433, and there is no 2101, only 2100) to see if it would work and it does) and on a laptop server and they are both running, I didn't think that would interfere.. I am also running things like a nextcloud instance and other stuff. Should any of this make a difference? There's an IKEA trådfri hub as well.

**Comment by juanesf** [comment]
You can confirm these two lines at: /etc/config/uhttpd

list listen_http 0.0.0.0:82
list listen_http [::]: 82

**Comment by juanesf** [comment]
And:
/etc/lighttpd/lighttpd.conf

server.port = 82

**Comment by juanesf** [comment]
taking a look at some forum nextcloud uses port 80 and 443, I have not tried to use different ports in openwrt, you can try to run only the emulator

**Comment by juanesf** [comment]
I forgot to mention that apparently Chrome saves the cache or some data from the Luci page, but when entering from a private tab it works

**Comment by tarneeb** [comment]
............. I am an idiot, for lighttpd.conf server.port = 82 was commented out all along, I didn't even think about it because I could reach the router on port 82 but that was due to uhttpd I guess. It works. 

Thanks so much for your help - I'm going to go kill myself now

**Comment by tarneeb** [comment]
Oh snap, it's still not all good... I'm not getting the luci web interface at 192.168.1.1:82 - it's downloading luci.bin again. tried in incognito and firefox, and from another device. 

I due get the diyhue web interface on 80 though, but when I go to import lights from tradfri the page fails to load

**Comment by juanesf** [comment]
At the moment I am on my way home, but I think you should try a clean installation to avoid other inconvenience, now it will be easier to install

**Comment by tarneeb** [comment]
Yeah I think I'm going to just reflash my router and start everything from scratch, as the web interface is back to not loading after reboot and downloading the luci lua script..  Thanks for all your help, I'll drop an update as soon as I get around to doing it

**Comment by BLADR-ONE** [comment]
Hello, I seem to have a problema also with the start of the script hueemulatorWrt-service and it won't start even from luci returning Failed to execute "/etc/init.d/hueemulatorWrt-service enable" action: Command failed. Someone please help me.
