### ISSUE TITLE
Light / Scene animation

### ISSUE THREAD

**Issue by Kroellie** [diyhue/diyHue#195]
If I'm not mistaken there are two ways of animating color loops with Philips Hue:

1) Hue Labs, depending on remote-api
2) Light animation scripts which are uploaded to the bridge for example by using iConnectHue

I've tried uploading a script to diyHue, however it only sets the color of the light to the first color in the animation.

What needs to be done to get these kind of locally running animations (2) working?

**Comment by mariusmotea** [comment]
start the hue emulator in debug and paste here the error you receive.

**Comment by Kroellie** [comment]
Sorry, I have stopped my endeavours with diyHue.
