### ISSUE TITLE
Hue entertainment using tradfri not working

### ISSUE THREAD

**Issue by BPHvZ** [diyhue/diyHue#196]
I added Ikea tradfri lamps to the hue app. They automatically all seem to be set to type LLM010 even though I have Color temperature lights (GU10 spots) and an Extended Color light (E27 bulb). I can control them using the app, but when I try to setup an entertainment room and select the e27 light it says that it doesn't support colors (because tradfri lamps automatically get set to LLM010 type lamps). I can continue but then I get the message the lamp needs to update to use the entertainment room feature. Updating doesn't work, I let it sit for 30 minutes and nothing happend. 

I tried to change the lamp type in the config file, I didn't need to change the software version because it was already using the lastest, but that didn't do anything.

**Comment by Mevel** [comment]
In general using entertainment via Zigbee Dongle or via Original Bridge to control Ikea Lamps or even Hue Bulbs wont work smooth as the data transferrate is too slow. Original Hue have a "special" protocol to keep up with the refreshrate.

In diyhue you can use ESP8266 based with entertainment working smooth.

**Comment by mariusmotea** [comment]
I think you are using the Tradfri Gateway that expose very limited control to the bulbs and cannot work in entertainment mode

**Comment by jespertheend** [comment]
I was having a similar issue, I explained what fixed it for me here: https://github.com/diyhue/diyHue/issues/15#issuecomment-522179338

**Comment by BPHvZ** [comment]
> I think you are using the Tradfri Gateway that expose very limited control to the bulbs and cannot work in entertainment mode

Would using the Raspbee module be any better?

**Comment by BPHvZ** [comment]
> I was having a similar issue, I explained what fixed it for me here: [#15 (comment)](https://github.com/diyhue/diyHue/issues/15#issuecomment-522179338)
> Though I'm using MiLights, not sure if this also works for tradfri

I edit the config with nano in the terminal and try to change swversion: 66009461 to 1.46.13_r26312 (which I found [here](https://www2.meethue.com/nl-nl/ondersteuning/versie-informatie/lamps-luminaires))
I save it using the terminal. Nothing changes. I save it using http://{emualtor ip}/save and the gets reverted back to 66009461

**Comment by mariusmotea** [comment]
It will work but not at protocol speed. Only esp8266 lights with firmware provided here work as original Hue bulbs. Once you switch to Raspbee or Conbee you will unlock lot of futures, for example you will be able to use a motion sensor and a remote to control same room (like with Hue devices)

**Comment by mariusmotea** [comment]
You need to stop the service before any change. The configuration is stored in ram and on service stop and also every hour the config.json file is overided from ram

**Comment by BPHvZ** [comment]
> You need to stop the service before any change. The configuration is stored in ram and on service stop and also every hour the config.json file is overided from ram

okay I'll try that

**Comment by BPHvZ** [comment]
It worked. But it's indeed not very fast at changing the colors. Thanks for the help

fix: stop the service, change the config.json, start the service and just to be sure do http://{emualtor ip}/save
