### ISSUE TITLE
Can't pair with Hue app

### ISSUE THREAD

**Issue by Deteorek** [diyhue/diyHue#197]
What should I do? Can't pair with Hue app. I can see bridge but paring not working. In debug mode I see this:

2019-09-14 22:31:05,682 - root - INFO - Using Host 10.0.0.29:80
2019-09-14 22:31:05,734 - root - INFO - b827ebf8a38b
2019-09-14 22:31:05,736 - root - INFO - IP range for light discovery: 0-255
2019-09-14 22:31:05,737 - root - INFO - 127.0.0.1
2019-09-14 22:31:05,741 - root - INFO - Config loaded
2019-09-14 22:31:05,746 - root - DEBUG - start ssdp broadcast
2019-09-14 22:31:05,747 - root - DEBUG - starting ssdp...
2019-09-14 22:31:05,751 - root - INFO - sync with lights
2019-09-14 22:31:05,759 - root - INFO - Starting httpd...
10.0.0.7 - - [14/Sep/2019 22:31:05] "GET /description.xml HTTP/1.1" 200 -
10.0.0.27 - - [14/Sep/2019 22:31:05] "GET /description.xml HTTP/1.1" 200 -
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1704, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by Mevel** [comment]
> OSError: [Errno 98] Address already in use

Seems like a different application is using a port needed for diyHue?

**Comment by mariusmotea** [comment]
is possible that hue-emulator service was using the ports. You can check this with `sudo netstat -lntp`. Before you start the emulator in debug mode you need to stop the service first with `sudo systemctl stop hue-emulator`. If you performed multiple installations wire hue app's data.

**Comment by Deteorek** [comment]
I run command you suggest but with no luck...

osmc@RaspperyPi:/opt/hue-emulator$ sudo systemctl stop hue-emulator
osmc@RaspperyPi:/opt/hue-emulator$ sudo netstat -lntp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN      558/smbd            
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      251/rpcbind         
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      505/domoticz        
tcp        0      0 0.0.0.0:19444           0.0.0.0:*               LISTEN      260/hyperiond       
tcp        0      0 0.0.0.0:51413           0.0.0.0:*               LISTEN      326/transmission-da 
tcp        0      0 0.0.0.0:19445           0.0.0.0:*               LISTEN      260/hyperiond       
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      352/sshd            
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      505/domoticz        
tcp        0      0 0.0.0.0:1883            0.0.0.0:*               LISTEN      497/mosquitto       
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN      558/smbd            
tcp        0      0 0.0.0.0:6144            0.0.0.0:*               LISTEN      505/domoticz        
tcp        0      0 0.0.0.0:9091            0.0.0.0:*               LISTEN      326/transmission-da 
tcp6       0      0 :::37029                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::40613                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::45897                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::34347                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::139                  :::*                    LISTEN      558/smbd            
tcp6       0      0 :::41293                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::43597                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::45103                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::42639                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::111                  :::*                    LISTEN      251/rpcbind         
tcp6       0      0 :::38545                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::51826                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::37427                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::40499                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::34547                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::39475                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::34739                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::51413                :::*                    LISTEN      326/transmission-da 
tcp6       0      0 :::22                   :::*                    LISTEN      352/sshd            
tcp6       0      0 :::46583                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::42009                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::43609                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::41019                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::1883                 :::*                    LISTEN      497/mosquitto       
tcp6       0      0 :::46493                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::42301                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::445                  :::*                    LISTEN      558/smbd            
tcp6       0      0 :::34113                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::36993                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::36515                :::*                    LISTEN      1117/homebridge     
tcp6       0      0 :::42915                :::*                    LISTEN      1117/homebridge     
osmc@RaspperyPi:/opt/hue-emulator$ sudo ./HueEmulator3.py --debug
2019-09-15 14:26:58,813 - root - INFO - Using Host 10.0.0.29:80
2019-09-15 14:26:58,868 - root - INFO - b827ebf8a38b
2019-09-15 14:26:58,870 - root - INFO - IP range for light discovery: 0-255
2019-09-15 14:26:58,870 - root - INFO - 127.0.0.1
2019-09-15 14:26:58,875 - root - INFO - Config loaded
2019-09-15 14:26:58,879 - root - DEBUG - start ssdp broadcast
2019-09-15 14:26:58,881 - root - DEBUG - starting ssdp...
2019-09-15 14:26:58,885 - root - INFO - sync with lights
2019-09-15 14:26:58,902 - root - INFO - Starting httpd...
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./HueEmulator3.py", line 1704, in run
    httpd = server_class(server_address, handler_class)
  File "/usr/lib/python3.5/socketserver.py", line 440, in __init__
    self.server_bind()
  File "/usr/lib/python3.5/http/server.py", line 138, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.5/socketserver.py", line 454, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use

**Comment by mariusmotea** [comment]
`tcp 0 0 0.0.0.0:443 0.0.0.0:* LISTEN 505/domoticz` you conflict with Docoticz. In order to successfully start the hue emulator you need ports 443 and 80 to be free.

**Comment by Deteorek** [comment]
OK. Now everything works as it should! I also wipe hue app's data and without any problem pair my bridge. Thank you very much.
