### ISSUE TITLE
Sync with lights runs every 10 seconds regardless if user is connected

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#198]
**Describe the bug**
Sync with lights runs every 10 seconds regardless if user is connected
**To Reproduce**

Watch debug logs

**Expected behavior**
Runs only ever 300 seconds unless user connected

**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.

**Additional context**

**Comment by mariusmotea** [comment]
Is made with intention that way. If nobody is connected then is no need to made lot of traffic in the network and create load on emulator. Important is that once the user open his phone to see the realtime status of the lights and also to get fast updates in case somebody else play with the lights via lights web interface or REST api.

**Comment by alexyao2015** [comment]
Yes, thats what should happen, but I think something happened because it now just always does it every 10 seconds. Should be 300 seconds if the user is connected.

**Comment by mariusmotea** [comment]
Go it. I will check the code.

**Comment by alexyao2015** [comment]
Nevermind sorry. I found out that I had home assistant connected but it showed as HueDynamic. Seems like Home assistant always pings diyhue which makes sense. Thanks for checking.
