### ISSUE TITLE
Updater point to old repo

### ISSUE THREAD

**Issue by mariusmotea** [diyhue/diyHue#2]
HueEmulator3.py need to get config updates from this git repo instead of the old one.

**Comment by shbatm** [comment]
Several hard-coded links in easy_install.sh need to be updated as well.

Suggest pushing a final update to the old repo with a brief `migrate.sh` script to update everything you need to update to point to the new repo and then put the instructions at the top of the old README.

**Comment by cheesemarathon** [comment]
As far as I can see there is only one line in HueEmulator3.py that references the old repo. Therefore I don't think a migrate script is necessary. I can just put a single command to run an update that line in existing installs at the top of the readme.

I can then update this repo (HueEmulator3.py and easy_install.sh) to reference the new repo.

I think the old repo should be left in its final working state. We don't want it to reference this repo.

**Comment by cheesemarathon** [comment]
Ah forget that, ill write a script, only going to be like 4 lines but then it's super easy to understand and run

**Comment by cheesemarathon** [comment]
migrate.sh created: https://github.com/mariusmotea/diyHue/blob/master/migrate.sh
README.md updated: https://github.com/mariusmotea/diyHue/blob/master/README.md

I'll now fix the links in this repo.

**Comment by cheesemarathon** [comment]
Ok, the wiki has been migrate to this repo also now, with all it's links updated to reference this repo. I think this can be closed now.

**Comment by cheesemarathon** [comment]
Oh and the docker images have now been updated and are built from this repo

**Comment by cheesemarathon** [comment]
The only thing that is left is to attempt to move the open issues on the old repo to this one.

**Comment by mariusmotea** [comment]
How i can move the opened issues?

**Comment by cheesemarathon** [comment]
@mariusmotea https://help.github.com/articles/transferring-an-issue-to-another-repository/

**Comment by mariusmotea** [comment]
Only options are my own repositories, this one did not appear in select list.

**Comment by shbatm** [comment]
Maybe this will help? https://github.com/IQAndreas/github-issues-import
