### ISSUE TITLE
Using another Port?

### ISSUE THREAD

**Issue by Nobodi99** [diyhue/diyHue#20]
Hello there,
I'm currently trying to set up diyHue on my raspberry pi.
I'm currently running a NGINX server on that device which definitely explains why I get "ERROR!! Port 80 already in use. Close the application that use this port and try again." when I try to use the installer.

Is there any possible thing I could do to change the port that diyHue uses?
I want to reroute everything with NGINX because I don't want to open a ton of ports for all the stuff I want to access on my raspberry pi.

I would really appreciate some help on this matter if it's possible...

Greetings

**Comment by mariusmotea** [comment]
Hi,

Change the hue emulator http port and disable https server (from the bottom of the HueEmulator3.py script). Redirect all /api + /description.xml http and https requests to hue emulator new http port.

Remember to put the certificate generated by hue emulator installation (nginx require .crt and .key so split the .pem into these two files)

Sample nginx[ config files](https://github.com/mariusmotea/diyHue/tree/bf0296fbe9784743f1bf23207cc378fbdddf5a5f/BridgeEmulator/nginx)

**Comment by shbatm** [comment]
While not officially supported, this is possible--and is what I do on my machine.

I created a gist with the relevant changes here:
https://gist.github.com/shbatm/f8f335a64ef5c364e6a62131e173e2a9

**Comment by Nobodi99** [comment]
Thank you guys for your answers.
So what I tried after reading the things both  was to remove the ssl/https part from the .py file (is this correct?).

And once with the ssl stuff and once without the stuff I added this to my nginx config:

`    location /diyhue {
        proxy_pass http://localhost:8080;
        proxy_set_header Connection "";

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

    }

`

Because that's the way I do all the redirects I currently have. So I thought that should do the job to at least reach the default page of diyhue?

But I get this response:

`Error response
Error code: 404

Message: not found.

Error code explanation: 404 - Nothing matches the given URI.`

Which doesn't make sense to me because I can perfectly reach the page when I connect to port 8080 on my device when I use its LAN IP.

Did I do anything wrong here maybe?

**Comment by Nobodi99** [comment]
The idea I had here was that when I connect to my device by using "Https://example.com/diyhue" I will end up on the same webpage that I can access by using "device.ip:8080"

Do I understand the usage of the reverse proxy wrong here?

I wanted to prevent the usage of an extra subdomain for this...
Which I would need to do because there is already a "/api" from another port.

But if that's really the only way then I probably have to do this.

**Comment by shbatm** [comment]
If you proxy /diyHue you'll end up at device.ip:8080/diyHue, unless you do a rewrite to remove the /diyHue. 

The issue lies with the fact that the Hue API (called by any devices trying to connect to your fake Hue bridge) is expecting to recieve resposnes directly at `http://example.com:80/api`

Perhaps you can look into using a Docker container and just get a unique ip for that container (https://docs.docker.com/network/)

**Comment by Nobodi99** [comment]
Thank you for the answer again. I guess I didn't really understood how nginx is working. I'm way too new to this stuff :D 

But in the end I now just made a subdomain like "diyhue.example.com" and it works like a charm.
