### ISSUE TITLE
Razer Synapse 3 can't distinguish this diyhue. Call me to update

### ISSUE THREAD

**Issue by chuz** [diyhue/diyHue#200]
![image](https://user-images.githubusercontent.com/2840119/65263821-ea30cc80-db3f-11e9-82d4-4ebfaf155fdf.png)

**Comment by chuz** [comment]
Is it possible the hue chang the protocol?

**Comment by mariusmotea** [comment]
you can change it manually in config.json file ("config" => "api"). Not sure if other changes will be required.

**Comment by chuz** [comment]
Thanks, I will try tonight....

**Comment by g3or63126** [comment]
I was having the same issue. I tried to change apiversion to 1.50.0 (not sure about the correct number I should use), and it kinda helped, but then Razer Synapse is stuck on the following window:
https://i.imgur.com/zJ6cMVO.png
It suggested to press the "bridge" tumble, which bring up the following window for 3 seconds after some scanning:
https://i.imgur.com/QtrXZdA.png
but then all return back to the stuck message.

**Comment by mariusmotea** [comment]
Set entertainment stream active from true to false in config.json. if you restart the service it may help.

**Comment by g3or63126** [comment]
It's already set to "false" (groups.2.stream.active for me).
I also tried sudo systemctl restart hue-emulator.service without any luck.

**Comment by mariusmotea** [comment]
only somebody with real hue bulb can help us here with output from bridge. I have just the original hue bridge but no hue bulbs

**Comment by OtavioMiguel19** [comment]
This is exactly what is happening to me. Any suggestion to try?

**Comment by chuz** [comment]
Maybe the Razer Synapse need the real bulb or led strip. Real hue bright need product SN.  And I try to connect the diylight to real hue bright, but fail.

**Comment by OtavioMiguel19** [comment]
Recently I was using diyHue with diyLights in Synapse 3 with no problems, but today I updated diyHue with the latest version and it stopped working. Did anyone knows how to make it work again?

**Comment by franciscoangelini** [comment]
> Set entertainment stream active from true to false in config.json. if you restart the service it may help.

this config is from diyhue or synapse ?

**Comment by franciscoangelini** [comment]
Hue app ask to update my lamps and diyhue and dont work of course :(

**Comment by mariusmotea** [comment]
Update swversion to last release, see the Bridge page of doyhue.

**Comment by franciscoangelini** [comment]
diyHue
Current version: 2.0.5

and last wled

**Comment by mariusmotea** [comment]
Open diyhue web interface, click Bridge menu. The Software Version field must be updated to the last hue bridge version and you can find it by clicking the link with "click here for last versions".

**Comment by franciscoangelini** [comment]
i stay with last version, works with pc hue software, 1 time, now dont work more, i try format my RPi, install rasperberian and diyhue again, now app Philips Hue original detect, but pc version no and razer synapse no :(

**Comment by mariusmotea** [comment]
Some debugging logs may help to understand what is going on. Most likely you need to wipe the applications cache if you reinstalled since the certificate was changed.
