### ISSUE TITLE
Can not connect Yeelight

### ISSUE THREAD

**Issue by gerripeach** [diyhue/diyHue#201]
I bought this bulb from Yeelight:
https://www.aliexpress.com/item/32885328641.html?spm=a2g0s.9042311.0.0.2aaa4c4dO2YxYG

I was able to connect it with the yeelight app for android.
I can ping the yeelight bulb from the host machine of diyhue
I activated lan control in the app settings
I use diyhue within docker
I checked with netstat that the port 1982 is open
yeelight has the ip 10.10.20.101 diyhue has the ip 10.10.20.10
I have a 10.10.0.0/16 net
In the config file from diyhue the netmask 255.255.255.0 is used

**Comment by mariusmotea** [comment]
Is a know issue with docker container and yeelight detection. Just add a dummy milight bulb from web interface then stop hue-emulator service, open in editor config.json file and replace milight with yeelight. Save and start back the emulator service.

**Comment by alexyao2015** [comment]
Try using host networking in docker. Required to find devices.
https://docs.docker.com/network/host/

**Comment by gerripeach** [comment]
It worked! Thank you. In the end i changed the network mode to host and added the bulb with the milight function.
