### ISSUE TITLE
Convert_xy function missing in entertainment

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#203]
github.com/diyhue/diyHue/blob/master/BridgeEmulator/functions/entertainment.py#L72

Seems that the convert_xy function is being used in the entertainment function but has not been imported. Doesn't seem to have been causing problems since this cie colorspace hasn't been used.

**Comment by mariusmotea** [comment]
True! Hope this was the reason why some entertainment applications where not working. Now is fixed.

**Comment by alexyao2015** [comment]
I thought it was strange that it wasn't imported!
