### ISSUE TITLE
Upgrade installation, syntax error

### ISSUE THREAD

**Issue by Fisico** [diyhue/diyHue#204]
Upgrading diyhue with "curl -s https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_install.sh | sudo bash /dev/stdin" on a raspberry, results in some errors during installation. 
The huebridge is working so i don't know if it is anything important.

Version:
Raspbian GNU/Linux 10 
10.1
Kernel:
4.19.66-v7+

errorlog:
byte-compiling build/bdist.linux-armv7l/egg/ws4py/utf8validator.py to utf8validator.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/framing.py to framing.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/async_websocket.py to async_websocket.cpython-37.pyc
  File "build/bdist.linux-armv7l/egg/ws4py/async_websocket.py", line 87
    asyncio.async(closeit())
                ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-armv7l/egg/ws4py/messaging.py to messaging.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/exc.py to exc.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/streaming.py to streaming.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/compat.py to compat.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/cherrypyserver.py to cherrypyserver.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/tulipserver.py to tulipserver.cpython-37.pyc
  File "build/bdist.linux-armv7l/egg/ws4py/server/tulipserver.py", line 43
    f = asyncio.async(self.handle_initial_handshake())
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/wsgirefserver.py to wsgirefserver.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/wsgiutils.py to wsgiutils.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/geventserver.py to geventserver.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/manager.py to manager.cpython-37.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO

**Comment by cheesemarathon** [comment]
This is an issue with ws4py installation. It appears you are running this on Raspbian buster which has several issues at the moment. We recommend people stick with stretch for now

**Comment by aralmpa** [comment]
This is issue as of now still appears during installation step (running install.sh)

byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/tulipserver.py to tulipserver.cpython-37.pyc
  File "build/bdist.linux-armv7l/egg/ws4py/server/tulipserver.py", line 43
    f = asyncio.async(self.handle_initial_handshake())
                    ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/wsgirefserver.py to wsgirefserver.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/wsgiutils.py to wsgiutils.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/__init__.py to __init__.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/server/geventserver.py to geventserver.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/streaming.py to streaming.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/messaging.py to messaging.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/framing.py to framing.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/utf8validator.py to utf8validator.cpython-37.pyc
byte-compiling build/bdist.linux-armv7l/egg/ws4py/async_websocket.py to async_websocket.cpython-37.pyc
  File "build/bdist.linux-armv7l/egg/ws4py/async_websocket.py", line 87
    asyncio.async(closeit())
                ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-armv7l/egg/ws4py/exc.py to exc.cpython-37.pyc

**Comment by ryancasler** [comment]
What operating system are you trying to install on?  What platform are you running DIYhue on?

**Comment by aralmpa** [comment]
Rasbian 10 (rasberrypi - host install)

**Comment by TonyHultqvist** [comment]
Same issue here. :/  

amd64, ubuntu 20.04 server. Python 3.8

**Comment by xfader2018** [comment]
Still no resolution?
