### ISSUE TITLE
Cie Entertainment

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#205]
https://github.com/diyhue/diyHue/blob/01d05eb37621b84e0a9b7fb4cdb2c596666599f7/BridgeEmulator/functions/entertainment.py#L58

Line 58 shows a while i < len(data) but i is never incremented, so if this ever runs, there is a neverending loop. What exactly is the cie colorspace? As far as I can tell, it is never used as seen by the last issue. Seems like it never even functions and is never called. Is this code even required?

**Comment by alexyao2015** [comment]
Can this piece of code be completely removed since it seems like it never even runs in the first place?

**Comment by mariusmotea** [comment]
How you test it? Do you have an app that is sending CIE x,y values?

**Comment by alexyao2015** [comment]
No I don't but just looking at the code, it seemed like it never worked in the first place. Do you have an app that sends cie values to test with?

**Comment by mariusmotea** [comment]
So far no, i wrote the code based on entertainment api. If you take a look the code is identical with rgb part and that one is executed. Maybe are more bugs in this part but we cannot know until we will have a test app.

**Comment by cheesemarathon** [comment]
ill close this as we don't have a way to test it right now. Added to the suggested enhancements project so it's not forgotten

**Comment by alexyao2015** [comment]
That works. Its probably not worth the effort trying to fix the infinite while loop since there's nothing that uses it
