### ISSUE TITLE
Integration in own software

### ISSUE THREAD

**Issue by cheak1974** [diyhue/diyHue#207]
Hi, nice project.
Am I missing something or is there either no possibility or documentation for using this package from own software projects? I made my own Python smarthome hub software because the existing solutions were not really suitable for me. Is there a rest API or even Python objects that I can use from my project?

I guess something should be there because  apperently there are bindings for HASS and OH2. Could you give me a hint how do implement your solution. I don't want ro reinvent the wheel :-) 

regards
Chris

**Comment by Mevel** [comment]
You can use the official hue api as this emulates a real hue bridge it also uses the official api resources.

**Comment by mariusmotea** [comment]
Integration with HASS an other 3rd party software is made using hue api. We extend the list of supported lights by creating libraries for them (ex Yeelight)

**Comment by cheak1974** [comment]
Ahh, I see. So you simulate the bridge and the access should be like normal HUE access. Will the other non-HUE devices like Yeelight be accessible through the same API or will there be an additional command set?

It would be great to integrate a lot of ZigBee system with your solution and have a unique API for unified access through the same API or Python (or other language) wrappers for direct integration.

Anyway, I think now I can try to integrate this.

regards Chris

**Comment by mariusmotea** [comment]
Yeelights and all other lights are emulated in Hue lights in order to have compatibility Hue apps as much as possible. Currently we have integration with Deconz for communication with zigbee devices but any other implementation is welcomed.
