### ISSUE TITLE
perform upgrade, it gets: /dev/stdin: line 1: 404:: command not found

### ISSUE THREAD

**Issue by chrisdata** [diyhue/diyHue#208]
what causing the command not found for /dev/stdin?
It used to be running fine.

Running ubuntu.

**Comment by cheesemarathon** [comment]
Do you have any more output from this error? It's impossible to debug from the small amount of info you have provided.

**Comment by chrisdata** [comment]
I use the curl cmd as usual for the upgrade but getting the error, just one line:

/dev/stdin: line 1: 404: command not found

WHat caused?

**Comment by cheesemarathon** [comment]
Looks like an error with bash. What's the output for `bash -lxe`

**Comment by chrisdata** [comment]
I fixed it, the link shoudl be case sensitive. Thanks.

**Comment by cheesemarathon** [comment]
Ah, hence the 404! Makes sense. Thank you
