### ISSUE TITLE
Manufacturer is not set

### ISSUE THREAD

**Issue by SvenGWK** [diyhue/diyHue#209]
I use diyHue together with the ESP8266 miLight-Hub and the Hue Essentials app. 
Control etc works, but I only got question marks in the app instead of icons for the lamps.
A request in the Hue Essentials Discord chat revealed that the manufacturer of the lamp is not being submitted. 
The type is displayed as LCT001, diyHue would have to transmit "Philips" as manufacturer as well.
In the program I saw that the line then is "manufacturername: ..." .
After I have entered this for my MiLights accordingly before the modelid of the lamps, everything works fine.
When creating a new lamp, the entry in the config is missing.
Maybe it´s a bug.
![1](https://user-images.githubusercontent.com/1237240/66061542-f48b9700-e53f-11e9-98a6-90b6083c4446.JPG)
![2](https://user-images.githubusercontent.com/1237240/66061547-f6edf100-e53f-11e9-8eb8-81054fed8569.JPG)
![3](https://user-images.githubusercontent.com/1237240/66061552-f8b7b480-e53f-11e9-8fe6-066a0412b86c.JPG)

**Comment by mariusmotea** [comment]
Did you performed a service restart? Some of these values are checked and fixed on startup.

**Comment by SvenGWK** [comment]
Yes, I have restarted the service a few times, but the value has not been added. For me, it only worked by manually adding the line.Am 03.10.2019 16:33 schrieb Motea Marius <notifications@github.com>:Did you performed a service restart? Some of these values are checked and fixed on startup.

**Comment by mariusmotea** [comment]
fixed with last commit. It will require to delete and add back the light again. I also added the new swversion in order be an entertainment compatible light (don't expect the speed of native lights here!)
