### ISSUE TITLE
ESPHome connection changing colors

### ISSUE THREAD

**Issue by betonishard** [diyhue/diyHue#211]
**Describe the bug**
ESPHome leds do get connected, however only on or off works from the Hue app
**To Reproduce**
Add the light (this works when following the esphome instructinons)
On and off works
Changing lights does not work

**Expected behavior**
Changing lights should work

**Logs**
What worked for me was adjusting the file esphome.py

`                if address["esphome_model"] == ("ESPHome-RGBW" or "ESPHome-RGB"):
                   if "xy" in data:
                        color = convert_xy(data['xy'][0], data['xy'][1], 255)
                        red = str(color[0])
                        green = str(color[1])
                        blue = str(color[2])`

In the code above remove "ESPHome-RGBW", in fact prevent it to being an or.
The issue that I had when I added logging and run in debug mode that the if condition althought it was true, did not worked. The modelid when I logged it was ESPHome-RGB, double checked it in the config as well. However it did not evaluate.. To be clear:
`               if address["esphome_model"] == ("ESPHome-RGBW" or "ESPHome-RGB"):
`
should become
`               if address["esphome_model"] == "ESPHome-RGB":
`
This is definitely not a solution, but hey it works for me.
**Additional context**

**Comment by mariusmotea** [comment]
I think the correct method is `if address["esphome_model"] in ["ESPHome-RGBW", "ESPHome-RGB"]:`

**Comment by cheesemarathon** [comment]
@betonishard Can you test @mariusmotea's fix and create a PR if it fixes the issue?

**Comment by alexyao2015** [comment]
Hmm that seems possible. Personally haven't tested anything except for the rgbw but I'm surprised that rgbw worked in the first place now...

**Comment by betonishard** [comment]
@cheesemarathon @mariusmotea @alexyao2015 

Thanks..!
