### ISSUE TITLE
Remote Discovery?

### ISSUE THREAD

**Issue by ryancasler** [diyhue/diyHue#217]
What's the purpose of the new Remote Discovery script?  It appears to be calling out to your servers and uploading my IP address, internal IP address and MAC address.  What's the purpose of that information going to your servers?

**Comment by mariusmotea** [comment]
Is is similar to official https://discovery.meethue.com and it is made for HueEssentials app that is using it  and also to made detection process more simple for users automation tools. HueEssentials is becoming official app and if you check in the script header there is also a remoteApi script disabled by default that will let users to control the emulator remotely without to expose the service to internet in home router.

**Comment by ryancasler** [comment]
Will the emulator continue to work if it is not allowed to connect to discovery.diyhue.org?

**Comment by mariusmotea** [comment]
Absolutely. In case the local ip address of the emulator is changing the HueEssentials application may not detect the new ip address. That's all for the moment.

**Comment by mariusmotea** [comment]
i recommend to comment following line instead to block the traffic on firewall:
https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L1774

**Comment by ryancasler** [comment]
Thanks!
