### ISSUE TITLE
Hue app wants to update the hub

### ISSUE THREAD

**Issue by JulesHuisman** [diyhue/diyHue#218]
The official Hue app want to update the hub. However, this update fails. Now I am unable to enter the main part of the Hue app.

Re-installing the emulator and the app did not fix the problem.

**Comment by mariusmotea** [comment]
I update the swversion to 1934129020. Try again now. Is normal to see update fail message, but after you open again the hue app it must not ask again for update.

**Comment by JulesHuisman** [comment]
Thanks it is working now!

**Comment by sascha777** [comment]
I just ran into this issue, too. 
Everything was working smooth for a long time and all of the sudden I got this update message using the original Hue app with a Pi host install. The strange thing is that the update message only appears on my IOS smartphone. My wife’s android is still running ok. 
Restarting service and smartphone didn‘t help. 
Any ideas of what this could be?

**Comment by mariusmotea** [comment]
Update the code/docker image and it will work fine.

**Comment by sascha777** [comment]
Great, thanks! Reinstalled code and also reinstalled app did the job.
