### ISSUE TITLE
RGB light not avalible

### ISSUE THREAD

**Issue by caustinbakker** [diyhue/diyHue#22]
Hello, I am trying to get the lighting to work but getting little progress.
I am able to flash the 'generic on/off' on to my nodeMcu and it works perfectly with the hue app. But once i upload the RGB bulb, and i scan for the light it shows up and then says not avalible. If i deleted it and scan again for the light it shows up but i am unable to control it with the rgb bulb sketch. What could the problem be?

**Comment by caustinbakker** [comment]
I can go to the web interface but it seems to to be working with the dyihue

**Comment by mariusmotea** [comment]
two possible reasons. 
 1. If same device is used the mac address will remain the same, so better delete the light before you change the lights type
 2. wrong firmware version added by me with last update. I will try to fix this.

**Comment by caustinbakker** [comment]
I deleted the light in the philips hue app. Is there an extra step i need to take by deleting it on the dyihue.

**Comment by mariusmotea** [comment]
With what app you perform light search? Be aware the in internal webui only the light that are member to groups are displayed, fresh detected lights not.

Can you paste here the output of this command from your device with hue emulator:

`nmap  192.168.1.0/24 -p80 --open -n | grep report | cut -d ' ' -f5`

replace the subnet from the command with your.

**Comment by caustinbakker** [comment]
this is the response i am getting

`pi@raspberrypi:~ $ nmap 192.168.1.1/24 -p80 --open -n | grep report | cut -d ' ' -f5
192.168.1.1
192.168.1.11
192.168.1.12
192.168.1.13
192.168.1.14
192.168.1.31
`

**Comment by mariusmotea** [comment]
any ip belong to the light?

**Comment by caustinbakker** [comment]
Yes 192.168.1.11 is the rgb bulb

**Comment by caustinbakker** [comment]
I got this code from the debug. not sure why this is happening only with the rgb light
```
2019-01-04 09:59:51,669 - root - INFO - sync with lights
2019-01-04 09:59:51,824 - root - INFO - [
    "192.168.1.1",
    "192.168.1.12",
    "192.168.1.13",
    "192.168.1.14",
    "192.168.1.32",
    "192.168.1.31"
]
2019-01-04 09:59:52,545 - root - INFO - {
    "hue": "bulb",
    "lights": 1,
    "mac": "CC:50:E3:05:06:8C",
    "modelid": "LCT015",
    "name": "test Hue RGB Light"
}
2019-01-04 09:59:52,554 - root - INFO - 192.168.1.32 is a hue bulb
2019-01-04 09:59:52,557 - root - INFO - Add new light: test Hue RGB Light
2019-01-04 09:59:52,607 - root - INFO - registration fail, is the link button pressed?
192.168.1.15 - - [04/Jan/2019 09:59:53] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.15 - - [04/Jan/2019 09:59:53] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.1.15 - - [04/Jan/2019 09:59:55] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.15 - - [04/Jan/2019 09:59:55] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.1.15 - - [04/Jan/2019 09:59:57] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.15 - - [04/Jan/2019 09:59:57] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.1.15 - - [04/Jan/2019 09:59:59] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.15 - - [04/Jan/2019 09:59:59] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
192.168.1.15 - - [04/Jan/2019 10:00:00] "GET /api/a7161538be80d40b3de98dece6e91f90/config HTTP/1.1" 200 -
192.168.1.15 - - [04/Jan/2019 10:00:01] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
192.168.1.15 - - [04/Jan/2019 10:00:02] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
2019-01-04 10:00:03,073 - root - INFO - sync with lights
2019-01-04 10:00:03,269 - root - ERROR - light 1 is unreachable
Traceback (most recent call last):
  File "./HueEmulator3.py", line 855, in syncWithLights
    updateGroupStats(light)
  File "./HueEmulator3.py", line 749, in updateGroupStats
    if bridge_config["lights"][group_light]["state"]["on"]:
KeyError: '2'

```

**Comment by mariusmotea** [comment]
Please update the code to latest version because detection function was changed. If you still have errors i recommend to start with default config.json from this repo. Also, in case you delete the certificate remember to reinstall the hue app on you phone.

**Comment by caustinbakker** [comment]
I solved it by. uploading the on/off light again. Deleting the bulbs and then it worked again.
