### ISSUE TITLE
Problem with the discovery of the "generic dimmable light".

### ISSUE THREAD

**Issue by SvenGWK** [diyhue/diyHue#221]
I flashed a NodeMCUV2 with the Sketch for Generic Dimmable Light and want to control 5 lamps. 
The controller is connected to my Wifi and I can open the light controls in my browser.
Unfortunately, adding this via Hue Essentials does not work, no lamps are found.

I started Hue Emulator in debug mode and was surprised to see that my controller was found and correctly recognized as 5 lamps.

My adresses are:
192.168.2.1 wifi router
192.168.2.8 my PC
192.168.2.21 ESP8266 miLight hub
192.168.2.26 raspberry pi with diyHue
192.168.2.31 Smartphone with Hue Essentials app
192.168.2.32 NodeMCU with 5 dimmable lights

This should be the relevant logfile content (repetitive lines are removed):
```
2019-10-08 22:21:12,362 - root - INFO - [
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]:     "192.168.2.1:80",
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]:     "192.168.2.21:80",
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]:     "192.168.2.32:80"
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: ]
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:12,393 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.2.1:80
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:12,401 - urllib3.connectionpool - DEBUG - http://192.168.2.1:80 "GET /detect HTTP/1.1" 404 1703
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:12,415 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.2.21:80
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:12,447 - urllib3.connectionpool - DEBUG - http://192.168.2.21:80 "GET /detect HTTP/1.1" 404 18
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:12,462 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.2.32:80
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:12,752 - urllib3.connectionpool - DEBUG - http://192.168.2.32:80 "GET /detect HTTP/1.1" 200 74
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:12,760 - root - INFO - {
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]:     "hue": "bulb",
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]:     "lights": 5,
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]:     "mac": "c5:66:bf:12:cf:a4",
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]:     "modelid": "LWB010"
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: }
Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:12,762 - root - INFO - ip 192.168.2.32:80 is unknown device: 'name'
Oct  8 22:21:18 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:18,506 - root - DEBUG - Sending M-Search response to 192.168.2.31
Oct  8 22:21:41 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:41,825 - root - DEBUG - tasmota: probing ip 192.168.2.1
Oct  8 22:21:41 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:41,834 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.2.1:80
Oct  8 22:21:41 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:41,839 - root - DEBUG - Sending M-Search response to 192.168.2.31
Oct  8 22:21:41 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:41,843 - urllib3.connectionpool - DEBUG - http://192.168.2.1:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 1703
Oct  8 22:21:41 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:41,848 - root - DEBUG - tasmota: probing ip 192.168.2.21
Oct  8 22:21:41 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:41,856 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.2.21:80
Oct  8 22:21:41 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:41,871 - urllib3.connectionpool - DEBUG - http://192.168.2.21:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 14
Oct  8 22:21:41 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:41,881 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
Oct  8 22:21:41 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:41,886 - root - DEBUG - tasmota: probing ip 192.168.2.32
Oct  8 22:21:41 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:41,895 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.2.32:80
Oct  8 22:21:42 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:42,018 - urllib3.connectionpool - DEBUG - http://192.168.2.32:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 66
Oct  8 22:21:42 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:42,205 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 None
Oct  8 22:21:43 raspberrypi HueEmulator3.py[1198]: {"ok"}
Oct  8 22:21:43 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:43,744 - root - DEBUG - Sending M-Search response to 192.168.2.31
Oct  8 22:22:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:22:12,265 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
Oct  8 22:22:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:22:12,619 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 None
Oct  8 22:22:18 raspberrypi HueEmulator3.py[1198]: {"ok"}
Oct  8 22:22:18 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:22:18,617 - root - DEBUG - Sending M-Search response to 192.168.2.31
Oct  8 22:22:28 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:22:28,140 - root - DEBUG - Sending M-Search response to 192.168.2.8
```

Am I doing something wrong?

**Comment by mariusmotea** [comment]
Are you sure the lights where not detected in the first scan? I can say that even with official Hue app the lights are discovered but the display message is that no lights where detected.

**Comment by SvenGWK** [comment]
Yeah, I'm relatively sure. The app says nothing was found and I don't see any additional lamps when I try to add new lamps to a room.

**Comment by mariusmotea** [comment]
Ok, i will debug this as i want to provide best experience with HueEssentials app.

**Comment by SvenGWK** [comment]
Thank you so much for getting on with this issue!
A few years ago I have built up a system in my flat which ran completely with Arduinos and NRF24, controlled by an ESP8266 webserver. Graphics and .css for the configuration interface came from a FritzBox, which has been replaced by a current model. For this reason I couldn't use my self-built system anymore and started to switch to MiLight and diyHue.
Apart from the technical side, I no longer understand the software I wrote at that time.
I'd have to start from scratch and it would probably result in something that doesn't come close to the comfort of your system.
If I could now replace the Arduinos with NodeMCU's, I would save myself the purchase of 30 MiLightMR16 spots and in addition a lot of wiring, that would be fantastic. :-) 

I obviously misunderstood something and didn't thought that I can simply press the update button in the official app. Now the official Hue App works again. :-)

I started the device search right away, but the official app doesn't find anything either.
The All4Hue app also can't find anything, so it seems to be a problem that isn't limited to the Hue Essentials app.
Oh - in the latest update of the Hue Essentials app there was a hint yesterday that a new Discovery version is now included.

**Comment by SvenGWK** [comment]
I think I solved the problem.
I noticed this line in the log:
`Oct  8 22:21:12 raspberrypi HueEmulator3.py[1198]: 2019-10-08 22:21:12,762 - root - INFO - ip 192.168.2.32:80 is unknown device: 'name'`

So I inserted a name in the "Discovery" string.
I changed the line:
```
server.on("/detect", []() {
    server.send(200, "text/plain", "{\"hue\": \"bulb\",\"lights\": " + (String)LIGHTS_COUNT + ",\"modelid\": \"LWB010\",\"mac\": \"" + String(mac[5], HEX) + ":"  + String(mac[4], HEX) + ":" + String(mac[3], HEX) + ":" + String(mac[2], HEX) + ":" + String(mac[1], HEX) + ":" + String(mac[0], HEX) + "\"}");
  });
```

to:

```
server.on("/detect", []() {
    server.send(200, "text/plain", "{\"hue\": \"bulb\",\"lights\": " + (String)LIGHTS_COUNT + ",\"modelid\": \"LWB010\",\"name\": \"ESPHome-Dimmable\",\"mac\": \"" + String(mac[5], HEX) + ":"  + String(mac[4], HEX) + ":" + String(mac[3], HEX) + ":" + String(mac[2], HEX) + ":" + String(mac[1], HEX) + ":" + String(mac[0], HEX) + "\"}");
  });
```

With this change, the 5 lights will be discovered by Hue Essentials.

**Comment by SvenGWK** [comment]
I've been playing around a little now and stumbling across a new bug. I haven't connected any lamps yet, I watch the setting of the values via the serial output.
Only 4 of my 5 lamps work. 
As soon as the lamp number 2 is changed, the console crashes for unclear reasons.
`Server-Arg Light number:1
111
111
111
111
111
111
111
111
110
110
110
110
110
110
110
110
110
110
109
109
109
109
Server-Arg Light number:3
54
54
54
54
54
55
Ser⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮⸮ (and forever the same...)`

At first I thought I was using a pin which is used for the console. 
(Array content is: {5, 4, 12, 13, 14} ).
But it doesn't matter which pin I use, as soon as lamp 2 is changed it goes wrong.
My first suspicion was, that it might be the content of the variable sent by the Hue emulator that causes the problems in the output, but you can see from the aborted text that it obviously can't be. Something seems to go wrong on the server side. Unfortunately, I speak almost no Python, so the function of the emulator is still a mystery to me.

Maybe I had a beer too much or I just need to sleep, but at the moment I think that for some reason for lamp number 2 garbage is being sent from the server that is messing up the ESP.

I want to enhance this sketch to control up to 16 lights with the TLC5940 PWM controller.

**Comment by mariusmotea** [comment]
Is true, the `name` key become mandatory and that sketch remain not updated. Regarding the issue with light 2 i have no issues what is happening.

**Comment by SvenGWK** [comment]
Oh, you're right, of course!
So I "fixed" a bug that had already been fixed a long time ago... :-))
There must be some more changes in the current version, no more crashes. It all works now, so I will add the PWM controller in the next days and it looks like I can continue to use my existing lights. Amazing!

**Comment by SvenGWK** [comment]
Issue resolved, an outdated version of the sketch with bugs was used, which are already fixed in the current one.
