### ISSUE TITLE
Entertainment mode not working due to SSL issue

### ISSUE THREAD

**Issue by andyman1222** [diyhue/diyHue#226]
I've recently updated diyHUE and have been receiving an error while trying the entertainment mode. I believe I've reported a similar error once before, with an issue with Synapse, except this time it's not just Synapse.

The error:

```
Last error was: -30976 - SSL - Processing of the ClientHello handshake message failed

  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -0x7900
```

This occurs both when I'm trying to enable Razer Synapse, which uses entertainment, and when I try to "test area" within the app.

Note: my entertainment area has some 30 lights now, added via editing config,json, which is above the max 10 lights that the app allows, but I doubt that would have anything to do with SSL.

**Comment by mariusmotea** [comment]
The entertainment are suport max 10 lights. Is not possible to add more because the package has a fixed number of bites. When the number of lighs is less than then the data of remaining lights is filles with zeros.

**Comment by alexyao2015** [comment]
Closing this since there was no response and it seems to not be a bug
