### ISSUE TITLE
Stale Bot

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#229]
Why does stale bot exist? I get it that there are some issues that should be marked as stale but other issues are actually bugs that should be fixed. Closing the issue with stale bot hides problems with the application and never lets them get fixed. Issues should be manually closed either if they are non issues or have been fixed.

There are plenty of bugs that still exist and need to be completed but have been closed by stale bot. 

Case and point: #169 #180

**Comment by mariusmotea** [comment]
it is usefull because in lot of cases the user fix the problem himself and don't provide any feedback. I will check the interfal to increase it.

**Comment by alexyao2015** [comment]
Some of these issues won't get fixed if people can't find them because they are lumped together with fixed issues. It will bet buried and never fixed.

**Comment by mariusmotea** [comment]
If you want i can add you as member to the organization so you can apply labels. Once it is labeled as bug the issue will not be closed by stalebot
