### ISSUE TITLE
Milight bulbs lacks "rich colors" and identified kind of like Hue Bulb gen 1

### ISSUE THREAD

**Issue by huongminh** [diyhue/diyHue#241]
**Describe the bug**
I notice all my milight bulbs cannot show cyan and blue spectrum by the standard Hue app via the Hue emulator. When adding into entertainment area there is comment in Hue app saying they do not support "rich color", just like original Hue bulbs gen 1. When controlled directly by milight hub or other app (say via apple homekit, domoticz or smarthings), all color spectrum is available 

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.

**Additional context**

**Comment by alexyao2015** [comment]
Post your config.json

**Comment by alexyao2015** [comment]
Closing because no response

**Comment by huongminh** [comment]
> Closing because no response
Sorry, I missed your previous mail. Please find attached the config.json as requested:

[config json.txt](https://github.com/diyhue/diyHue/files/3805407/config.json.txt)
