### ISSUE TITLE
Website empty, but deconz connected and working

### ISSUE THREAD

**Issue by thetemplar** [diyhue/diyHue#243]
**Describe the bug**
Short: The Hue-Emulator site is empty, although I connected it to deconz (with raspbee) and the "turn all on" is working. It also works with android apps like "Hue Essentials".

Long: I needed to re-install diyHue and deCONZ, and therefore delete all saved settings. After a new configuration of deconz (+finding the lamps) I installed diyHue. Everything works as intended now, except that the list of diyHue is empty (see 1st screenshot). 
I can use the android app perfectly (which is re-connected to diyHue, not deconz) and the top-right button "Turn all on" also works on all the lights. 
How do I import the lights?
Also a ESP8266/WS2812 light was added via android-app, but is not listet anywhere.

Empty list:
![image](https://user-images.githubusercontent.com/5371336/67344608-cabf0200-f538-11e9-85d4-61dad086b407.png)

The /deconz screen, should it look this way?
![image](https://user-images.githubusercontent.com/5371336/67344619-d27ea680-f538-11e9-82cc-1296ba06d6b9.png)

**Comment by Mevel** [comment]
Lights will show up, after you have assigned a room / group to it via hue app.

`/deconz` shows sensors that are not directly emulated into original hue sensors. Original hue sensors that are imported via deconz and conbee module are directly shown in the app.

**Comment by thetemplar** [comment]
Thank you, this worked.
