### ISSUE TITLE
Add Type other to groups

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#244]
- [x] Room or Zone created without a class, automatically add class "other" to config

- [ ] If entertainment is specified without a class, return an error.

**Comment by Thomas-Vos** [comment]
So basically this means:

If "type" is not provided -> set type to "LightGroup"

If "type" has a value of "Room" or "Zone" and "class" is not provided -> "class" is set to "Other" automatically

If "type" has a value of "Entertainment" and "class" is not provided -> return error:
```json
[
  {
    "error": {
      "type": 5,
      "address": "/groups/class",
      "description": "invalid/missing parameters in body"
    }
  }
]
```

**Comment by mariusmotea** [comment]
I fix this with last commit

**Comment by Thomas-Vos** [comment]
@mariusmotea did you fix the class as well? See https://github.com/diyhue/diyHue/issues/244#issuecomment-546679864

**Comment by mariusmotea** [comment]
i fix now also the class. I put it to be "Other" according to Hue api. I fix lot of bugs today because i start with a fresh installation.

**Comment by Thomas-Vos** [comment]
That's great, but it should only do that for Room and Zone. A LightGroup for example cannot have a class.

Furthermore, "Other" is not a valid class for Entertainment.  The hue api gives an error in that case.

**Comment by mariusmotea** [comment]
Good to know. I will fix it.

**Comment by alexyao2015** [comment]
This bug still isn't fixed. We need to add in an error code if entertainment is specified without a class.

**Comment by alexyao2015** [comment]
It seems that returning an error might require potentially reworking the POST method. Seems like now it just returns success no matter what unless its an unauthorized user.

**Comment by mariusmotea** [comment]
the user must be in whitelist, check this line:
https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L1506
