### ISSUE TITLE
Entertainment mode high latency with ESP01

### ISSUE THREAD

**Issue by rkkoszewski** [diyhue/diyHue#246]
Hi,
This may or may not be a bug. I have a Philips TV and setup diyHue together with an ESP01 controller that connects to diyHue and controls the lights (From the Devices repo). It seems that the entertainment mode has a very visible latency (I would say of 1 to 2 seconds) from what is visible on screen and the diyHue light.

Is this normal? What is the latency of official Hue products? I have seen some videos on YouTube with the official Hue lamps using the entertainment mode and there was a visible latency between the screen and the lights, so maybe this is normal. But I have seen videos of the hue play bars which did not seem to suffer from the visible latency, which makes me think that there are different versions of the entertainment API.

I'm aware that network latency may be an issue, but I have the TV connected via ethernet and the ESP01 via WiFi right next to the router. Previously I was using a Dreamscreen device which also has a UDP protocol to send colors to WiFi connected light devices where both the sender device is connected through WiFi and then the light itself is also connected by WiFi, and it was able to push color updates at 60fps without any visible latency (with a much more complex protocol that had special headers, payloads and CRC checks for ever frame), so 60fps is clearly not an impossible thing to achieve.

Is there anybody who could shed some light on how much latency the original Hue devices have with the entertainment API and what kind of latencies should be expected with diyHue in the same mode. Is there any way to reduce the latency with diyHue?

**Comment by mariusmotea** [comment]
Hi,

Philips TV's don't use entertainment mode (not sure about recent ones), so probably this is the reason why have latency. Try Hue Sync and check if you still have latency

**Comment by rkkoszewski** [comment]
Hi @mariusmotea ,
How can I enable hue sync mode? On the TV the light shows as "Extended color light". 
Is there any way to announce the device as a hue play bar?

**Comment by mariusmotea** [comment]
I think the TV is not that advanced to support fast entertainment frames. I have two 2017 Philips TV's and both work with http hue api protocol, not entertainment.

**Comment by alexyao2015** [comment]
Hmm I'm curious at least with ESPHome, I could change it so it only uses UDP to send light changes which would be significantly faster, potentially same with native firmwares as well. Unsure of downsides to doing this. 

@mariusmotea Any ideas of disadvantages to only using UDP?

**Comment by rkkoszewski** [comment]
I can just confirm that the TV is just hammering the HTTP REST API rather than using the Entertainment API. I tried Hue Sync on my PC and with the Entertainment API there is nearly no perceivable latency.

I really hope Philips will update their TV software to properly support entertainment API.. 

@alexyao2025 The biggest downside of UDP are lost frames. It might not happen often in a LAN but it can. It usually doesn't matter when there are many updates to loose a frame or two, but of you loose the last frame or just do a single update that gets lost, it may leave the light in an inconsistent state unless you create some verification protocol of some kind. 

As of this bug report I think it can be closed, as it seems that the Philips TVs don't (hopefully just yet) do not support the Entertainment API unless there is some secret way to enable it. I'll still try to get some more info regarding that.

**Comment by alexyao2015** [comment]
Hmm yeah that is true about frame loss.

**Comment by mariusmotea** [comment]
UDP is only way to go with such protocols, because is not important to ensure all data is received, important is to display the data as fast as possible. In case of network intrerruption is better to 
ignore the lost packages instead of displaying them with high latency.

**Comment by rkkoszewski** [comment]
Hi @mariusmotea @alexyao2015 
I just noticed something interesting in the Hue settings on my Philips TV. In the section "Immersion" it says that that option is only useful when the Hue bridge does not support "entertainment capability", which should be the "Entertainment API". 

Here is a photo of the menu:
![20191102_152850](https://user-images.githubusercontent.com/2161487/68072679-7b72a000-fd88-11e9-8e7b-3d0a9029dadf.jpg)

Which makes me understand that the TV does support Entertainment mode but it detects the bridge or the bulb as not capable of it. Hue Sync on PC detects the diyHue and Entertainment mode works, maybe the TV uses some other method of detecting the Entertainment mode? Any ideas?

**Comment by mariusmotea** [comment]
Is hard to figure what method the tv is using except the apiversion and swversion of the bridge.

**Comment by alexyao2015** [comment]
I don't have one personally nor do I have an actual bridge so unless you have both of those and can test to see if it's using entertainment mode, it's not something we can fix.

**Comment by Paalap** [comment]
Is it maybe because diyhue is recognized as hub v1?

**Comment by mariusmotea** [comment]
No, is v2, otherwise Hue Sync will not work.

**Comment by Paalap** [comment]
Ok, was just an idea because of the icon
