### ISSUE TITLE
HueEmulator3 crashes with struct.error: argument for 's' must be a bytes object in OpenWrt 18.06.4 (LXC)

### ISSUE THREAD

**Issue by rkkoszewski** [diyhue/diyHue#247]
**Describe the bug**
Hi,
I'm trying to run diyHue in OpenWrt 18.06.4. But the service fails to start.
The exception I get when running HueEmulator3.py manually is as follows:

```
python3 /opt/hue-emulator/HueEmulator3.py
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 71, in <module>
    HOST_IP = getIpAddress()
  File "/opt/hue-emulator/functions/network.py", line 30, in getIpAddress
    ip = get_interface_ip(ifname)
  File "/opt/hue-emulator/functions/network.py", line 11, in get_interface_ip
    ifname[:15]))[20:24])
struct.error: argument for 's' must be a bytes object
```

Some info on my system:
On OpenWrt 18.06.4 (x86_64) running inside a LXC container.

- Kernel: Linux huebridge 5.0.21-3-pve x86_64 GNU/Linux
- Python: 3.6.9

**Comment by mariusmotea** [comment]
I saw your PR, thanks. I will consider this fixed and i will close it.
