### ISSUE TITLE
Hue-Emulator not starting "syntax error: invalid syntax"

### ISSUE THREAD

**Issue by philipphunger** [diyhue/diyHue#249]
**Describe the bug**
starting the emulator gives me the error:
-----------------------------------------------------------------------------------
./HueEmulator3.py
  File "./HueEmulator3.py", line 1512
    if post_dictionary["type"] == "Room" and class" not in post_dictionary:
                                                 ^
SyntaxError: invalid syntax
-----------------------------------------------------------------------------------

none of the command-line arguments are working (--debug and so on)

**Comment by mariusmotea** [comment]
Oops, is a bug introduced by me few minutes ago

**Comment by philipphunger** [comment]
i think theres an typo error 
"Room and "class" ???

**Comment by mariusmotea** [comment]
Fixed

**Comment by philipphunger** [comment]
thanks
