### ISSUE TITLE
Diyhue Crash after update on Docker running on Unraid

### ISSUE THREAD

**Issue by phutruong1801** [diyhue/diyHue#252]
I have just updated the Diyhue App running on Docker, Unraid. Yesterday the app running very well, but today after update the app, it was totally crash. cant start the app, and it's showed up the error like below? 

**"
Host MAC given as bc5ff4cdc619
Docker Setup Initiated
Restoring Certificate
Certificate Restored
Restoring config
Config restored
Docker Setup Complete
Traceback (most recent call last):
File "/opt/hue-emulator/HueEmulator3.py", line 1809, in <module>
updateConfig()
File "/opt/hue-emulator/HueEmulator3.py", line 220, in updateConfig
scene["type"] = LightGroup
NameError: name 'LightGroup' is not defined
Host MAC given as bc5ff4cdc619
Docker Setup Initiated
Restoring Certificate
Certificate Restored
Restoring config
Config restored
Docker Setup Complete
Traceback (most recent call last):
File "/opt/hue-emulator/HueEmulator3.py", line 1809, in <module>
updateConfig()
File "/opt/hue-emulator/HueEmulator3.py", line 220, in updateConfig
scene["type"] = LightGroup
NameError: name 'LightGroup' is not defined
Host MAC given as bc5ff4cdc619
Docker Setup Initiated
Restoring Certificate
Certificate Restored
Restoring config
Config restored
Docker Setup Complete
Traceback (most recent call last):
File "/opt/hue-emulator/HueEmulator3.py", line 1809, in <module>
updateConfig()
File "/opt/hue-emulator/HueEmulator3.py", line 220, in updateConfig
scene["type"] = LightGroup
NameError: name 'LightGroup' is not defined**

Please help me fix it if i can manually adjusted the file.

and there are no debug log, because i can't run the app. 

I cant run the diyhue App in bridge mode or host mode. just custom Bro mode. but the previous version running very well. everything work well.

Thanks you so much!!!

**Comment by phutruong1801** [comment]
After changing and change back the Hue-emulater direction, it's work again. close issue.

**Comment by mariusmotea** [comment]
The bug is fixed now. Thanks for log.
