### ISSUE TITLE
Breakdown HueEmulator3.py into Modules

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#253]
Create modules for sections of HueEmulator. Right now, its way too long and hard to read to easily find and fix bugs. 

- [ ] Tradfri Module
- [ ] Deconz Module
- [ ] Native Lights Module
- [ ] Sensors Module (POST, GET, DELETE)
- [ ] Scenes Module (POST, GET, DELETE)
- [ ] Groups Module (POST, GET, DELETE)
- [ ] Response Code Module

**Comment by Mevel** [comment]
Good idea!

**Comment by 0x47726567** [comment]
Submitted a pr for initial work of this. #389

**Comment by gmallios** [comment]
Hey i'm working on this and i have moved commonly used variables such as bridge_config, new_lights, dxState and cwd to a Globals.py file. Is this a good idea in your opinion?

**Comment by alexyao2015** [comment]
Hi there has already been a lot of progress towards this in the master-refactor branch. Feel free to contribute there.

**Comment by mariusmotea** [comment]
Bridge_config need to remaim separate because it store the configuration which is dumped in json when some changes are made.

**Comment by alexyao2015** [comment]
Not necessarily. It works pretty much the same as before right now. There have been 0 functional changes but the backend code has been changed significantly. The plan is to build a responsebuilder package which create the responses and dump them out as json accordingly.

**Comment by alexyao2015** [comment]
@mariusmotea I think this latest change here achieves what you have been wanting to do with separating the actual bridge config and emulator config. At least it provides the baseline for it and makes doing so easier.
1a41728e2beb785b660328204c341d1cd8012846

**Comment by gmallios** [comment]
@alexyao2015  So you want to separate the webserver and the response logic so that the server just calls the response builder and just sends the json data to the client?

**Comment by alexyao2015** [comment]
Ideally, yes. If you take a look at the webserver file, it is over 1k lines since there is so much logic being done there. Things from adding devices, changing settings, and building the response are all done in the webserver file when each of those actions should be done elsewhere.

**Comment by mariusmotea** [comment]
@gmallios please look at flask branch. I want to perform the switch to flask in order to create a new web interface. Currently it is working, there are some minor bugs which i hope to fix soon.

**Comment by gmallios** [comment]
Yeah i think first transitioning to flask and then designing a response builder is what should be done. But i cant think how a response builder class would be structured.

**Comment by alexyao2015** [comment]
No need. A ton of this is slowly but surely being taken care of as I have time. I am quite in favor of using django since it is quite robust. Marius and I are working separately, and my work is in master-refactor and marius's is in flask. 
I am not sure of the status of the flask branch, but the master-refactor branch is getting closer to completion of this issue. The next stage would be to implement the response builder and, following that, django.

Even if you are unable to help by contributing code, you can still help by beta testing the master-refactor branch builds which are available on Docker Hub under the tag ```master-refactor```.

**Comment by alex-polosky** [comment]
Is this still being worked on?

I know that the work was being done on `master-refactor`, but it looks like that is now gone. Looking at the slack messages at some point that was removed, and only `master` / `dev` exist to work off of.

Looking at the tags, it looks like 2.1 exists with some weird src structure. I'm looking at `flask` and `beta`, and neither of those seem to be it.

I do see `experimental`, which seems to be on parity with tag 2.1, but that hasn't had any commits since the end of December.

I wouldn't mind helping out with this, just need to know where to look.

**Comment by mariusmotea** [comment]
beta branch will be the next master. It has now support for last Hue Sync and Hue App V4. Currently still in tests, but number of bugs decrease very fast.
