### ISSUE TITLE
OpenWRT update script chooses always MIPS binary for entertain-srv

### ISSUE THREAD

**Issue by rkkoszewski** [diyhue/diyHue#258]
**Describe the bug**
The update script for OpenWRT uses always the MIPS entertain-srv binary. Also the 64bit binary doesn't seem to work.

**To Reproduce**
Install diyHue in OpenWRT on a 64bit (Non ARM) CPU and try to run  entertain-srv.

**Expected behavior**
entertain-srv should run

**Comment by juanesf** [comment]
https://github.com/diyhue/diyHue/commit/4b49324c0feabe344d24501bdea8baa852028ce6

select the correct binary during installation

**Comment by juanesf** [comment]
I think this is solved at the moment, there is also an OpenWrt-arm binary that I will soon add

**Comment by alexyao2015** [comment]
Since it seems like @juanesf added commits to resolve this, I'll be closing this now.
