### ISSUE TITLE
Can't Connect to Lights when failure happens for lower IP addresses

### ISSUE THREAD

**Issue by jstonedotorg** [diyhue/diyHue#260]
I was trying to add lights to my diyHue bridge, but it failed every time.  My sk6812 lights on an esp8266 board were on IP address 192.168.1.46.  I have a bond ceiling fan controller on 192.168.1.25 (both set by DHCP).  When the scan for lights function gets to the bond ceiling fan controller, I think the controller doesn't send back any response to diyhue's request which causes an error.  This causes the loop that checks IP addresses for lights to stop checking, and my lights on the higher IP address 192.168.1.46 never get added.  I was able to work around the issue by unplugging the bond ceiling fan controller when I add lights to diyHue.

Also, I thought I'd let you know that I installed diyHue on a raspberry pi zero wh, and it seems to be working well so far (other than the above problem).  (I hadn't seen anyone use the cheap zero, so I thought I'd let you know it works so far.)

Here is the code section in HueEmulator3.py:

> def scan_for_lights(): #scan for ESP8266 lights and strips
>     Thread(target=yeelight.discover, args=[bridge_config, new_lights]).start()
>     Thread(target=tasmota.discover, args=[bridge_config, new_lights]).start()
>     Thread(target=esphome.discover, args=[bridge_config, new_lights]).start()
>     #return all host that listen on port 80
>     device_ips = find_hosts(80)
>     logging.info(pretty_json(device_ips))
>     logging.debug('devs', device_ips)
>     for ip in device_ips:
>         try:
>             response = requests.get("http://" + ip + "/detect", timeout=3)

Here is the section of the log file where it fails:

> 2019-10-29 14:00:19,969 - root - INFO - in post method
> 2019-10-29 14:00:19,979 - root - INFO - b'{}'
> 2019-10-29 14:00:19,991 - root - DEBUG - tasmota: <discover> invoked!
> 2019-10-29 14:00:20,013 - root - DEBUG - ESPHome: <discover> invoked!
> 2019-10-29 14:00:22,991 - root - DEBUG - Yeelight search end
> 2019-10-29 14:00:23,534 - root - INFO - sync with lights
> 2019-10-29 14:00:24,940 - root - DEBUG - Sending M-Search response to 192.168.1.31
> 2019-10-29 14:00:25,272 - root - INFO - [
>     "192.168.1.1:80",
>     "192.168.1.10:80",
>     "192.168.1.15:80",
>     "192.168.1.24:80",
>     "192.168.1.25:80",
>     "192.168.1.31:80",
>     "192.168.1.36:80",
>     "192.168.1.46:80"
> ]
> --- Logging error ---
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
>     msg = self.format(record)
>   File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
>     return fmt.format(record)
>   File "/usr/lib/python3.7/logging/__init__.py", line 619, in format
>     record.message = record.getMessage()
>   File "/usr/lib/python3.7/logging/__init__.py", line 380, in getMessage
>     msg = msg % self.args
> TypeError: not all arguments converted during string formatting
> Call stack:
>   File "/usr/lib/python3.7/threading.py", line 885, in _bootstrap
>     self._bootstrap_inner()
>   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.7/threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "./HueEmulator3.py", line 650, in scan_for_lights
>     logging.debug('devs', device_ips)
> Message: 'devs'
> Arguments: (['192.168.1.1:80', '192.168.1.10:80', '192.168.1.15:80', '192.168.1.24:80', '192.168.1.25:80', '192.168.1.31:80', '192.168.1.36:80', '192.168.1.46:80'],)
> 2019-10-29 14:00:25,381 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.1:80
> 2019-10-29 14:00:25,480 - urllib3.connectionpool - DEBUG - http://192.168.1.1:80 "GET /detect HTTP/1.1" 401 None
> 2019-10-29 14:00:25,520 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.10:80
> 2019-10-29 14:00:25,558 - urllib3.connectionpool - DEBUG - http://192.168.1.10:80 "GET /detect HTTP/1.1" 404 343
> 2019-10-29 14:00:25,591 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.15:80
> 2019-10-29 14:00:26,021 - urllib3.connectionpool - DEBUG - http://192.168.1.15:80 "GET /detect HTTP/1.1" 404 None
> 2019-10-29 14:00:26,070 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.24:80
> 2019-10-29 14:00:26,091 - urllib3.connectionpool - DEBUG - http://192.168.1.24:80 "GET /detect HTTP/1.1" 404 None
> 2019-10-29 14:00:26,137 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.25:80
> 2019-10-29 14:00:29,246 - root - INFO - ip 192.168.1.25:80 is unknown device: HTTPConnectionPool(host='192.168.1.25', port=80): Read timed out. (read timeout=3)
> Exception in thread Thread-58:
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
>     six.raise_from(e, None)
>   File "<string>", line 3, in raise_from
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
>     httplib_response = conn.getresponse()
>   File "/usr/lib/python3.7/http/client.py", line 1321, in getresponse
>     response.begin()
>   File "/usr/lib/python3.7/http/client.py", line 296, in begin
>     version, status, reason = self._read_status()
>   File "/usr/lib/python3.7/http/client.py", line 257, in _read_status
>     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
>   File "/usr/lib/python3.7/socket.py", line 589, in readinto
>     return self._sock.recv_into(b)
> socket.timeout: timed out
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
>     timeout=timeout
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
>     _stacktrace=sys.exc_info()[2])
>   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 367, in increment
>     raise six.reraise(type(error), error, _stacktrace)
>   File "/usr/lib/python3/dist-packages/six.py", line 693, in reraise
>     raise value
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
>     chunked=chunked)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
>     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
>   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 306, in _raise_timeout
>     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
> urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='192.168.1.25', port=80): Read timed out. (read timeout=3)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.7/threading.py", line 865, in run
>     self._target(*self._args, **self._kwargs)
>   File "./HueEmulator3.py", line 653, in scan_for_lights
>     response = requests.get("http://" + ip + "/detect", timeout=3)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 75, in get
>     return request('get', url, params=params, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
>     return session.request(method=method, url=url, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
>     r = adapter.send(request, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 529, in send
>     raise ReadTimeout(e, request=request)
> requests.exceptions.ReadTimeout: HTTPConnectionPool(host='192.168.1.25', port=80): Read timed out. (read timeout=3)
> 
> 2019-10-29 14:00:30,506 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
> 2019-10-29 14:00:32,148 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 None
> {"ok"}
> 2019-10-29 14:00:34,365 - root - DEBUG - tasmota: probing ip 192.168.1.1
> 2019-10-29 14:00:34,394 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.1:80
> 2019-10-29 14:00:34,413 - urllib3.connectionpool - DEBUG - http://192.168.1.1:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 401 None
> 2019-10-29 14:00:34,434 - root - DEBUG - tasmota: probing ip 192.168.1.10
> 2019-10-29 14:00:34,457 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.10:80
> 2019-10-29 14:00:34,475 - urllib3.connectionpool - DEBUG - http://192.168.1.10:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 343
> 2019-10-29 14:00:34,489 - root - DEBUG - tasmota: probing ip 192.168.1.15
> 2019-10-29 14:00:34,514 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.15:80
> 2019-10-29 14:00:34,540 - urllib3.connectionpool - DEBUG - http://192.168.1.15:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 None
> 2019-10-29 14:00:34,550 - root - DEBUG - tasmota: probing ip 192.168.1.24
> 2019-10-29 14:00:34,552 - root - INFO - sync with lights
> 2019-10-29 14:00:34,576 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.24:80
> 2019-10-29 14:00:34,594 - urllib3.connectionpool - DEBUG - http://192.168.1.24:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 None
> 2019-10-29 14:00:34,606 - root - DEBUG - tasmota: probing ip 192.168.1.25
> 2019-10-29 14:00:34,628 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.25:80
> 2019-10-29 14:00:35,379 - root - DEBUG - Sending M-Search response to 192.168.1.31
> 2019-10-29 14:00:37,647 - root - DEBUG - tasmota: ip 192.168.1.25 is unknow device, HTTPConnectionPool(host='192.168.1.25', port=80): Read timed out. (read timeout=3)
> 2019-10-29 14:00:37,650 - root - DEBUG - tasmota: probing ip 192.168.1.31
> 2019-10-29 14:00:37,685 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.31:80
> 2019-10-29 14:00:37,703 - urllib3.connectionpool - DEBUG - http://192.168.1.31:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 0
> 2019-10-29 14:00:37,717 - root - DEBUG - tasmota: probing ip 192.168.1.36
> 2019-10-29 14:00:37,751 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.36:80
> 2019-10-29 14:00:37,796 - urllib3.connectionpool - DEBUG - http://192.168.1.36:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 15
> 2019-10-29 14:00:37,808 - root - DEBUG - tasmota: probing ip 192.168.1.46
> 2019-10-29 14:00:37,830 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.46:80
> 2019-10-29 14:00:37,855 - urllib3.connectionpool - DEBUG - http://192.168.1.46:80 "GET /cm?cmnd=Status%200 HTTP/1.1" 404 66

**Comment by alexyao2015** [comment]
Ugh scanning has been an issue that needs to be completely reworked. #180

**Comment by jstonedotorg** [comment]
> 
> 
> Also #157

So it sounds like I just need to remove the "raise" on line 720 of HueEmulator3.py, and that will let it loop through the rest of the IP addresses?  It sounds like it isn't a solution for all of 180, but seems like a better work around that unplugging my Bond when I install new lights.

Thanks.

**Comment by jstonedotorg** [comment]
Wow.  Thanks for doing that so quick.
