### ISSUE TITLE
Limit of scenes

### ISSUE THREAD

**Issue by AxelF1977** [diyhue/diyHue#265]
As I wrote, I´m new to github issuses, so I don´,t know, if it´s ok to aks my question. If  not, please delete.

Is there the same number of scenes, 200, in diyhue? That´s the reason for me, to change the bride to diyhue.

In the hue essential app, I´ve seen that there are also only just 200 scenes in the bridge diyhue.

Thanks

**Comment by mariusmotea** [comment]
There are no limits on bridge emulator, you can save as many scenes and rules you want.
