### ISSUE TITLE
Problem with remote api

### ISSUE THREAD

**Issue by Scotty-89** [diyhue/diyHue#268]
Hello,

I have an problem with the remote api  it wouldn't work ...
I activate the away from home in the essential app but it is not working  

If I check on https://discovery.diyhue.org/ I will geht only []
I use an raspberry to run the diyhue    someone can help me I would like to use some more efects out of hue laps etc     like color wiping :) 

Thx

**Comment by mariusmotea** [comment]
Do you use a recent version? Discovery usr may not work if you have public ipv6 ip's on bridge.

**Comment by Scotty-89** [comment]
The hue app says  version 1.24.0 / 1934129020 or what you mean?

How can I check for public ipv6 is on the pi ? I only install raperian and diyhue :)

**Comment by mariusmotea** [comment]
Please run again the install script. This will update the bridge emulator. Remote api was added one month ago, probably you use an older version.

**Comment by Scotty-89** [comment]
hey i run the installer again and disable the ipv6 on the pi but still the same ^^

**Comment by mariusmotea** [comment]
Do you use host or docker version? If you execute from emulator host the command `curl https://discovery.diyhue.org `do you receive similar output?

```
curl https://discovery.diyhue.org
[{"id": "dca632fffe0059d6", "internalipaddress": "192.168.10.112"}]
```

Another command to check if you enabled the remote api is `grep "Remote API enabled" /opt/hue-emulator/config.json`

example:
```
pi@diyhue:~ $ grep "Remote API enabled" /opt/hue-emulator/config.json 
        "Remote API enabled": true,
```

If this still don't provide any help you may need to start the emulator in debug mode (explained in wiki).

**Comment by Scotty-89** [comment]
i use the host version on a pi ;) because it istint run freely on my Synology because of the port 80 problem ^^ 

if i check  curl https://discovery.diyhue.org i get something ;) see below.
but the Hue Essentials istn working out of the WiFi...

pi@raspberrypi:~ $ curl https://discovery.diyhue.org
[{"id": "b827ebfffee137f1", "internalipaddress": "192.168.178.49"}]pi@raspberryp

**Comment by mariusmotea** [comment]
What version of Hue Essentials are you using (Settings => About)? Must be 1.6.0

**Comment by Scotty-89** [comment]
yes it is 1.6.0 ....

**Comment by mariusmotea** [comment]
`grep "Hue Essentials key" /opt/hue-emulator/config.json` please provide me last 5 characters of the long hash. I can check if it reach the remote api server.

**Comment by Scotty-89** [comment]
hello,

i solve this Problem ...  i delete all the cache and data off the Hue Essentials app .... after the new "installation"  it seems to work out off the Wifi ;) 

But manybe someone can help ...   i still have the Problem that if i "install" some effects on the bride they wont do ... only if i store the effect on the Hue Essentials app they will work... 
is this normal ??

**Comment by mariusmotea** [comment]
We are aware of the problem with the effects and hope to find time to fix it soon

**Comment by Scotty-89** [comment]
ok thx ...
one more Question ^^ it is possible to use the Hue laps features ??? 
And the remote out oh the original Hue app ? not or ?

**Comment by mariusmotea** [comment]
No,  all official cloud services are not working. We provide similar remote api, but only Hue Essentials is made to use it.

**Comment by Scotty-89** [comment]
ok thx verry much .. so hopefully the effects on the bride will work soon ;)
