### ISSUE TITLE
Last State not working Wemos D1 min :(

### ISSUE THREAD

**Issue by Scotty-89** [diyhue/diyHue#269]
Hello,

actualy i have the problem that the setting will not save over an power cycle ..
so i would like to use the function "start up = last state"  so that my child can chose an liked collor and have this up to the next pwercycle ;)   

the only thing what will save is if i setup for start-up "on" and chose an sceene...

**Comment by alexyao2015** [comment]
Please use the slack for support questions. If you have a bug, please provide logs and additional data to debug the issue. Follow the template.
