### ISSUE TITLE
Google assistant /account.meethue.com does not find bridge

### ISSUE THREAD

**Issue by HudsonProdigy** [diyhue/diyHue#27]
When attempting to log into phillips hue account for linking with google assistant or out of home control. no bridge is found. but when in phillips hue app the bridge is found and can control lights.  

my setup is ubuntu vm running bridge.

any help would be appreciated.

Cheers

**Comment by mariusmotea** [comment]
Anything related to Remote API is not working as this is private traffic to Philips Cloud servers with a high level of security.

**Comment by Ryan911199** [comment]
Does this mean I can not use the google assistant for any lights connected to this hub? If not is there anyone working on supporting this?

**Comment by cheesemarathon** [comment]
The only way to get google assistant to work with diyHue is to set it up to talk via home assistant or possibly OpenHAB though I have not used that. This can be done for free, you don't have to use HomeAssistant cloud.
