### ISSUE TITLE
Generic_ON_OFF_device can't found by hue.

### ISSUE THREAD

**Issue by chuz** [diyhue/diyHue#273]
**Describe the bug**
Generic_ON_OFF_device can't found by hue. I download the code to esp8266, and I can connect the device when it boot first time. But when I setup the Wifi, hue can't discover this device.

**Comment by mariusmotea** [comment]
you must start the emulator in debug to see what is displayed during the light search.

**Comment by chuz** [comment]
OK, Let me get this log tonight.

**Comment by chuz** [comment]
Doest diyhue support by some Voice assistant? Like Little love sound， xiao du sound.

**Comment by alexyao2015** [comment]
This should be moved to the slack channel. First start by posting a log while scanning and making sure the ip of the device is accessible over the network. If we determine its a bug with diyhue itself, open an issue. This is not a bug with the program.
