### ISSUE TITLE
Can not pair hue emulator or HueStrips - RaspberryPi 3 - Stretch and Buster

### ISSUE THREAD

**Issue by HudsonProdigy** [diyhue/diyHue#274]
**Describe the bug**
Host Install:
on host install deployment i can get the hue bridge emulator to link but then it will not find any lights and get stuck on add lights screen.
Docker Install:
when using docker image image emulator will not link at all. After i push activate button from hue web link form the app does not connect. nothing happens. 

Reproduce:
I am very tired of fresh installs of raspbian so would like to work with docker from here on. 
after fresh install of docker and running docker image i can navigate to ip of emulator and get web interface. I then go to hue app on ios and bridge can be found. Once found  i push connect on app. when asked to push link button i navigate to web interface and active link. Nothing happens app times out and says no bridge found.

Logs:
i am unsure where to access logs if more information can be shared on this i can post logs.

any and all help would be appreciated. Thanks

**Comment by mariusmotea** [comment]
Youa are using Android or iOS? On every reinstall you must reinstall also the hue app otherwise will not pair because the certificate on the bridge was changed.

**Comment by HudsonProdigy** [comment]
I am using ios app on iphone and ipad i have tried. and i have deleted app when i reinstall. when i redownload app though it continues where i left off. makes me think app data is persistent through app deletion. is there way to full wipe app + data? or is delete and reinstall enough?

**Comment by HudsonProdigy** [comment]
Deleting app after fresh install was able to get bridge to sync. I am unable to find any lights now though. It’s stuck on the add lights page. I’m using the ws2812 Arduino sketch from diyhue lights. I can access the strips from there ip and control no problem but bridge emulator can’t find them.

**Comment by HudsonProdigy** [comment]
After resetting bridge connection again it found lights but can not create room or save config. I get the “saving could take a while . Please keep the app open until save is completed” but it never completes

**Comment by alexyao2015** [comment]
I would try wiping your config and starting fresh with diyhue and the app. You can find information regarding debug mode for logs in the docs. It is also possible to manually add a light to the config.

This does not appear to be a bug with diyhue, so find support in the slack. If it happens to be an actual bug, report back with logs and a detailed description.
