### ISSUE TITLE
Docker diyHue - generateSensorsState is not defined

### ISSUE THREAD

**Issue by MaxiBerdy** [diyhue/diyHue#275]
Hello,

I am currently trying to use diyHub with a docker image, to test out if the hub would work with an Android app called Sleep as Android. I am using a NodeMCU 1.0 to test out some lights (currently using the sketch file "Generic_ON_OFF_device" with the on-board led to try it out).

**Describe the bug**
I ran into some bugs when trying to add a room to my Philips Hue hub on my phone, turns out there is a problem with the function called "generateSensorsState" when trying to add the room.
A friend of mine and I were wondering what could be the problem, so we tried to change the config of the lights, using different sketches, etc... And we also found out that the file "config.json" would be recovered every time we would reinstall the docker machine. I'm not sure that this is supposed to be the case, because if you want to completely reset your configs, that's what users would do in the first place.
We could in the end find out that docker was recovering config files from and other folder ("export/config.json")

**To Reproduce**
1. Install the latest docker build on a machine
2. Flash one of the example sketches and setup as described on https://diyhue.readthedocs.io/en/latest/lights/diylights.html
3. Use the app Philips Hue on the app store and launch it
4. Press configure, and accept the setup by going on the diyHue page on the computer running the docker
5. Add lights to a room and try creating that room
6. You get an error message saying you were disconnected from the Hue hub and then reconnects right away. In the logs of the docker machine you can find that the function generateSensorsState is causing the error. (NameError: name 'generateSensorsState' is not defined, at File "/opt/hue-emulator/HueEmulator3.py", line 1585, in do_POST)

**Expected behavior**
It should go past the configuration without any hassle, I guess ? Maybe it has to do with the fact there is a "sensor" setting in the config.json file, even if you don't physically own a sensor, so it cannot resolve the sensor ? (I don't really know why this is happening to be honest...)

**Logs**
https://pastebin.com/PLkrhjet

**Docker Info (please complete the following information):**
- Architecture: x64
- Docker image version: latest
 - Hardware: PC running Kubuntu 19.04 with docker 18.06.1-ce build e68fc7a

**Additional context**
None

Thank you for your help and patience.

**Comment by alexyao2015** [comment]
Something doesn't make sense. The function "generateSensorsState" does not exist at all in the source code of the HueEmulator3.py file. You are either running a modified version or older version of diyhue. Update the image. This is not an issue with diyhue, so it will be closed. For support, join the slack channel.

**Comment by alexyao2015** [comment]
Actually, I take that back. There was actually a bug, but it has since been fixed. Check out this commit.

https://github.com/diyhue/diyHue/commit/20d4e3702a7f475959b74bc98d59d831cc1a1a8a

**Comment by mariusmotea** [comment]
Yes, was my mistake. As Hue Essentials use dx rules for group states i extend the support from just the sensors also to lights and groups, so the name of the function cannot remain `generateSensorsState`
