### ISSUE TITLE
Philips TV Ambilight connection error

### ISSUE THREAD

**Issue by ilkekaratas** [diyhue/diyHue#279]
My 58pus7304 finds the hue emulator but when I try to continue the process it quits and send me the main menu. 

I have my hue emulator set up in lattepanda on ubuntu. It works with Hue App in iPhone with no problems. I am able to control the lights. But no luck with my philips tv. 

> 192.168.1.38 - - [12/Nov/2019 22:55:18] "GET /description.xml HTTP/1.1" 200 -
> 2019-11-12 22:55:18,737 - root - DEBUG - Sending M-Search response to 192.168.1.37
> 
> 2019-11-12 22:55:20,641 - root - DEBUG - Sending M-Search response to 192.168.1.249
> 2019-11-12 22:55:28,151 - root - DEBUG - Sending M-Search response to 192.168.1.38
> 2019-11-12 22:55:29,120 - requests.packages.urllib3.connectionpool - INFO - Starting new HTTPS connection (1): discovery.diyhue.org
> 2019-11-12 22:55:29,354 - root - DEBUG - Sending M-Search response to 192.168.1.38
> 2019-11-12 22:55:29,667 - requests.packages.urllib3.connectionpool - DEBUG - "POST / HTTP/1.1" 200 None
> 
> 2019-11-12 22:55:30,857 - root - DEBUG - Sending M-Search response to 192.168.1.38
> 192.168.1.38 - - [12/Nov/2019 22:55:32] "GET /api/null HTTP/1.1" 200 -
> 
IP is 192.168.1.38. 

Also 

> admin@lattepanda:~$ curl https://127.0.0.1/api/nouser/config -k -v
> *   Trying 127.0.0.1...
> * Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
> * found 148 certificates in /etc/ssl/certs/ca-certificates.crt
> * found 597 certificates in /etc/ssl/certs
> * ALPN, offering http/1.1
> * SSL connection using TLS1.2 / ECDHE_ECDSA_AES_128_GCM_SHA256
> *        server certificate verification SKIPPED
> *        server certificate status verification SKIPPED
> *        common name: 00e04cfffe36661d (does not match '127.0.0.1')
> *        server certificate expiration date OK
> *        server certificate activation date OK
> *        certificate public key: EC
> *        certificate version: #3
> *        subject: C=NL,O=Philips Hue,CN=00e04cfffe36661d
> *        start date: Tue, 12 Nov 2019 17:39:21 GMT
> *        expire date: Fri, 09 Nov 2029 17:39:21 GMT
> *        issuer: C=NL,O=Philips Hue,CN=00e04cfffe36661d
> *        compression: NULL
> * ALPN, server did not agree to a protocol
> > GET /api/nouser/config HTTP/1.1
> > Host: 127.0.0.1
> > User-Agent: curl/7.47.0
> > Accept: */*
> >
> < HTTP/1.1 200 OK
> < Server: nginx
> < Date: Tue, 12 Nov 2019 20:34:23 GMT
> < Content-type: application/json
> < Content-Length: 227
> < Access-Control-Allow-Origin: *
> < Access-Control-Allow-Methods: GET, OPTIONS, POST, PUT, DELETE
> < Access-Control-Allow-Headers: X-Requested-With
> < Access-Control-Allow-Headers: Content-Type
> <
> * Connection #0 to host 127.0.0.1 left intact
> {"mac":"00:e0:4c:36:66:1d","datastoreversion":70,"bridgeid":"00E04CFFFE36661D","replacesbridgeid":null,"swversion":"1935074050","modelid":"BSB002","starterkitid":"","name":"Philips hue","factorynew":false,"apiversion":"1.35.0"}

What is null request? How can I fix it? Thank you!

**Comment by mariusmotea** [comment]
your output looks correct (also Hue app confirm this because had a successful pair). Thre request to `/api/null` is probably made by the TV. When in the request there is no valid username or no username specified the bridge must output the minimal config. You can test if you get same output for `/api/null` like the one you already have for `/api/nouser/config`

**Comment by ilkekaratas** [comment]
Thank you for your answer. I was able to connect it with Philips TV 2019( 58PUS7304 )

The trick was after the TV finds the emulator, i stopped it and clicked next. After that I restarted it again and it connects.

But now I have another problem. The TV doesn't control the lights with movie. It is able to "alert" the lambs but cannot do more.

The error is:

192.168.1.36 - - [13/Nov/2019 23:12:32] "GET /api/52f5a186066611ea983fdd027ec090df/capabilities HTTP/1.1" 200 -
192.168.1.36 - - [13/Nov/2019 23:12:35] "GET /api/52f5a186066611ea983fdd027ec090df/lights/1 HTTP/1.1" 200 -
192.168.1.36 - - [13/Nov/2019 23:12:35] "PUT /api/52f5a186066611ea983fdd027ec090df/groups/2 HTTP/1.1" 200 -
2019-11-13 23:12:35,845 - root - INFO - in PUT method
2019-11-13 23:12:35,845 - root - INFO - /api/52f5a186066611ea983fdd027ec090df/groups/2
2019-11-13 23:12:35,845 - root - INFO - b'{"stream":{"active":false}}'
2019-11-13 23:12:35,845 - root - INFO - stop hue entertainent
2019-11-13 23:12:35,847 - root - INFO - [
    {
        "success": {
            "/groups/2/stream": {
                "active": false
            }
        }
    }
]
entertain-srv: no process found
192.168.1.36 - - [13/Nov/2019 23:12:35] "GET /api/52f5a186066611ea983fdd027ec090df/capabilities HTTP/1.1" 200 -
2019-11-13 23:12:38,191 - root - DEBUG - Sending M-Search response to 192.168.1.37
192.168.1.36 - - [13/Nov/2019 23:12:38] "GET /api/52f5a186066611ea983fdd027ec090df/lights/1 HTTP/1.1" 200 -
192.168.1.36 - - [13/Nov/2019 23:12:38] "PUT /api/52f5a186066611ea983fdd027ec090df/groups/2 HTTP/1.1" 200 -
2019-11-13 23:12:38,901 - root - INFO - in PUT method
2019-11-13 23:12:38,901 - root - INFO - /api/52f5a186066611ea983fdd027ec090df/groups/2
2019-11-13 23:12:38,901 - root - INFO - b'{"stream":{"active":false}}'
2019-11-13 23:12:38,901 - root - INFO - stop hue entertainent
2019-11-13 23:12:38,903 - root - INFO - [
    {
        "success": {
            "/groups/2/stream": {
                "active": false
            }
        }
    }
]
entertain-srv: no process found
192.168.1.36 - - [13/Nov/2019 23:12:32] "GET /api/52f5a186066611ea983fdd027ec090df/capabilities HTTP/1.1" 200 -
192.168.1.36 - - [13/Nov/2019 23:12:35] "GET /api/52f5a186066611ea983fdd027ec090df/lights/1 HTTP/1.1" 200 -
192.168.1.36 - - [13/Nov/2019 23:12:35] "PUT /api/52f5a186066611ea983fdd027ec090df/groups/2 HTTP/1.1" 200 -
2019-11-13 23:12:35,845 - root - INFO - in PUT method
2019-11-13 23:12:35,845 - root - INFO - /api/52f5a186066611ea983fdd027ec090df/groups/2
2019-11-13 23:12:35,845 - root - INFO - b'{"stream":{"active":false}}'
2019-11-13 23:12:35,845 - root - INFO - stop hue entertainent
2019-11-13 23:12:35,847 - root - INFO - [
    {
        "success": {
            "/groups/2/stream": {
                "active": false
            }
        }
    }
]
entertain-srv: no process found
192.168.1.36 - - [13/Nov/2019 23:12:35] "GET /api/52f5a186066611ea983fdd027ec090df/capabilities HTTP/1.1" 200 -
2019-11-13 23:12:38,191 - root - DEBUG - Sending M-Search response to 192.168.1.37
192.168.1.36 - - [13/Nov/2019 23:12:38] "GET /api/52f5a186066611ea983fdd027ec090df/lights/1 HTTP/1.1" 200 -
192.168.1.36 - - [13/Nov/2019 23:12:38] "PUT /api/52f5a186066611ea983fdd027ec090df/groups/2 HTTP/1.1" 200 -
2019-11-13 23:12:38,901 - root - INFO - in PUT method
2019-11-13 23:12:38,901 - root - INFO - /api/52f5a186066611ea983fdd027ec090df/groups/2
2019-11-13 23:12:38,901 - root - INFO - b'{"stream":{"active":false}}'
2019-11-13 23:12:38,901 - root - INFO - stop hue entertainent
2019-11-13 23:12:38,903 - root - INFO - [
    {
        "success": {
            "/groups/2/stream": {
                "active": false
            }
        }
    }
]
entertain-srv: no process found


However I am able to control lights with Hue Sync no problems.

Can you help me?

**Comment by mariusmotea** [comment]
Please restart the emulator and show same records from beginning. What i see here is that TV is trying to stop the entertainment service continuously so maybe it believe another app is using it?

**Comment by marcinprzybysz86** [comment]
@ilkekaratas I've used your trick to connect hue-emulator to Philips TV. 
It connected but after 1-3 mins it losts all the settings and the connection wizard starts again. 
Does your TV faced this issue?

**Comment by alexyao2015** [comment]
Curious, I just rolled back the change that allowed /API/null to receive a minimal config which fixed sleep as android. Potentially might have fixed this as well.
