### ISSUE TITLE
Can't use Scenes

### ISSUE THREAD

**Issue by marvin181296** [diyhue/diyHue#280]
** Error Description **
When i try to use a scene (whether in the "Hue" app or in the "Hue Essentials") I get a "Hue disconnected"-notification.

** Steps **
Have the newest diyHue version.
Go to your Hue app and select a scene. 

** Logs **
```
----------------------------------------
Exception happened during processing of request from ('192.168.0.7', 37068)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 428, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "./HueEmulator3.py", line 1773, in do_PUT
    splitLightsToDevices(bridge_config["scenes"][put_dictionary["scene"]]["group"], {}, bridge_config["scenes"][put_dictionary["scene"]]["lightstates"])
KeyError: 'lightstates'
----------------------------------------
```

** Additional Info **
I have the newest version of diyHue on a Raspberry Pi 4. I also tried it on my NAS (Debian buster), but got the same error.

**Comment by alexyao2015** [comment]
Clear your config, start debug logging, create a room with a light and default scenes, select a scene, stop logging. If you see the exception in the log, post the entire log (yes the entire thing) with the config.json. 

Also update before doing any of this.

**Comment by marvin181296** [comment]
My entire log → [pastebin](https://pastebin.com/WZFbWFUZ)
uploaded it to pastebin, because it's pretty huge.

**Comment by alexyao2015** [comment]
Config.json

**Comment by marvin181296** [comment]
Forgot the config...
My entire config.json → [pastebin](https://pastebin.com/6MAUkJLX)

**Comment by alexyao2015** [comment]
Just to be clear, you wiped the config before posting these logs correct? This is starting from a clean state?

**Comment by marvin181296** [comment]
I'm pretty sure, I deleted the config.json beforehand. but i can do the entire procedure again, just to be sure.

**Comment by alexyao2015** [comment]
I'm still looking over your logs but it seems that you used hue essentials. Can you report back on if you have the same error with the normal hue app?

**Comment by marvin181296** [comment]
I have with both apps exactly the same error in the logs... but i can do a complete log with the hue app if you want

**Comment by alexyao2015** [comment]
Ok well I see what the problem is. It appears that something is causing diyhue to not save lightstates into the config which leads to a corrupted scene. Now we have to just figure out exactly why its not saving the lighstates.

**Comment by marvin181296** [comment]
Ok, this sounds promising. Glad I could help to figure it out, good luck with the fix.

**Comment by alexyao2015** [comment]
Can you try rolling back to previous versions to see where the bug started? It appears that there have been no changes to the code relating to this recently and I know that it worked for me before. Personally haven't been able to validate if this is occurring on my setup or not

**Comment by marvin181296** [comment]
I have no previous versions... did my first install yesterday evening. is it possible to try a different version?

**Comment by alexyao2015** [comment]
What are you using to run it? If you use docker, you can go to docker hub and check the previous versions there. If you're running the install script you can go on the github and check previous commits.

**Comment by marvin181296** [comment]
I use raspbian without docker. i try to install a previous commit.

**Comment by alexyao2015** [comment]
I'm seeing other people who report having the same issue over on slack and they appear to have lightstates in the config. Can you try clearing your config again and making sure that you use the hue app and post the config and log?

Something between people's configs and logs is not adding up.

**Comment by mariusmotea** [comment]
I think the issue is this:

```scenelist["scenes"][scene] = bridge_config["scenes"][scene]	
                            if "lightstates" in scenelist["scenes"][scene]:	
                                del scenelist["scenes"][scene]["lightstates"]```

`scenelist["scenes"][scene] = bridge_config["scenes"][scene] made a link between the two dictionaries and when the lighstates is removed from scenelist it will be removes also from bridge_config

I made a new commit with i hope will fix all the issues

**Comment by alexyao2015** [comment]
Umm that commit just basically undid everything that I did for dynamic scenes. I think you maybe right about the linking so I'll just switch back to using deepcopy.

**Comment by mariusmotea** [comment]
i improve the scene sanitize function and i call it every time there is a change on bridge (HTTP PUT request). So the lighstates are fixed right after they become invalid because there was a change on groups. Now i remember i need to add this function also when a light or a group is deleted...

**Comment by alexyao2015** [comment]
Right what I did before was not output lightstates if /scenes was called but I output lightstates if /scenes/1 was called. Sanitize scenes is a different fix all together. I'll remake the commit to use deepcopy

**Comment by alexyao2015** [comment]
Something isn't working with the empty lightstate check. Also I think there should be a beta program because I feel that new fixes introduce more bugs if we push too quickly

```
2019-11-13 22:23:26,756 - root - INFO - Config loaded
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 1920, in <module>
    initialize()
  File "/opt/hue-emulator/HueEmulator3.py", line 189, in initialize
    sanitizeBridgeScenes()
  File "/opt/hue-emulator/HueEmulator3.py", line 208, in sanitizeBridgeScenes
    if len(bridge_config["scenes"][scene]["lightstates"]) == 0: # empty scenes are useless
KeyError: '12'
```

**Comment by alexyao2015** [comment]
Also I think something bugged out the original fix because it seems that my fix for sleep and huemanic no longer is working. Not sure which commit broke it but it does not work at all anymore....

**Comment by alexyao2015** [comment]
Well I don't have time to investigate now, but what I do now is some commit between now and my stable fork here caused sleep and like apps to stop wprking again. The particular commit, I have no idea now.

github.com/alexyao2015/diyHue/tree/debug-stable
