### ISSUE TITLE
rPi GPIO - WS2812B neopixel ring

### ISSUE THREAD

**Issue by stvnmbr1** [diyhue/diyHue#284]
Hi

just starting my first builds and for a specific case I want to control a neopixel ring, connected to the GPIO of rPi through Hue.
I did find a script for locally connected led strip, issue 28 on the old repo, but I couldn't get it to work for the ring.

i understand there is a second emulator needed to control the gpio but i got kinda lost. 

Is there any new / other info about this ?

**Comment by stvnmbr1** [comment]
i got as far as getting the light into hue and be able to control it, server responds ok, but how do i get it to control the ring ?

**Comment by stvnmbr1** [comment]
`#!/usr/bin/python
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
from time import strftime, sleep
from urlparse import urlparse, parse_qs
from math import log
import json

lightstate = {"on" : False, "bri": 0, "xy": [0.0, 0.0], "ct": 153, "hue": 0, "sat": 0, "colormode": "ct"}


def convert_xy(x, y, bri): #needed for milight hub that don't work with xy values
    Y = bri / 250.0
    z = 1.0 - x - y

    X = (Y / y) * x
    Z = (Y / y) * z

  # sRGB D65 conversion
    r =  X * 1.656492 - Y * 0.354851 - Z * 0.255038
    g = -X * 0.707196 + Y * 1.655397 + Z * 0.036152
    b =  X * 0.051713 - Y * 0.121364 + Z * 1.011530

    if r > b and r > g and r > 1:
    # red is too big
        g = g / r
        b = b / r
        r = 1

    elif g > b and g > r and g > 1:
    #green is too big
        r = r / g
        b = b / g
        g = 1

    elif b > r and b > g and b > 1:
    # blue is too big
        r = r / b
        g = g / b
        b = 1

    r = 12.92 * r if r <= 0.0031308 else (1.0 + 0.055) * pow(r, (1.0 / 2.4)) - 0.055
    g = 12.92 * g if g <= 0.0031308 else (1.0 + 0.055) * pow(g, (1.0 / 2.4)) - 0.055
    b = 12.92 * b if b <= 0.0031308 else (1.0 + 0.055) * pow(b, (1.0 / 2.4)) - 0.055

    if r > b and r > g:
    # red is biggest
        if r > 1:
            g = g / r
            b = b / r
            r = 1
        elif g > b and g > r:
        # green is biggest
            if g > 1:
                r = r / g
                b = b / g
                g = 1

        elif b > r and b > g:
        # blue is biggest
            if b > 1:
                r = r / b
                g = g / b
                b = 1

    r = 0 if r < 0 else r
    g = 0 if g < 0 else g
    b = 0 if b < 0 else b

    return [int(r * 255), int(g * 255), int(b * 255)]

def convert_ct(ct, bri):
    hectemp = 10000 / ct
    r = 0
    g = 0
    b = 0
    if hectemp <= 66:
        r = 255;
        g = 99.4708025861 * log(hectemp) - 161.1195681661
        b = 0 if hectemp <= 19 else (138.5177312231 * log(hectemp - 10) - 305.0447927307)
    else:
        r = 329.698727446 * pow(hectemp - 60, -0.1332047592)
        g = 288.1221695283 * pow(hectemp - 60, -0.0755148492)
        b = 255;

    r = 255 if r > 255 else r
    g = 255 if g > 255 else g
    b = 255 if r > 255 else b
    return [ int(r * (bri / 255.0)), int(g * (bri / 255.0)), int(b * (bri / 255.0))]



class S(BaseHTTPRequestHandler):
    def _set_headers(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_GET(self):
        self._set_headers()
        if self.path.startswith("/get"):
            self.wfile.write(json.dumps(lightstate))
        elif self.path.startswith("/set"):
            get_parameters = parse_qs(urlparse(self.path).query)
            if "on" in get_parameters:
                if get_parameters["on"][0] == "True":
                    lightstate["on"] = True
                    print("start pwm on all channels. If last state is not automatically applied, then execute the function that is set in lightstate[\"colormode\"] again")
                elif get_parameters["on"][0] == "False":
                    lightstate["on"] = False
                    print("stop pwm on all channels")
            if "bri" in get_parameters:
                lightstate["bri"] = int(get_parameters["bri"][0])
                print("setup bri to " + get_parameters["bri"][0])
            if "ct" in get_parameters:
                lightstate["ct"] = int(get_parameters["ct"][0])
                lightstate["colormode"] = "ct"
            elif "x" in get_parameters:
                lightstate["xy"] = [float(get_parameters["x"][0]), float(get_parameters["y"][0])]
                lightstate["colormode"] = "xy"

            if lightstate["on"] == True:
                if lightstate["colormode"] == "xy":
                    raw_hue_rgb = convert_xy(lightstate["xy"][0], lightstate["xy"][1], lightstate["bri"])
                    #convert this from 0 <-> 255 to 0.0 <-> 1.0
                    pwm_rgb = [raw_hue_rgb[0] / 255.0, raw_hue_rgb[1] / 255.0, raw_hue_rgb[2] / 255.0]
                    print("red: " + str(pwm_rgb[0]) + ", green: " + str(pwm_rgb[1]) + ", blue: " + str(pwm_rgb[2]))

                elif lightstate["colormode"] == "ct":
                    raw_hue_rgb = convert_ct(lightstate["ct"], lightstate["bri"])
                    #convert this from 0 <-> 255 to 0.0 <-> 1.0
                    pwm_rgb = [raw_hue_rgb[0] / 255.0, raw_hue_rgb[1] / 255.0, raw_hue_rgb[2] / 255.0]
                    print("red: " + str(pwm_rgb[0]) + ", green: " + str(pwm_rgb[1]) + ", blue: " + str(pwm_rgb[2]))

            self.wfile.write("OK")
        else:
            self.wfile.write("WRONG PATH")



def run(server_class=HTTPServer, handler_class=S):
    server_address = ('', 81)
    httpd = server_class(server_address, handler_class)
    print 'Starting httpd...'
    httpd.serve_forever()

if __name__ == "__main__":
    try:
        run()
    except:
        print("server stopped")`

**Comment by stvnmbr1** [comment]
O, got this working, the only thing is that the color selected is not reflecting on the ring.
what type of bulb do I need to define ?

**Comment by stvnmbr1** [comment]
talking to myself but you never know someone can use this
RGB color is not calculated correctly
full red example red: 254, green: 38, blue: 30

how can i correct R & G


>` 
from neopixel import *
                   ring = Adafruit_NeoPixel(16, 18, 800000, 5, False, lightstate["bri"])
                    ring.begin()

                    for i in range(ring.numPixels()):
                            ring.setPixelColor(i,Color(raw_hue_rgb[0],raw_hue_rgb[1],raw_hue_rgb[2]))
                            ring.show()
`

**Comment by mariusmotea** [comment]
the xy conversion is not perfect, try to use the onle from ws2812 arduino sketch. It was changed 6 months ago

**Comment by stvnmbr1** [comment]
i got it near perfect, r & g stay at 20 where they should be 0, and had to swap r & g to the leds.
I'll check that one out, thanks !
