### ISSUE TITLE
too many initializers for 'uint16_t [2] {aka short unsigned int [2]}'

### ISSUE THREAD

**Issue by stvnmbr1** [diyhue/diyHue#290]
**Describe the bug**
too many initializers for 'uint16_t [2] {aka short unsigned int [2]}'

**To Reproduce**
#define light_name "WS2812 Hue Ring"  //default light name
#define lightsCount 1
#define pixelCount 16
uint16_t pixelStart[lightsCount + 1] = {0, 1, 21, pixelCount};

build to ESP NODE MCU

**Logs**
too many initializers for 'uint16_t [2] {aka short unsigned int [2]}'

**Additional context**

**Comment by stvnmbr1** [comment]
lightsCount 3 fixed it

**Comment by mariusmotea** [comment]
Default values are just an example for a light with 3 rings. Every ring is a virtual light .
