### ISSUE TITLE
Keyerror light states

### ISSUE THREAD

**Issue by Pantastisch** [diyhue/diyHue#294]
Hello, 

since a few days my auto updated diyhue docker container is not working anymore.
This is the output I am getting on console:

diyhue_1      | 2019-11-18 21:11:20,674 - root - INFO - Using Host 192.168.178.60:80
diyhue_1      | Host MAC given as b827eb6eb75b
diyhue_1      | 2019-11-18 21:11:20,675 - root - INFO - b827eb6eb75b
diyhue_1      | Docker Setup Initiated
diyhue_1      | Restoring Certificate
diyhue_1      | Certificate Restored
diyhue_1      | Restoring config
diyhue_1      | Config restored
diyhue_1      | Docker Setup Complete
diyhue_1      | 2019-11-18 21:11:20,679 - root - INFO - IP range for light discovery: 0-255
diyhue_1      | 2019-11-18 21:11:20,679 - root - INFO - 127.0.0.1
diyhue_1      | 2019-11-18 21:11:20,679 - root - INFO - Online Discovery/Remote API Enabled!
diyhue_1      | 2019-11-18 21:11:20,682 - root - INFO - Config loaded
diyhue_1      | Traceback (most recent call last):
diyhue_1      |   File "/opt/hue-emulator/HueEmulator3.py", line 1904, in <module>
diyhue_1      |     initialize()
diyhue_1      |   File "/opt/hue-emulator/HueEmulator3.py", line 189, in initialize
diyhue_1      |     sanitizeBridgeScenes()
diyhue_1      |   File "/opt/hue-emulator/HueEmulator3.py", line 200, in sanitizeBridgeScenes
diyhue_1      |     for lightstate in list(bridge_config["scenes"][scene]["lightstates"]):
diyhue_1      | KeyError: 'lightstates'

I hope I can help someone with this output, fixing this.

Thanks!

**Comment by alexyao2015** [comment]
Go ahead and run beta. Should be fixed.
