### ISSUE TITLE
Unable to pair with Hue app (docker install on macOs)

### ISSUE THREAD

**Issue by carlocanlas** [diyhue/diyHue#30]
Hi, I'm fairly new to python / docker. Currently, I'm trying to run the app on macOs using the docker method. I was able to open the /hue/linkbutton page, and manually find the bridge emulator in the hue mobile app. However the `activate` method within the linkbutton page doesn't seem to do anything. The mobile app doesn't register any 'push-link' events.

**Comment by mariusmotea** [comment]
Two main reason:
1. You play with the setup and deploy again new certificate. To solve this reinstall the hue app so the previews cached certificate will be cleared.

2. wrong ip/mac address specified as env variables to docker container.

Will help a lot the output of this command:
`curl https://127.0.0.1/api/nouser/config -k -v`

this will output a json that must contain the ip and mac address of your macOS.

**Comment by Death111** [comment]
Having the same problem. Using docker the image on Win10 and activate does not seem to do anything. Result of the curl command responds with some weird mac format:
{"mac":"33:-2:6-:7A:-E:9-","starterkitid":"","apiversion":"1.24.0","replacesbridgeid":null,"datastoreversion":70,"bridgeid":"33-26-FFFE7A-E9-A5-F2","swversion":"1809121051","factorynew":false,"name":"Philips hue","modelid":"BSB002"}* Connection #0 to host 127.0.0.1 left intact

I'm starting the container with -e 'MAC=33-26-7A-E9-A5-F2'.
Full output is:
`
C:\Users\Death>curl https://127.0.0.1/api/nouser/config -k -v
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* schannel: SSL/TLS connection with 127.0.0.1 port 443 (step 1/3)
* schannel: disabled server certificate revocation checks
* schannel: verifyhost setting prevents Schannel from comparing the supplied target name with the subject names in server certificates.
* schannel: using IP address, SNI is not supported by OS.
* schannel: sending initial handshake data: sending 147 bytes...
* schannel: sent initial handshake data: sent 147 bytes
* schannel: SSL/TLS connection with 127.0.0.1 port 443 (step 2/3)
* schannel: encrypted data got 740
* schannel: encrypted data buffer: offset 740 length 4096
* schannel: sending next handshake data: sending 126 bytes...
* schannel: SSL/TLS connection with 127.0.0.1 port 443 (step 2/3)
* schannel: encrypted data got 226
* schannel: encrypted data buffer: offset 226 length 4096
* schannel: SSL/TLS handshake complete
* schannel: SSL/TLS connection with 127.0.0.1 port 443 (step 3/3)
* schannel: stored credential handle in session cache
> GET /api/nouser/config HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.55.1
> Accept: */*
>
* schannel: client wants to read 102400 bytes
* schannel: encdata_buffer resized 103424
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 154
* schannel: encrypted data buffer: offset 154 length 103424
* schannel: decrypted data length: 125
* schannel: decrypted data added: 125
* schannel: decrypted data cached: offset 125 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 125 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 125
* schannel: decrypted data buffer: offset 0 length 102400
< HTTP/1.1 200 OK
< Server: nginx
< Date: Tue, 25 Dec 2018 23:36:00 GMT
< Content-type: application/json
< Content-Length: 232
<
* schannel: client wants to read 232 bytes
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: encrypted data got 261
* schannel: encrypted data buffer: offset 261 length 103424
* schannel: decrypted data length: 232
* schannel: decrypted data added: 232
* schannel: decrypted data cached: offset 232 length 102400
* schannel: encrypted data buffer: offset 0 length 103424
* schannel: decrypted data buffer: offset 232 length 102400
* schannel: schannel_recv cleanup
* schannel: decrypted data returned 232
* schannel: decrypted data buffer: offset 0 length 102400
{"mac":"33:-2:6-:7A:-E:9-","starterkitid":"","apiversion":"1.24.0","replacesbridgeid":null,"datastoreversion":70,"bridgeid":"33-26-FFFE7A-E9-A5-F2","swversion":"1809121051","factorynew":false,"name":"Philips hue","modelid":"BSB002"}* Connection #0 to host 127.0.0.1 left intact
`

I tried changing the mac to  a normal format in the config.json, but it will override on restart of the container. Also i see that there is not certificate data - if I check the ssl certificate used in the webui I have the following output:
CN = 025000fffe000001
O = Philips Hue
C = NL
which seems off aswell.

Sorry @carlocanlas if I post here, but maybe we have the same problem - if not I'll create a new issue ;)

**Comment by carlocanlas** [comment]
After clearing the config and certs, I was finally able to connect to the hue app. I didn't even need to do the push-link step, it was connected right after entering the IP of the bridge emulator. Though it prompted me for an update to the bridge, which I tried but failed -- probably because the docker image I'm running is not yet updated.

Nonetheless, it's now connected to the hue app. 👍
