### ISSUE TITLE
Support for 24V RGBCCT 6 Channel 

### ISSUE THREAD

**Issue by Xorfee** [diyhue/diyHue#300]
Hey Dev,
I am planning to buy some 24v LED with Rgb Cct (cold white and warm white) with 6 Channels. Any way to support those LEDs?

Here is the link 
https://s.click.aliexpress.com/e/hZtcpXwL

24v led rgb cct with 6 ports

**Comment by mariusmotea** [comment]
I don't think there are 6 channels. RGB-CCT has only 5 channels and we have the software for this kind of light. You only need the strip controller.

**Comment by alexyao2015** [comment]
Yeah those are just the LED strips. You'll need a controller as well. Take a look at the h801. There is support for rgbcct in the native firmware. You can also use esphome as well.

For future reference, do not post light questions here. If it's a firmware issue, use the lights repository. For help/comments use the Discourse.
