### ISSUE TITLE
Milight Hub Emulator/ Milight Bulb Problem - Color Mix/ Warm White

### ISSUE THREAD

**Issue by AlexKusnezov** [diyhue/diyHue#301]
**Describe the bug**
I'm using an esp8266 with the milight hub emulator: https://github.com/sidoh/esp8266_milight_hub
Connected are 5 Milight Bulbs CTT (FUT103).

The problem is that since v1.10 was released I can't set the bulb into color mode via Philips Hue/Hue Essentials App. When I choose a color it will work for a a second and then flip back to white.
If I use v1.9(older) its the other way around (color works, white don't)
In the milight hub emulators web interface (https://github.com/sidoh/esp8266_milight_hub)
it works, so maybe it is the communication between the milight hub emulator and diyhue emulator?

Can you help me out?

**Comment by mariusmotea** [comment]
I don't think the issue is with diyhue because from what i remember there is just one http request sent to Milight Hub. If i'm correct (can be verified in debug mode) then the Milight Hub send a second request to the bulb without any intervention from the hue emulator and this revert the bulb color mode.

**Comment by AlexKusnezov** [comment]
@mariusmotea thanks for the info. I'm not sure if I understood it.
>the Milight Hub send a second request to the bulb without any intervention from the hue emulator and this revert the bulb color mode.
So is this the problem? Is there a workaround for this?

**Comment by alexyao2015** [comment]
Does the "beta" branch work?

**Comment by AlexKusnezov** [comment]
@alexyao2015 sorry, haven't tried it yet, how can I switch to beta?

**Comment by alexyao2015** [comment]
Check the branches at the top of GitHub. You'll see something labeled master. If you're using docker, checkout docker hub to find the correct image

**Comment by AlexKusnezov** [comment]
@alexyao2015 got it, thanks
