### ISSUE TITLE
Pairing with homebridge-hue

### ISSUE THREAD

**Issue by andre68723** [diyhue/diyHue#302]
Hi,

im unable to pair diyhue with the homebridge-hue due to GET `/config`
fails unauthenticated, yet required by hb-hue to create the user.

```
[12/5/2019, 19:34:40] [Hue] 192.***.***.59: bridge request 7: get /config
[12/5/2019, 19:34:40] [Hue] 192.***.***.59: bridge error 1: unauthorized user
heartbeat lost, close socket and reconnect
closed the socket and retry
```
https://github.com/ebaauw/homebridge-hue/issues/567

Is there a way to create a user in config.json manually or do you expose the bridgeid under a different path?

Thanks!

**Comment by andre68723** [comment]
https://github.com/ebaauw/homebridge-hue/issues/265

**Comment by mariusmotea** [comment]
You have all valid usernames in config.json file from /opt/hue-emulator folder. Pick one and place it in config.json file from homebridge-hue.

**Comment by andre68723** [comment]
I checked config.json but were not able to locate any user + token section under config.

The bridgeid is there under config and also 2 further entries under config/whitelist, but just a username and no token.

**Comment by mariusmotea** [comment]
look for "whitelist" and the big hash strings are the usernames.
```
        "whitelist": {
            "0cf86418033511eab7werca6320059d6": {
                "create date": "2019-11-09T21:08:17",
                "last use date": "2019-12-06T21:56:35",
                "name": "Hue 3#HTC U11"
            },
            "61746a2a0c9811ea9ewra6320059d6": {
                "create date": "2019-11-21T19:51:59",
                "last use date": "2019-11-22T13:21:39",
                "name": "hue-dashboard#hue"
            },

```
here `0cf86418033511eab7werca6320059d6` and `61746a2a0c9811ea9ewra6320059d6` are the usernames

**Comment by ebaauw** [comment]
Homebridge-hue supports multiple bridges in parallel.  It identifies the bridge using the `bridgeid` attribute, to insulate against changed to the IP address or bridge name.  The username (API key) is also stored under the bridge ID, so homebridge-hue needs to do an unauthenticated GET of `/api/config`, to retrieve the bridge ID, before it can do authenticated requests, like GET `/api/`_username_`/lights`.

I've never looked into diyhue, but I've seen reports that it used to work with homebridge-hue.  Did you make a recent change that broke the unauthenticated request?

**Comment by mariusmotea** [comment]
Yes, i know where the issue is. I expect any possible username in http path like other applications i monitor (ex Hue app /api/nouser/config). I will fix this.

**Comment by mariusmotea** [comment]
@andre68723 please update the bridge and try again now.

**Comment by BPHvZ** [comment]
> @andre68723 please update the bridge and try again now.

It works for me

**Comment by andre68723** [comment]
works, thank! 
```

[12/7/2019, 16:58:19] [Hue] Philips hue: HA-Bridge v1935074050, api v1.35.0
[12/7/2019, 16:58:19] [Hue] Philips hue: /sensors/1: warning: Daylight sensor not configured
[12/7/2019, 16:58:19] [Hue] Philips hue: 2 accessories
[12/7/2019, 16:58:19] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
[12/7/2019, 16:58:19] [Hue] Initializing platform accessory 'Philips hue'...
[12/7/2019, 16:58:19] [Hue] Philips hue: 2 services
[12/7/2019, 16:58:19] [Hue] Initializing platform accessory 'Daylight'..
```
