### ISSUE TITLE
Can't pair Entertainment

### ISSUE THREAD

**Issue by Fienberber** [diyhue/diyHue#304]
The hue bridge is working properly in the hue app but I can't pair the bridge to any other apps. When I try the debug mode I didn't even receive any log from the network scan.

Note than then I restart the service I find the bridge in the iOS app but then the sync process doesn't work and I can't find it anymore. 

The main app is working so it's not very critical but I was ordering if there is a fix.

**Comment by coolcoons** [comment]
Same problem here. I have the bridge paired to the mobile app but I can't find it from my computer using hue sync.

**Comment by mariusmotea** [comment]
You use windows or macos? Try to restart the emulator service and retry.

**Comment by coolcoons** [comment]
I use windows. I have restarted hue sync and uninstalled it countless times. I will try restarting the hue emulator.

**Comment by mariusmotea** [comment]
I made now a test with Windows 10 and lastest Hue Sync app. I notice that when i perform bridge search only the original Hue Bridge is detected whitout the emulator. Once i disconnect the original bridge from the network the emulator was discovered on first search, so i think the Hue Sync app try first the cloud based detection and if a bridge is detected (only original ones work) it don't perform the SSDP search on local network. If you have a hue bridge unplug it and wait 2 minutes, then perform bridge search.

**Comment by Fienberber** [comment]
I don't have any original hue Bridge. 
My hue-emulator run on Raspbian.
I reinstalled the hue-emulator many times and I'm up to date.

**Comment by mariusmotea** [comment]
This can be a problem. On reinstallation (not upgrade) a new certificate is generated and the hue apps cache the old certificate. You need to wipe the data of the Hue Sync to be sure the old certificate is cleared.

**Comment by Fienberber** [comment]
My bad I wanted to say upgraded. I going to check the certificate it can be the problem. 
The Hue app wanted me to make an update (from the iOS app) and it has thrown an error (quite what I was expecting). But the problem occurs ever since. Can it be the reason ?

**Comment by coolcoons** [comment]
I tried restarting the service and upgrading it. Nothing changed. There is an executable called entertain-srv. Do I need to run this? Hue Sync sits searching forever so I am wondering if it is detecting something and doesn't show up? Before it would give up in like 5 minutes and I could type an IP address.

**Comment by mariusmotea** [comment]
You need to ensure just one interface is connected to network (ex: raspberry pi has ethernet and wifi) and you need to access the bridge on the interface used during certificate generation (certificate CN must contain the mac address of the interface). Other than this i don't see any reasons why Hue Sync will not pait. entertain-srv is a service that will be started manually by the emulator when an entertianment application want to stream .

**Comment by coolcoons** [comment]
Do I need to have lights on the bridge and groups? My lights are in the mail and I will set them up in a few days.

**Comment by mariusmotea** [comment]
I don't think so. You can start the emulator in debug mode and see if from hue sync pc there are registration requests. Try also to see if the Hue app pair with the emulator.

**Comment by coolcoons** [comment]
I don't think Hue Emulator was actually running at all when I tried debug mode, but I did find something interesting. Hue Sync didn't find any bridges instead of searching forever. I can put in an ip address

**Comment by coolcoons** [comment]
I think it must be finding the hue bridge but displaying infinite searching instead of showing me a connect button.

**Comment by coolcoons** [comment]
10 seconds after stopping the hue emulator hue sync stops searching and fails. So it is finding it. I think.

**Comment by coolcoons** [comment]
I got it working! This will sound weird but I stopped hue emulator had hue sync search then fail. I typed in the IP address started hue emulator and hue link button and tried connecting hue sync and it worked immediately. I don't understand it though.

**Comment by mariusmotea** [comment]
Your router may block SSDP protocol used to retrieve the ip addresses of the devices from the network.

**Comment by coolcoons** [comment]
That makes sense. I think your right.

**Comment by coolcoons** [comment]
It should work though now that it is set up right?

**Comment by mariusmotea** [comment]
Must work, you need to add lights and create entertainment areas.

**Comment by Fienberber** [comment]
> I got it working! This will sound weird but I stopped hue emulator had hue sync search then fail. I typed in the IP address started hue emulator and hue link button and tried connecting hue sync and it worked immediately. I don't understand it though.
I tried, but didn't do the trick for me... 

I removed the certificate and before upgrading (for re-generation) the bridge was found but I was unable to pair it.
I upgraded it to have a fresh certificate and now even the hue app can't connect to the bridge.

I'm going to wipe everything and re-install it from scratch. it will maybe solve the issue.

**Comment by Fienberber** [comment]
I uninstalled everything and reinstalled and now everything works properly. 

Thanks for your help. 
I close the issue.
