### ISSUE TITLE
Connecting Lights

### ISSUE THREAD

**Issue by coolcoons** [diyhue/diyHue#305]
I setup diyhue on virtual raspberry pi within virtual box. I can connect to it but I can't add my lights. Are they supported and how do I add them if they are? 

https://www.amazon.com/HaoDeng-Edison-
Timer-Sunrise-Sunset/dp/B07F7D8GD1/ref=sr_1_1_sspa?keywords=haodeng&qid=1575732570&sr=8-1-spons&psc=1&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEzQ0JVN1FQUkpKT01JJmVuY3J5cHRlZElkPUEwOTY1Mzg4MjQ3OFdaNFVYOFVKTyZlbmNyeXB0ZWRBZElkPUEwNzI2NDA4MUFJUzREWkVHMzUxRyZ3aWRnZXROYW1lPXNwX2F0ZiZhY3Rpb249Y2xpY2tSZWRpcmVjdCZkb05vdExvZ0NsaWNrPXRydWU=

The link is for the lights I am using. I can't seem to figure out if they are ESP8266 based or not.

**Comment by mariusmotea** [comment]
Not any esp8266 light is working. First thing you need to flash the firmware from Lights repo in esp flash memory, then connect the light to wifi network.

**Comment by coolcoons** [comment]
The link I sent didn't work here is the other.  https://www.amazon.com/HaoDeng-Edison-Timer-Sunrise-Sunset/dp/B07F7D8GD1/

**Comment by coolcoons** [comment]
The link still says something is wrong but I tested it and it is working.

**Comment by coolcoons** [comment]
How do I figure out if they will work after flashing them? If I flash them that is it and there is no going back.

**Comment by coolcoons** [comment]
Maybe I should just use a bulb that you know works. What about IKEA Trafdri bulbs?

**Comment by coolcoons** [comment]
It appears they can already connect with the Philips Hue Bridge and work they just don't have all the features. Since I did the hue emulator wouldn't all those locked features work?

**Comment by coolcoons** [comment]
https://www.amazon.com/Sylvania-Osram-Lightify-Smart-White/dp/B07HGBVK1T/ What about these?

**Comment by coolcoons** [comment]
I don't want to ruin the bulbs I already have but I am fine with flashing them. Is it possible to figure out if they will be fine after flashing?

**Comment by mariusmotea** [comment]
Open one bulb. If there is one 8 pin ic then that is the spi flash chip. You can desolder it and place one already flashed from another esp board. You can also save current flash with esptool, but i don't know the commands.

**Comment by coolcoons** [comment]
As well as flashing firmware onto those devices I wanted to add a few more bulbs to diyhue. Are there any bulbs that work with diyhue and can just be connected right out of the box? Maybe these? https://www.amazon.com/Sylvania-Smart-Home-73739-Adjustable/dp/B0196M5YAS/
They say that they work with any Zigbee hub of my choice so they should work with my diy Philips Hue Hub right?

**Comment by coolcoons** [comment]
https://huehomelighting.com/different-philips-hue-bulb-types/
I just found a Philips Hue faq page on bulb compatibility with their software and Sylvania is supported as well as Gledopto, Cree Connected, Innr, GE Link, and Ikea Tradfri!

**Comment by Mevel** [comment]
Those compatible lights use the zigbee wireless technology, it is not wifi as the esp8266. As this is a truly Diy project, you will most likely only find out if you try and error.

**Comment by coolcoons** [comment]
It did say that normal Hue bulbs can connect to the Hue emulator. So I think it is safe to assume that Philips Hue Compatible Bulbs will work with it as well. I will try it out though and let you guys know.

**Comment by mariusmotea** [comment]
Are working, but in order to use any ZigBee compliant device you need your host to be ZigBee compliant and to be able to communicate with ZigBee devices. In order to do this you need the Rasbee module or the ConBee stick.

**Comment by coolcoons** [comment]
I have a raspberry module in Virtual Box. Does that count?

**Comment by mariusmotea** [comment]
No, you still need ZigBee radio communication device.

**Comment by coolcoons** [comment]
https://www.amazon.com/HiLetgo-Wireless-Protocol-Analyzer-Interface/dp/B07X52QKK6/

Can I plug this into the back of my server and make the bulbs work?

**Comment by mariusmotea** [comment]
Is not supported. I want to give it a try as i have one home but i don't know when i will find time

**Comment by coolcoons** [comment]
So I need to buy more esp8266 bulbs or a raspberry pie?

**Comment by mariusmotea** [comment]
You mix things. Esp8266 is wifi chip. We provide custom firmware for it. On the market there are also ZigBee bulbs and sensors witch work with original Hue Bridge. If tou want to use them you need ZigBee communication capabilities witch work but with Conbee stick or Raspbee module for Raspberry pi. To play with esp8266 bulbs you need any linux host, you can install VirtualBox and create an Ubuntu VM.

**Comment by coolcoons** [comment]
I think I want to buy one of those USB Zigbee sticks. You said they should work you just haven't tested them.

**Comment by Paalap** [comment]
@coolcoons supported Zigbee Stick was and is Conbee. There is also a similar module for raspberry pi (but conbee is also working). I think it is pretty simple.

**Comment by coolcoons** [comment]
I understand what you mean. I just don't want to spend $50 for a Zigbee gateway. Will, the $7 device not work?

**Comment by coolcoons** [comment]
https://www.reddit.com/r/homeassistant/comments/bt576h/what_is_the_difference_between_conbee_ii_and_a/ Here is a post I found. people on there say you can use either but this is diyhue so I don't know.

**Comment by mariusmotea** [comment]
Diyhue is able to pair with Deconz, the main application of Conbee/Raspbee, so all the lights and sensors will be imported. Regarding the sensors even if the sensor is imported, the support is provided only for a few, i specified in wiki. You can create your own rules to support more sensors but you need to have the know how.

**Comment by coolcoons** [comment]
Oh, I think I understand now.  I have to get either the Conbee USB stick or raspberry pi extension from Conbee if I want this to work. Otherwise, there are no alternatives because those two are the only ones diyhue will support or work with. I guess I will just go with it then if it is the only thing that works.

**Comment by coolcoons** [comment]
My last thing is the led strips. Is this the right things to buy?
https://www.ebay.com/itm/33ft-Extension-Red-Black-Wire-Cable-Cord-for-3528-5050-5630-LED-Strip-Lamp-20AWG/232789538045
https://www.ebay.com/itm/WeMos-D1-Mini-NodeMCU-Double-Socket-Dual-Base-Shield-for-Arduino-ESP8266-DIY/123445153129
https://www.ebay.com/itm/9-Channel-8CH-Security-Camera-Power-Supply-Box-DC-12V-10A-CCTV-DVR-Distribution/172331730583
https://www.ebay.com/itm/WS2811-2812-RGB-LED-Strip-Addressable-DC12V-1M-2M-3M-4M-5M-IP65-Waterproof/273996601333?var=573999068459
I think this last thing is wrong because it doesn't have a power cable coming from it.
https://www.ebay.com/itm/10-Pairs-JST-SM-3-Pin-Male-Female-Plug-Connector-Cable-For-WS2811-LED-Lamp-Strip/283704461978

**Comment by mariusmotea** [comment]
You need one WS2812 strip with the desired number of leds and length, one Wemod D1 mini board and one power supply 5V with 30mA x number of leds (ex: 3A for 100 leds.

**Comment by coolcoons** [comment]
What kind of wires and cables do I use to connect everything together?

**Comment by coolcoons** [comment]
Thank you for all your help I have measured my spaces and made an online shopping cart and here are the totals:
Diyhue setup-$206.83
If I had done Philips Hue-$1287.8
Those are awesome savings.

**Comment by coolcoons** [comment]
> Is not supported. I want to give it a try as i have one home but i don't know when i will find time

When you test it can you let me know if it works?
