### ISSUE TITLE
DIYhue + deconz not loading anything in dockerized setup

### ISSUE THREAD

**Issue by da-anton** [diyhue/diyHue#306]
**Describe the bug**

I'm trying to pair diyhue with deconz according to this:

https://diyhue.readthedocs.io/en/latest/lights/raspbee.html#deconz-installation

Like mentioned here https://github.com/diyhue/diyHue/issues/266 unfortunately nothing is happening. Under https://192.168.1.56/deconz I can see nothing and the logs also show nothing. 

- I of course unlocked the deconz gateway during diyhue startup
- I can access deconz web ui via 192.168.1.56:8080 and can configure my lights

 Any idea whats wrong?

**Logs diyhue**

```
docker Setup Initiated
Restoring Certificate
Certificate Restored
Restoring config
Config restored
Docker Setup Complete
2019-12-09 10:52:47,799 - root - INFO - IP range for light discovery: 0-255
Deconz IP given as 192.168.1.56
2019-12-09 10:52:47,800 - root - INFO - 192.168.1.56
2019-12-09 10:52:47,802 - root - INFO - Online Discovery/Remote API Enabled!
2019-12-09 10:52:47,807 - root - INFO - Config loaded
2019-12-09 10:52:47,814 - root - DEBUG - starting ssdp...
2019-12-09 10:52:47,815 - root - DEBUG - start ssdp broadcast
2019-12-09 10:52:47,821 - root - INFO - sync with lights
2019-12-09 10:52:47,831 - root - INFO - Starting httpd...
2019-12-09 10:52:47,857 - root - INFO - Starting ssl httpd...
2019-12-09 10:52:47,860 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2019-12-09 10:52:48,172 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
```

**Logs deconz**

```
[marthoc/deconz] Current deCONZ version: 2.05.71
[marthoc/deconz] Web UI port: 8080
[marthoc/deconz] Websockets port: 8081
[marthoc/deconz] VNC Disabled
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
```

**Docker Info (please complete the following information):**
 - Architecture: [ARM]
 - Docker image version: [latest]
 - Hardware: [Raspberry Pi 3B+]

**Additional context**

**Conbee Info**

- ConBee II stick
- SW version 2.05.71

**deconz docker command**

`docker run -d --name=deconz --net=host --restart=always -v /etc/localtime:/etc/localtime:ro -v /opt/deconz:/root/.local/share/dresden-elektronik/deCONZ -e DECONZ_WEB_PORT=8080 -e DECONZ_WS_PORT=8081 -e DECONZ_VNC_PORT=8082 --device=/dev/ttyACM0 marthoc/deconz
`

**diyhue docker command**

`docker run -d --name "diyhue" --network="host" -e "DEBUG=true"  -e "DECONZ=192.168.1.56" -v '/opt/diyhue/':'/opt/hue-emulator/export/':'rw' diyhue/core:latest`

**netstat -lntp**

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      6629/python3        
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      5512/deCONZ         
tcp        0      0 0.0.0.0:8081            0.0.0.0:*               LISTEN      5512/deCONZ         
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      530/sshd            
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      6629/python3        
tcp6       0      0 :::22                   :::*                    LISTEN      530/sshd 
```

**Comment by ryancasler** [comment]
I'm having the same problem in a non-dockerized config.  And I have previous lights set up in Deconz already and am able to control them.  But now I can't add any new ones that have been connected to Deconz.  It's like the light discovery has been lost for some reason.

**Comment by alexyao2015** [comment]
Try using the "beta" branch

**Comment by pobvjansz** [comment]
I have the same issue in a dockerized environment

**Comment by da-anton** [comment]
@alexyao2015 I tried the beta-latest channel from docker hub but still the same result. Nothing is loaded from deconz.

**Comment by alexyao2015** [comment]
Did you clear your config and cert?

**Comment by alexyao2015** [comment]
Since there has been no reply, I will be closing this issue.

**Comment by pobvjansz** [comment]
Hi, Can this be re-opened?

I tried with the beta version and removed config and cert.

This is the error I am not getting:
diy_hue_beta   | 2020-01-18 22:22:41,600 - root - INFO - sync with lights
diy_hue_beta   | 2020-01-18 22:22:41,992 - root - INFO - {"e":"changed","id":"2","r":"sensors","state":{"consumption":22250,"lastupdated":"2020-01-18T22:22:41"},"t":"event","uniqueid":"00:15:8d:00:03:61:a3:ed-01-0702"}
diy_hue_beta   | 2020-01-18 22:22:41,992 - root - INFO - unable to process the request'2'
diy_hue_beta   | 2020-01-18 22:22:41,993 - root - INFO - {"e":"changed","id":"2","r":"sensors","state":{"consumption":22250,"lastupdated":"2020-01-18T22:22:41"},"t":"event","uniqueid":"00:15:8d:00:03:61:a3:ed-01-0702"}
diy_hue_beta   | 2020-01-18 22:22:41,993 - root - INFO - unable to process the request'2'
