### ISSUE TITLE
Handle Brightness Incr. and Stopping

### ISSUE THREAD

**Issue by ryancasler** [diyhue/diyHue#311]
So, there is a standard command in Zigbee cluster definition "Begin Move" which is passed along with the direction of either "up" or "down".  Then, when you want it to stop dimming (or brightning) you issue the stop changing command.

I have a Hubitat Elevation Hub, which has a built in integration with Hue over lan.  The commands that work on a real Hue hub are not working here.  Here is one of the commands that are issued:

```
192.168.1.12 - - [22/Dec/2019 21:04:15] "PUT /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/5/state HTTP/1.1" 200 -
2019-12-22 21:04:15,410 - root - INFO - in PUT method
2019-12-22 21:04:15,411 - root - DEBUG - Sending M-Search response to 192.168.1.2
2019-12-22 21:04:15,413 - root - INFO - /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/5/state
2019-12-22 21:04:15,417 - root - INFO - b'{"bri_inc":-254,"transitiontime":30}'
2019-12-22 21:04:15,435 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8080
2019-12-22 21:04:15,454 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "PUT /api/283145a4e198cc6535/lights/1/state HTTP/1.1" 200 39
2019-12-22 21:04:16,163 - root - INFO - LightRequest: http://127.0.0.1:8080/api/283145a4e198cc6535/lights/1/state
192.168.1.12 - - [22/Dec/2019 21:04:16] "GET /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/ HTTP/1.1" 200 -
2019-12-22 21:04:16,466 - root - INFO - [
    {
        "success": {
            "/lights/5/state/transitiontime": 30
        }
    },
    {
        "success": {
            "/lights/5/state/bri_inc": -254
        }
    }
]
192.168.1.12 - - [22/Dec/2019 21:04:17] "PUT /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/5/state HTTP/1.1" 200 -
2019-12-22 21:04:17,747 - root - INFO - in PUT method
2019-12-22 21:04:17,748 - root - INFO - /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/5/state
2019-12-22 21:04:17,749 - root - INFO - b'{"bri_inc":0,"transitiontime":30}'
2019-12-22 21:04:17,764 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8080
2019-12-22 21:04:17,769 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "PUT /api/283145a4e198cc6535/lights/1/state HTTP/1.1" 200 39
192.168.1.2 - - [22/Dec/2019 21:04:18] "GET /api/hueess0c21d611ea8c19b827ebdbe8fb/groups HTTP/1.1" 200 -
192.168.1.2 - - [22/Dec/2019 21:04:18] "GET /api/hueess0c21d611ea8c19b827ebdbe8fb/lights HTTP/1.1" 200 -
2019-12-22 21:04:18,474 - root - INFO - LightRequest: http://127.0.0.1:8080/api/283145a4e198cc6535/lights/1/state
2019-12-22 21:04:18,778 - root - INFO - [
    {
        "success": {
            "/lights/5/state/transitiontime": 30
        }
    },
    {
        "success": {
            "/lights/5/state/bri_inc": 0
        }
    }
]
192.168.1.12 - - [22/Dec/2019 21:04:26] "GET /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/ HTTP/1.1" 200 -
2019-12-22 21:04:26,773 - root - INFO - sync with lights
2019-12-22 21:04:26,807 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.139:80
2019-12-22 21:04:26,854 - urllib3.connectionpool - DEBUG - http://192.168.1.139:80 "GET /state?light=1 HTTP/1.1" 200 80
2019-12-22 21:04:26,890 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.118:80
```
For perspective, the light is starting out at 100% and is on.  Also, this is a Zigbee light connected through Deconz.  Now, upon receipt of the first command, the bulb begins to slowly dim, the way I would expect it to.  However, the switch state immediately changes to off.  Then, when the second command, the bri_inc:0 command is issued from the hub, the bulb stops dimming.  In this case, it was somewhere around 60.  I know this because I can see in the Phoscon app, that the light has the correct level but DIYHue is showing the light as off.  Eventually it refreshes the switch state but it never corrects the Dimmer Level.  That remains at 100% even though Deconz is reporting it somewhere around 60.  I let it sit for a LONG time and it never updates the dimmer value again from deconz.  It did take a couple of seconds before it got that info was updated in the Phoscon app but I don't know if that is just a delay in updating the interface on the webapp or if it is actually taking time to refresh the bulb.  No visibility into what's going on under the hood in Deconz. Although, it appears that it never even gets the lights states at boot from deconz but just assumes they are all at the previous established level...which is a little strange.

There is a community developed Hue integration for Hubitat that uses the level 1 instead of -254 for dimming down. That one sets the light level to 1 and then never updates it again, even though the Phoscon app shows that it knows that the light is the correct level after a seconds or two.

The issue is much worse for ESP controlled LED strips.  It appears that the same set of commands are sent from my Hub:
```
192.168.1.12 - - [22/Dec/2019 21:11:36] "GET /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/ HTTP/1.1" 200 -
2019-12-22 21:11:36,623 - root - DEBUG - Sending M-Search response to 192.168.1.2
2019-12-22 21:11:37,065 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
192.168.1.12 - - [22/Dec/2019 21:11:37] "PUT /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/3/state HTTP/1.1" 200 -
2019-12-22 21:11:37,171 - root - INFO - in PUT method
2019-12-22 21:11:37,175 - root - INFO - /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/3/state
2019-12-22 21:11:37,178 - root - INFO - b'{"bri_inc":-254,"transitiontime":30}'
2019-12-22 21:11:37,203 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.125:80
2019-12-22 21:11:37,237 - urllib3.connectionpool - DEBUG - http://192.168.1.125:80 "PUT /state HTTP/1.1" 200 42
2019-12-22 21:11:37,545 - root - INFO - [
    {
        "success": {
            "/lights/3/state/transitiontime": 30
        }
    },
    {
        "success": {
            "/lights/3/state/bri_inc": -254
        }
    }
]
2019-12-22 21:11:38,240 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2019-12-22 21:11:38,326 - root - DEBUG - Sending M-Search response to 192.168.1.2
192.168.1.12 - - [22/Dec/2019 21:11:39] "PUT /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/3/state HTTP/1.1" 200 -
2019-12-22 21:11:39,083 - root - INFO - in PUT method
2019-12-22 21:11:39,084 - root - INFO - /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/3/state
2019-12-22 21:11:39,084 - root - INFO - b'{"bri_inc":0,"transitiontime":30}'
2019-12-22 21:11:39,098 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 192.168.1.125:80
2019-12-22 21:11:39,147 - urllib3.connectionpool - DEBUG - http://192.168.1.125:80 "PUT /state HTTP/1.1" 200 39
2019-12-22 21:11:39,451 - root - INFO - [
    {
        "success": {
            "/lights/3/state/transitiontime": 30
        }
    },
    {
        "success": {
            "/lights/3/state/bri_inc": 0
        }
    }
]
192.168.1.12 - - [22/Dec/2019 21:11:39] "GET /api/eda6d61a252311ea8c44b827ebdbe8fb/lights HTTP/1.1" 200 -
192.168.1.12 - - [22/Dec/2019 21:11:39] "GET /api/eda6d61a252311ea8c44b827ebdbe8fb/groups HTTP/1.1" 200 -
```
But in this case (a string of WS2812B controlled by a Wemos D1 mini with a DIYHue Sketch loaded) the LEDs never stop changing and just blow right past the stop changing command.

Something similar happens on dimming up.  In this case, this is a deconz bulb starting at a level of 5%.

```
192.168.1.12 - - [22/Dec/2019 21:44:53] "PUT /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/5/state HTTP/1.1" 200 -
2019-12-22 21:44:53,442 - root - INFO - in PUT method
2019-12-22 21:44:53,443 - root - INFO - /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/5/state
2019-12-22 21:44:53,443 - root - INFO - b'{"bri_inc":254,"transitiontime":30}'
2019-12-22 21:44:53,456 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8080
2019-12-22 21:44:53,462 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "PUT /api/283145a4e198cc6535/lights/1/state HTTP/1.1" 200 41
2019-12-22 21:44:54,167 - root - INFO - LightRequest: http://127.0.0.1:8080/api/283145a4e198cc6535/lights/1/state
2019-12-22 21:44:54,470 - root - INFO - [
    {
        "success": {
            "/lights/5/state/bri_inc": 254
        }
    },
    {
        "success": {
            "/lights/5/state/transitiontime": 30
        }
    }
]
2019-12-22 21:44:54,682 - root - DEBUG - Sending M-Search response to 192.168.1.2
192.168.1.12 - - [22/Dec/2019 21:44:55] "PUT /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/5/state HTTP/1.1" 200 -
2019-12-22 21:44:55,406 - root - INFO - in PUT method
2019-12-22 21:44:55,407 - root - INFO - /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/5/state
2019-12-22 21:44:55,407 - root - INFO - b'{"bri_inc":0,"transitiontime":30}'
2019-12-22 21:44:55,421 - urllib3.connectionpool - DEBUG - Starting new HTTP connection (1): 127.0.0.1:8080
2019-12-22 21:44:55,427 - urllib3.connectionpool - DEBUG - http://127.0.0.1:8080 "PUT /api/283145a4e198cc6535/lights/1/state HTTP/1.1" 200 41
2019-12-22 21:44:56,132 - root - INFO - LightRequest: http://127.0.0.1:8080/api/283145a4e198cc6535/lights/1/state
192.168.1.12 - - [22/Dec/2019 21:44:56] "GET /api/08bbe25c095d11ea8ce8b827ebdbe8fb/lights/ HTTP/1.1" 200 -
2019-12-22 21:44:56,434 - root - INFO - [
    {
        "success": {
            "/lights/5/state/bri_inc": 0
        }
    },
    {
        "success": {
            "/lights/5/state/transitiontime": 30
        }
    }
]

```
In this case, when the stop was issued, the light stopped brightening correctly but the dimmer level stays at 5 even though Phoscon (deconz) is reporting that the light is actually at around 40%. DIYHue never updates the level correctly from Phoscon.

The community integration I mentioned, issues the same commands, except it issues a transitiontime of 40.  In that case, the dimmer always goes to 100% no matter where the light really stops.  

With the ESP LED strips, Raising is even stranger than lowering.  If the transitiontime is 40, upon the first command, the light begins to brighten.  But upon the Stop changing command, it immediately goes to 100%.  But if the transitiontime is 30, the light actually drops by 1% and then never changes again.  The state is correct in DIYHue...but it should be brightening.  

All of these commands work correctly to a real Hue Bridge.

Now, I see only two possibilities here:
1. This isn't really supposed to work this way and the fact that it does is just a happy coincidence for the folks who make my hub.
2. Something needs to change in DIYHue to handle the commands properly. 

If the answer is #1, then I'd like to be able to tell the folks who make the Hub what commands they should be using, so any help there would be appreciated.  But I believe this is the same command you would get from a ST hub, although, for some reason, I can't link my DIYHue with ST all of a sudden, so that will be the next thing I tackle.  

If there is any more in-depth logging you want me to do, I'm happy to do it.  I can also test out anything you need me to.  I'm more than willing to do whatever I can (although limited) to help get this all working correctly.  Thanks!!!

**Comment by mariusmotea** [comment]
Hi,

Long story short, Deconz expose sensors events via websocket using Hue Api. The Hue api do not contain low level ZigBee commands like `Begin Move` so in some cases i need to figure that a button code is a long press and even if the code is sent only one time the rules related to that code need to be executed in a loop until the button code is changed to something else. For this purpose i created the function `longPressButton` witch monitor the sensor when a certain buttonevent is received on websocket

https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L817


As currently i own just Tradfri remotes and Hue switches made with ESP8266 i added following code:
```
if "buttonevent" in message["state"] and bridge_config["deconz"]["sensors"][message["id"]]["modelid"] in ["TRADFRI remote control","RWL021"]:
    if message["state"]["buttonevent"] in [1001, 2001, 3001, 4001, 5001]:
        Thread(target=longPressButton, args=[bridge_sensor_id, message["state"]["buttonevent"]]).start()
```

at this moment i found just `1001, 2001, 3001, 4001, 5001` to be long press buttons codes witch probably contain that `Begin Move` command that i cannot receive on websocket.


Now regarding your output, `bri_inc": 254` with `transitiontime: 30` followed by a `bri_inc": 0` looks to be a loop command even if the maximum brightness is obtained just from first command. Probably my implementation of looping the button codes instead to have this `Begin Move` implemented in bulb firmware is not correct, but now i think is hard to change this. In your case is not possible to go forward with current workarround by adding the sensors buttonevents in  `longPressButton` function?

**Comment by ryancasler** [comment]
Thanks so much for your quick reply!  

> In your case is not possible to go forward with current workarround by adding the sensors buttonevents in `longPressButton` function?

Sorry, but I'm not familiar enough with the API to know how to pass that command over via an HTTP request.  I certainly could if you let me know what it is.  Also, I would need to pass over the button release to stop the light either dimming or brightening, wouldn't I? The issue is that the button is not directly connected to DIYHue but instead connected to my Hub.  That's why the command is sent across the way it is.  I assume you mean this for the ESP run LED strips, correct?  Not for the Deconz bulbs?

The only real problem for the Deconz connected lights is the fact that the bulb's level is incorrect in DIYHue after the dimming/brightening is done.  The bulb dims/brightens correctly and stops appropriately, the level is just incorrect.  Can the level be polled from Deconz so that it knows what the real level is?  If the level is wrong for a few seconds, that's fine.  The hub will eventually poll the bridge to get the correct switch state and level.  So, it just have to be right say 5 seconds after the ramping is complete.  If I could add a function to pull that from deconz, that would work.  Again, I'm not familiar enough with how that's implemented to know what's possible, just throwin stuff against the wall to see what sticks.  

Thanks so much for your help!

**Comment by ryancasler** [comment]
I think there might be something bigger going on, either with my setup or in general, I can't tell.  But I still can't add new devices from Deconz to my system, including the Tradri on/off remote.  Also, I touchlinked a remote to deconz and then to a couple of lights.  When I turn them on or off with the remote, the status never updates in DIYHue.  I thought it was supposed to poll Deconz for any other changes to the lights.  Or can we not use TouchLinked devices with DIYhue?   I can control the lights from DIYHue or the remote but the changes with the remote never show up in DIYHue.

**Comment by mariusmotea** [comment]
Diyhue receive the sensors events from Deconz via websocket. If the websocket stop working then there are no events received. This may happen if you restart deconz service. Regarding your output i don't see anything that may say there is a Begin Move command and not a simple one.

**Comment by ryancasler** [comment]
Well, I came home from my parents' house one Christmas Night to find the micro SD card that ran my diyhue, along with other things, totally corrupted.  So, I spent most of last night and this morning, re-installing DIYHue (along with everything else it was running) back again.  

One of the consequences of this is that it is now functioning much better as far as the Deconz lights go.  When I issue the commands that I originally did with `{"bri_inc":-254,"transitiontime":30}'`
the switch still turns off immediately for the light but after dimming or brightening stops by the command `b'{"bri_inc":0,"transitiontime":30}'`  the switch returns to the correct status and shortly thereafter, the brightness is corrected in DIYHue also.  So, it appears that I had one of the settings between Deconz and DIYHue either set incorrectly or DIYHue had become unauthorized from Deconz only partially.  But it was very strange because Deconz would accept all of the commands issued by DIYHue but any change made in Deconz would not be reflected in DIYHue.  So, I don't know how I would have fixed this without completely re-installing and rebuilding the configuration but it is working now.  

As a consequence, the other issue with lights not being imported from Deconz was also fixed.

**Comment by ryancasler** [comment]
As a side note, if anything could be done to address those commands and directly connected ESP lights, that would be huge help.  Right now I am "mirroring" a virtual dimmer on the system which results in multiple level setting commands being sent to the bridge.  Thanks!

**Comment by ryancasler** [comment]
FOUND IT!!!  Dunno why I didn't notice this before.  Instead of issuing a Bri:1 to start lowering the lights and then a Bri Inc: 0 to stop it, My hub is issuing a Bri Inc -254 to bring the brightness down by 254 steps.  This has the result of turning the light off since it's below zero.  So, the command coming from the hub is incorrect.  

However, for the ESP lights, setting the bri inc: 0 doesn't stop the lights from reaching the original commanded brightness.  I dunno if that's a problem with the lights firmware or the bridge but I suspect you'd have to add a function to both.  But I'll look into it and see if i can turn up anything.

**Comment by mariusmotea** [comment]
look [here](https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L1109)

if brightness go below 1 it must be set to 1.

**Comment by ryancasler** [comment]
Yes, exactly my point.  The command to bri inc -254 is the problem.  So, I have that corrected on the other system sending the commands to DIYHue and it is working correctly now.   Just closing the "loop".  :-)
