### ISSUE TITLE
arm64/v8 docker image

### ISSUE THREAD

**Issue by sakrist** [diyhue/diyHue#312]
**Describe the bug**
I've tried to run docker container on arm64 bit, Armbian Linux distributive.

**Docker script**
```
docker run -d --name "diyHue" --network="bridge" \
-v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' \
-e 'MAC=_my_mac_Address' -e 'IP=_my_IP_' \
-p 80:80/tcp \
-p 443:443/tcp \
-p 1900:1900/udp \
-p 2100:2100/udp diyhue/core:latest
```

**Logs**
```
Unable to find image 'diyhue/core:latest' locally
latest: Pulling from diyhue/core
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.
```

**Docker Info (please complete the following information):**
 - Architecture: ARM64/v8
 - Docker image version: latest
 - Hardware: Pine 64

**Comment by sakrist** [comment]
It's probably not that hard to create ARM64/v8 compiled container. I can try, but I don't have original Raspberry Pi to test on.

**Comment by Gizmo-Ger** [comment]
Sorry for opening up the thread again. I´m looking also to run a diyhue docker next to the deconz docker alined with some others on my Rock64 aarch64. 
uname -a
Linux rock64 4.4.190-1233-rockchip-ayufan-gd3f1be0ed310 #1 SMP Wed Aug 28 08:59:34 UTC 2019 aarch64 GNU/Linux
