### ISSUE TITLE
Stream busy error with Entertainment Area

### ISSUE THREAD

**Issue by OtavioMiguel19** [diyhue/diyHue#315]
I was using DiyHue for a few weeks. With it, I was using some version of November 2019 until yesterday, when I updated to latest diyhue version. Until then, I was using the entertainment area to connect Hue to razer synapse 3, but now in the latest version something was changed in code and it doesn't work anymore. What can be done?
[image](https://imgur.com/a/Tyg9dRL)

**Comment by mariusmotea** [comment]
Can you try to restart the hue-emulator service? Maybe something remain stuck.

**Comment by OtavioMiguel19** [comment]
> Can you try to restart the hue-emulator service? Maybe something remain stuck.

I tried, but no results
still the same problem

**Comment by mariusmotea** [comment]
Please share the config.json file from /opt/hue-emulator using pastebin link. If you enabled remote controll with Hue Essentials please join Slack channel and provide me your configuration in private.

**Comment by alexyao2015** [comment]
Since there has been no reply, I will be closing this issue.
