### ISSUE TITLE
CT Zigbee Bulbs Not Updated from Deconz + Possible Solution

### ISSUE THREAD

**Issue by ryancasler** [diyhue/diyHue#317]
When the level or switch state of a zigbee light connected through deconz changes, the change is not reflected in DIYHue.  Do i have the CT bulbs defined incorrectly in DIYHue?  Dimmable only and RGBW lgihts work perfectly now.  This is what I am seeing in the logs when the state changes in Deconz for one of the CT bulbs.

2019-12-29 18:39:27,057 - root - INFO - {"e":"changed","id":"2","r":"lights","state":{"alert":null,"bri":252,"colormode":"ct","ct":278,"hue":0,"on":true,"reachable":true,"sat":254,"xy":[0.3805,0.3769]},"t":"event","uniqueid":"f0:d1:b8:00:00:02:c5:28-01"}

But that state doesn't update the state of the light in DIYHue.  

Conversely, when I change a dimmable only bulb in Deconz, i get the following:

2019-12-29 18:42:22,966 - root - INFO - {"e":"changed","id":"4","r":"lights","state":{"alert":null,"bri":254,"on":true,"reachable":true},"t":"event","uniqueid":"e2:0d:b9:ff:fe:08:a8:5e-0a"}
2019-12-29 18:42:23,016 - root - INFO - {"e":"changed","id":"13770","r":"groups","state":{"all_on":false,"any_on":true},"t":"event"}

And that change is reflected in DIYHue.  Any idea why they would be handled differently?  How should I have the CT bulbs defined in DIYHue.  They are currently set as  "type": "Color temperature light",
If they should be something else, just let me know.

**Comment by ryancasler** [comment]
I think i found the fix though.....
old line 982 from the HueEmulator3.py file:

`if "state" in message and "colormode" not in message["state"]:`

changing that to this:
`if "state" in message:`
totally fixed the problem.  Dunno if that will break anything else but it definitely fixed it for me.

**Comment by mariusmotea** [comment]
That is a fix because Deconz report xy colormode for ct bulbs after some time. If the xy colormode is set the app will try to look for xy values witch are missing as the bulb is ct only. That line prevent the change of colormode. I had opened issue on Deconz repo and they state the bug is in Tradfri bulbs (witch i have) and Deconz send what they get

**Comment by ryancasler** [comment]
This isn't a Tradfri bulb though.  It's an Osram Edge-Lit Under-cabinet Light.  It still works fine in both DIYHue and Deconz with that line modified.

**Comment by janmannl** [comment]
@mariusmotea the implemented check fails, as it bounces all update calls from deconz (in the case of lights). Couldn't there be a more sophisticated check or removal of keys?
