### ISSUE TITLE
Support for Quin Led 

### ISSUE THREAD

**Issue by Xorfee** [diyhue/diyHue#324]
Since I love ur project, I would go a few steps forward. I would love to see that ur sketches also support quinLed sketches.. Like this: https://quinled.info/2019/02/24/quinled-deca-esphome-sample-configuration/

One board is driving two rgb ww nw strips

**Comment by mariusmotea** [comment]
But why generic rgb-cct sketch is not working?

**Comment by Xorfee** [comment]
Cause this sketch is controlling two 5 m stripes 5-24v with one board

**Comment by Xorfee** [comment]
And as far as I know the sketch for home assistant isn't compatible with those from diyhue? Or am I wrong?

**Comment by mariusmotea** [comment]
If Quin Led use ESP8266 PWM pins to controll the leds brigthess then use the generic sketch and set the GPIO pins for every led channel in WEB GUI.

**Comment by Xorfee** [comment]
QuinLed have his own sketch with a own pinouts in order to place a pcb.. But how does ur sketch example for standard rgb cct knows how many leds are hooked in. I thought diyhue lights can only be separated by leds with data line.. Those from quin are analog and works with just one board for two stripes.. Ur sketch is just for one strip

**Comment by mariusmotea** [comment]
The number of leds is important for led drivers to know what is the maximum power it must apply to the leds. To use two RGB-CCT lights on a single board you need 5 x 2 channels and ESP8266 don't provide this number  of GPIO pins. Probably they use ESP32.

**Comment by Xorfee** [comment]
I think he used a Esp32.. So it is possible to use his sketch for diyhue?

**Comment by Xorfee** [comment]
https://quinled.info/2019/12/19/quinled-deca-hardware-v1r7/

Here is the hardware

**Comment by mariusmotea** [comment]
Currently we have no sketch for ESP32. Despite is easy to migrate any sketch made for ESP8266 to ESP32, there will be a much bigger challange to upgrade the RGB-CCT sketch to support multiple lights.

**Comment by alexyao2015** [comment]
ESP32 will work with ESPhome integration. Multiple lights on a single device is currently not supported.
