### ISSUE TITLE
WS2812B Strip without transition Leds

### ISSUE THREAD

**Issue by Lunissystems** [diyhue/diyHue#325]
Dear all, 
First of all I'm not sure wether this is the right place to post this so if it isn't please move / point me to the right direction. 

I have recently built some WS2812b Led strips using diyhue and esp8266 controllers. I flashed them using the provided sketches in diyhue/Lights. Problem is, I am trying to achive a museum like spot look for the leds (I cut them into equally long pieces (5 Leds per spot) and connected them via some wires in various distances on a shelf) so the transition leds ruin the look, since they have to be at least 1 and therefore transition the colours frol spot to spot. Is there an easy way of turning them off / disabling them in the script ? I could of course try and understand the entirety of the code and patch them out but it seems like uneccesary work and I am not familliar with the Arduino IDE. I hope someone can help me. Thanks in advance!

**Comment by mariusmotea** [comment]
If you set 0 transistion leds in light configuration web interface it will not work as expected?

**Comment by Lunissystems** [comment]
To be honest I have not actually tried that since the Comment in the code of the lights variable said "Has to be divisible by number of lights", so I thought dividing by 0 would crash it. I will try nonetheless and thank you for the quick response!

**Comment by alexyao2015** [comment]
Try using esphome and modifying the default config to have no transitions.

**Comment by Lunissystems** [comment]
How exactly is this issue 'solved'?

**Comment by alexyao2015** [comment]
Please read the pinned issue for information on where to find support.

**Comment by Lunissystems** [comment]
Thank you for being less than helpfull :)

**Comment by alexyao2015** [comment]
#292
