### ISSUE TITLE
Zigbee Herdsman As A Framework To Integrate Zigbee Hardware And Devices

### ISSUE THREAD

**Issue by danieledwardgeorgehitchcock** [diyhue/diyHue#326]
**Is your feature request related to a problem? Please describe.**
At present, the only Zigbee controller framework supported by DiyHue is Deconz. There have been various requests (as well as Enhancement Projects [here](https://github.com/diyhue/diyHue/issues/83) and [here](https://github.com/diyhue/diyHue/issues/10)) that desire more Zigbee cheaper / generic controllers to be addable to the DiyHue ecosysem.

**Describe the solution you'd like**
[Zigbee Herdsman](https://github.com/Koenkk/zigbee-herdsman) (formally Shepherd) is an offshoot of the Zigbee2MQTT project which aims to create a generic API framework for Zigbee controllers and devices including various Zigbee derivations (Hue, Ikea, Xiaomi). Using this as a layer between DiyHue and hardware controllers will greatly simplify the integrations of new devices as well as avoiding the re-invention of the wheel when it comes to hardware support.

There is also a branch of Zigbee Herdsman which incorporates Deconz therefore, a refactor of coding for Herdsman will still allow for Deconz support within DiyHue while occupying a single codebase.

**Describe alternatives you've considered**
The only other alternative would be to manually code in the support and functionality which would divert developers time away from adding other features, or keeping on top of the ever-changing Hue API structure,

**Comment by alexyao2015** [comment]
Feel free to attempt integration if you have the time. Diyhue can be extended easily to support multiple protocols (use esphome and yeelight as examples).

**Comment by svrooij** [comment]
Possibly related to #310
