### ISSUE TITLE
Yeelight Music Mode

### ISSUE THREAD

**Issue by SilveIT** [diyhue/diyHue#327]
**Explanation**

My setup is:
1. Yeelight Color v2 bulb with v2.0.6_0065 firmware
2. Latest version of diyHue, installed on WSL.
3. Philips Hue Sync app.

The problem is when I use hue sync app as fast ambilight algorithm I encounter "client quota exceeded" error. The reason for this is not using Yeelight's music flow mode, it disables the quota. The reason for quota is cloud sync.

<details>
  <summary>Explanation from Yeelight forum</summary>

![Yeelight forum 1](https://user-images.githubusercontent.com/11407298/72294875-7b83fb80-3667-11ea-8201-a03556524852.png)
![Yeelight forum 2](https://user-images.githubusercontent.com/11407298/72294877-7de65580-3667-11ea-8217-6c5fe309cdbd.png)

</details>

**Steps to reproduce the behavior:**

1. Install and configure diyHue bridge to have a Yeelight bulb in Entertainment area.
2. Install a Hue Sync app (or ScreenBloom for example) and get it connected to the bridge.
3. Start light sync for video (for example).
4. Connect to the bulb via telnet 
![Connected](https://user-images.githubusercontent.com/11407298/72295491-bf2b3500-3668-11ea-881b-6d78e6228183.png)
and when it stops to receive commands from Hue Sync via diyHue enter any of Yeelight's commands, for example:
`{"id":1,"method":"toggle","params":[]}`
What you will get is this:
![Error](https://user-images.githubusercontent.com/11407298/72295461-ade22880-3668-11ea-9b3b-7275f167f228.png)

<details>
  <summary>Same thing with ScreenBloom app</summary>

![ScreenBloom](https://user-images.githubusercontent.com/11407298/72298585-8cd10600-366f-11ea-9b6e-e6378f49ea9f.png)

</details>

**Expected behavior**

Maintenance of all "Light Sync" lights in a separate network socket with music mode. You can achieve it by using "set_music" method to tell the Yeelight's device that it should connect to your server socket.

**Comment by alexyao2015** [comment]
Yep, music mode has not been implemented yet so usage of hue sync with yeelight will not work properly.

**Comment by mariusmotea** [comment]
Unfortunatelly music mode implementation is not an easy task because of the api that request the creation of dedicated services on server side for every bulb. I can support only with ideas on how to do it.

**Comment by alexyao2015** [comment]
Yeah I personally don't see myself investing the time into this because there are other more pressing issues.

**Comment by joaquinvacas** [comment]
Actually this has been fixed AFAIK two weeks ago.

https://gitlab.com/stavros/python-yeelight/-/issues/73

This issue also affects entertainment mode on TV with Ambilight

**Comment by SilveIT** [comment]
> Actually this has been fixed AFAIK two weeks ago.

What issue was fixed exactly? The issue you are commenting to is already closed. The music mode in the diyHue was implemented by me nearly 2 years ago already.
After that, the problem was a delay in signal output by Yeelight devices. I don't know if this has been fixed since then.
https://github.com/diyhue/diyHue/pull/331
