### ISSUE TITLE
DIYHUE + Generic_RGB_Light doesn't work

### ISSUE THREAD

**Issue by jellewie** [diyhue/diyHue#333]
**Describe the bug**
I'm working on trying to get the [Generic_RGB_Light ](https://github.com/diyhue/Lights/tree/master/Arduino/Generic_RGB_Light) to work on an ESP32, but the commands send from the DIYHUE hub seems be be wrong.

I get these 2 request on the ESP when I search for new devices, while the wiki says I should get a '/discover' and ESP8266 + DIYHUE code says I should get a '/detect'
`URI: /cm
Method: GET
Arguments: 1
 cmnd: Status 0`

`URI: /text_sensor/light_id
Method: GET
Arguments: 0`

**To Reproduce**
1. Get a url grabber; modifying the [Generic_RGB_Light ](https://github.com/mariusmotea/diyHue/blob/master/Lights/Arduino/Generic_RGB_Light/Generic_RGB_Light.ino)to only have the handleNotFound and post it to Serial would work fine. (this will send every command to the Serial as for debugging)
2. Make sure that DIYHUE  (check_updates.sh) and the android app are updated
3. do a 'Search for light' in the app
4. Now it will be unable to find the light (if you uploaded the original Generic_RGB_Light sketch, and 
when you debug it as listed above, it will give url request stated before "/text_sensor/light_id" and "/cm"

**Expected behavior**
That it would use a "/detect" command 
Also that the [WIKI ](https://diyhue.readthedocs.io/en/latest/lights/diylights.html#lights-api)shows the right command

**Comment by mariusmotea** [comment]
Sorry for wrong data present in the documentation. We made some improvements witch required changes at api level. I will update the documentation as currently is wrong.

**Comment by jellewie** [comment]
Wiki seems to be fixed (or at least worked on 👍)

So just the code to do? (I have no knowledge of python, so sorry here)

The ESP seems to get the "/text_sensor/light_id" command stated [here 'esphome.py'](https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/protocols/esphome.py)
and not the "/detect" command I was thinking it would get stated [here 'HueEmulator3.py'](https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py) and in the [wiki](https://diyhue.readthedocs.io/en/latest/lights/diylights.html#lights-api)

**Comment by alexyao2015** [comment]
It does. the esphome code is for esphome devices. the native firmware is handled elsewhere.

**Comment by jellewie** [comment]
@alexyao2015 So How would I be able to add/control an [Arduino light? ](https://github.com/diyhue/Lights/tree/master/Arduino)(for example a 'Generic_RGB_Light' posted on At '[diyhue/Lights](https://github.com/diyhue/Lights)')

**Comment by alexyao2015** [comment]
Thats not correct. Specifically, the text sensor is used for esphome only, so if you would like to use esphome to control the lights, go ahead.
