### ISSUE TITLE
Entertainment via CIE not working correctly (RGB works)

### ISSUE THREAD

**Issue by Kitula** [diyhue/diyHue#335]
Hi,
I recently set up DiyHue with mit Philips TV. I got the Ambilight+Hue working, but the colors did not change. I tried it with PC and HueSync. With HueSync the color change did work flawlessly.

I had a look at [entertainment.py](https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/functions/entertainment.py) and did some debugging with PC and TV. I noticed that PC used RGB telegrams and the TV used CIE telegrams.

The fix is to add a a new line in the CIE section after line 92 (count up to start of next lamp):
`i = i + 9`

**Comment by SilveIT** [comment]
Yeah, I've mentioned this bug 3 days ago. https://github.com/diyhue/diyHue/pull/329#issuecomment-575621592
Should be fixed.

**Comment by mariusmotea** [comment]
If no PR will be opened i will fix it later today.

**Comment by alexyao2015** [comment]
Sounds like this has been fixed
