### ISSUE TITLE
Latest Version Fails to load config

### ISSUE THREAD

**Issue by ryancasler** [diyhue/diyHue#336]
I updated to the latest version and am getting the following error when I try to run.

 File "./HueEmulator3.py", line 1932, in <module>
    updateConfig()
  File "./HueEmulator3.py", line 294, in updateConfig
    if light["modelid"].startswith("TRADFRI"):
AttributeError: 'NoneType' object has no attribute 'startswith'

I've put my config on pastebin.  

https://pastebin.com/nYCZMByV

Is it the Tradfri Remote that is causing the problem or the on/off plug?

**Comment by ryancasler** [comment]
I found it....for some reason when I brought in a simple on-off plug from Deconz, it didn't register a model  ID for it.  Dunno what it is supposed to be but I got it to load now.  I'll leave the broken config on paste bin if you want to look into why it came into DiyHue that way.

**Comment by mariusmotea** [comment]
This is Deconz bug. I faced similar issue with swversion key, see issue reported by me here:
https://github.com/dresden-elektronik/deconz-rest-plugin/issues/670

**Comment by ryancasler** [comment]
Okay.  Is there something I should set it to manually that would work best?  I just put it as "Phillips on/off light".  Everything works but if there is something else I should use, just let me know.  Thanks!!
