### ISSUE TITLE
Changes to CT lights in Deconz not Reflected in DIYHue

### ISSUE THREAD

**Issue by ryancasler** [diyhue/diyHue#337]
So, when changes are made to a CT light in Deconz, those changes are not being reflected in DIYHue.  It appears this event:

2020-01-21 12:56:55,223 - root - INFO - {"e":"changed","id":"2","r":"lights","state":{"alert":null,"bri":252,"colormode":"ct","ct":323,"hue":0,"on":true,"reachable":true,"sat":254,"xy":[0.3805,0.3769]},"t":"event","uniqueid":"f0:d1:b8:00:00:02:c5:28-01"}

Is being ignored and not reflected in the device state within DIYHue.

**Comment by janmannl** [comment]
I think this is due the following check, which prevents processing the data due to "colormode" existing in "state":

https://github.com/diyhue/diyHue/blob/9c6ece367ef035524725c5faeeb3b98a2898d419/BridgeEmulator/HueEmulator3.py#L972

**Comment by ryancasler** [comment]
I had forgotten that I'd posted this one already.  But I never did really receive an answer to why it couldn't be changed.  Thanks!

**Comment by janmannl** [comment]
@mariusmotea can’t this be solved differently?

**Comment by janmannl** [comment]
@mariusmotea any idea? This is pretty annoying and doesn’t seem Needed?

**Comment by mariusmotea** [comment]
On my home installation i discovered another issue, the colormode key is missing. However on lights i saw it remain in hs mode. I still debug.

**Comment by mariusmotea** [comment]
i don't find anything in the code that can set colormode for a group. I think this is changing from external request.
