### ISSUE TITLE
[FR] Vocolinc wifi bulb support?

### ISSUE THREAD

**Issue by Hukuma1** [diyhue/diyHue#340]
**Is your feature request related to a problem? Please describe.**
I know Yeelights were added and are the budget champ, but was wondering if anyone's seen the Homekit-ready/Google Assistant/Alexa Vocolinc lights? They're comparable to Yee and even the new 800 lumen bulb costs half the price of the Yee equivalent.

**Describe the solution you'd like**
I got 4 of these Voco bulbs and would love to help add support to diyHue so everyone can benefit from these bulbs too. I can't contribute with code, but more than willing to help by testing it on the hardware side?

**Describe alternatives you've considered**
Currently using them paired with Home Assistant via HomeKit. But since HA doesn't have a working Hue Entertainment solution, hoping diyHue can work.

**Comment by mariusmotea** [comment]
- As the Vocolinc bulbs have no public api is not possible to provide support for them.
- Open issues cannot be deleted.
