### ISSUE TITLE
KeyError: 'lightstates' after updating

### ISSUE THREAD

**Issue by obelix05** [diyhue/diyHue#343]
**Describe the bug**
After updating diyHue today it is unable to start because of the following KeyError:
```
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 1931, in <module>
    initialize()
  File "/opt/hue-emulator/HueEmulator3.py", line 187, in initialize
    sanitizeBridgeScenes()
  File "/opt/hue-emulator/HueEmulator3.py", line 199, in sanitizeBridgeScenes
    for lightstate in list(bridge_config["scenes"][scene]["lightstates"]):
KeyError: 'lightstates'
```

I checked my config and here is an extract of it:
```
    "scenes": {
        "13": {
            "appdata": {
                "data": "gCabc_z05_d02",
                "version": 1
            },
            "group": "3",
            "lastupdated": "2019-09-10T20:48:00",
            "lights": [
                "4",
                "1",
                "2",
                "3"
            ],
            "locked": false,
            "name": "Lesen",
            "owner": "me",
            "picture": "",
            "recycle": false,
            "type": "GroupScene",
            "version": 2
        },
    },
```
and there are no lightstates. I also checked the older issues and the code and there is one line https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L195 which checks if the group exists in groups. I checked that manually in my config and all scene-groups are available in groups. But no lightstates. 

**To Reproduce**
1. Docker pull diyhue/core:latest
2. start with my config
3. KeyError

**Expected behavior**
The shouldn't be a KeyError

**Comment by mariusmotea** [comment]
Delete the scenes from config.json file that don't have the `lightstates` key. Without `lightstates` the scenes are useless.

**Comment by obelix05** [comment]
Right. That makes sense. Okay I've deleted all the scenes from the config file and restart diyHue. Then I delete the rooms in the Hue app and recreate them to have the default scenes back.
Thanks a lot :+1:
