### ISSUE TITLE
Custom Deconz CC2531

### ISSUE THREAD

**Issue by coolcoons** [diyhue/diyHue#344]
I have Osram Lightify Bulbs which use ZigBee but I didn't want to buy a $40 deconz. I bought a $14 cc debugger and CC2531 but I don't know which firmware to use. I saw the firmware from zigbee2mqtt.io but I don't know if it is the right firmware. Is this the right one or is there something else I should be using?

**Comment by Paalap** [comment]
Just use deconz according to the documetation...of course on deconz hardware

**Comment by Mevel** [comment]
The only zigbee transceiver currently supported is the one from Dresden Elektronik, conbee or conbee 2 with phoscon software.

**Comment by coolcoons** [comment]
But can't I make that ZigBee USB stick by flashing Deconz's firmware onto it? I didn't want to buy deconz and instead make one by flashing firmware onto the CC2531. Is this possible? Or can I make diyhue recognize it when it isn't deconz?

**Comment by Mephistofeles** [comment]
You can't flash Deconz to CC2531, it's a completely different device. You can use it with zigbee2mqtt, however diyHue does not support it yet.
See https://github.com/diyhue/diyHue/issues/326

**Comment by coolcoons** [comment]
Will it have integration with zigbee2mqtt soon? Or can I code it myself?

**Comment by Mevel** [comment]
You are welcome to help diyhue! If you can contribute with zigbee2mqtt integration that would be wonderful.

**Comment by coolcoons** [comment]
Can you add this into the projects section?
