### ISSUE TITLE
Yeelight Meterorite control both leds

### ISSUE THREAD

**Issue by Xorfee** [diyhue/diyHue#345]
Any chance to control both lamps for my yeelight meteorite ceiling lamp? I currently can control just the warm and cold light but not the rgbw one on the top

**Comment by arneeichhorn** [comment]
Would also love this feature!
Does someone have a work around for this until this feature is getting implemented?

Maybe running a "FakeHue Bulb" Script that's communicating with diyHue and just redirecting all commands to the correct endpoints of the meteorite lamp?

**Comment by vKnmnn** [comment]
As a workaround we could add the background light as it's own RGB light. The yeelight protocol description tells us how to give commands to that one.
All there is to do is try do discover the background light on certain yeeligh models and then add that with a special handler. I'll take a look at it this week, but i'm not familiar with the code yet.

**Comment by mariusmotea** [comment]
Probably you need just to replace the bulb type in the emulator to have the color control enabled in hue apps. I expect the light just forward color commands to colored leds from the top and color temperature commands to the leds from the bottom. To enable this stop the hue emulator service or docker container (important!!!), locate the id of the light in /opt/hue-emulator/config.json and replace the values with the ones below:
```
        "13": {
            "capabilities": {
                "certified": true,
                "control": {
                    "colorgamut": [
                        [
                            0.6915,
                            0.3083
                        ],
                        [
                            0.17,
                            0.7
                        ],
                        [
                            0.1532,
                            0.0475
                        ]
                    ],
                    "colorgamuttype": "C",
                    "ct": {
                        "max": 500,
                        "min": 153
                    },
                    "maxlumen": 800,
                    "mindimlevel": 1000
                },
                "streaming": {
                    "proxy": true,
                    "renderer": true
                }
            },
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": false,
                    "mode": "safety"
                }
            },
            "manufacturername": "Philips",
            "modelid": "LCT015",
            "name": "preserve the initial name",
            "productname": "Hue color lamp",
            "state": {
                "alert": "none",
                "bri": 1,
                "colormode": "ct",
                "ct": 367,
                "effect": "none",
                "hue": 56141,
                "mode": "homeautomation",
                "on": false,
                "reachable": true,
                "sat": 53,
                "transitiontime": 9,
                "xy": [
                    0.502455,
                    0.265472
                ]
            },
            "swversion": "1.46.13_r26312",
            "type": "Extended color light",
            "uniqueid": "00:17:88:01:02:e5:b2:93-0b"
        }
```

**Comment by vKnmnn** [comment]
i'm sorry, marius, could you maybe highlight what parts you changed in that snippet?

**Comment by vKnmnn** [comment]
i just tested this and no, the lamp doesn't just translate color input to it's backlight.
The backlight has it's own API call in yeelight.

**Comment by mariusmotea** [comment]
I think the best will be to add two lights because this will cover all possible cases (ex you want just backlight to be on and main leds off). If we emulate just one light then the on / off command will be applied to both..
I propose the following things:
https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/protocols/yeelight.py#L61

`bridge_config["lights_address"][new_light_id] = {"ip": properties["ip"], "id": properties["id"], "protocol": "yeelight", "model": properties["model"], "background": False}`

here i added the `model` and the `background` key

The background rgb leds will be emulated in color bulb (in my dev i added a new type Hue Aura that is only color light, so this will be perfect) with `"background": True` and primary leds in CT bub with `"background": False`.
We will need to look for "background" key everytime and if this exist and is True we need to send the commands with `bg` preffix.

**Comment by vKnmnn** [comment]
I agree, this seems like the way to go.

**Comment by mariusmotea** [comment]
Any idea what models of Yeelight use this approach with two lights in one? I want to fix this for all.

**Comment by vKnmnn** [comment]
the yeelight Halo and Meteorite, as far as i know. The Meteorite calls itself ceiling10 in the yeelight app, i don't have access to the Halo one

**Comment by vKnmnn** [comment]
A good guess might be that lamps of type `ceiling*` support the backlight functions

**Comment by Paalap** [comment]
Ceiling4 has also a background light (yeelight 650mm lamp), but not all ceiling* having the background. There is also a new er Model with background light but I don't know the interna na ing.

And just to do it a little bit more complex, there is also a moon light mode for the main light (if it is on you can still dimm the light but the brightness is below usual level). Unfortunately the moon mode is gone for metiorite after last firmware update...

**Comment by Real-Konai** [comment]
I don't think so, because there are yeelight ceiling light without the color function.
I know the Yeelight Meteorite aka ceiling10.
From Philips there are also some Lights with the same function, the Hue Beyond, Hue Ensis and the Hue Flourish.

**Comment by vKnmnn** [comment]
In that case it might be interesting to see how Hue handles this and maybe go expose the yeelights to that

**Comment by mariusmotea** [comment]
Please test the following code:
https://pastebin.com/2xyufkaT

This is the content for yeelight.py.

You need to delete the current light and perform new search. 
Currently i update just `set_light` function, `get_light_state` function will read the state of the light without `bg_` prefix. This is easy to implement with the example from `set_light`

**Comment by vKnmnn** [comment]
i tried it just now and it seems to me that the discovery is in an endless loop. 
The app is responsive, but it keeps saying "searching". Even with the --debug switch i'm not seeing any yeelight related output on the console.

**Comment by vKnmnn** [comment]
And now the app just keeps crashing whenever i go to lamp settings... might be time for another completely new setup...

**Comment by mariusmotea** [comment]
I think one issue may be the fact that both lights have the same name. When the color light is added in this dedicated if statement look for `light_name` and replace it with `light_name` + "-bg".

**Comment by vKnmnn** [comment]
I edited the JSON file manually and added the new fields. I am able to control the lights separately, but i must've done somehting wrong, because one light reports as being unreachable and i can set CT and RGB on them both.

**Comment by vKnmnn** [comment]
i added the string to yeelight.py but nothing changes, still now discovery

**Comment by mariusmotea** [comment]
Any errors show in debug mode during light search? Remember to delete the lights first.

**Comment by vKnmnn** [comment]
yes, sure, i deleted the lights and even tried deleting the whole config. it seems to be a general yeelight-discovery problem though, as i can't discover any of me yeelights. They don't even answer to `echo -e "M-SEARCH * HTTP/1.1\r\nMAN:\"ssdp:discover\"\r\nST:wifi_bulb\r\n"  | netcat -u 239.255.255.250 1982`

Somebody else should test this, too.

**Comment by Xorfee** [comment]
So is this issue fixed now? Can't wait to control those lights
