### ISSUE TITLE
aarch64 Docker image 

### ISSUE THREAD

**Issue by Gizmo-Ger** [diyhue/diyHue#347]
Update: Stupid me. I just had to pull diyhue/core:aarch64. Mea culpa

I was hoping to run a diyhue docker next to the deconz docker alined with some others on my Rock64 aarch64.

```
uname -a
Linux rock64 5.4.20-rockchip64 #20.02.1 SMP PREEMPT Mon Feb 17 04:45:00 CET 2020 aarch64 GNU/Linux
```

root@rock64:~# `docker run -d --name "diyHue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' diyhue/core:latest`
Unable to find image 'diyhue/core:latest' locally
latest: Pulling from diyhue/core
docker: no matching manifest for unknown in the manifest list entries.
See 'docker run --help'.

**Expected behavior**
I don´t know why it isn´t working since there is a aarch64 manifest available.

**Docker Info (please complete the following information):**
 - Architecture: [aarch64]
 - Docker image version: [latest]
 - Hardware: [Pine Rock64 SBC]

**Comment by Mevel** [comment]
Working?

**Comment by mariusmotea** [comment]
can you provide docker container logs? Also is possible to start the emulator in debug mode and the output will be mote detailed.

**Comment by Gizmo-Ger** [comment]
Sorry for my late reply. It´s been a busy week. I started this morning from scratch again. Unfortunalty I didn´t work. I changed the command to docker run -d --name "diyHue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' diyhue/core:aarch64 but the container stopped immeadialty. Error output was under Portainer: standard_init_linux.go:211: exec user process caused "exec format error"

How can I provide more information?

**Comment by Gizmo-Ger** [comment]
Ok, for now I´m using a different route.
I started from scratch and built the docker locally:
`git clone https://github.com/diyhue/diyHue.git`
`cd diyhue`
`docker build -f /root/diyHue/.build/aarch64.Dockerfile`
`docker run -d --name "diyHue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' 6a17de61463e`

So far the docker runs and I´ll test attaching to deCONZ and setup some lights.
to be continued...

**Comment by svrooij** [comment]
I'm trying to create a new image (with mqtt functionally), can you try if this solves your issue?
https://hub.docker.com/r/svrooij/diyhue-mqtt

So you change to `svrooij/diyhue-mqtt:beta` it should be multi architecture

**Comment by Gizmo-Ger** [comment]
Thank you svrooij, I´ll test later tonight.

**Comment by svrooij** [comment]
@Gizmo-Ger did the new image work?

**Comment by Gizmo-Ger** [comment]
It worked but with yours or the original I coudn´t work a connection between deCONZ and diyHue. Only my Tradfri sensors would show up and no lights at all. After a whole sunday setting up and retry and setting up and try again I give up diyHue for now.

**Comment by svrooij** [comment]
#353
