### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by OtavioMiguel19** [diyhue/diyHue#352]
Hello!
I use the diyhue in my orange pi and worked fine until yesterday. Then, it stopped and now i can't access the service. It shows a fail in the systemctl.

I tried to uninstall and reinstall, and it still happens.

![image](https://user-images.githubusercontent.com/18494389/76298289-fb10fe00-6297-11ea-9ac5-f341a25f7f60.png)

**Comment by mariusmotea** [comment]
Please show the output of `sudo systemctl status hue-emulator -l`

**Comment by Mevel** [comment]
I updated today aswell and had trouble starting Hue emulator.
Reason was a missing python package that is needed for the mqtt integration. Check debug output!

**Comment by svrooij** [comment]
We implemented mqtt support yesterday. I only tested the docker part (which include the new requirement). I think you can fix by running `pip3 install -r requirements.txt --no-cache-dir` in the folder where it's installed

**Comment by svrooij** [comment]
Or I mean as stated in the new [install script](https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/easy_install.sh#L33-L40)

```
### installing paho-mqtt library
echo -e "\033[36m Installing Python MQTT.\033[0m"
curl -sL https://files.pythonhosted.org/packages/59/11/1dd5c70f0f27a88a3a05772cd95f6087ac479fac66d9c7752ee5e16ddbbc/paho-mqtt-1.5.0.tar.gz -o paho-mqtt-1.5.0.tar.gz
tar zxvf paho-mqtt-1.5.0.tar.gz
cd paho-mqtt-1.5.0/
python3 setup.py install
cd ../
rm -rf paho-mqtt-1.5.0.tar.gz paho-mqtt-1.5.0/
```

**Comment by OtavioMiguel19** [comment]
> Please show the output of `sudo systemctl status hue-emulator -l`

```
* hue-emulator.service - Hue Emulator Service
   Loaded: loaded (/lib/systemd/system/hue-emulator.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Tue 2020-03-10 09:39:11 UTC; 9h ago
  Process: 2788 ExecStart=/opt/hue-emulator/HueEmulator3.py (code=exited, status=1/FAILURE)
 Main PID: 2788 (code=exited, status=1/FAILURE)

Mar 10 09:39:11 orangepione systemd[1]: hue-emulator.service: Service RestartSec=30s expired, scheduling restart.
Mar 10 09:39:11 orangepione systemd[1]: hue-emulator.service: Scheduled restart job, restart counter is at 5.
Mar 10 09:39:11 orangepione systemd[1]: Stopped Hue Emulator Service.
Mar 10 09:39:11 orangepione systemd[1]: hue-emulator.service: Start request repeated too quickly.
Mar 10 09:39:11 orangepione systemd[1]: hue-emulator.service: Failed with result 'exit-code'.
Mar 10 09:39:11 orangepione systemd[1]: Failed to start Hue Emulator Service.
```

**Comment by vKnmnn** [comment]
as root, go to `/opt/hue-emulator` and run `python3 HueEmulator3.py`

you'll get the output we need then
