### ISSUE TITLE
Discovery problems

### ISSUE THREAD

**Issue by vKnmnn** [diyhue/diyHue#359]
I am unable to find the hue bridge with my Philips TV. I can find it with the phone, but the button turns to show 'settings' for a split second only. Hue essentials connects without problems.

I am using the openwrt version that I installed with the script an hour ago
(which BTW has a dependency missing)

Do you have an idea what we could do to find out why this is?

**Comment by vKnmnn** [comment]
In case it might be important, I migrated the existing config of a docker version of diyhue to the new install. Could that be the problem? The emulator recognizing the phone and it failing to authenticate because I reset the app?

**Comment by mariusmotea** [comment]
Based on your os i think you have more interfaces and the certificate was generated using wrong interface mac address. If you inspect the CN of the certificate with curl -v -k https://ipaddress it looks close with the LAN interface mac address?

**Comment by mariusmotea** [comment]
I just receive your second message. You cannot migrate the existing installation withour to generate new certificate. Perform a fresh install from witch you take just the cert.pem file, then restore existing installation but use the new certificare. The hue app cache old certificate and will require reset, for the tv i don't know.

**Comment by vKnmnn** [comment]
It looks like A Mac adress, but there is no such address on my network

**Comment by vKnmnn** [comment]
Is there a way to regenerate the cert without losing the config?

**Comment by mariusmotea** [comment]
Yes, use this:
`curl http://mariusmotea.go.ro:9002/gencert?mac=FF:FF:FF:FF:FF:FF`

Replace FF with the mac address the hue app and tv will see (LAN interface if is not complex setup)
Put the returned content in cert.pem file and restart the hue emulator.

**Comment by vKnmnn** [comment]
I kept the original certificate from the installation. This has a wrong Mac address as well. Can I force certificate creation with a certain Mac? I think that's what the docker version does, right?

**Comment by mariusmotea** [comment]
Perform [this debug method](https://diyhue.readthedocs.io/en/latest/AddFuncts/debug.html#https-certificate-check) and don't forget to wipe Hue app data after every certificate change. In Hue app click Help button and type emulator ip, don't use local detection. I notice in new versions it use just cloud based detection if internet connection is detected...

**Comment by vKnmnn** [comment]
OK so the bridge ID and Mac in the json object are correct, but the cert still isn't. I got a new one via curl and put it in the folder, but curl still tells me the wrong CN

**Comment by vKnmnn** [comment]
Interesting: https:192.168.10.1:443 redirects me to the luci login page of the router but also returns a json object in Firefox

**Comment by vKnmnn** [comment]
A reboot of the router resolved the issue with the certificate,but I'm still unable to  discover it with the tv

**Comment by mariusmotea** [comment]
Cut temporary the internet in order to force the tv to use local SSDP discovery.

**Comment by vKnmnn** [comment]
I have already tried this, doesn't help.
Also the TV finds the bridge that I spin up on the container even with an internet connection.

**Comment by vKnmnn** [comment]
ha, there's something going wrong. this is the output of the emu on the router
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 870, in run
  File "/opt/hue-emulator/functions/ssdp.py", line 22, in ssdpSearch
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)
OSError: [Errno 19] No such device

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
  File "/usr/lib/python3.7/threading.py", line 870, in run
  File "/opt/hue-emulator/functions/ssdp.py", line 51, in ssdpBroadcast
    sock.sendto(bytes(message + "NT: " + custom_message[x]["nt"] + "\r\nUSN: " + custom_message[x]["usn"] + "\r\n\r\n", "utf8"),multicast_group_s)
OSError: [Errno 101] Network unreachable

```

**Comment by vKnmnn** [comment]
I made an error.

The interface that the emu should be available on is `62:38:e0:b6:78:90` (ends with 0)
but /api/nouser/config returns `62:38:e0:b6:78:91` (ends with 1) , which is another interface on the router. In the `config.json` file it reports also the IP address of that wrong interface.

**Comment by mariusmotea** [comment]
You can provide the mac address as argument to the script.

**Comment by vKnmnn** [comment]
The bridge is available now with the correct MAC, ID and CN in the certificate, but the TV still cannot find it.

**Comment by mariusmotea** [comment]
Only thing you can do now is to start a new installation on a Ubuntu/Debian vm (Virtual Box) and see if the tv detect this. If yes maybe the tv cached the old certificate and now deny any connection to router mac address.

**Comment by vKnmnn** [comment]
I grabbed a raspberry and put buster on it, got the file `curl -s https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_install.sh ` and ran it.
then i started it and put the TV in discovery mode and it found both bridges!

i have no idea what changed or why this worked, but hey, i'll take it.

**Comment by vKnmnn** [comment]
Wait, actually i do know. I disconnected the TV from power today, so it might have something to do with that.
