### ISSUE TITLE
Pairing issue with Philips TV

### ISSUE THREAD

**Issue by FezVrasta** [diyhue/diyHue#36]
**Describe the bug**
I'm trying again to pair Hue Emulator to my old Philips TV but I can't manage to make the pair work.

Something I noticed is that when I scan for bridges through the TV, it finds "Philips hue" even if I renamed the hue emulator to "Hue Emulator" (and I can see the new name on the iOS app).

I already formatted the TV with the factory reset option but it always finds "Philips hue" and when I click the "activate" button nothing happens.

**Logs**
```
10.0.0.2 - - [25/Dec/2018 19:33:48] "GET /description.xml HTTP/1.1" 200 -
10.0.0.2 - - [25/Dec/2018 19:34:50] "GET /description.xml HTTP/1.1" 200 -
10.0.0.17 - - [25/Dec/2018 19:34:57] "GET /description.xml HTTP/1.1" 200 -
10.0.0.2 - - [25/Dec/2018 19:35:18] "GET /description.xml HTTP/1.1" 200 -
10.0.0.2 - - [25/Dec/2018 19:36:27] "GET /description.xml HTTP/1.1" 200 -
10.0.0.2 - - [25/Dec/2018 19:39:44] "GET /description.xml HTTP/1.1" 200 -
10.0.0.231 - - [25/Dec/2018 19:40:43] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
```

**Comment by mariusmotea** [comment]
I believe i know why. On /description.xml there is the field `friendlyName` that contain the name and the ip address. I was believe the name is static there used for detection only, but after i rename my original bridge i saw that was changed. I will fix this in next commit.

**Comment by mariusmotea** [comment]
Fixed

**Comment by timbru31** [comment]
Sometimes I need to rescan 3-5 times for the TV (55OLED903) to (re-)discover my bridge. Sometimes a full Android reboot of the TV is required for the Ambilight+Hue to work again. Looking forward to the Android 8 upgrade to see if things change.
