### ISSUE TITLE
Portal iOS Application fails to detect Hue Bridge

### ISSUE THREAD

**Issue by bhagyas** [diyhue/diyHue#365]
I think this is related to the discovery issue. #217

**Comment by mariusmotea** [comment]
If you cut the internet access on your phone it is still not detecting anything. Any SSDP interrogation messages in emulator debug output when you perform the discovery?

**Comment by bhagyas** [comment]
@mariusmotea I tried turning the mobile data off and unplugging the router external connection, but it seems to fail. I was unable to see any debug output.
