### ISSUE TITLE
Emulate Fake Devices like HA-Bridge

### ISSUE THREAD

**Issue by cylon147** [diyhue/diyHue#368]
is it possible to Emulate Fake Devices Like HA-Bridge for Further Integration with Other Systems? I would love to use Bridge V2 Features but as I set up involves another system for Integration, I can't use it.

If this cant is done right now I suggest it should be added in a future version as it has a lot Potential for integration.

**Comment by mariusmotea** [comment]
Is possible to emulate fake devices, only that you need to add them in config.json file manually.

**Comment by cylon147** [comment]
I have Searched Everywhere in PI but Could not find the file. please let me know from where may i find the config.json file?

**Comment by mariusmotea** [comment]
it is located in /opt/hue-emulator/config.json. You need to stop the service before you perform any changes in this file, otherwise they will be overrides.
