### ISSUE TITLE
Color Mode Reporting

### ISSUE THREAD

**Issue by ryancasler** [diyhue/diyHue#369]
Is there a way currently (or could one be added) to force a color light to use the HS mode rather than the XY mode?  Currently, I am controlling my DIYHue connected lights from another platform that doesn't support XY mode.  And DIYHue accepts the commands to set the light via HS mode perfectly.  But as soon as I make a color change from within DIYHue, it changes from HS mode to XY mode.  I was hoping there would be a way to force the bridge software to use HS mode and not revert to XY mode.  

Thanks!!

**Comment by mariusmotea** [comment]
Diyhue accept both xy and hs values to comply with the hue api. As multiple light vendors are supported, we incorporate converstes to all other types (including rgb). In the `state` key of every light is stored last applied state, if it was xy then xy values are updated and colormode will have xy value, if is hs hue and sat values are updated and colormode will be set to hs. If you want to manually change this, comment folllowing statements:

https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L575
https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L1158

**Comment by ryancasler** [comment]
That's the thing tough, I am requesting a HS for a group and then the Bridge is returning an XY for each of the components inside the group.

**Comment by mariusmotea** [comment]
I will try to replicate this, what type of lights you have in that group?

**Comment by ryancasler** [comment]
WS2812 LED strips with the DIYHue Arduino sketch loaded on an ESP8266.  Do you want the config from my config.json?
