### ISSUE TITLE
HueEmulator3.scanForLights does not scan all found ips

### ISSUE THREAD

**Issue by Death111** [diyhue/diyHue#37]
**Describe the bug**
I'm using the WS2812B HueStrip example with a dockerized bridge. When I search for the lamp with the hue app, it is not found. 

I found that there is a problem in the python code. It uses nmap to search for devices listening on port 80. From this list, the last element is deleted. See code snippet from HueEmulator3.py
760 -    logging.info(pretty_json(device_ips))
761 -    del device_ips[-1] #delete last empty element in list
I do not know why the last one is deleted - comment suggests that the last element should be empty - which is not the case for me.  In fact, the last element is the device I'm searching.

I'm using the docker image hosted on a Windows 10 with Docker for Windows.

**Logs**
Logs after pressing the search button in the Hue App
172.17.0.1 - - [26/Dec/2018 11:57:13] "POST /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
2018-12-26 11:57:13,226 - root - INFO - in post method
2018-12-26 11:57:13,226 - root - INFO - /api/a7161538be80d40b3de98dece6e91f90/lights
2018-12-26 11:57:13,226 - root - INFO - b'{}'
172.17.0.1 - - [26/Dec/2018 11:57:13] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:13] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
2018-12-26 11:57:13,648 - root - INFO - sync with lights
172.17.0.1 - - [26/Dec/2018 11:57:14] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:14] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:15] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:15] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:16] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:16] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:17] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:17] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:18] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:18] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:18] code 404, message not found
172.17.0.1 - - [26/Dec/2018 11:57:18] "GET /cm?cmnd=Status%200 HTTP/1.1" 404 -
172.17.0.1 - - [26/Dec/2018 11:57:19] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:19] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -
2018-12-26 11:57:19,947 - root - INFO - [
    "192.168.178.1",
    "192.168.178.22",
    "192.168.178.26",
    "192.168.178.31",
    "192.168.178.47"
]
2018-12-26 11:57:20,084 - root - INFO - registration fail, is the link button pressed?
172.17.0.1 - - [26/Dec/2018 11:57:20] "GET /api/a7161538be80d40b3de98dece6e91f90/groups HTTP/1.1" 200 -
172.17.0.1 - - [26/Dec/2018 11:57:20] "GET /api/a7161538be80d40b3de98dece6e91f90/lights HTTP/1.1" 200 -

The last ip in the list is the correct one.

I commented the line with the del instruction and the app found the lamp! :)

**Comment by mariusmotea** [comment]
I fix the bug. While rstrip was added to nmap output that line was not necessary anymore.
