### ISSUE TITLE
Tasmota lights unreacheable but still works

### ISSUE THREAD

**Issue by betonishard** [diyhue/diyHue#370]
**Describe the bug**
Tasmota lights show unreachable in the app, however they do respond to changes (e.g. On/off / color change)

**To Reproduce**
Add tasmota lights (version 8.2) to diyhue. This can not be done via the app since they are unreacheable. But you can do it with manual config. I am running diyHue from docker.

**Expected behavior**
Not an error message
**Logs**
diyhue                  | WARNING:root:xxxr is unreachable: invalid literal for int() with base 16: ',2'
diyhue                  | WARNING:root:xxxx is unreachable: invalid literal for int() with base 16: ',10'

**Additional context**

Thanks for the great product

**Comment by mariusmotea** [comment]
The lights are displayed unreachable when there is an error when the lights are fetched. The error seams to be `invalid literal for int() with base 16: ',2'`. I don't have Tasmota lights, but maybe i can understand the cause.

**Comment by mariusmotea** [comment]
I check the code. The docker image update process is not working anymore. The line that cause the error is now commented in the master branch:

https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/protocols/tasmota.py#L129

**Comment by mariusmotea** [comment]
Please update now the docker image. The publish was fixed.

**Comment by mariusmotea** [comment]
Thanks for the tip. I don't use Tasmota but based on your findings i made a new change. I will be glad if you can test it to confirm i did not broke something. I think last commit was made by an user who saw the color value is in hex and not list, so he comment the previews lines without to know about this setting for color reporting.

**Comment by betonishard** [comment]
Sorry doesn't work

WARNING:root:Txxx is unreachable: '>' not supported between instances of 'str' and 'float'

**Comment by mariusmotea** [comment]
Thanks. I revert my changes.

**Comment by betonishard** [comment]
why

**Comment by alexyao2015** [comment]
What is the issue happening here?

**Comment by mariusmotea** [comment]
While we tried to fix this issue i created another one bigger, so i revert the changes. Is possible to be fixed in this moment because i notice some pull requests to this function.

**Comment by marcelkordek** [comment]
Hi, you have to change the "def get_light_state(light)" in /opt/hue-emulator/lights/protocols/tasmota.py:

```
def get_light_state(light):
    logging.debug("tasmota: <get_light_state> invoked!")
    data = sendRequest ("http://" + light.protocol_cfg["ip"] + "/cm?cmnd=Status%2011")
    #logging.debug(data)
    light_data = json.loads(data)["StatusSTS"]
    #logging.debug(light_data)
    state = {}

    if 'POWER'in light_data:
        state['on'] = True if light_data["POWER"] == "ON" else False
        #logging.debug('POWER')
    elif 'POWER1'in light_data:
        state['on'] = True if light_data["POWER1"] == "ON" else False
        #logging.debug('POWER1')

    if 'Color' not in light_data:
       #logging.debug('not Color')
        if state['on'] == True:
            state["xy"] = convert_rgb_xy(255,255,255)
            state["bri"] = int(255)
            state["colormode"] = "xy"
    else:
        #logging.debug('Color')
        #logging.debug(light_data["Color"])
        if "," in light_data["Color"]:
            # RGB
            rgb = light_data["Color"].split(",")
            state["xy"] = convert_rgb_xy(int(rgb[0],16), int(rgb[1],16), int(rgb[2],16))
        else:
            # HEX
            hex = light_data["Color"]
            rgb = hex_to_rgb(hex)
            state["xy"] = convert_rgb_xy(rgb[0],rgb[1],rgb[2])

        state["bri"] = (int(light_data["Dimmer"]) / 100.0) * 254.0
        state["colormode"] = "xy"

    return state
```

The function checks whether tasmota delivers hex values or rgb values. it works fine for me.

greetings
marcel

**Comment by mariusmotea** [comment]
I don't use Tasmota but has logic. I applied your fix to the repo.
