### ISSUE TITLE
MQTT (zigbee2mqtt) lights not found / found as wrong bulb / unavailable

### ISSUE THREAD

**Issue by muePatrick** [diyhue/diyHue#371]
The Problem is, that MQTT lights from Zigebee2MQTT are not detected via the app (Phillips App and Hue Essentials). It throws an error, that 0 bulbs were found.
Everything is set up like in the diyHue docs under MQTT - Configuration
I used the newest (as of April 1st 2020) Docker versions of Zigbee2MQTT and diyHue.

To fix the problem I had to change the protocols/mqtt.py file:

In the "on_autodiscovery_light" function it gives an error while parsing the JSON since it expects a string but gets bytes. So in the "on_autodiscovery_light" and the "on_state_update" function I had to change "data = json.loads(msg.payload)" to "json.loads(msg.payload.decode("utf-8"))".

Next it discovered the bulbs but as the wrong type of light (Color instead of Color and Color Temperature Lights). That is because (at least in my tests) Zigbee2MQTT calls the "ct" flag "color_temp". So while selecting the model in the discover function it should be "light_ct = "color_temp" in keys and data["color_temp"] == True".

Finally to be able to change the color temperature the "set_light" function needs "if key == "ct": state['color_temp'] = value". And in "get_light_state" the opposite "if key == "color_temp": state['ct'] = value".

With all this I can control the bulbs but I am still getting the light unavailable notification.
(I am sorry, that I kept the issue that short but I wrote it the first time and it did not get submitted so this is my second attempt)
Anyway thank you so much for implementing MQTT support.

**Comment by mariusmotea** [comment]
Hi,

Can you create a PR with proposed changes?  Current release was made by @svrooij. I go forward and i had added support for entertainment and sensors (limited to Ikea, xiaomi and Hue motion sensor) and this can be found in develop branch.

**Comment by muePatrick** [comment]
Hi,

thank you for the answer.

I will create the pull request once I am back home over the weekend.

**Comment by malt3** [comment]
I created a pull request as suggested.

**Comment by muePatrick** [comment]
Thank you so much. I just could not get the mqtt to work on a non-docker instance for some reason. So I never got around to create a pull request. Thank you, again.
