### ISSUE TITLE
diyHue fails to start: IndexError: string index out of range

### ISSUE THREAD

**Issue by Zireael** [diyhue/diyHue#377]
**Describe the bug**
Hi,
I have installed diyHue manually and as a docker container in raspberry pi 4 (rapsbian).
For both methods the `HueEmulator3.py` script fails to run with the following error:

> Docker Setup Initiated
> 
> Restoring Certificate 
> Certificate Restored> 
> Restoring config> 
> Config restored> 
> Docker Setup Complete> 
> Traceback (most recent call last):> 
>   File "/opt/hue-emulator/HueEmulator3.py", line 1936, in <module>> 
>     initialize()> 
>   File "/opt/hue-emulator/HueEmulator3.py", line 184, in initialize> 
>     bridge_config["config"]["mac"] = mac[0] + mac[1] + ":" + mac[2] + mac[3] + ":" + mac[4] + mac[5] + ":" + mac[6] + mac[7] + ":" + mac[8] + mac[9] + ":" + mac[10] + mac[11]
>   IndexError: string index out of range

**To Reproduce**
1. Follow the docs: https://diyhue.readthedocs.io/en/latest/getting_started.html#docker-install
2. execute `sudo docker run -d --name "diyHue" --restart="always" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' diyhue/core:latest`
3. Check docker container logs

**Expected behavior**
diyHue starts and works

**Logs**
Docker Setup Initiated
Restoring Certificate
Certificate Restored
Restoring config
Config restored
Docker Setup Complete
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 1936, in <module>
    initialize()
  File "/opt/hue-emulator/HueEmulator3.py", line 184, in initialize
    bridge_config["config"]["mac"] = mac[0] + mac[1] + ":" + mac[2] + mac[3] + ":" + mac[4] + mac[5] + ":" + mac[6] + mac[7] + ":" + mac[8] + mac[9] + ":" + mac[10] + mac[11]
IndexError: string index out of range

**Additional context**
Running in raspberry Pi 4 (raspbian)

**Comment by mariusmotea** [comment]
You must specify the mac address and host ip address as env variables to the container. Delete curent data folder and start with fresh install because https certificate must contain the mac address in CN

**Comment by Zireael** [comment]
I got it working after adding MAC in the docker command line

> docker run -d --name "diyHue" --restart="always" --network="host" **-e MAC='XX:XX:XX:XX:XX:XX'**  -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' diyhue/core:latest

The 'host' snippet example in the docs installation page is incorrect as it is missing `-e MAC` argument and anyone following that snippet will fail.
https://diyhue.readthedocs.io/en/latest/getting_started.html#docker-install

**Comment by Mevel** [comment]
Thank you!
