### ISSUE TITLE
Lights control / Link device broken=?

### ISSUE THREAD

**Issue by erichegit** [diyhue/diyHue#38]
### 1st
I used "Import from Bridge" and I got the message, that 3 devices are found.
config.json shows them

`
    "lights_address": {
        "1": {
            "ip": "192.168.1.211",
            "light_id": "1",
            "protocol": "hue",
            "username": "********"
        },
        "2": {
            "ip": "192.168.1.211",
            "light_id": "2",
            "protocol": "hue",
            "username": "********"
        },
        "3": {
            "ip": "192.168.1.211",
            "light_id": "3",
            "protocol": "hue",
            "username": "********"
        }
`

But in the Webinterface, on Lights control, I see nothing,...
I supose to see the 3 devices?

### 2nd
I try to use "Link Device".
In my app I find the diyHUE Bridge, but it tells me to press the round Button.
How are I am suposed to do this?

**Comment by Mevel** [comment]
Import from bridge is for use with genuine hue bridge. Lights show in web interface, once they are configured via hue app. For that, you need to pair app and DiyHue.

In web interface of hue emulator, see "linking" page and use Hue:Hue as login and password. Klick active to push the "virtual link button" of Diy hue

**Comment by erichegit** [comment]
The app always finds the diyHUE Bridge, but asks me to press the button.

http://192.168.1.228/hue/linkbutton?username=Hue&password=Hue&action=Activate
doesn`t solve the problem.

Here is what I get from the console

```
192.168.1.2 - - [26/Dec/2018 18:37:07] "GET / HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:37:07] "GET /config.js HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:37:07] "GET /static/js/main.7409e575.js HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:37:07] "GET /static/css/main.23de7225.css HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:37:07] "GET /favicon-16x16.png HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:37:08] "GET /api/web-ui-49658/groups HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:37:08] "GET /api/web-ui-49658/lights HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:37:09] "GET /api/web-ui-49658/groups HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:37:09] "GET /api/web-ui-49658/lights HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:37:10] "GET /hue/linkbutton HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:37:47] "GET /hue/linkbutton?username=Hue&password=Hue&action=Activate HTTP/1.1" 200 -
192.168.1.206 - - [26/Dec/2018 18:37:52] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:38:24] "GET /hue/linkbutton?username=Hue&password=Hue&action=Activate HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:38:31] "GET /hue/linkbutton?username=Hue&password=Hue&action=Activate HTTP/1.1" 200 -
192.168.1.206 - - [26/Dec/2018 18:38:53] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:39:17] "GET /hue/linkbutton?username=Hue&password=Hue&action=Activate HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:39:27] "GET /hue/linkbutton?username=Hue&password=Hue&action=Activate HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:39:30] "GET /hue/linkbutton?username=Hue&password=Hue&action=Activate HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:39:32] "GET /hue/linkbutton?username=Hue&password=Hue&action=Activate HTTP/1.1" 200 -
192.168.1.2 - - [26/Dec/2018 18:39:32] code 404, message not found
192.168.1.2 - - [26/Dec/2018 18:39:32] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by mariusmotea** [comment]
Reinstall the Hue app. In webgui only the lights that belong to groups are displayed. New lights need first to be added to groups.

**Comment by erichegit** [comment]
I did everything, but it is not working!

I setup a clean new Raspbian Stretch for my Pi 3.
Did an update, upgrade

cloned the GIT
this time used your easy_install script.

deinstalled the HUE app on my android phone.
reinstalled it.

same behavor then bevore.

App says 2 Bridges are detected.
On my hardware HUE Bridge I press the Button --> works fine.
For the diyHUE the App wants me to press also the button - I can not do this (Activate is not enougth).
--> FAILs :(

Also for me strange is that when saving I get
`[{"success":{"filename":"/opt/hue-emulator/config.json","configuration":"saved"}}]`

But when I look at the filedate, it is still old.
In the "BridgeEmulator" Folder the config.json see to get updated instead (wrong message=?)

What can be the problem I am facing - con`t be the only one with an raspberry struggling = ?

**Comment by mariusmotea** [comment]
You need to execute the script from /opt/hue-emulator location. Now because you put habridge on same device will require to wipe hue app data because the certificate is cached and any other certificate will be refused from same device.
