### ISSUE TITLE
Tasmota ON/OFF state isn't being tracked

### ISSUE THREAD

**Issue by mcer12** [diyhue/diyHue#381]
I use several smart plugs with Tasmota and they work great with diyHue, except when I switch them with a button. diyHue doesn't seem to track physical button change. 
I guess this is because it would have to send updates to the Bridge. Is it possible for the bridge to check for the changes regularly?

**Comment by mariusmotea** [comment]
This is already implemented, but maybe there is a bug:

https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/protocols/tasmota.py#L101

Can you check if POWER or POWER1 values are changing when you press the button on smart plug status?

http://plug_ip/cm?cmnd=Status%2011

**Comment by mcer12** [comment]
Sorry, false alarm, it works. Can't explain it but it works now and didn't before. Maybe there was just some network delay, who knows.
