### ISSUE TITLE
FW version in web ui

### ISSUE THREAD

**Issue by mcer12** [diyhue/diyHue#382]
Would be nice to be able to check currently installed version quickly in web ui. Somewhere in the footer. Would this be difficult to implement?

release version (commit hash)
```
v2.3.4 (fe37796e223dcd18abd39d5c853a9ae427e4a958)
```

**Comment by mariusmotea** [comment]
Probably easy, but i don;t know react. I try to compile the web interface code again and now it don't work at all with latest libraries.

**Comment by mcer12** [comment]
Maybe we can ask original creator of the web interface?

**Comment by mariusmotea** [comment]
We can try. @FezVrasta  can you help us again?

**Comment by FezVrasta** [comment]
I'm taking a look, give me a minute.

**Comment by FezVrasta** [comment]
This should fix the build
https://github.com/diyhue/diyHue/pull/387

**Comment by alexyao2015** [comment]
Sounds like this was fixed?

**Comment by mariusmotea** [comment]
@mcer12 can this be closed now?
