### ISSUE TITLE
Can't get mi_box (Milight ibox2)  working in diyhue

### ISSUE THREAD

**Issue by scholzmichael** [diyhue/diyHue#383]
diyHue(latest version) installed and running on a pi3B+, added multiple ESP8266 devices (tasmota) and they are working fine. Now tried to add groups of my original Milight Box (ibox2,V6) according to [https://github.com/diyhue/diyHue/pull/163](url). I guessed that I must add the code(modified number, IP address of the box and port to my settings) to the "config. json" file which I did (and saved as root). Problem is that the lights are not found, and my entries are thrown away in the config.json when I reopen it. What am I doing wrong?

**Comment by mariusmotea** [comment]
you need to stop the hue-emulator service before any change becuase the last know configuration is write to disk on service stop/restart

**Comment by scholzmichael** [comment]
Sorry, of Course, I should have known, but when I enter the following:
 "lights_address": {
    	"1": {
       	    "protocol": "mi_box",
       	    "group": 1,
            "ip": "192.168.1.65",
            "port": 8899,
            "light_type": "rgbww"
    	}
    },
hue-emulater Service does not start (no other Lights added so far): (code=exited, status=1/FAILURE). Don't know what I'm doing wrong here.

**Comment by mariusmotea** [comment]
Paste entire json to a validator like this one:  https://jsonformatter.curiousconcept.com/ 
It will tell you where is the error.

**Comment by mariusmotea** [comment]
Be aware, you need to have light "1" present in two locations, "lights" and "lights_address". What you show is just "lights_address".

**Comment by scholzmichael** [comment]
Ok, now we get closer. Validater shows valid, Do I need to enter the same code under "lights"?
Since it would be the first one I'm not quite sure what tu put there

**Comment by mariusmotea** [comment]
No, there is what the hue app's receive. You can put this for an color bulb with color temperature function:

```
"1": {
            "capabilities": {
                "certified": true,
                "control": {
                    "colorgamut": [
                        [
                            0.6915,
                            0.3083
                        ],
                        [
                            0.17,
                            0.7
                        ],
                        [
                            0.1532,
                            0.0475
                        ]
                    ],
                    "colorgamuttype": "C",
                    "ct": {
                        "max": 500,
                        "min": 153
                    },
                    "maxlumen": 800,
                    "mindimlevel": 1000
                },
                "streaming": {
                    "proxy": true,
                    "renderer": true
                }
            },
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": false,
                    "mode": "safety"
                }
            },
            "manufacturername": "Philips",
            "modelid": "LCT015",
            "name": "Aplica Dormitor 1",
            "productname": "Hue color lamp",
            "state": {
                "alert": "none",
                "bri": 214,
                "colormode": "ct",
                "ct": 367,
                "effect": "none",
                "hue": 43690,
                "mode": "homeautomation",
                "on": false,
                "reachable": true,
                "sat": 254,
                "transitiontime": 9,
                "xy": [
                    0,
                    0
                ]
            },
            "swversion": "1.46.13_r26312",
            "type": "Extended color light",
            "uniqueid": "00:17:88:01:02:e5:b2:93-0b"
}
```

**Comment by scholzmichael** [comment]
ok, service running again, but now light does not appear in hue-emulater webIF

**Comment by mariusmotea** [comment]
Only lights attached to groups are displayed there. Install Hue Essentials or any hue app to create the groups

**Comment by scholzmichael** [comment]
Hmm,attached Light to a group now showing in the app and HUE Essentials, but still not working, won't turn on...

**Comment by mariusmotea** [comment]
Try to see if there are changes at API level between original ibox and ibox2. I suggest to try also other light types (not only light_type": "rgbww")

**Comment by mariusmotea** [comment]
@jespertheend made this implementation, maybe he can help you with some suggestions.

**Comment by scholzmichael** [comment]
Thanks @mariusmotea for your help,Ther are differences in communication between original ibox and ibox2 as can be seen here [https://github.com/mwittig/node-milight-promise](url) for example, but I guess I''m not experienced enough to get them implemented.

**Comment by mariusmotea** [comment]
Unfortunately only somebody with this v6 brige and skills can implement the protocol. I take a look and the differences from the two protocols are not minor.

**Comment by jespertheend** [comment]
Did you make sure the lights are paired to the box using the original MiLight app?
I'm using this app https://apps.apple.com/nl/app/mi-light-3-0/id1156007632?l=en and I think android has a similar one. You need to assign your lights to a group using the app first. Once you are able to change the lights using the original app you mover over to the diyHue implementation.

**Comment by scholzmichael** [comment]
Hi @jespertheend, I already use the original Milight app 
> https://play.google.com/store/apps/details?id=com.irainxun.wifilight&gl=AT(Android) for quite a while (2 Groups), and I'm able to switch them using node milight promise (mentioned above) as well. I also checked the port setting (8899) by connecting to the web IF of the ibox2. If you have any idea what the problem could be please let me know.

**Comment by jespertheend** [comment]
Hmm it's hard to say. I have GU10 lights rgbww lights myself, I'm not sure what wifi box version I have but the app says it's not compatible with the MiLight 2.0 wifi box. The wifibox that I'm using has 'Model No.: iBox2' written on it. Maybe we have two different versions?

**Comment by scholzmichael** [comment]
Mine has ibox2 written on it as well. According to the WebIF of the ibox2 it has SW Version V1.0.08.
Can you verify?
Will go on testing...

**Comment by scholzmichael** [comment]
Please close, its working now, misstype in port setting. Thanx @jespertheend  and @mariusmotea  for all your support.

**Comment by scholzmichael** [comment]
closed as it is working.
