### ISSUE TITLE
Yeelights retain old color when turning on

### ISSUE THREAD

**Issue by mcer12** [diyhue/diyHue#386]
This has been discussed in the past, but doesn't seem to be fixed as of yet. 

When the yeelight is OFF and I switch it to a scene, it turns ON but with old color, so I have to set the scene again to correct it. Maybe it's an issue with timing, sending ON state + color at the same time? This only happends when setting a scene from OFF state.

**Comment by mariusmotea** [comment]
We need to understand how Yeelights works. It accept lot of arguments, but i think not all at the same time. The best will be if it can accept RGB + ON (or only RGB if it will turn the light on).

**Comment by mcer12** [comment]
Could you please navigate me a bit where I can change it in the python script? I would test it on my setup and make a PR if I manage to fix it.

**Comment by mariusmotea** [comment]
Everything is happening in this funtion:
https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/protocols/yeelight.py#L83

i will try to add a sleep(0.5) after these lines:
```
    for key, value in payload.items():
        try:
            c.command(key, value)
            sleep(0.5) # added by me now
```

**Comment by alexyao2015** [comment]
I believe that the yeelight api requires for the light to be on prior to changing the color/temperature. When powering on the light, there is no way to change the color until after the power on command is sent. Sounds like the issue here can be resolved by adding a delay between the power on and color change.

**Comment by Zireael** [comment]
Maybe this will help:
https://gitlab.com/stavros/python-yeelight/-/blob/master/yeelight/main.py

Basically, disable saving lightbulb state (set_default) into the bulbs non-volatile memory.

``` python
    @_command
    def set_default(self, light_type=LightType.Main, **kwargs):
        """
        Set the bulb's current state as the default, which is what the bulb will be set to on power on.

        If you get a "general error" setting this, yet the bulb reports as supporting `set_default` during
        discovery, disable "auto save settings" in the YeeLight app.

        :param yeelight.LightType light_type: Light type to control.
        """
        return "set_default", [], dict(kwargs, light_type=light_type)

```

**Comment by alexyao2015** [comment]
That's for if the bulb has a power loss to provide it with a power on state. It will not fix this. The only true way to fix this would be to introduce some delay when turning on scenes. This would also mean that diyhue's bulb state information would have to be correct for it to work.
