### ISSUE TITLE
Hue Entertainment and Alexa

### ISSUE THREAD

**Issue by coolcoons** [diyhue/diyHue#388]
**Describe the bug**
I am unable to set up entertainment areas or connect the DiyHue bridge to my Philips Hue account. Since I cannot link the bridge to the account it won't work with Alexa, IFTTT, etc.

**To Reproduce**
Steps to reproduce the behavior for entertainment areas:
1. Go to Settings in the Hue App
2. Click on Entertainment areas
3. Click create area
4. Select lights from the list
5. The app says "We have noticed that you've selected lights which do not have rich colors. We strongly advise to only use recommended lights to get the most optimal experience." Then I clicked Got it
6. It then tells me the lights require a software update to work in entertainment areas. I click Go to update
7. It then sits there in an infinite loop saying Checking for update

Steps to reproduce the behavior for my Philips Hue account:
1. Go to account.meethue.com
2. Sign in with my account
3. Click search for bridges and it tells me there are no bridges on my network

**Expected behavior**
I expected account.meethue.com to find my Diyhue bridge and connect to it and I thought after I selected lights for the entertainment area, it would ask me where they belong and what I want to name the group.

**Comment by Mevel** [comment]
diyHue will NEVER work with a official Hue account.

You can use Entertainment Area only in combination with ESP8266 Microcontrollers and diyHUe Firmware. All others are "too slow" to keep up with the fast data transfer while in entertainment mode.

Updating: Click Update, it may fail, restart Emulator, should now be "updated".

**Comment by coolcoons** [comment]
So is there any way for it to work with Alexa?

**Comment by coolcoons** [comment]
It says on the diyhue website that it works with Alexa but not Google Assitant.

**Comment by Mevel** [comment]
actually i dont use any cloud services. i heard from some users they managed to get it working via home assistant.

**Comment by coolcoons** [comment]
Why would Diyhue not work with an official hue account? It was able to emulate a hue bridge and make the app work wouldn't the hue website work the same way?

**Comment by Mevel** [comment]
Original hue products authenticate themselves with unique identifiers. Can't emulate this.

**Comment by coolcoons** [comment]
I tried to get the entertainment working by clicking do updates and then restarting the hue emulator. It said disconnected for a moment in the app and then connected but it didn't say it updated and didn't go to the next step.

**Comment by coolcoons** [comment]
I already ran this set of code. I'm not sure if it installed in the correct directory or if it matters where it is. https://diyhue.readthedocs.io/en/latest/AddFuncts/entertainment.html

**Comment by coolcoons** [comment]
I have HomeAssistant up and running with Alexa and Diyhue. It's working flawlessly! What else should I try for Entertainment areas in Philips Hue?

**Comment by coolcoons** [comment]
Is this the problem I'm having? https://github.com/diyhue/diyHue/issues/234

**Comment by alexyao2015** [comment]
What specific light firmware are you using? The rich colors issue is due to the bulb firmware not being registered correctly by diyhue. The checking for update loop is likely related to a new commit that introduced the error. Try installing the beta and testing if it works.

**Comment by coolcoons** [comment]
Marius said to change the light config to this:
        "6": {
            "capabilities": {
                "certified": true,
                "control": {
                    "colorgamut": [
                        [
                            0.6915,
                            0.3083
                        ],
                        [
                            0.17,
                            0.7
                        ],
                        [
                            0.1532,
                            0.0475
                        ]
                    ],
                    "colorgamuttype": "C",
                    "ct": {
                        "max": 500,
                        "min": 153
                    },
                    "maxlumen": 800,
                    "mindimlevel": 1000
                },
                "streaming": {
                    "proxy": true,
                    "renderer": true
                }
            },
            "config": {
                "archetype": "sultanbulb",
                "direction": "omnidirectional",
                "function": "mixed",
                "startup": {
                    "configured": false,
                    "mode": "safety"
                }
            },            
            "manufacturername": "Philips",
            "modelid": "LCT015",
            "name": "Bulb 2",
            "productname": "Hue color lamp",            
            "state": {
                "alert": "none",
                "bri": 144,
                "colormode": "ct",
                "ct": 447,
                "effect": "none",
                "hue": 32760,
                "mode": "homeautomation",                
                "on": false,
                "reachable": true,
                "sat": 0,
                "transitiontime": 1,
                "xy": [
                    0.561,
                    0.404
                ]
            },
            "swversion": "1.46.13_r26312",
            "type": "Extended color light",
            "uniqueid": "f0:d1:b8:00:00:06:45:ff-01"
I was then able to setup entertainment areas, but if I try to sync the lights to music, games, or movies the lights just sit on their last state. Are the lights being updated too fast during sync for the deconz to make the lights do anything?

**Comment by coolcoons** [comment]
I don't know why but GitHub changed the spacing of the config when I pasted it.

**Comment by HobboRobin** [comment]
I have the same Problem. But i didn´t change anything from the original code. I can set up an entertaiment area but when i start synching then nothing happening. I have actually an Rasp 3B+ and an ESP8266 (tried also the ESP32) with WS2812B.

**Comment by alexyao2015** [comment]
As mentioned, this is likely an issue due to a later commit. Install the beta version and see if it still exhibits this behavior.

**Comment by HobboRobin** [comment]
Sorry for the Question but where and how can i install the beta ? I just did everything with the easy install command :D

**Comment by alexyao2015** [comment]
You can use docker and pull the beta tag or use the manual install method and pull the beta branch.

**Comment by alexyao2015** [comment]
Closing due to no feedback
