### ISSUE TITLE
Sleep / Wakeup activities (to turn light off or on) seems not working properly

### ISSUE THREAD

**Issue by noisemaker00** [diyhue/diyHue#39]
**Describe the bug**
When I open the Hue app and set a new activity the behaviour is:
• in case of 'wake up' activity (lights should be turn on smoothly) nothing happens at the time I set
• in case of 'sleep' activity the Hue app crash (I don't know if the response of the hue emulator is wrong or it is a problem of the app itself)

**To Reproduce**
1. Download and open the HUE app on Android
2. Set new sleep/wake up activity

**Expected behavior**
Lights should turn on or off according with the type of the selected acitivity

**Additional context**

**Comment by mariusmotea** [comment]
What types of lights are you using?

**Comment by noisemaker00** [comment]
I use a custom esp8266 light strip with the code copied form your old repo form that.
Is the feature depending by the light device? I though the hub handle it (keep time tracking and fire the actions)

**Comment by mariusmotea** [comment]
I will check this in a few days.

**Comment by mariusmotea** [comment]
Please check if now is working properly. Unfortunately this commit will not fix already broken config, if you cannot access anymore the routines you will need to start from scratch .

**Comment by noisemaker00** [comment]
I'll check as soon as possible.
So I have to update the emulator on the Pi and reset data on the HUE app on my smartphone? I didn't understand very well this part:
> Unfortunately this commit will not fix already broken config, if you cannot access anymore the routines you will need to start from scratch

**Comment by mariusmotea** [comment]
you don't need to reset the data on the hue app. If you configured the sleep routine already the app will crush when you will access this menu, for these reason you need to start with default config.json from this repo.

**Comment by noisemaker00** [comment]
I made a backup of my config.json and switched to the 'default' one on this repo.
But now I cannot find any light now.

**Comment by noisemaker00** [comment]
Despite the mess with lights and scenes I tried "wake up" and "sleep" routines, but without success.
The Hue App does not crash anymore on "Sleep" but lights does not turn off/on neither fading.

**Comment by mariusmotea** [comment]
For me the wake up was working. Remember that you must set the time with 30 - 40 minutes before the event

**Comment by noisemaker00** [comment]
After a lot of tests, finally it seems to work.

And about the "Cannot find any lights" issue reported before, during tests I forced
`args.debug = "true"`
in _HueEmulator3.py_ to enable debug and it finally found lights. I don't check if it is something related to it btw
