### ISSUE TITLE
Searching for new lights doesn't work: 404

### ISSUE THREAD

**Issue by Zireael** [diyhue/diyHue#395]
**Describe the bug**
Searching for new lights with Hue Essentials gives timeout error.
Container log has the following entries:
Looks like /detect route fails?
```
192.168.1.134 - - [07/May/2020 14:37:51] "GET /api/0a96e776907011eaa7badca632137310 HTTP/1.1" 200 -
192.168.1.134 - - [07/May/2020 14:37:51] "GET /api/0a96e776907011eaa7badca632137310 HTTP/1.1" 200 -
192.168.1.107 - - [07/May/2020 14:37:51] "GET /description.xml HTTP/1.1" 200 -
192.168.1.134 - - [07/May/2020 14:37:53] "POST /api/0a96e776907011eaa7badca632137310/lights HTTP/1.1" 200 -
192.168.1.129 - - [07/May/2020 14:37:58] code 404, message not found
192.168.1.129 - - [07/May/2020 14:37:58] "GET /detect HTTP/1.1" 404 -
{"ok"}
```

**To Reproduce**
1. Search for light through any Hue app
2. See error

**Expected behavior**
API endpoint is reached and new lights scanned for

**Logs**
If applicable, provide output logs. These can be obtained via running `docker logs diyHue`

**Docker Info (please complete the following information):**
 - Architecture: ARMv7
 - Docker image version: diyhue/core:latest 
 - Hardware: Raspberry Pi 4b
- Docker version 19.03.8, build afacb8b

**Comment by mariusmotea** [comment]
That code 404 is received after 5 seconds, i think is the response from an web service from your home (aka router). What lights are you trying to detect?

**Comment by Zireael** [comment]
Yeelight LED Bulb 1S (Color) `yeelink.light.color4`
https://github.com/mariusmotea/diyHue/wiki/Yeelight
These are WiFi bulbs, but I've enabled 'Lan Control' in Yee App. I'm able to add the bulb to Home Assistant directly through their integration. And I can communicate with the bulb over LAN through for example https://github.com/Bastl34/node-yeelight-wifi

NB: I also can't add the diyHue bridge to the official Philips Hue app, getting this in the logs:
```
192.168.1.134 - - [10/May/2020 11:53:14] "GET /api/nouser/config HTTP/1.1" 200 -
192.168.1.134 - - [10/May/2020 11:53:14] "GET /api/nouser/config HTTP/1.1" 200 -
```
The Hue app blinks for a split second showing '1 new Hue bridge found' and then displays 'No new Hue Bridge found'. If I spam the Search button super fast, I'm able to get to the Touchlink Screen, but then nothing happen even if I clicked Activate in diyHue.
I was able to add diyHue bridge to Hue Essentials tho, and it works fairly fine there.

Would my issues have something to do with me running the diYHue in a Docker container? Maybe diyHue isn't pinging the right host/IP range? Altho I was able to 'copy' the 3 lights from the real Huev2 bridge (2x Hue White bulb and 1x GLEDOPTO colour strip), and those work fine on diyHue.

My network looks like this:
![image](https://user-images.githubusercontent.com/3856578/81499221-ccc49480-92c1-11ea-83c9-2819024b9d41.png)

diyHue docker container details:
1) started like so: sudo docker run -d --name "diyHue" --network="host" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' -e 'MAC=dc:a6:32:13:73:11' -p 80:80/tcp -p 443:443/tcp -p 1900:1900/udp -p 2100:2100/udp diyhue/core:latest
(I tried bridge mode too, but the effects were the same)
![image](https://user-images.githubusercontent.com/3856578/81499337-d0a4e680-92c2-11ea-892b-f1977b20df80.png)

![image](https://user-images.githubusercontent.com/3856578/81499489-f4b4f780-92c3-11ea-8a9b-151acedf88e6.png)

I'm able to add diyHue bridge and it's lights to Home Assistant:
![image](https://user-images.githubusercontent.com/3856578/81499584-93415880-92c4-11ea-8138-ffd1b1d904a3.png)

**Comment by Zireael** [comment]
Possibly related to this issue?
https://github.com/diyhue/diyHue/issues/33

**Comment by alexyao2015** [comment]
Potentially an issue related to a recent commit. Try older version of diyHue, specifically the beta branch...

**Comment by alexyao2015** [comment]
If that works, install older commits until the problem occurs again and report back which commit was causing the issue.

**Comment by alexyao2015** [comment]
Closing due to no response.

**Comment by Thomas-Vos** [comment]
The timeout in Hue Essentials is (probably) caused due to diyHue sleeping for 7 seconds. See the following thread for more information: https://diyhue.slack.com/archives/CC83YEPDZ/p1593668981487600
