### ISSUE TITLE
cannot organize rooms and zones in preferred order

### ISSUE THREAD

**Issue by huongminh** [diyhue/diyHue#397]
**Describe the bug**
First the Hue app asked me to perform an update for the bridge. I clicked update and it tried and said update failed. I tried to reinstall hue-emulator by running the script and the Hue app works again. However I notice my room order is changed so I tried to rearrange the room back to previous order but immediately after I released the dragged room to the new position order in settings, it just got back to its original place. I guess somehow the new position cannot be saved in the bridge (hue-emulator). Pls help

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.

**Additional context**

**Comment by alexyao2015** [comment]
Setup process is a little buggy but works fine after setup.
