### ISSUE TITLE
Adding Hue Dimmer Switch

### ISSUE THREAD

**Issue by gazuzu** [diyhue/diyHue#4]
Hi there, I have set up DIYHue on my Pi a few weeks ago and everything has been running smoothly so far.
Today I bought a Hue Dimmer Switch thinking I could just add this via the Hue App Accessory tab, but if the Hub I'm connected to on the app is the RaspberryPi, it just searches for the accessory for ages and does not find it.
If I switch to the Hue Hub, this is found within 10 seconds.
Can I not add the original Hue Dimmer switch to the emulator?

I have found the schematics for the DIY Hue Switch, but I rather use the original one if I can.

Your assistance is much appreciated!

**Comment by mariusmotea** [comment]
Hi,

Original Hue devices work on ZigBee protocol, not WiFi. If you want to get rig of original Hue Bridge you can buy the Raspbee module that DiyHue support and provide communication with several ZigBee devices.

**Comment by cheesemarathon** [comment]
If you need more help, check the wiki or repo this issue. Thanks!
