### ISSUE TITLE
Impossible to change timezone

### ISSUE THREAD

**Issue by RobertPegu** [diyhue/diyHue#40]
Hi there! First of all, I would like to thanks the developer for his job, this project rocks! 

I'm facing a little issue while trying to change the timezone set on Bucarest as default to the one of my country. In fact, if I try to change it in the setting of the Hue App, it displays an error saying it is impossible to load the timezones.

**Comment by Mevel** [comment]
Change the timezone in `config.json`

**Comment by mariusmotea** [comment]
Hi!
@RobertPegu we had an issue in the past with timezones not located on proper key in capabilities. I was fixed 2-3 months ago. Do you use recent version or something older?

**Comment by mariusmotea** [comment]
Fixed in last commit
