### ISSUE TITLE
bulb unreachable

### ISSUE THREAD

**Issue by huongminh** [diyhue/diyHue#400]
**Describe the bug**
I installed the Hue Emulator on Pi4 by running the auto installation script (host installation). then I added some milight bulbs from the milight bridge. All bulbs appear in Hue app as unreachable and do not work. The debug says:WARNING:root:MiLight xxxxxxx is unreachable:list indices must be integers or slices, not str

**To Reproduce**

**Expected behavior**

**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.

**Additional context**

**Comment by alexyao2015** [comment]
Appears to be related to #370. Issue potentially extends to protocols other than tasmota. Refer to comments there

**Comment by huongminh** [comment]
Thanks for your response. I think it is not related since in my situation my bulbs show unreachable and no response but in the other case the bulbs do respond. And I use milight bulbs. One more update: I retried the same installation on my pi3 and the bulbs work perfectly. So I guess the issue is related specifically to pi4. Could you give me some hints on dependencies so I can check if the same version is on my Pi3 and Pi4?


Sent from Yahoo Mail for iPhone


On Thursday, May 21, 2020, 8:10 AM, alexyao2015 <notifications@github.com> wrote:




Appears to be related to #370. Issue potentially extends to protocols other than tasmota. Refer to comments there

**Comment by alexyao2015** [comment]
Hmm interesting, perhaps delete the config and reinstall from scratch.
