### ISSUE TITLE
Deconz: Hue Entertainment with delay

### ISSUE THREAD

**Issue by Cludch** [diyhue/diyHue#401]
**Describe the bug**
Using diyHue with Hue Entertainment causes a delay of 5-10 seconds.

**To Reproduce**
1. Start diyHue
2. Link deConz lights
3. Pair Hue Sync
4. Start Hue Sync video or music sync

**Expected behavior**
Instantaneous sync to video or music (with a slight delay).

**Logs**
No interesting log output other than the occasional access logs.

**Additional context**
diyHue on local pc, which also runs Hue Sync. Connects via Ethernet to Rapsberry Pi 4, which uses a ConBee II with deConz.

I, sadly, cannot test this with Ambilight+Hue, since this does not work at all for me, yet. Still trying to figur this one out.

**Comment by WRP1992** [comment]
I have exactly the same issues.

**Comment by Mevel** [comment]
Entertainment mode does not work fast enough with deconz (zigbee bulbs) the data transmittion rate is not fast enough. Philips uses a special "secret" protocol with their bulbs to use entertainment mode.

For diyhue you need to use a esp8266 based bulb/light strip.

Hope that helps.

**Comment by Cludch** [comment]
Good to know, thanks.
Could it make a difference if we use ZigBee2MQTT with the ConBee?

**Comment by mariusmotea** [comment]
Next update will work much better in entertainment mode with zigbee bulbs.

**Comment by Cludch** [comment]
But it should only make a slight difference.
Is there an open or already closed issue regarding the zigbee bulb performance?
I'd like to test the development version out, if this could help.

**Comment by mariusmotea** [comment]
The development version is in develop branch ( i think you need only entertainment.py file). The difference may be bigger because currently from 24 frames per second from entertainment protocol is sent just one every second to not overload the destination device (Deconz in your case). In the new version the frames are inspected and only when a noticeable difference is detected the frame is sent right away. From my test in movies and with music this is very efficient.

**Comment by Cludch** [comment]
Will give this a try in the next two days and report back.

On a side note:
There is another emulated_hue addon especially for Home Assistant:
https://github.com/marcelveldt/hass_emulated_hue
This does not have any delay, but the lights flash without transitions.
If I recall correctly, the developer also add a check for only noticable differences in order to reduce the traffic.

**Comment by Cludch** [comment]
I just used the stable version and updatet the `entertainment.py` to this version https://github.com/diyhue/diyHue/blob/develop/BridgeEmulator/functions/entertainment.py
However, I can see no difference in delay.

**Comment by mariusmotea** [comment]
True, i read again the code, the function "skipSimilarFrames" is applied to certain types of lights and not for Deconz. If i will find some free time i will implement it.

**Comment by mariusmotea** [comment]
you may try to tune the frame skip interval. Put `2` or `1`.  With 1 no frames will be skipped. 

`if fremeID % 4 == 0: # can use 2, 4, 6, 8, 12 => increase in case the destination device is overloaded`

Note this line is present two times in the file (one for RGB mode, another for CIE color mode)

**Comment by Cludch** [comment]
Thanks again for your fast response!

First off all: If wasn't using the development branch as I just realized. Don't know why, I did checkout the development branch. But now I am!

When using Music as the Entertainment source, Hue Sync shows all kind of colors, but my bulb hasn't changed once from white. This seems like a different issue now. I will try to restart deConz and everything later to see why this is happening.

However, diyHue rarely sends out PUT requests to deConz to request a change.
Logs:
```
10.0.5.32 - - [22/May/2020 18:41:47] "PUT /api/cdbef3269b3611ea84ca6045cb9c5f7f/groups/2 HTTP/1.1" 200 -
2020-05-22 18:41:47,831 - root - INFO - in PUT method
2020-05-22 18:41:47,831 - root - INFO - /api/cdbef3269b3611ea84ca6045cb9c5f7f/groups/2
2020-05-22 18:41:47,832 - root - INFO - b'{"stream":{"active":true}}'
2020-05-22 18:41:47,832 - root - INFO - start hue entertainment

  . Seeding the random number generator... ok
  . Loading the CA root certificate ... ok (0 skipped)
  . Loading the server cert. and key... ok
  . Bind on udp://*:2100/ ... ok
  . Setting up the SSL/TLS structure... ok
  . Waiting for a remote connection ...2020-05-22 18:41:48,434 - root - INFO - [
    {
        "success": {
            "/groups/2/stream": {
                "active": true
            }
        }
    }
]
 ok
  . Performing the SSL/TLS handshake... hello verification requested
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... ok
    [ Protocol is DTLSv1.2 ]
    [ Ciphersuite is TLS-PSK-WITH-AES-128-GCM-SHA256 ]
    [ Record expansion is 37 ]
    [ Maximum fragment length is 16384 ]
  . Verifying peer X.509 certificate... ok
2020-05-22 18:41:49,309 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org
2020-05-22 18:41:49,311 - root - INFO - sync with lights
2020-05-22 18:41:49,456 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
10.0.5.32 - - [22/May/2020 18:41:53] "GET /api/cdbef3269b3611ea84ca6045cb9c5f7f/ HTTP/1.1" 200 -
10.0.5.32 - - [22/May/2020 18:41:58] "GET /api/cdbef3269b3611ea84ca6045cb9c5f7f/ HTTP/1.1" 200 -
2020-05-22 18:42:00,313 - root - INFO - sync with lights
10.0.5.32 - - [22/May/2020 18:42:03] "GET /api/cdbef3269b3611ea84ca6045cb9c5f7f/ HTTP/1.1" 200 -
10.0.5.32 - - [22/May/2020 18:42:08] "GET /api/cdbef3269b3611ea84ca6045cb9c5f7f/ HTTP/1.1" 200 -
2020-05-22 18:42:09,697 - root - DEBUG - Sending M-Search response to 192.168.220.33
2020-05-22 18:42:10,899 - root - DEBUG - Sending M-Search response to 192.168.220.33
2020-05-22 18:42:12,001 - root - DEBUG - Sending M-Search response to 192.168.220.33
2020-05-22 18:42:13,403 - root - DEBUG - Sending M-Search response to 192.168.220.33
10.0.5.32 - - [22/May/2020 18:42:13] "GET /api/cdbef3269b3611ea84ca6045cb9c5f7f/ HTTP/1.1" 200 -
2020-05-22 18:42:15,317 - root - INFO - sync with lights
10.0.5.32 - - [22/May/2020 18:42:18] "GET /api/cdbef3269b3611ea84ca6045cb9c5f7f/ HTTP/1.1" 200 -
2020-05-22 18:42:19,460 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org
2020-05-22 18:42:20,607 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
```

But I will try to reset everything and test with a clean test bench later.

I am also planning to get a Hue Bridge for the Hue bulbs and only include the WS2812 through diyHue. This should at least resolve the issue.

**Comment by Cludch** [comment]
Small update:
The master branch still works, but with a delay.
After I update the `entertainment.py` the bulb does not change at all.
I even updated all the files from `functions/`.

**Comment by mariusmotea** [comment]
Probably a bug with Deconz lights. Can you do following things?
```
sudo systemctl stop hue-emulator
cd /opt/hue-emulator
sudo ./HueEmulator3.py
```

start the entertainment steaming and tell me f you see any errors.

**Comment by Cludch** [comment]
I can't start as it crashes, because `deconz_ip` is undefined.

**Comment by mariusmotea** [comment]
You made some manual chnanges? deconz_ip must be defined:

```
if args.deconz:
  deconz_ip = args.deconz
  print("Deconz IP given as " + deconz_ip)
elif os.getenv('DECONZ'):
  deconz_ip = os.getenv('DECONZ')
  print("Deconz IP given as " + deconz_ip)
else:
  deconz_ip = "127.0.0.1"
logging.info(deconz_ip)
```

**Comment by eazyves** [comment]
I have the same problem. I am on normal master branch. Hue Sync Windows Desktop App syncs perfectly fine, but with a delay (2-3 seconds?).
Anything I can do to help you or test something?

**Comment by eazyves** [comment]
> I just used the stable version and updatet the `entertainment.py` to this version https://github.com/diyhue/diyHue/blob/develop/BridgeEmulator/functions/entertainment.py
> However, I can see no difference in delay.
> 
> > <img alt="" width="48" src="https://avatars3.githubusercontent.com/u/45603380?s=400&amp;v=4"><img alt="" height="14" src="https://camo.githubusercontent.com/040b5519c6d1891329f5f6d3e511003657131cf2/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[diyhue/diyHue](https://github.com/diyhue/diyHue)**Main diyHue software repo. Contribute to diyhue/diyHue development by creating an account on GitHub.

With this entertainment.py it doesnt work at all. I can control the lights normaly, but when I activate the entertainment mode, it doesnt sync.

Startet with `sudo ./HueEmulator3.py --debug`

[entertainment.log](https://github.com/diyhue/diyHue/files/4701619/entertainment.log)

**Comment by pszewello** [comment]
I also see 2-3sec delay when in entertainment, using both philips hue bulbs, plays and ws2812b, all are delayed the same way.

**Comment by Cludch** [comment]
I can confirm that entertainment mode works great using the generic ESP8266 solution.
It also works without delay using WLED. However, the WLED solution still has other bugs.
And I didn't manage to get ESPHome to work.
Waiting for my hue bridge to test the hue bulbs through the original bridge.

**Comment by eazyves** [comment]
Would the problem be solved with an original Hue Sync HDMI-Box? Or is the HDMI-Box also using the entertainmant api `?

**Comment by Cludch** [comment]
The Philips Sync box is also utilizing the Hue Entertainment API.

**Comment by pszewello** [comment]
All my hue bulbs are connected to the official hue bridge, diyhue connects to this hue bridge, I have ws2812 with generic imo flashed on controllers, and syncing is done with hue sync box, which is connected to the DIYHue bridge... dealys on the ws2812 are around 2 s, and the official bulbs do not enter entertainment mode.

**Comment by Cludch** [comment]
That is strange. I have almost zero delay with generic ws2812.
However, this issue is about the deConz lights primarily.
Please open another issue if you keep seeing delays with the generic esp8266 scripts.

**Comment by mariusmotea** [comment]
The connection from Hue Emulator to original Hue Bridge is done using the Hue API, not the entertainment API, for this reason the response is not that fast.

**Comment by pszewello** [comment]
Seems I was using the arduino from old git hub lights repo, I'll flash the one from new repo (might go with WLED) and see again about the delays. But it would be nice if DIYHue get's request to run with entertainment API to connect to official bridge in entertainment mode.

**Comment by Cludch** [comment]
I would not recommend using the WLED binary as this is still work in progress and has a few bugs.
The generic one works fine though.
