### ISSUE TITLE
Hue App wants update - App Fails to update - Can not use app without updating

### ISSUE THREAD

**Issue by CM000n** [diyhue/diyHue#407]
Hi everyone, I have been using diyhue for some time now and it has done a great job on my usecases so far.

Since today I get a hint that an update is available when I open the hue App. 

This hint cannot be avoided and an attempt to update diyhue via the app fails of course.  A new installation of the hue app or an update of the diyhue Docker Container does not help either.  So the hue app is currently not usable for me.

Is there maybe workaraound for this?

Best regards and thanks a lot!

**Comment by gastonMM** [comment]
I HAVE THE SAME FAILURE

**Comment by NickB23** [comment]
Same here.

**Comment by mariusmotea** [comment]
I will fix thin in a few hours

**Comment by CM000n** [comment]
Thank you, it's working again now, after last container update
