### ISSUE TITLE
Not all lights in entertainment area enter sync mode

### ISSUE THREAD

**Issue by pszewello** [diyhue/diyHue#408]
**Describe the bug**
I created entertainment area with a ws2812b strip of 180 leds divided into 4 lights, 2 hue plays and 2 hue color bulbs. When using the entertainment area, only the ws2812b enter sync enteremode, the other lights seem to use standard protocol which introduces massive lag, see screenshot below. Any ideas why? 

![Screenshot_20200607-185701_Hue](https://user-images.githubusercontent.com/40065024/83974940-220bba00-a8f1-11ea-82cd-3cc3410ec2bf.jpg)

**To Reproduce**
Mix hue lights with diy lights in entertainment mode and try hue sync. 

**Expected behavior**
All lights to enter entertainment mode. No lag.

**Comment by mariusmotea** [comment]
Only ESP8266 lights with firmware provided by us work as expected in entertainment mode. In the future there will be more improvements for other types of lights.

**Comment by pszewello** [comment]
But the other lights are hue lights so why not pass through directly to hue bridge?

**Comment by alexyao2015** [comment]
Esphome lights with the custom component will also work with entertainment mode.

**Comment by Cludch** [comment]
I tried ESPHome but it does not change when using a WS2812b. SMD5050 strips seem to work fine.
However, I just created a new controller yesterday and still have to test this again.
