### ISSUE TITLE
Hue App wants update - App Fails to update - Can not use app without updating

### ISSUE THREAD

**Issue by HudsonProdigy** [diyhue/diyHue#41]
Hello,
I am using hue emulator on ubuntu vm. has been up and running for some time. Now when i open hue app it asks for update. when i click update it fails and sends me back to update screen.
 there does not seem to be a way to avoid update. I tried deleting cert file and updating hue bridge software. same issue persists. 

help would be much appreciated.

Cheers

**Comment by mariusmotea** [comment]
I manually downgrade the swversion on my bridge and upgrade works for me fine. Maybe you did not upgrade to latest version. Anyway i will push an update that will automatically apply latest swversion on service start.

**Comment by cheesemarathon** [comment]
Please re-open if issue persists
