### ISSUE TITLE
Hue  Entertainment with Yeelight not working

### ISSUE THREAD

**Issue by chrisdata** [diyhue/diyHue#412]
**Describe the bug**
Hue Entertainment not working with Yeelight.

**To Reproduce**
Hue Entertainmentwith Yeelight RGB bulb and strip able to create in Hue app (android).
After setup while it detect light working properly or not, it won't change color.
THen in any app with Hue Entertainment, it won't work.

**Expected behavior**
WIll yeelight work with Hue Entertainment ever?

**Logs**
WARNING:root:behind tv light not reachable: Yeelight with IP 192.168.0.112 doesn't want to connect in music mode: timed out
192.168.0.1 - - [20/Jun/2020 11:04:10] "GET /api/6815105eb0bd11ea8fd4b526e3fa79f4/lights HTTP/1.1" 200 -

FYI, it has enabled LAN Control in yeelight app.

**Comment by chrisdata** [comment]
Yeelight music mode in Yeelight app also working.

Just the Hue Entertainment not.

**Comment by chrisdata** [comment]
![Screenshot 2020-06-23 at 10 43 47 PM](https://user-images.githubusercontent.com/1939868/85418313-39120380-b5a3-11ea-9233-4130c7a7ba55.png)

The hue mac app actually working, it changing color in sync mode, but you see the debug console, Yeelight rejecting connection.. so what's the problem?

**Comment by chrisdata** [comment]
I opened port 55443 already on router and disable Ubuntu firewall. (just in case) still no fix.

**Comment by mariusmotea** [comment]
I think the music mode was working fine until few weeks ago. Unfortunatelly this require advanced debugging, probably you need to connect with telent on the same service to see is the music mode server is available and can receive connections

**Comment by chrisdata** [comment]
Any documentation I can reference to do it?

**Comment by mariusmotea** [comment]
https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf

**Comment by chrisdata** [comment]
Today I tried changing the port to default 54321 and it seem able to turn music mode on?
![Screenshot 2020-06-27 at 5 27 10 AM](https://user-images.githubusercontent.com/1939868/85902582-f405ff80-b836-11ea-94c2-11c96b01a1a0.png)

**Comment by chrisdata** [comment]
Any updates?

**Comment by Lord-Grey** [comment]
> ![Screenshot 2020-06-26 at 6 26 53 AM](https://user-images.githubusercontent.com/1939868/85801741-1b48c800-b776-11ea-9aa5-9d8a80672758.png)
> 
> https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf
> 
> Here's what I get. 192.168.0.102 is my Ubuntu DiyHue server.
> Is that correct but return an error...?

The telnet test does not makes sense in this scenario:
Your program needs to open a TCP-Server and with the port you provide the port the Yeelight will connect to for music mode. Using the Yeelight API port 5543 does not makes sense here...

I guess in case Yeelight is already in music mode, you will get the invalid param answer....

I tested with my yeelight rountine (not the diyHue one:
music mode is on, you get the error:

{"method":"props","params":{"power":"off","rgb":2300704,"hue":323,"sat":22,"bright":13,"music_on":0}}

{"method":"props","params":{"power":"on"}}
{"method":"props","params":{"music_on":1}}
{"id":3,"method":"set_music","params":[1,"192.168.2.152",39739]}
{"id":3,"error":{"code":-5001,"message":"invalid params"}}

if music mode is off, you get OK:

{"method":"props","params":{"power":"off","music_on":0}}
{"id":3,"method":"set_music","params":[1,"192.168.2.152",39739]}
{"method":"props","params":{"music_on":1}}
{"id":3,"result":["ok"]}
{"method":"props","params":{"music_on":0}}

Tested with a Yeelight Stripe

**Comment by chrisdata** [comment]
I don't get it, so it still not fix? I
I unable to debug because I not a programmer, can't really help.
