### ISSUE TITLE
Hue BT not supported in Hue Entertainment

### ISSUE THREAD

**Issue by kaisax** [diyhue/diyHue#414]
**Describe the bug**
I have 2 Hue White And Color (5th gen.) (Model Number: LCA001) connected to my RaspBee Module, they work fine. However when trying to add them to an Entertainment Area, I get the prompt to update said bulbs.

**To Reproduce**
1. Open Hue App
2. Click on "Entertainment Areas"
3. Select your Hue 5.th Gen Lamps and click 'Next'.
4. See error.

**Expected behavior**
I expected that I would be able to add my Lamps to a Hue Entertainment area. I was expecting a slow response but not that it's not supported (yet?)

**Logs**
-

**Additional context**

I have also tried changing the Model number in the config.json file, sadly it just reverted upon restart.

**Comment by mariusmotea** [comment]
These values are imported from Deconz. You need to update swversion value to last one. Be aware that entertainment on Deconz is emulated and is using lazy http api.

**Comment by kaisax** [comment]
This is proably not your concern, but would you know how to do so?

I've tried changing the swversion value via deCONz's REST API, but that didn't seem to work.

**Comment by Mevel** [comment]
You can change the version in `config.json` of hue emulator

**Comment by kaisax** [comment]
As mentioned above, I've tried it and it reverts basically instantly as it's imported from deconz.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
