### ISSUE TITLE
Native libraries for coap and dtls

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#415]
Replace coap-client and entertain-srv with native python libraries.

Thinking that [this](https://pypi.org/project/python-mbedtls/) project may be able to replace the entertain-srv.

For the coap client, [this](https://github.com/Tanganelli/CoAPthon3) may work or simply [this](https://github.com/ggravlingen/pytradfri) native library for Tradfri may work better. Personally, I am not quite sure since I do not own any Tradfri devices. Some advice regarding this would be helpful.

Migrating to native libraries would help with maintenance and installation.

**Comment by juanesf** [comment]
Looking for information, I came across a hue emulator for homeassistant which has entertainment too. maybe it helps to see your code:
https://github.com/marcelveldt/hass_emulated_hue/blob/master/emulated_hue/hue_entertainment.py

**Comment by alexyao2015** [comment]
Great link but that doesn't relate to this issue

**Comment by gmallios** [comment]
Maybe this helps: https://github.com/hass-emulated-hue/core/blob/master/emulated_hue/entertainment.py

**Comment by mariusmotea** [comment]
dtls is now handled by openssl
