### ISSUE TITLE
Drop support for install methods other than Docker?

### ISSUE THREAD

**Issue by alexyao2015** [diyhue/diyHue#416]
Remove non-docker install methods as they are becoming harder to keep track of and create extra work that do not improve functionality of the project.

Benefits:
Reduce issues such as #411 which are related to installation.
Create a unified user experience.
Helps ensure issues are related to the actual project rather than user error.

**Comment by alexyao2015** [comment]
@mariusmotea What do you think about this?

**Comment by mariusmotea** [comment]
It will be a big problem for some users, i saw lot of commits in last period for openwrt platform and i don't think docker run on low power openwrt devices.

**Comment by alexyao2015** [comment]
An alternative is creating an installer script repository? As it stands now, the installer scripts aren't being maintained very much at all and seems to be more trouble than it's worth

**Comment by juanesf** [comment]
So there will be a folder with the installation scripts? can there be a subfolder depending on the platforms?
... /installs/openwrt
... /installs/deb
... /installs/other
since OpenWrt has some changes compared to distributions nothing in Debian

**Comment by alexyao2015** [comment]
Considering simply creating another repository for installers. Say "alternate-diyhue-installers". 
I would say that it will be unsupported but will take all pull requests to it (so yes to folders if there is a pull request there). As with the python program, I'll try to ensure things stay compatible but can't be sure. Find the refactor at the master-refactor branch.
