### ISSUE TITLE
Color Temp Xiaomi Ceiling 

### ISSUE THREAD

**Issue by Xorfee** [diyhue/diyHue#417]
Thanks for updating the second control of xiaomi meteorite ceiling light. Is it possible to change the color temp of the main lamp since you could change that before

**Comment by mariusmotea** [comment]
Can you provide more details as i don't have such lamp. Normally now must be 2 lights, main with color temp control, second with RGB control. You don't have color temp controls or you have them but nothing happen while you play with these?

**Comment by Xorfee** [comment]
Basically i am using Hue Essentials.. the mainlight doesnt show up the option to change the color temp ist just a dimmable on off light .. the second one works fine..
