### ISSUE TITLE
Searching for lights sleeps for 7 seconds

### ISSUE THREAD

**Issue by Thomas-Vos** [diyhue/diyHue#418]
**Describe the bug**
Searching for lights using the API sleeps for 7 seconds. This is different than the Hue API.

See the code here: https://github.com/diyhue/diyHue/blob/7c35ca3b35be0375629246b4c262340a52109d30/BridgeEmulator/HueEmulator3.py#L1605

**To Reproduce**
Do a POST request to `/api/<username>/lights`. It is expected that this returns a response immediately, but instead it hangs for 7 seconds. This could cause timeouts for users/apps not expecting this.

**Expected behavior**
I expect the request to return immediately. That would be in line with the Hue API.

What the Hue api does is return a response immediately and starts a light search in the background that will take 40 seconds. While the search is active, `/lights/new` will return `{"lastscan":"active"}`. That is very useful because Hue Essentials polls `/lights/new` every second and can show whether the search is still active. When new devices are found, they will be added to `/lights/new` and Hue Essentials will see them within a second. When the search is completed, lastscan will return a time.

**Additional context**
You can find the Hue documentation here: https://developers.meethue.com/develop/hue-api/lights-api/#search-for-new-lights
<details>
  <summary>Hue documentation screenshot</summary>
  
![Screenshot 2020-07-06 at 16 42 27](https://user-images.githubusercontent.com/11077217/86606112-e1fb2e00-bfa7-11ea-9fec-dc7c645cc7ce.png)

</details>

Slack discussion: https://diyhue.slack.com/archives/CC83YEPDZ/p1593668981487600

**Comment by Thomas-Vos** [comment]
I think the easiest way to fix this would be the following:
- Remove the `sleep(7)` line
- Make sure that `/lights/new` returns `{"lastscan":"active"}` (and found devices) when the scan is active in the background.
- When all scans are finished in `scan_for_lights` and the started threads, change the response of `/lights/new` to `{"lastscan":"<time when last scan was completed>"}` (and found devices).

**Comment by Mevel** [comment]
has this been resolved? @Thomas-Vos @mariusmotea

**Comment by mariusmotea** [comment]
Fixed in the new version with a totaly new method of lights discovery
