### ISSUE TITLE
 Change the type of a Tasmota (or other) device

### ISSUE THREAD

**Issue by dchwilk** [diyhue/diyHue#419]
**Is your feature request related to a problem? Please describe.**
I see Tasmota devices as bulbs. But these should be sockets.

Is there a way to change this manually?
Or have I configured something wrong?

**Describe the solution you'd like**
Ideally would be a page on which I can reconfigure all devices separately.

**Describe alternatives you've considered**
Automatic recognition of the device based on its properties. However, I am not sure how tasmota devices are implemented.

**Additional context**
One of the Tasmota devices has a DHT22 temperature sensor. How can I provide it?

**Comment by alexyao2015** [comment]
Tasmota is lacking many features. Suggest using esphome instead. The temperature sensor will never be able to be integrated because it is not supported normally with hue.

**Comment by dchwilk** [comment]
Dennoch wäre ein Page auf der Geröte konfiguriert oder erzeugt werden können sehr nützlich.
Beispielsweise könnte ich (mit MQTT) ein Bewegungsmelder küstlich erstellen.

**Comment by dchwilk** [comment]
Still, a page on which the devices can be configured or created would be very useful.
For example, I could create a motion detector (with MQTT).
