### ISSUE TITLE
diyHue responds differently than Hue-Bridge

### ISSUE THREAD

**Issue by Lord-Grey** [diyhue/diyHue#422]
**Describe the bug**

Trying to test the Hue Entertainment-API via diyHue from hyperion-ng, it came apparent that diyHue provides a different response to a group activation request than the original Hue-Bridge.

Original Hue Response: [{"success":{"**/groups/6/stream/active":true}**}]
diyHue Response: [{"success":{""**/groups/4/stream:{"active":true}}**}]

In the orginal respose "active" is part of the resource path while in diyHue active is modelled as a key value.

**To Reproduce**

a) Start CLIP API Debugger on diyHUE
http://DIYHUE_IP/debug/clip.html
b) Send PUT request with
URL: /api/USERNAME/groups/GROUPID
Body: {"stream":{"active":true}}
c) Review response and compare to orginal Bridge reponse

**Expected behavior**

It is expected that the diyHue response's structure is equal to the original Hue-Bridge one.

**Logs**
If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with `python3 HueEmulator3.py`.

**Additional context**

**Comment by mariusmotea** [comment]
Thanks for this important observation. I will debug using my original bridge.

**Comment by alexyao2015** [comment]
Are you able to provide steps that will send that request using the hue app? I.e. how can I get that response using the official hue app?

**Comment by Lord-Grey** [comment]
Hey,
I do not own a Hue-Brigde myself, but the CLIP utility is there available too.
i.e. Test-Scenario should be the same, but 

a) Start CLIP API Debugger on Hue-Bridge
http://HUEBRIDGE_IP/debug/clip.html
...

I was provided with the following screenshot from a Hue-Bridge owner.
Same you should be able to execute with your Hue-bridge (and hopefully produces the same result).

![image](https://user-images.githubusercontent.com/48840279/87278656-4a389b00-c4e5-11ea-843d-615c8f0263c6.png)

**Comment by mariusmotea** [comment]
I know what is the problem:
because the tree level of the json has two levels '{"stream":{"active":true}}' the reply path must contain the url + `stream` + `active`.

In order to fix this we need perform additional check:

https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/HueEmulator3.py#L1853

            for key, value in put_dictionary.items():
                    if isinstance(value,dict): # append the key to response_location also
                        second_key = list(value.keys())[0]
                        response_location += key + '/' + second_key
                        response_dictionary.append({"success":{response_location: value[second_key]}})
                    else:
                        response_dictionary.append({"success":{response_location + key: value}})

**Comment by alexyao2015** [comment]
My question was how did you discover the bug? And how to reproduce it using the hue app on mobile.

**Comment by Lord-Grey** [comment]
@alexyao2015 

> My question was how did you discover the bug?

As outlined in the intro, I was using hyperion.ng with the Entertainment-API and diyHue.
With the group activation an unexpected response had been detected.
Further investigations has shown, that the response from diyHue is different to the original bridge ones.

>  And how to reproduce it using the hue app on mobile.

I am not using the Hue app.
See the way to reproduce using Philips CLIP API -Debugger.

**Comment by JorinL** [comment]
Hey there,
I get "ERR_EMPTY_RESPONSE" on http://192.168.0.7/debug/clip.html

I use the dockerimage: diyhue/core:latest

Is it something in my config or in that image?
