### ISSUE TITLE
OTA is gone on recent WS2812 Firmware/ Connect APA102

### ISSUE THREAD

**Issue by AlexKusnezov** [diyhue/diyHue#425]
**Is your feature request related to a problem? Please describe.**
Guys, I recently updated the firmware OTA with the latest on 3 of my ws2813 strips.
They're working properly, but now I'm not seeing them in Ardurino IDE as OTA?
Did something changed?

I've also try to connect APA102 To a nodemcu v3, but it's just not working using ws2812 firmware.
What I've tried so far there was:
 - connecting external 5v power to APA102 directly
 - connecting DI to RX pin
 - connecting CI to G pin

How to connect APA102 properly?

**Comment by Mevel** [comment]
You can now compile and direct upload bin files through web ui. `Ipofesp8266/update`

**Comment by AlexKusnezov** [comment]
> You can now compile and direct upload bin files through web ui. `Ipofesp8266/update`

Cool, thanks. Any thoughts on why APA102 aren't working?

**Comment by AlexKusnezov** [comment]
@Mevel what I've also tried was changing Neopixelbus to DotStarBgrFeature, DotStarSpiMethod, but that didn't helped either

**Comment by alexyao2015** [comment]
Try using esphome. My guess is that simply isn't supported by the native firmware

**Comment by AlexKusnezov** [comment]
@alexyao2015 I'll take a look thank, but than I won't be able to use it with diyhue right?

**Comment by alexyao2015** [comment]
You can. Check out the docs.

**Comment by AlexKusnezov** [comment]
@alexyao2015 my bad, I'll try thanks
