### ISSUE TITLE
Help using the Raspbee module

### ISSUE THREAD

**Issue by gazuzu** [diyhue/diyHue#43]
Hi Team,

I was wondering if you could help me figure out what am I doing wrong while trying to set up an official Hue Switch to use with DiyHue.

I have acquired and installed the Raspbee module on my RaspberryPi, and followed the instructions to install Deconz.
I managed to install it, but this is where everything starts to get a little blurry.
While trying to follow the instructions on the Raspbee page, it is clear that these are mostly out of date...
The 1st time I opened http://rpi-ip:8080, the page loading up was clearly different to the one described on your page.
This loads the "Phoscon App", which seems to be a newer version of Deconz? Through trial and error though, I managed to find the old portal, and managed to click "Open Network" in "Settings" to search for devices.

This has found the Philips Hue Dimmer Switch, however I'm not sure how to tie it all together, (i.e. Deconz, Hue App and the Switch set up).

I have noticed that since having the Raspbee module, the Hue App detects a new accessory (it didn't before). If I dare click on it however, the app immediately crashes, so I can't set up the switch via the Hue App.
While the Deconz software has "Network Open" no other devices are found other than the Dimmer Switch (I have a Lightstrip Plus, Hue Iris and a standard Bulb that I was expecting to see there as well).

Can you please clarify how can I use the Hue Dimmer switch to control my Hue lights and Yeelight bulbs through the Hue App?
I thought the Switch could be added through the app if we had the Raspbee module, but this doesn't seem to be the case after all...

On another subject, I have tried using the Hue Essentials app as suggested to add the DiyHue emulator, I've selected Connect Manually when adding a Bridge, tried "DiyHue" and "Philips Hue" options and both crash the App after clicking "Activate" on the http://xxxxxx:8080/hue/linkbutton page...

Many thanks

**Comment by braini1511** [comment]
Hi Gazuzu,

you are not the first one having some trouble with the Raspbee-module. How dit you managed to get rid if the Phoscon App-Site?

**Comment by gazuzu** [comment]
On the Phoscon Webpage I went into Help, and there is a link to the "Old WebApp version". Clicking here will open the old portal.

**Comment by braini1511** [comment]
ok, but where is here a help button? for me there is just a big P in the middle, nothing more.

**Comment by mariusmotea** [comment]
Please provide a pastebin link with your config.json file. There must be some values that Hue app don't like.

**Comment by mariusmotea** [comment]
Phoscon works fine, no need to change to old gui. Simply go to gateway and enable app connect.

**Comment by gazuzu** [comment]
Hi Marius, Thanks for the reply.
Are you saying that I should be able to add the Hue Dimmer Switch or any other Official Hue accessory via the Hue App using DiyHue?

Please find the pastebin below:
https://pastebin.com/gGWksVEs


Braini, I'm not sure what you're seeing, sounds like the main webpage before logging in, which in my case there's not just the big "P", there's also the gateway of the Pi with the IP address.
Once I click on this and log in to the control panel (had to create the password as part of the initial set up), that's where I see the Help link on the left.

**Comment by mariusmotea** [comment]
Yes, other users already did it. Deconz add some extra keys to the sensor, or import them without uniqueid key. The good news is that once sensor was imported you can change all the values, add/delete until you fix the thing that hue app don't like. I recommend to search on internet for some output sample of that switch and replace the content in config.json (backup this file first!). I will trybto tell you what is wrong in attached file and provide you a new one.

**Comment by gazuzu** [comment]
I appreciate it Marius, I'll be waiting to see if you can spot anything that is causing the Hue App And Hue Essentials to crash.

Many thanks

**Comment by mariusmotea** [comment]
@braini1511 In you case i suspect hardware issue. Did you use your pi on other projects that may broke the gpio pins? You need to place the Rasbee module in another PI to exclude the module is faulty.

**Comment by braini1511** [comment]
i will check it with another Pi. But Pi, SD-Card an Raspbee module are all mint. Dresden-electronics just replied to my issue, it seems to be a problem with Safari. I will keep you updated.

**Comment by mariusmotea** [comment]
@gazuzu I believe i know what is the issue. Based on uniqueid same sensor was imported two times and this is because it was present in Deconz two times on different key id's ("2" and "3"). I believe you removed the sensors and add it back. 

Update: you are affected also by a bug that create huge values for Yeelight bulbs, please endure you are using recent version.

fixed config, stop hue-emulator service before you replace it:
https://pastebin.com/A4MAPHBn

**Comment by gazuzu** [comment]
Hi Marius,

Before raising this issue I've ran curl -s https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_install.sh | sudo bash /dev/stdin

as I was under the impression that this updates the software, and it said it was already up to date...

Thanks for the config, unfortunately the Hue app continues to crash when clicking on Accessory setup, however I have been able to connect to the emulator with the Hue Essentials app, so we're definitely making progress.

Many thanks

**Comment by mariusmotea** [comment]
Try to remove last sensor from config and check if still crash. If yes remove sensors one by one until the hue app will not crush. Also to be sure the problem persist wipe hue app data and pair it again.
