### ISSUE TITLE
esp8285 rgb led strip home assistant 

### ISSUE THREAD

**Issue by gordonf130** [diyhue/diyHue#438]
i have diy hue up and running, i have 4 esp8285 led controllers i have flashed them with esphome on home assistant, what am not sure of is the code i need to flash after, in home assistant i can turn the lights on and off but no colour option, they show up in the hue app but are prompted to do an update, i know the app cant update them, i have looked online and googled but i can't find the answer to my question, do i need to update them or is the code i have on them wrong, and if so does anyone have a working config/ code that works with the eps8266 with diyhue that allows colour change and hue entertainment area

**Comment by alexyao2015** [comment]
#292 

Read the wiki.

**Comment by gordonf130** [comment]
so helpful nice to see you contribute to the community
