### ISSUE TITLE
Vulnerabilities in web interface of diyHue

### ISSUE THREAD

**Issue by emtsubasa** [diyhue/diyHue#440]
**Describe the bug**
I found some vulnerabilities in diyHue. The vulnerabilities enable an attacker to steal personal information and take over home devices.
How should I share them? If there are no problems, I append detailed information on this issue.

**Comment by Mevel** [comment]
Please inform Marius directly to get it fixed directly. Slack would be the most direct way

**Comment by emtsubasa** [comment]
OK, thank you!

**Comment by alexyao2015** [comment]
Were you able to communicate the bug to Marius and have it resolved? If not, please message me on slack (Alex).

**Comment by emtsubasa** [comment]
I could contact Marius and sent detailed information a few days ago.
If I lose contact, I'll send the same message to you.
Thank you!

**Comment by alexyao2015** [comment]
I think we should look to just depreciate the web ui as a solution for this. It would not only remove this vulnerability but also remove the need to continue supporting a feature that isn't entirely necessary. If users need a web ui, they can install home assistant which will do the same thing that the current web ui does and more.
