### ISSUE TITLE
Armv6 docker image

### ISSUE THREAD

**Issue by yochy4671** [diyhue/diyHue#444]
**Is your feature request related to a problem? Please describe.**
Yes.  I tried to run Docker image of diyHue on Raspberry PI B+ (armv6l, Raspberry Pi OS debian/Buster), but it didn't work properly. 

**Describe the solution you'd like**
Can you give me instructions on how to create an existing Docker image?
When I install it using easy_install.sh, it works correctly. So I want to create a Docker image that works with armv6l (including modifying the existing Dockerfile by myself).

**Describe alternatives you've considered**
If there is a document on how to create a Docker image, please let me know its location.

**Additional context**
Not anything.

**Comment by alexyao2015** [comment]
What errors did you get? I could probably have an image in a few hours to test since I don't have one myself.

**Comment by yochy4671** [comment]
I'm not getting the error.

The docker virtual machine seemed to repeatedly restart. I confirmed it with the docker ps command.
Also, I couldn't find the diyHue bridge in the Hue Essentials app.

**Comment by alexyao2015** [comment]
Go ahead and try it now. I just build an armv6 image.

**Comment by yochy4671** [comment]
Thank you,
However, there is no change in appearance.
I tried the following procedure. Is there anything wrong?

1. remove existing docker image using "docker rmi" command.
2. re-install and run docker image using "docker run" command in the documentation.

**Comment by alexyao2015** [comment]
Check docker logs containerid. But yes, those were the correct steps.

**Comment by yochy4671** [comment]
I used the "docker logs" command, but no logs were output.
Docker container is exit with a status 139. It seems to mean a segmentation fault.
Any good ideas to debug?

```
CONTAINER ID        IMAGE                COMMAND                  CREATED              STATUS                            PORTS               NAMES
dc005ecd49a3        diyhue/core:latest   "python3 -u /opt/hue…"   About a minute ago   Restarting (139) 10 seconds ago 
```

**Comment by alexyao2015** [comment]
Can you show the output of docker inspect on the image?

**Comment by alexyao2015** [comment]
Ah I believe it's not working since we use ubuntu which does not have an armv6 image available. I would like to switch to alpine but that would require recompiling the entertainment server and coap server for musl.

**Comment by yochy4671** [comment]
Yes, I can show you docker inspect output.
Should I wait for the next armv6 Docker image?

**Comment by alexyao2015** [comment]
Probably along with the refactor we'll switch to alpine as a base image which should resolve this.

**Comment by yochy4671** [comment]
I will wait for the next armv6 Docker image.
You can feel free to request me, if there is anything I can do.

**Comment by alexyao2015** [comment]
Can you run docker inspect just to be sure?

**Comment by yochy4671** [comment]
Yes, please refer to the attached file.

[20200817_docker_inspect_armv6.txt](https://github.com/diyhue/diyHue/files/5081846/20200817_docker_inspect_armv6.txt)

**Comment by alexyao2015** [comment]
`        "Image": "sha256:bca601368ba3c353691bead9a465e1d76b6b632b6afd5ae01888497fe80b172b",`

Hmm. The image sha doesn't match either 109 or 110 from master for the armv6 image. Try using docker run with this tag:

`diyhue/core:110@sha256:983d6223f9aecbadcf337c043964674e5fb7f346cf0aebbf56b6dff11799faa2`

**Comment by yochy4671** [comment]
I tried it, it's working correctly.
Thank you!

Can I close this issue?

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                                              NAMES
5313edb07f59        diyhue/core:110     "python3 -u /opt/hue…"   About an hour ago   Up About an hour    0.0.0.0:80->80/tcp, 0.0.0.0:1900->1900/udp, 0.0.0.0:1982->1982/udp, 0.0.0.0:443->443/tcp, 0.0.0.0:2100->2100/udp   diyHue
```

**Comment by alexyao2015** [comment]
Well something still isn't getting tagged correctly since you had to use the digest to get a functioning image. Can you show the output of uname -a?

**Comment by alexyao2015** [comment]
Also can you try rmi'ing all images and running again from latest?

**Comment by yochy4671** [comment]
I tryed again from tag "diyhue/core:latest", it isn't work properly.
Docker container exit with status code 139.
The following is a part of the output of docker inspect.
```
        "Image": "sha256:bca601368ba3c353691bead9a465e1d76b6b632b6afd5ae01888497fe80b172b",
```
The output of uname -a is below.
```
Linux raspberrypi 5.4.51+ #1333 Mon Aug 10 16:38:02 BST 2020 armv6l GNU/Linux
```

**Comment by alexyao2015** [comment]
What does docker inspect show for the image you pulled using the digest? It shows the same digest right? 

I honestly cannot figure out where that digest is coming from because it doesn't appear on docker hub at all.

**Comment by yochy4671** [comment]
I used the latest tag without using the digest.
It is the result of inspest when starting docker with the following command.
```
$ sudo docker run -d --name diyHue --restart=always --network=bridge -v /mnt/hue-emulator/export:/opt/hue-emulator/export -e MAC=XX:XX:XX:XX:X:XX -e IP=192.168.0.72   -p 80:80/tcp -p 443:443/tcp -p 1900:1900/udp -p 2100:2100/udp -p 1982:1982/udp diyhue/core:latest
```

**Comment by alexyao2015** [comment]
Right so when you pulled it using the sha what does docker inspect show?

**Comment by yochy4671** [comment]
When I used digest, the output of docker inspect is below.

[20200817_docker_inspect_armv6_work.txt](https://github.com/diyhue/diyHue/files/5082445/20200817_docker_inspect_armv6_work.txt)

**Comment by alexyao2015** [comment]
Can you show the output of docker inspect on the image instead of the container?

**Comment by yochy4671** [comment]
Sorry, It's below.

[20200818_inspect_image_work.txt](https://github.com/diyhue/diyHue/files/5087560/20200818_inspect_image_work.txt)

**Comment by alexyao2015** [comment]
Now can you show docker inspect of the latest image which does not function?

**Comment by yochy4671** [comment]
Yes, That's below.

[20200818_inspect_image_notwork.txt](https://github.com/diyhue/diyHue/files/5087609/20200818_inspect_image_notwork.txt)

**Comment by alexyao2015** [comment]
Something definitely has to be cached. Try pulling diyhue/core:master

Are you sure you deleted the latest image and pulled it again?

**Comment by yochy4671** [comment]
First, I tried pulling using the diyhue/core:master tag without deleting the Docker image.

Then, the image ID was the same in the latest tag and the master tag. Then, the execution of this image(with master tag) exits with status 139.
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
diyhue/core         <none>              32d9fa8e896d        36 hours ago        126MB
diyhue/core         latest              bca601368ba3        36 hours ago        113MB
diyhue/core         master              bca601368ba3        36 hours ago        113MB
```
The image with "none" tag is pulled using digest.

Next, I deleted the Docker image and then pulled it using the diyhue/core:master tag.
Then the image ID was the same as the latest/maseter tag above. Then, the execution of this container exits with status 139.
```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
diyhue/core         master              bca601368ba3        36 hours ago        113MB
```

**Comment by alexyao2015** [comment]
> diyhue/core:latest@sha256:983d6223f9aecbadcf337c043964674e5fb7f346cf0aebbf56b6dff11799faa2
What happens if you pull this image?

**Comment by yochy4671** [comment]
The console output is below, and I see the Docker image working correctly.
```
pi@raspberrypi:~ $ sudo docker run -d --name diyHue_tmp --restart=always --network=bridge -v /mnt/hue-emulator/export:/opt/hue-emulator/export -e MAC=XX:XX:XX:XX:XX:XX -e IP=192.168.0.72   -p 80:80/tcp -p 443:443/tcp -p 1900:1900/udp -p 2100:2100/udp -p 1982:1982/udp diyhue/core:latest@sha256:983d6223f9aecbadcf337c043964674e5fb7f346cf0aebbf56b6dff11799faa2
Unable to find image 'diyhue/core:latest@sha256:983d6223f9aecbadcf337c043964674e5fb7f346cf0aebbf56b6dff11799faa2' locally
sha256:983d6223f9aecbadcf337c043964674e5fb7f346cf0aebbf56b6dff11799faa2: Pulling from diyhue/core
895d793fa7bf: Already exists 
d4aae70cffb2: Already exists 
d7d670eb7b80: Already exists 
d83de6b1fd07: Already exists 
c576dd9f06e0: Already exists 
794590ded8b0: Already exists 
27b2b5f326c2: Already exists 
b81a7fc4bc62: Already exists 
4bbe43243743: Already exists 
293350a6370a: Already exists 
f3b73e3db940: Already exists 
8898e61ea2d7: Already exists 
Digest: sha256:983d6223f9aecbadcf337c043964674e5fb7f346cf0aebbf56b6dff11799faa2
Status: Downloaded newer image for diyhue/core@sha256:983d6223f9aecbadcf337c043964674e5fb7f346cf0aebbf56b6dff11799faa2
343c644d6b718618ed27dc5ed7597fd8e70968394994ba0a530c8d12cc494776
pi@raspberrypi:~ $ sudo docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
diyhue/core         <none>              32d9fa8e896d        36 hours ago        126MB
```

**Comment by alexyao2015** [comment]
Can you show docker info?

**Comment by alexyao2015** [comment]
Perhaps also join the slack or create a thread on the discourse and move the conversation there? The github comments are getting too long.

**Comment by alexyao2015** [comment]
This is looking a lot like docker/for-linux#1025

**Comment by alexyao2015** [comment]
@yochy4671 I've implemented a new workaround. Try pulling latest now.
