### ISSUE TITLE
why can't i start the service properly?

### ISSUE THREAD

**Issue by kompas1** [diyhue/diyHue#453]
**Describe the bug**
So I am trying to start  the service with: sudo systemctl start hue-emulator.service It looks like it started but if i look at the status: it says the following thing:

● hue-emulator.service - Hue Emulator Service
   Loaded: loaded (/etc/systemd/system/hue-emulator.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-08-31 13:53:01 BST; 3s ago
  Process: 783 ExecStart=/home/pi/HueEmulator.py (code=exited, status=203/EXEC)
 Main PID: 783 (code=exited, status=203/EXEC)

so it's just after a clean install, nothing else was done except for installing it with the automated installing script. Same happens after manual install

**To Reproduce**
1. Clean Install (automated or manual, doesn't matter)
2. Start the service via systemctl
3. check the status over systemctl with sudo systemctl status hue-emulator.service
4. See the error:
Process: 783 ExecStart=/home/pi/HueEmulator.py (code=exited, status=203/EXEC)
 Main PID: 783 (code=exited, status=203/EXEC)

**Expected behavior**
Well it shouldn't be like this if i am not mistaken, it should just work after I did all the steps that are written in the docs

**Logs**

status:
● hue-emulator.service - Hue Emulator Service
   Loaded: loaded (/etc/systemd/system/hue-emulator.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Mon 2020-08-31 13:53:01 BST; 3s ago
  Process: 783 ExecStart=/home/pi/HueEmulator.py (code=exited, status=203/EXEC)
 Main PID: 783 (code=exited, status=203/EXEC)

**Comment by alexyao2015** [comment]
#292 
Please read the getting started.
