### ISSUE TITLE
Home Assistant addon

### ISSUE THREAD

**Issue by TopdRob** [diyhue/diyHue#456]
It would be great to use diyHue as addon in Home Assistant. I tried to use the dockerfile to build one however I noticed i'm to inexperienced to get it to work. Perhaps a docker specialist could have a look.

https://developers.home-assistant.io/docs/add-ons
https://community.home-assistant.io/t/diyhue-addon-hue-emulator/62737

What I tried sofar:
copied Dockerfile, docker-compose.yml, select.sh and startup.sh from .build folder and BridgeEmulator folder.

This is my folder structure:
```
addons
├── diyhue
    ├── config.json
    ├── docker-compose.yml
    ├── startup.sh
    └── .build
    │   └── select.sh
    ├── BridgeEmulator
        └── ***

```
config.json
```
{
    "name": "diyHue",
    "version": "1",
    "slug": "diyhue",
    "description": "Emulated Hue Bridge",
    "arch": ["armhf", "armv7", "aarch64", "amd64", "i386"],
    "startup": "before",
    "boot": "auto",
    "options": {},
    "schema": {}
}
```

**Comment by Mevel** [comment]
You can simply use the hue component to connect to diyhue.

**Comment by TopdRob** [comment]
> You can simply use the hue component to connect to diyhue.

This request is meaned to host diyHue on the same raspberry as were my Home Assistant is running.

**Comment by jaagupku** [comment]
I am running Home Assistant and diyHue in docker in my raspberry.

**Comment by alexyao2015** [comment]
This will be a future feature.

**Comment by juanesf** [comment]
how mevel says to use the hue plugin which is compatible with homeassistant, I have homeassistant, diyHue host and hyperion.ng on the same machine

**Comment by alexyao2015** [comment]
The request is to create a hassio add-on that simply makes installation of diyhue easier. It was not saying that installation of diyhue is not possible without the add-on. I believe mevel simply misunderstood the request as people wanting to connect to diyhue from home assistant which was not the case.

**Comment by foxy82** [comment]
This now exists https://github.com/MaxBec/hassio-diyHue
