### ISSUE TITLE
MQTT server get's flooded with messages from diyhue

### ISSUE THREAD

**Issue by balonchiks** [diyhue/diyHue#458]
**Is your feature request related to a problem? Please describe.**

Sort of. I have a diyhue installed on a raspberry pi, and one mqtt light connected to it (via Zigbee2MQTT). The I've got [Hyperion ng](https://github.com/hyperion-project/hyperion.ng) sending the data to the diyhue via the Philips hue integration that Hyperion has. The thing is that diyhue sends about 25 mqtt messages per second (at least in my case) to the bulb, and that overloads my mqtt server almost instantly, making all light changes appear with a increasing delay.

Example, turn on Hyperion to send the data to diyhue for a minute - it takes approx 3-5 minutes for the mqtt server to process and deliver all the messages to the bulb.

**Describe the solution you'd like**

Ideally it would be great to have some sort of limiter, or some way of not sending data to mqtt that quickly. I've read in [this thread](https://github.com/diyhue/diyHue/issues/401#issuecomment-631695900) that using a entertainment.py from a develop branch might solve that issue as the protocol is implemented there differently, but apparently when using this file in the "master" branch - the diyhue does not work at all. It is also confirmed in that tread [here](https://github.com/diyhue/diyHue/issues/401#issuecomment-632847360)

**Additional context**

Is there anything that can be done to prevent mqtt messages of being sent that often? entertainment.py from develop branch looks like exactly what I need, but it doesn't work with the master version as mentioned earlier, or I am i missing something?

Or maybe the changes should be done to some other file?

Thanks in advance!

**Comment by alexyao2015** [comment]
If it's using entertainment, it should be limited by default though things may have changed. It will be resolved with the refactor if not.

**Comment by balonchiks** [comment]
spend whole day yesterday trying both entertainment and not - still about 25 messages per second. anything i can do now to fix it maybe?

**Comment by alexyao2015** [comment]
Well if it was last updated in March. The first step would be to update. If that doesn't work, try updating to master-refactor. Old versions are unsupported.

**Comment by balonchiks** [comment]
ell, the latest release version is from March 31. version 2.0.4, so the release version is outdated? :)

**Comment by alexyao2015** [comment]
Very true. Tags should be used again...

**Comment by alexyao2015** [comment]
I've thought about this. In any case, entertainment will not work very well unless you are using supported bulbs which at this time are ESPhome, diyHue, and Yeelight. ESPhome would be your best bet for most supported. So due to that and the potential that this functionality may be changed with the refactor, I will be closing this.
