### ISSUE TITLE
Hue Sync not working with lights?

### ISSUE THREAD

**Issue by chrisdata** [diyhue/diyHue#46]
**Describe the bug**
The app side all seems working fine, I playing some youtube video and the Hue Sync app did detect it and changing color in the app, but all my lights seem nothing happens, won't sync. I can change the scene, turn on/off , even using another app like Hue Disco, iLightShow, no problem, just any app related to Hue Entertainment, it able to detect my entertainment area, but the lights just won't do anything.

**Comment by mariusmotea** [comment]
What types of lights you have in entertainment area? If you restart hue-emulator service it will work?

**Comment by chrisdata** [comment]
I have yeelight 2 and yeelight strip plus, it working before.
Ya, I tried restart computer, and still out of luck.

**Comment by mariusmotea** [comment]
Start in debug mode and show output during lights state change.

**Comment by chrisdata** [comment]
I read Wiki but not understand how to enable debug mode in the .py file in Ubuntu?
Add any code to the .py file?

**Comment by chrisdata** [comment]
Also I tried stop the emulator, but when I try 'restart' it, it said the port is in use, how to kill the port so I can restart the service? Thanks.

**Comment by mariusmotea** [comment]
First stop hue-emulator service tonrelease the ports, then cd /opt/hue-emulator && sudo ./HueEmulator3.py --debug=true

**Comment by chrisdata** [comment]
OK, thanks. I get it working but how to stop the service after running the py, I press CTRL+Z and it stopped but when I start the py again it said the address already in use?

**Comment by mariusmotea** [comment]
Not `CTRL+Z` but `CTRL+C` two times. `CTRL+Z` send the process to background. Type `fg` to bring it back

**Comment by mariusmotea** [comment]
I see nothing related to Hue Entertainment protocol in your output. Did you start Hue Sync? Also ia better to provide pastebin url that provide much more data than a print screen.

**Comment by chrisdata** [comment]
Now it unable to add lights in Hue app but able to connect with the bridge, what's may be the problem u guess?

**Comment by mariusmotea** [comment]
There was a pull request this morning that replace nmap light detection with native python socket.

**Comment by mariusmotea** [comment]
Please restart hue-emulator service. I believe the swversion keys are updated on startup.
