### ISSUE TITLE
EspHome Light not turning on through Hue App

### ISSUE THREAD

**Issue by Jhaward** [diyhue/diyHue#461]
**Describe the bug**
A Lohas 9W Smart Bulb flashed with EspHome using Tuya-Convert is detected in the Hue app and can be toggled on and off but the light itself does not react. The bulb will turn on and off using Home Assistant.

**To Reproduce**
1. Go to Hue App
2. Toggle Bulb on and off
3. See error

**Expected behavior**
The bulb will turn on as being reported in the Hue app.

**Logs**
`2020-09-14` 14:11:54,886 - root - INFO - Using Host 192.168.1.105:80
2020-09-14 14:11:54,966 - root - INFO - b827ebe04bd2
2020-09-14 14:11:54,967 - root - INFO - IP range for light discovery: 0-255
2020-09-14 14:11:54,967 - root - INFO - 127.0.0.1
2020-09-14 14:11:54,967 - root - INFO - Online Discovery/Remote API Enabled!
2020-09-14 14:11:54,970 - root - INFO - Config loaded
2020-09-14 14:11:54,984 - root - DEBUG - starting ssdp...
2020-09-14 14:11:54,985 - root - DEBUG - start ssdp broadcast
2020-09-14 14:11:54,988 - root - INFO - sync with lights
2020-09-14 14:11:54,993 - root - INFO - Starting httpd...
2020-09-14 14:11:55,000 - root - INFO - Starting ssl httpd...
2020-09-14 14:11:55,008 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-09-14 14:11:55,298 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
2020-09-14 14:12:05,444 - root - DEBUG - Sending M-Search response to 192.168.1.162
192.168.1.162 - - [14/Sep/2020 14:12:05] "GET /description.xml HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:08] "GET /api/36531b1af68b11eab372b827ebe04bd2/config HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:08] "GET /api/36531b1af68b11eab372b827ebe04bd2 HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:08] "GET /api/36531b1af68b11eab372b827ebe04bd2/config HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:08] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:08] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
2020-09-14 14:12:10,029 - root - INFO - sync with lights
192.168.1.213 - - [14/Sep/2020 14:12:10] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:10] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:13] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:13] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:13] "PUT /api/36531b1af68b11eab372b827ebe04bd2/lights/1/state HTTP/1.1" 200 -
2020-09-14 14:12:13,286 - root - INFO - in PUT method
2020-09-14 14:12:13,286 - root - INFO - /api/36531b1af68b11eab372b827ebe04bd2/lights/1/state
2020-09-14 14:12:13,287 - root - INFO - b'{"on":true}'
2020-09-14 14:12:13,589 - root - INFO - [
    {
        "success": {
            "/lights/1/state/on": true
        }
    }
]
2020-09-14 14:12:14,878 - root - DEBUG - Sending M-Search response to 192.168.1.162
192.168.1.213 - - [14/Sep/2020 14:12:15] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:15] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:17] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:17] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:19] "GET /api/36531b1af68b11eab372b827ebe04bd2/config HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:19] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:19] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
2020-09-14 14:12:21,042 - root - INFO - sync with lights
192.168.1.213 - - [14/Sep/2020 14:12:21] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:21] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:23] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:23] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
2020-09-14 14:12:25,112 - root - DEBUG - Sending M-Search response to 192.168.1.162
2020-09-14 14:12:25,344 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-09-14 14:12:25,640 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
192.168.1.213 - - [14/Sep/2020 14:12:25] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:25] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:28] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:28] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:29] "GET /api/36531b1af68b11eab372b827ebe04bd2/config HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:30] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:30] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
2020-09-14 14:12:32,055 - root - INFO - sync with lights
192.168.1.213 - - [14/Sep/2020 14:12:32] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:32] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:34] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:34] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
2020-09-14 14:12:34,853 - root - DEBUG - Sending M-Search response to 192.168.1.162
192.168.1.213 - - [14/Sep/2020 14:12:36] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:36] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:38] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:38] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:39] "GET /api/36531b1af68b11eab372b827ebe04bd2/config HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:40] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:40] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:43] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:43] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:43] "PUT /api/36531b1af68b11eab372b827ebe04bd2/lights/1/state HTTP/1.1" 200 -
2020-09-14 14:12:43,376 - root - INFO - in PUT method
2020-09-14 14:12:43,377 - root - INFO - /api/36531b1af68b11eab372b827ebe04bd2/lights/1/state
2020-09-14 14:12:43,378 - root - INFO - b'{"on":false}'
2020-09-14 14:12:43,680 - root - INFO - [
    {
        "success": {
            "/lights/1/state/on": false
        }
    }
]
2020-09-14 14:12:45,070 - root - INFO - sync with lights
192.168.1.213 - - [14/Sep/2020 14:12:45] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 14:12:45] "GET /api/36531b1af68b11eab372b827ebe04bd2/groups HTTP/1.1" 200 -
2020-09-14 14:12:45,482 - root - DEBUG - Sending M-Search response to 192.168.1.162
192.168.1.213 - - [14/Sep/2020 14:12:47] "GET /api/36531b1af68b11eab372b827ebe04bd2/lights HTTP/1.1" 200 `-`

**Additional context**
Running on rp3 using host install. I have renamed the bulb 1 in the Hue app (I have also tried this without remaning the bulb and it produces the same result). Here is the YAML Configuration for the bulb:
`esphome:
 
  name: lohas_cct
  platform: ESP8266
  board: esp01_1m
  includes:
    - diyhueasyncudp.h
  libraries:
    - ESPAsyncUDP
 

custom_component:
- lambda: |-
    auto diyhue = new diyhueudp();
    return {diyhue};
 
wifi:
  ssid: XXXXXXXX
  password: XXXXXXXXX
 
  ap:
    ssid: Lohas1
    ap_timeout: 3min    

captive_portal:

logger:

ota:

web_server:

api:

switch:
  - platform: template
    name: alert
    id: alert
    optimistic: true
    turn_on_action:
      - light.turn_off: color_led
      - light.turn_on:
          id: white_led
          brightness: 100%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: white_led
          brightness: 10%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: white_led
          brightness: 100%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: white_led
          brightness: 10%
          color_temperature: 4000 K
      - delay: 1s
      - light.turn_on:
          id: white_led
          brightness: 100%
          color_temperature: 4000 K
      - switch.turn_off: alert
  - platform: template
    name: entertainment_switch
    id: entertainment_switch
    optimistic: true

output:
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO5
  - platform: esp8266_pwm
    id: output_green
    pin: GPIO4
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO13
  - platform: esp8266_pwm
    id: output_cold_white
    pin: GPIO14
  - platform: esp8266_pwm
    id: output_warm_white
    pin: GPIO12

light:
  - platform: rgb
    id: color_led
    name: "color_led"
    red: output_red
    green: output_green
    blue: output_blue
    default_transition_length: 0.4s
    effects:
      - random:
           name: Random Effect With Custom Values
           transition_length: 5s
           update_interval: 3s
 
  - platform: cwww
    id: white_led
    name: "white_led"
    warm_white: output_warm_white
    cold_white: output_cold_white
    cold_white_color_temperature: 6000 K
    warm_white_color_temperature: 2700 K
    default_transition_length: 0.4s

text_sensor:
  - platform: template
    name: "light_id"
    id: light_id
    lambda: |-
     return {"esphome_diyhue_light;XX:XX:XX:XX:XX:XX;lohas_cct;0;0"};
    update_interval: 24h`

The X's are simply there for this post; the actual configuation has the correct info in it.
Any help would be much appreciated, thank you.

**Comment by alexyao2015** [comment]
Try master-refactor.

**Comment by Jhaward** [comment]
I have uninstalled and reinstalled using the master-refactor branch but it still isn't turning on. Here are the logs from running the debug command now:
`2020-09-14 15:36:55,208 - root - INFO - Using Host 192.168.1.105:80
2020-09-14 15:36:55,260 - root - INFO - b827ebe04bd2
2020-09-14 15:36:55,261 - root - INFO - IP range for light discovery: 0-255
2020-09-14 15:36:55,261 - root - INFO - 127.0.0.1
2020-09-14 15:36:55,261 - root - INFO - Online Discovery/Remote API Enabled!
2020-09-14 15:36:55,264 - root - INFO - Config loaded
2020-09-14 15:36:55,280 - root - DEBUG - starting ssdp...
2020-09-14 15:36:55,281 - root - DEBUG - start ssdp broadcast
2020-09-14 15:36:55,295 - root - INFO - sync with lights
2020-09-14 15:36:55,303 - root - INFO - Starting httpd...
2020-09-14 15:36:55,317 - root - INFO - Starting ssl httpd...
2020-09-14 15:36:55,324 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-09-14 15:36:55,610 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
192.168.1.213 - - [14/Sep/2020 15:36:58] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2/config HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 15:36:58] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2 HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 15:36:59] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2/config HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 15:36:59] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 15:36:59] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 15:37:00] "PUT /api/04fa2ef8f69711ea9fb4b827ebe04bd2/lights/1/state HTTP/1.1" 200 -
2020-09-14 15:37:00,620 - root - INFO - in PUT method
2020-09-14 15:37:00,621 - root - INFO - /api/04fa2ef8f69711ea9fb4b827ebe04bd2/lights/1/state
2020-09-14 15:37:00,621 - root - INFO - b'{"on":false}'
2020-09-14 15:37:00,923 - root - INFO - [
{
        "success": {
            "/lights/1/state/on": false
        }
    }
]
192.168.1.213 - - [14/Sep/2020 15:37:01] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 15:37:01] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 15:37:02] "PUT /api/04fa2ef8f69711ea9fb4b827ebe04bd2/lights/1/state HTTP/1.1" 200 -
2020-09-14 15:37:02,769 - root - INFO - in PUT method
2020-09-14 15:37:02,770 - root - INFO - /api/04fa2ef8f69711ea9fb4b827ebe04bd2/lights/1/state
2020-09-14 15:37:02,770 - root - INFO - b'{"on":true}'
2020-09-14 15:37:03,072 - root - INFO - [
 {
        "success": {
            "/lights/1/state/on": true
        }
    }
]
192.168.1.213 - - [14/Sep/2020 15:37:03] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 15:37:03] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2/groups HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 15:37:05] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2/lights HTTP/1.1" 200 -
192.168.1.213 - - [14/Sep/2020 15:37:05] "GET /api/04fa2ef8f69711ea9fb4b827ebe04bd2/groups HTTP/1.1" 200 -
2020-09-14 15:37:07,328 - root - INFO - sync with lights
2020-09-14 15:37:21,284 - root - DEBUG - Sending M-Search response to 192.168.1.162`

**Comment by alexyao2015** [comment]
That's definitely not that master-refactor branch. Use docker and install again

**Comment by Jhaward** [comment]
Which command would you use to install the correct branch?

**Comment by Jhaward** [comment]
I have installed using the master-refactor branch on docker and can confirm the bulb is now turning on. Thank you a lot!

**Comment by Jhaward** [comment]
Sorry to reopen this but it seems that the entertainment function isn't working. I can create an area in the app but in every app that uses the entertainment function (such as Hue Sync for Windows and Hue Essentials), it says bridge disconnected when trying to sync. Using the entertainment function also permanently leaves the room the light is in stuck in "Light Sync is active" and will not turn of this function when clicking Stop light sync, meaning I have to reset the app and bridge every time I attempt this. The colour also does not change. 

As a separate issue, I have to manually keep starting the docker container each time I start the pi due to the docker saying exited (137). Any ideas what might be causing this? Thanks.

**Comment by juanesf** [comment]
At some point I can do something similar, if you use an effect with entertainment in hue essentials this stops the previous service and allows the service to close correctly

**Comment by Jhaward** [comment]
Is there something I can do differently to get the service to work or do I need to wait for changes to be made to the project?
