### ISSUE TITLE
Support for MQTT Plugs (done already, not allowed to branch and add pull request)

### ISSUE THREAD

**Issue by wzbfyb** [diyhue/diyHue#464]
Hi,

I added support for Plugs to mqtt.py but am not allowed to create a branch. I'd be happy to work on that :)

altered the on_connect method:
`    autodiscoveryTopicLights = discoveryPrefix + "/light/+/light/config" # + in topic is wildcard
    client.subscribe(autodiscoveryTopicLights)
    autodiscoveryTopicSwitches = discoveryPrefix + "/switch/+/switch/config" # + in topic is wildcard
    client.subscribe(autodiscoveryTopicSwitches)`

and in line 144

`if modelid != "Plug 01":
                bridge_config["lights"][new_light_id]["config"] = light_types[modelid]["config"]`

**Comment by dchwilk** [comment]
Hm, that doesn't work for me. But I'm not sure I copied that correctly either.
Does this only work with hue plugs?
Here is a topic from me:
homeassistant/switch/0x7cb03eaa0a01d998/switch/config
`{"payload_off":"OFF","payload_on":"ON","value_template":"{{ value_json.state }}","command_topic":"zigbee2mqtt/pc/set","state_topic":"zigbee2mqtt/pc","json_attributes_topic":"zigbee2mqtt/pc","name":"pc_switch","unique_id":"0x7cb03eaa0a01d998_switch_zigbee2mqtt","device":{"identifiers":["zigbee2mqtt_0x7cb03eaa0a01d998"],"name":"pc","sw_version":"Zigbee2mqtt 1.14.2-dev","model":"Smart+ plug (AB3257001NJ)","manufacturer":"OSRAM"},"availability_topic":"zigbee2mqtt/bridge/state"}`

**Comment by wzbfyb** [comment]
Hi!

interesting, I tried it with Osram and Blitzwolf plugs (but only kept the Blitzwolf ones).
here is my full mqtt.py
maybe I did a copy&paste error. I also added preliminary support for RGB+W dual ID  LED strip controllers (Dresden is what I use).

**Comment by cheesemarathon** [comment]
@wzbfyb create a fork of this repo, make your changes to that and then create a PR from your fork.

**Comment by wzbfyb** [comment]
Thanks, will do that!

LG

**Comment by sascha777** [comment]
Hi, I would love to add my Osram Plugs (connected via zigbee2mqtt) to diyhue to get a more convenient control via the Hue App. 
Any news about merging this to the diyhue repo?

**Comment by mariusmotea** [comment]
But support for plugs must be already in place.

**Comment by sascha777** [comment]
Thanks Marius!
I just didn't realize that my version was outdated. 
Problem solved.
