### ISSUE TITLE
Hue Sync only works one time

### ISSUE THREAD

**Issue by DukyNuky** [diyhue/diyHue#475]
hi,

i have a big problem with mit diyhue setup. 
when i fresh start the hue emulator everything is fine. I can connect with HUE Sync PC Software to my hue emulator bridge and sync my screen.

when i then stop syncing and try to start again, pc sync cant connect to the bridge anymore till i restart hue emulator.

debug log attached.
192.168.0.184 - PC with Hue Sync
192.168.0.202 - another hue bridge
[hue-emulator-hangs.txt](https://github.com/diyhue/diyHue/files/5396401/hue-emulator-hangs.txt)

Thank you for this awesome project...

regards

DukyNuky

**Comment by mariusmotea** [comment]
Hi,

I don't know your installation mode, but the problem is the lack of `killall` command:
```
FileNotFoundError: [Errno 2] No such file or directory: 'killall': 'killall'
```

If you use docker then probably is our fault and we need to investigate further, if not then check how you can install killall command. Probably solution is to install psmisc package:

```
apt-get install psmisc
```
or 
```
yum install psmisc
```

**Comment by DukyNuky** [comment]
apt-get install psmisc did it...

It was a fresh debian 10 with your install script.. maybe include this package in the install script..

many thanks.. nice weekend..
