### ISSUE TITLE
control existing hue bridge

### ISSUE THREAD

**Issue by MeisterTea** [diyhue/diyHue#478]
Hi, is it possible to use this emulator to control hue lights on a genuine hue Bridge?

I have no idea if two genuine hue bridges can communicate together in normal circonstances. 

I would like to keep as much devices on the genuine one as I have some hue play which to my understanding are not compatible to third party bridges (plus hue control outside network is just plug and play) 

I would use it in order to control my lights with tradfri dimmers

**Comment by ryancasler** [comment]
Yes, it is.  After installing DIYHue, simply navigate to the web-admin page.  There you will see a button labeled "import from bridge"
![image](https://user-images.githubusercontent.com/30270489/96944369-a168e700-14a8-11eb-8f28-7c32cb672c4d.png)
Click it.  Then you will enter the IP of your Hue bridge, tap the link button on the bridge and then tap the "Save" button.
![image](https://user-images.githubusercontent.com/30270489/96944427-bf364c00-14a8-11eb-90f2-91b382d43da0.png)

**Comment by alexyao2015** [comment]
#292
