### ISSUE TITLE
Suggestion for light discovery without external dependency to nmap

### ISSUE THREAD

**Issue by loefkvist** [diyhue/diyHue#48]
The external dependency to nmap has given me problems over the last few weeks. 
The nmap system call for light discovery in scanForLights( ) is giving inconsistent results and is rather slow. The Hue-app almost always times out before discovery finishes and never finds all the lights in one go. Some lights may even never be found. 

Suggested solution:
I wrote my own host discovery based on sockets instead. As all hosts are on the same network as diyHue you can set a rather short timeout value and still be able to connect. 
It is fast enough to discover all hosts on a /24 network and register them before the Hue-app times out.
The code only supports /24 networks but could easily be changed to allow for /16 if needed (not without significant penalty to the time it would consume though).

```python
import socket
...
def scanHost(host, port):
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.settimeout(0.01)
    result = sock.connect_ex((host, port))
    sock.close()
    return result

def findHosts():
    addr = 0
    validHosts = []
    host = HostIP.split('.')
    while addr <= 255:
        host[3] = str(addr)
        testHost = host[0]+"."+host[1]+"."+host[2]+"."+host[3]
        if scanHost(testHost, 80) == 0:
            validHosts.append(testHost)
        addr = addr+1

    return validHosts
```

Calling findHosts( ) from scanForLights( ) instead of the current nmap-based system call will do the trick.
Try it out and feel free to use it as you like.

**Comment by mariusmotea** [comment]
This is great because is python native and extend this solution to multiple platforms where nmap is not available (windows?). You can create a pull request to record your contribution to github, otherwise i can push your code.

Thanks.

**Comment by loefkvist** [comment]
Great. I will try to create a PR as soon as possible.
I need to do some cleanup first though as the code I have currently also contains some MQTT publishing for switches and other hacks I did to support my setup ;)

If you'd like to see I can put the MQTT stuff up for review too?
It's great when using Home Assistant as you will not have to poll the bridge to get switch-status.

**Comment by mariusmotea** [comment]
Already merge it.
Thank you.
