### ISSUE TITLE
Changing from Latest to Master-Refactor Broke all Connections

### ISSUE THREAD

**Issue by ryancasler** [diyhue/diyHue#481]
After updating my docker container from the "latest" tag to the "master-refactor" tag using the existing volume information(so the existing config files) no lights are displayed and I am unable to connect to the bridge with the Hue app.  Moving back to the "latest" tag allowed me to connect again without a problem.  

So, are there changes to the config file that the master-refactor branch is not able to adjust for when running with an older config?  To be clear, I literally just swapped "diyhue/core:latest" with "diyhue/core:master-refactor" in my docker run command, which is: 
```
`docker run -d 
   --name "diyHue" 
   --restart="always" 
   --network="host" 
   -e MAC='MACADDRESS' 
   -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' 
   diyhue/core:latest`
```

Any idea if I'm doing something wrong or if there is something else I need to be doing before upgrading?  I'm assuming the master-refactor branch is the "latest and greatest", correct?  I was using the directions on "readthedocs".

![image](https://user-images.githubusercontent.com/30270489/97049415-acc01f00-1549-11eb-96a4-7a9bfd1282b8.png)

Any help would be appreciated.  Thanks!!!

**Comment by alexyao2015** [comment]
Yep, there are many breaking changes with the new build causing it to be incompatible with previous configs.

**Comment by ryancasler** [comment]
So, the only option is to rebuild with a new config?  That seems a little harsh.  There's no way to convert an old config to fill in what is missing?  Are the changes to the config documented anywhere?

**Comment by alexyao2015** [comment]
The change is here
https://github.com/diyhue/diyHue/commit/1a41728e2beb785b660328204c341d1cd8012846

**Comment by ryancasler** [comment]
I actually tried installing the new refactor version and as soon as I attempted to control my Strips (With DIYHue Sketches), they went "unreachable".  Is there a change to the firmware for the lights as well for the new version?

**Comment by alexyao2015** [comment]
There shouldn't be? If that is the case, there might be a bug in there.
