### ISSUE TITLE
Hue Motion Sensor

### ISSUE THREAD

**Issue by Xorfee** [diyhue/diyHue#484]
I don't get the point, why I am able to control zigbee and esp8266 lights via a zigbee remote like hue smart switch or tradfri and not able to control the behaviour of my esp8266 lights with hue motion sensor?

I mean I am currently running diyhue with deconz, both are headless diyhue is running on port 80 and deconz on 8080.

Both ip are on hue essentials app, I am able to control deconz hue motion sensor just with zigbee devices but able to control the behaviour of my diyhue ip..

Am I doing something wrong?

**Comment by alexyao2015** [comment]
#292 phrased more as a question rather than an issue

**Comment by ryancasler** [comment]
Is the sensor paired to Deconz?  You say you are able to use a Hue remote paired with Deconz through the Hue Essentials App?  If so, the Hue Motion sensor should also pair the same way.  You just have to go into DIYHue and refresh the Deconz switches by clicking on the Deconz button in the WebUI.
