### ISSUE TITLE
Unable to pair hue dimmer switch

### ISSUE THREAD

**Issue by foldericon** [diyhue/diyHue#485]
I am using diyHue with deconz and everything seems fine. However I am not able to connect an original hue dimmer switch.

Hue apps just don't see it and the web UI of the emulator seems to be stripped and is therefore useless (See screenshot below).
In Phoscon web UI when I try to connect the switch, it seems like it recognizes all my lights as the switch since they all start blinking and I am able to connect the "switch" which is not usable afterwards though.
I just don't know what I do wrong, I read the docs carefully and tried to set this up multiple times.
Am I missing something?

![Screenshot 2020-10-25 at 16 49 30](https://user-images.githubusercontent.com/2416994/97112544-250f1780-16e5-11eb-80de-dec7322369c6.png)

**Comment by Mevel** [comment]
Steps in short:
Link diyhue and deconz as described in the docs. Make sure websocket port and ui port are set correct. 
Add switch via deconz ui
manage switch via hue app and assign rules. 
done

**Comment by alexyao2015** [comment]
#292
