### ISSUE TITLE
Option to run a shell command or a shell script to curl an api to turn on/off a device 

### ISSUE THREAD

**Issue by amyth1884** [diyhue/diyHue#486]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Option to run a shell command or a shell script to curl an api to turn on/off a device 

**Describe alternatives you've considered**
HA-bridge, but its not working for me anymore.

**Comment by alexyao2015** [comment]
What are you trying to control?

**Comment by amyth1884** [comment]
Multiple esphome devices using api, also trying trigger wol for media
center pc using raspberry pi, currently there is no alexa integration which
would operate devices locally

**Comment by mariusmotea** [comment]
You can use the following curl command:

`curl -X PUT -d '{"on": true}' http://{hue emulator ip}/api/{username}/groups/{group id}/action`

Replace:
{hue emulator ip} with the ip of the hue emulatir bridge
{username} with a valid username, can be found in config.json under whitelist key
{group id} the group id you want to control

use `{"on": false}` to turn off the lights in that group.

If you start the emulator in debug mode you are able to see the commands sent by hue apps and use the same.

**Comment by alexyao2015** [comment]
Will look into adding this feature.

**Comment by amyth1884** [comment]
> You can use the following curl command:
> 
> `curl -X PUT -d '{"on": true}' http://{hue emulator ip}/api/{username}/groups/{group id}/action`
> 
> Replace:
> {hue emulator ip} with the ip of the hue emulatir bridge
> {username} with a valid username, can be found in config.json under whitelist key
> {group id} the group id you want to control
> 
> use `{"on": false}` to turn off the lights in that group.
> 
> If you start the emulator in debug mode you are able to see the commands sent by hue apps and use the same.

Could you please explain with an example, eg I want to run a command "wol - 192.168.1.1"

**Comment by alexyao2015** [comment]
This feature does not exist. That is related to controlling the bridge itself
