### ISSUE TITLE
No debug/clip.html using Docker(rancher) diyhue/core:latest

### ISSUE THREAD

**Issue by JorinL** [diyhue/diyHue#488]
Hey there,
I get "ERR_EMPTY_RESPONSE" on http://192.168.0.7/debug/clip.html

When using "http://192.168.0.7/debug/clip" I get:
`[{"error":{"type":1,"address":"/debug/clip","description":"unauthorized user"}}]`

I use the dockerimage: diyhue/core:latest

Is it something in my config or in that image?

**Comment by alexyao2015** [comment]
#292
