### ISSUE TITLE
Frequent disconnections using master-refactor branch

### ISSUE THREAD

**Issue by WanderingStark** [diyhue/diyHue#492]
**Describe the bug**
After updating to the latest docker image I am unable to control my lights as reliably as before the update. This includes now not being able to toggle all lights on at the same time in the Hue app, having no functionality in the Hue Essentials app due to disconnecting after every action, and Hue Sync app also disconnecting after every action. Tried wiping config and starting again but made no change.

**Expected behavior**
Lights worked as before update

**Logs**
```
Exception happened during processing of request from ('192.168.0.23', 44660)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/opt/hue-emulator/webServer/server.py", line 832, in do_PUT
    lightManager.control.splitLightsToDevices(url_pieces[4], put_dictionary)
AttributeError: module 'lightManager' has no attribute 'control'
```

**Additional context**
Pulled Master-refactor branch from Docker Hub

**Comment by alexyao2015** [comment]
Thanks for reporting the issue! Try downloading the image again. This bug should now be fixed.

**Comment by Jhaward** [comment]
Can confirm this fixed the issue, thanks very much!

**Comment by WanderingStark** [comment]
Can confirm this fixed the issue, thanks very much!
