### ISSUE TITLE
Official Hue App does not discover the bridge properly 

### ISSUE THREAD

**Issue by mihneagtt** [diyhue/diyHue#495]
I am running diyHue in a Ubuntu 20.04 VMware on top of Windows 10, using docker. I cannot connect to the bridge via the official app, because it finds the bridge, but only for a couple of seconds then it says "no new hue bridge found". I can connect to it using Hue Essentials, but only manually, it does not discover the bridge automatically. I attached a video so you can understand better what's going on. https://drive.google.com/file/d/1Q-aa1si-uGMQkkyu-lxjrPiiOq5z_LmJ/view?usp=sharing
Thank you!

**Comment by alexyao2015** [comment]
#292 Read the docs. Certificate issue
