### ISSUE TITLE
MQTT light control

### ISSUE THREAD

**Issue by DaOliver86** [diyhue/diyHue#497]
Hello, 

I want to control a MQTT light (https://github.com/spigotx/Moodlite) within the HUE Essential Android App. 
For this, I followed the MQTT light guide. I managed to pair my light with the App, not by auto discovery, 
but by sending auto discovery protocol from this page: https://diyhue.readthedocs.io/en/latest/lights/mqtt.html
via mqtt.fx after hitting pair new light in the Hue Essential App. Because, how would any MQTT light know
about the discovery protocol of DIYHUE or Zigbee2MQTT?
This worked out and the  light shows up in the App and in the DIYHUE config.json.
Here, I am able to add the Moodlite specific topics but the payload send by DIYHUE do not fit the requirements of Moodlite. 

The payload send by DIYHUE for turning the lights on: **{"transition": 0.3, "state": "ON"}**
The payload required by Moodlite: **1**

Is it somehow possible, to edit the payload send by DIYHUE for enabling/disabling, setting brightness, pattern, 
speed, colour?
Unfortunatly, I cant find much information or documentation about possbible topics in DIYHUE.
Is DIYHUE using the same topics as zigbee2mqtt as found here: https://www.zigbee2mqtt.io/information/mqtt_topics_and_message_structure.html?

How can I change the payload for the single topics or define the features of my MQTT light in the config.json?

I love the project and love the effort. 
Thank you very much!

**Comment by alexyao2015** [comment]
1. There is a template for a reason
2. #292
