### ISSUE TITLE
diyHue lights not working with master-refactor

### ISSUE THREAD

**Issue by AlexKusnezov** [diyhue/diyHue#498]
Hey guys, today I've tried the master refactor image and started with a completely clean setup.
I used docker compose and started diyhue/core:master-refactor, correct me please, if it's not the right container.

Unfortunately I'm not able to control my WS2812 diyhue lightstrips. I've also updated the firmware to the latest.
I also can't enable debug, when I uncomment de DEBUG: true this comes up:
```
ERROR: The Compose file '/home/pi/diyHue/build/docker-compose.yml' is invalid because:
services.diyHue.environment.DEBUG contains true, which is an invalid type, it should be a string, number, or a null
```

when I use diyhue/core everything works, but the config doesn't appear in /mnt/hue-emulator
even, when I have the volume set to this path.
with diyhue/core:master-refactor image the path works. Please, I need some clarification on how to use master-refactor with diyHue lights. I'm dumb, please don't be angry at me ;)

**Comment by alexyao2015** [comment]
Few things to read #292, readme, and documentation
