### ISSUE TITLE
coap-client-linux not found, tradfri lights not added

### ISSUE THREAD

**Issue by BPHvZ** [diyhue/diyHue#518]
**Describe the bug**

When trying to add Tradfri lights, coap-client-linux cannot be found.

**Steps to Reproduce**

1. Insert the Tradfri IP address and security code.
2. Click on save
3. A blank screen appears instead of the "added ... lights".
The logs of the docker container show the error code.

**Expected behavior**

Tradfri lights should have been added.

**Logs**

```
192.168.178.185 - - [05/Dec/2020 18:25:58] "GET /tradfri?ip=192.168.178.221&code=zwcThq8p2dZ1cpxl HTTP/1.1" 200 -,
/bin/sh: 1: ./coap-client-linux: not found,
----------------------------------------,
Exception happened during processing of request from ('192.168.178.185', 58333),
Traceback (most recent call last):,
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread,
    self.finish_request(request, client_address),
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request,
    self.RequestHandlerClass(request, client_address, self),
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__,
    self.handle(),
  File "/usr/lib/python3.7/http/server.py", line 426, in handle,
    self.handle_one_request(),
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request,
    method(),
  File "/opt/hue-emulator/HueEmulator3.py", line 1311, in do_GET,
    registration = json.loads(check_output("./coap-client-linux -m post -u \"Client_identity\" -k \"" + get_parameters["code"][0] + "\" -e '{\"9090\":\"" + new_identity + "\"}' \"coaps://" + get_parameters["ip"][0] + ":5684/15011/9063\"", shell=True).decode('utf-8').rstrip('\n').split("\n")[-1]),
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output,
    **kwargs).stdout,
  File "/usr/lib/python3.7/subprocess.py", line 487, in run,
    output=stdout, stderr=stderr),
subprocess.CalledProcessError: Command './coap-client-linux -m post -u "Client_identity" -k "zwcThq8p2dZ1cpxl" -e '{"9090":"Hue-Emulator-246"}' "coaps://192.168.178.221:5684/15011/9063"' returned non-zero exit status 127.,
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): armv7l
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Raspbian GNU/Linux 10 (buster)
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry Pi 3 Model B Plus Rev 1.3

**Checklist**
- [x] I confirm that this is a bug report
- [X] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by alexyao2015** [comment]
Thanks for the report! What version and branch are you using?

**Comment by BPHvZ** [comment]
I just used the command from the guide:
```docker run -d --name diyHue --restart=always --network=host -e MAC=XX:XX:XX:XX:XX:XX -v /mnt/hue-emulator/export:/opt/hue-emulator/export diyhue/core:latest```
So the image is diyhue/core:latest

**Comment by BPHvZ** [comment]
Pull diyhue/core:armv7-master-refactor fixed the bug.
I see now that documentation says that the 'latest' tag in diyhue/core:latest pulls from the 'master' branch. It might be better to change this to the 'master-refactor' branch

**Comment by alexyao2015** [comment]
We've renamed the master-refactor branch to experimental better reflect that it is indeed more of an experimental/development branch. That being said, I will be doing everything in my power to ensure that it is stable enough for daily usage. New features and development will occur in the experimental branch for now. I hope this clears up some confusion and please do report any more bugs that you find! Thanks!
