### ISSUE TITLE
Upgrade to firmware 1941132070 to support Adaptive Lighting (with Homebridge)

### ISSUE THREAD

**Issue by BPHvZ** [diyhue/diyHue#520]
**Is your feature request related to a problem? Please describe.**

Adaptive Lighting is currently not supported because the firmware is too low.

**Describe the feature that you would like to be added**

Upgrade to firmware 1941132070 to support Adaptive Lighting. Using homebridge and homebridge-hue (which are already updated for Adaptive Lighting) HomeKit users will be able to use Adaptive Lighting.

**Describe alternatives you've considered**

There are no alternatives than to upgrade the firmware.

**Describe your use case for this feature**
HomeKit users are able to use Adaptive Lighting using diyhue, homebridge and homebridge-hue.

**Checklist**
- [X] I confirm that this is a feature request
- [X] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by alexyao2015** [comment]
What version are you using #433 added support for this already automatically

**Comment by BPHvZ** [comment]
> What version are you using #433 added support for this already automatically
Docker image armv7-experimental, digest: c185d099d861.
The Hue app reports sw: 1939070020 and the update page keeps searching for updates

**Comment by alexyao2015** [comment]
Issue should be fixed!
