### ISSUE TITLE
Home Assistant Integration

### ISSUE THREAD

**Issue by foxy82** [diyhue/diyHue#524]
**Is your feature request related to a problem? Please describe.**

I want to allow my family to use the Hue app to control my Home Assistant lights

**Describe the feature that you would like to be added**

I want diyhue to connect to Home Assistant and control the lights in Home Assistant

**Describe alternatives you've considered**

You can use the Home Assistant web UI instead but it isn't as nice as hue when just working with your lights.

**Describe your use case for this feature**
I use the Hue App to turn on my Zwave light connected to Home Assistant.

**Checklist**
- [x] I confirm that this is a feature request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by foxy82** [comment]
PR here: https://github.com/diyhue/diyHue/pull/523

**Comment by Mevel** [comment]
Merged #523
