### ISSUE TITLE
IKEA Tradfri Remote not recognized from the Hue app

### ISSUE THREAD

**Issue by noisemaker00** [diyhue/diyHue#525]
**Describe the issue**

I tried to add an Ikea Tradfri Remote using RaspBee (v1) but I cannot find it from the Philips Hue app. 

**Steps you tried**

1. Opened Phoscon webapp and paired the remote succesfully
2. Checked into the `config.json` file and seems the hue emulator recognize the remote
3. If I tried to run `HueEmulator.py --debug` and when I press buttons on remote something is recognized by the emulator and show the deCONZ message with sensor state, etc
4. I tried to open the `<hue_emulator_IP>/deconz` page and set-up the switch, but when I click save redirect me to `<hue_emulator_IP>/deconz?7=ZGPSwitch&mode_7=CT` and report page error
5. When I open the Hue app and search for switch, no results

**How we can help**

Any hint is appreciated

**Logs**

These are pieces of my `config.json` about the sensor (I masked some data with ***)
```
"deconz": {
        "enabled": true,
        "lights": {
            "1": {
                "bridgeid": "1",
                "modelid": "TRADFRI bulb E27 WS opal 980lm",
                "type": "Color temperature light"
            }
        },
        "port": 8080,
        "sensors": {
            "1": {
                "bridgeid": "2",
                "modelid": "PHDL00",
                "type": "Daylight"
            },
            "3": {
                "bridgeid": "7",
                "hueType": "ZGPSwitch",
                "modelid": "TRADFRI remote control",
                "type": "ZHASwitch"
            }
        },
        "username": "***",
        "websocketport": 8081
    }
```

```
"sensors": {
        ...
        "7": {
            "config": {
                "battery": 100,
                "on": true,
                "reachable": true
            },
            "manufacturername": "Philips",
            "modelid": "ZGPSWITCH",
            "name": "Tap Switch",
            "state": {
                "buttonevent": 0,
                "lastupdated": "none"
            },
            "swversion": "1.2.214",
            "type": "ZGPSwitch",
            "uniqueid": "***"
        }
    }
```

**Docker Info (please complete the following information):**
 - Hardware (Raspberry Pi Zero) 

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
I think changes to Hue app or Hue API broke the configuration of Hue devices. You have two choices, one is to configure the Tradfri Remote as CT Switch or Scene Switch (these work much better because reflect the remote layout) or use Hue Essentials to configure the emulated Hue Remote. Unfortunatelly will be hard to remove this remote from emulation of the Hue Remote, you need to remove from config.json in sensors => "7" part but also in "deconz => "sensors" root key search for `bridge_id: "7"`

**Comment by noisemaker00** [comment]
I removed the Tradfri Remote from config.json
Then when restarted the HueEmulator.py seems it found the remote again, now is:
```
"deconz": {
        "enabled": true,
        "lights": {
            "1": {
                "bridgeid": "6",
                "modelid": "TRADFRI bulb E27 WS opal 980lm",
                "type": "Color temperature light"
            }
        },
        "port": 8080,
        "sensors": {
            "1": {
                "bridgeid": "7",
                "modelid": "PHDL00",
                "type": "Daylight"
            },
            "2": {
                "bridgeid": "8",
                "modelid": "TRADFRI remote control",
                "type": "ZHASwitch"
            }
        },
        "username": "***",
        "websocketport": 8081
    },
```
and
```
"sensors": {
        ...
        "8": {
            "config": {
                "alert": "none",
                "battery": null,
                "group": "57797",
                "on": true,
                "reachable": true
            },
            "manufacturername": "IKEA of Sweden",
            "modelid": "TRADFRI remote control",
            "name": "TR\u00c5DFRI remote control",
            "state": {
                "buttonevent": 3002,
                "lastupdated": "2020-12-10T19:20:56"
            },
            "swversion": "1.2.214",
            "type": "ZHASwitch",
            "uniqueid": "***"
        }
    }
```

I do nothing else by now. So what are the next step?
The remote works with the lamp due to in Phoscon webapp it has a group that associate them, but I would like to be able to use the remote to control other lights in the Hue app.

**Comment by mariusmotea** [comment]
You don't need to setup any rules in Phoscon. Just import the remote and configure from /Deconz page. When configured from both places there will be a conflict on commands.

**Comment by noisemaker00** [comment]
These are the changes after setup the remote in /deconz page
```
"deconz": {
        "enabled": true,
        "lights": {
            "1": {
                "bridgeid": "6",
                "modelid": "TRADFRI bulb E27 WS opal 980lm",
                "type": "Color temperature light"
            }
        },
        "port": 8080,
        "sensors": {
            "1": {
                "bridgeid": "7",
                "modelid": "PHDL00",
                "type": "Daylight"
            },
            "2": {
                "bridgeid": "8",
                "hueType": "ZLLSwitch",
                "modelid": "TRADFRI remote control",
                "type": "ZHASwitch"
            }
        },
        "username": "***",
        "websocketport": 8081
    },
```
```
sensors : {
   ...
    "8": {
            "config": {
                "alert": "none",
                "battery": 100,
                "group": "57797",
                "on": true,
                "reachable": true
            },
            "manufacturername": "Philips",
            "modelid": "RWL021",
            "name": "Dimmer Switch",
            "state": {
                "buttonevent": 4000,
                "lastupdated": "2020-12-10T20:14:10"
            },
            "swversion": "5.45.1.17846",
            "type": "ZLLSwitch",
            "uniqueid": "***"
        }
    }
```
So it seems to emulate philips Hue Dimmer Switch in the right way, but I still cannot detect the remote in the Hue app.
I'm trying to understand the scan process reading the HueEmulator.py code and the logs

**Comment by rednaxela1111** [comment]
Try seeing if the remotes is visible to the ‘Hue Essentials’ app. This app allowed me to configure my remote, but it is still not visible in the official hue app.

**Comment by mariusmotea** [comment]
Official hue app configure just the original hue devices. The Tradfri remote can be configured from /deconz page of the hue emulator or from Hue Essentials app.
