### ISSUE TITLE
Can't get connection with mqtt broker when running in Docker

### ISSUE THREAD

**Issue by rogiertermeer** [diyhue/diyHue#532]
**Describe the issue**

I'm running diyHue in a docker container on my raspberry pi 4. I would like to use it with mqtt but when I turn on MQTT in the config nothing happends. Whem i'm looking in the config.json I can see the online api is disabled, but in debug mode i can see it starts. So it seems the config.json is not used.

**Steps you tried**

1. Edit the config.json in /opt/hue-emulator/export/
2. restart the docker container.
3. i've checked the the config in /opt/hue-emulator/.
4. the changes are there.

**How we can help**

Can someone help me with changing the config and making it active?

**Logs**

```
2020-12-18 21:52:09,126 - root - INFO - Using Host 10.20.20.1:80
Host MAC given as 3e886b94b65b
2020-12-18 21:52:09,127 - root - INFO - 3e886b94b65b
Docker Setup Initiated
Restoring Certificate
Certificate Restored
Restoring config
Config restored
Docker Setup Complete
2020-12-18 21:52:09,129 - root - INFO - IP range for light discovery: 0-255
2020-12-18 21:52:09,130 - root - INFO - 127.0.0.1
2020-12-18 21:52:09,130 - root - INFO - Online Discovery/Remote API Enabled!
2020-12-18 21:52:09,132 - root - INFO - Config loaded
2020-12-18 21:52:09,145 - root - DEBUG - Connected with result code 0
2020-12-18 21:52:09,146 - root - DEBUG - start ssdp broadcast
2020-12-18 21:52:09,146 - root - DEBUG - starting ssdp...
2020-12-18 21:52:09,149 - root - INFO - sync with lights
2020-12-18 21:52:09,154 - root - INFO - Starting httpd...
2020-12-18 21:52:09,160 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): discovery.diyhue.org:443
2020-12-18 21:52:09,161 - root - INFO - Starting ssl httpd...
10.20.20.253 - - [18/Dec/2020 21:52:09] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:09] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
2020-12-18 21:52:09,339 - urllib3.connectionpool - DEBUG - https://discovery.diyhue.org:443 "POST / HTTP/1.1" 200 6
{"ok"}
10.20.20.253 - - [18/Dec/2020 21:52:09] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:09] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:10] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:10] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:11] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:11] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
2020-12-18 21:52:12,553 - root - DEBUG - Sending M-Search response to 10.20.20.91
10.20.20.253 - - [18/Dec/2020 21:52:12] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:12] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:13] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:13] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:14] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:14] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:15] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:15] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:16] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:16] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:17] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:17] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:18] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:18] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:19] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:19] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
2020-12-18 21:52:20,172 - root - INFO - sync with lights
10.20.20.253 - - [18/Dec/2020 21:52:20] "GET /api/web-ui-29430/groups HTTP/1.1" 200 -
10.20.20.253 - - [18/Dec/2020 21:52:20] "GET /api/web-ui-29430/lights HTTP/1.1" 200 -
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM):  ARM
 - Docker image version (Ex: latest, arm-05f043b, 128):  latest
 - OS (Ex: Windows 10, Ubuntu Buster):  Raspbian
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero):  Raspberry pi 4

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by Mevel** [comment]
`2020-12-18 21:52:09,145 - root - DEBUG - Connected with result code 0`

Is the Debug Output from mqtt protocol when connection is established.

Do you use zigbee2mqtt? do you have the `"discoveryPrefix": "homeassistant",`  in `config.json` set correct?



`
2020-12-18 21:52:09,130 - root - INFO - Online Discovery/Remote API Enabled!`
 
We will work on the wording. I think the output needs to be swapped.

**Comment by rogiertermeer** [comment]
I'm not using zigbee2mqtt. I'm sending my own mqtt message to fake a light. I need some virtual lights in my ABB free@home system witch has an hue integration. 

This is the message i'm sending on topic: diyhue/light/scenetvkijken/light/config

{
    "brightness": false,
    "xy": false,
    "schema": "json",
    "command_topic": "fathscenes/tvkijken/set",
    "state_topic": "fathscenes/tvkijken",
    "json_attributes_topic": "fathscenes/tvkijken",
    "name": "tvkijken",
    "unique_id": "tvkijken_scene_fathscenes",
    "device": {
        "identifiers": [
            "fathscenes_tvkijken"
        ],
        "name": "tvkijken",
        "sw_version": "fathscenes 1.1.1",
        "model": "Virtual Device",
        "manufacturer": "Termeer"
    },
    "availability_topic": "fathscenes/tvkijken/availability"
}

I'm using diyhue as discoveryprefix

**Comment by Mevel** [comment]
Not sure if sw_version, model, and manufacturer need to be set correct to be detected. As the model_id determens the functions of the light.

**Comment by Mevel** [comment]
any success?

**Comment by rogiertermeer** [comment]
Sorry for the late reaction!!

I didn't get it to work. I found out that HomeAssistant olso has an hue emulator in it so I started using that. Because all my Docker containers are on the same host I can't use diyHue next to it.

When if I start using a second docker host in the future I will try to run diyHue on that, because I don't want 2 HomeAssistant instances.

Thank you for your help!!!
