### ISSUE TITLE
Generated SSL certificate valid for 30 days in some cases

### ISSUE THREAD

**Issue by maberle** [diyhue/diyHue#54]
The generated SSL certificate is only valid for 30 days if

* /opt/hue-emulator already exists but no cert.pem is available (first path in easy_install.sh)
* or the bridge is running as docker image

Is that by intention or an bug?

**Comment by mariusmotea** [comment]
This is wired because i fixed this a few months ago. Now i see the days parameter in openssl command is missing again.

**Comment by mariusmotea** [comment]
Fixed

**Comment by maberle** [comment]
Thanks. Whats about genCert.sh, shouldn't that be changed too?

**Comment by mariusmotea** [comment]
For some reason my commit https://github.com/diyhue/diyHue/commit/9412a22161c56c64d569a4f42e0670660aecaa34 was not applied to master repo. I still see the file don't contain -days 3600. It can be a bug in github.

**Comment by mariusmotea** [comment]
Fixed both now with new commits.

**Comment by maberle** [comment]
You applied the change to the wrong openssl line. now the parameter is contained two times in the second call.

**Comment by mariusmotea** [comment]
Correct. I Forget this is two times added in the script.

**Comment by maberle** [comment]
Excellent. Much better since it was a little bit cumbersome to rebuild the cert and do the paring with the client app every 30 days...
