### ISSUE TITLE
Update problems

### ISSUE THREAD

**Issue by Don87** [diyhue/diyHue#547]
**Describe the issue**

After the hue wanted to update the bridge nothing works anymore!?
Can you put the the lightstrip tm1914 in diyhue?

**Steps you tried**

**How we can help**

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - OS (Ex: Windows 10, Ubuntu Buster): raspbian
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero):  3

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by alexyao2015** [comment]
Please fill out the ENTIRE template
