### ISSUE TITLE
Functionality restricted | Update needed

### ISSUE THREAD

**Issue by ma-mod** [diyhue/diyHue#550]
**Describe the issue**

Unfortunately since 2-3 days im getting the error message inside the Hue App that my system needs an update and the functionality is restricted until I'll run it. I have one diyHue VM running on my server and one real Hue Bridge V2.1.
The real hue bridge does not need an update, only if I choose the diyHue "bridge" inside the app.
I've tried to run the update, but unfortunately it didnt help. Any ideas here?

**Steps you tried**

update via **sudo /opt/hue-emulator/check_updates.sh**

**Logs**
> Installing Hue Emulator.
> Existing installation found, performing upgrade.
> Installation completed. Open Hue app and search for bridges.

**Architecture (Ex: x86, ARM): x64 (inside QEMU/KVM VM)**
OS (Ex: Windows 10, Ubuntu Buster): Ubuntu 20.04.1 LTS
Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC/Server X64

**Checklist**

 I confirm that this is a help request
 I confirm that I have completed this template to the best of my ability
Additional context

**Comment by mariusmotea** [comment]
Use Hue Essentials or upgrade manually swversion key of the bridge in config.json file. We don't enable automatic swversion config because it can broke Hue Sync compatibility.
