### ISSUE TITLE
Docker install "/bin/sh: 1: ./coap-client-linux: not found"

### ISSUE THREAD

**Issue by JanneAalto** [diyhue/diyHue#558]
**Describe the issue**

**Steps you tried**

1. Go to /tradfri
2. Enter data for gateway
3. This page isn’t working XXX.XXX.XX.XX didn’t send any data. ERR_EMPTY_RESPONSE

**How we can help**

I can't get lights imported from Trådfri

**Logs**

/bin/sh: 1: ./coap-client-linux: not found

Exception occurred during processing of request from ('XXX.XXX.XX.XX', 59511)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.9/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.9/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.9/http/server.py", line 427, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.9/http/server.py", line 415, in handle_one_request
    method()
  File "/diyhue/webServer/server.py", line 160, in do_GET
    registration = json.loads(check_output(
  File "/usr/local/lib/python3.9/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command './coap-client-linux -m post -u "Client_identity" -k "XXXXXXXXXXXXXXX" -e '{"9090":"Hue-Emulator-375"}' "coaps://XXX.XXX.XX.XX:5684/15011/9063"' returned non-zero exit status 127.

**Docker Info (please complete the following information):**
 - Architecture: ARM 
 - Docker image version: latest 
 - OS: Ubuntu Buster 
 - Hardware: Raspberry Pi 3 

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by alexyao2015** [comment]
This is likely an issue with docker pulling the wrong architecture. Try changing the tag to a manually specified tag for your architecture.

**Comment by JanneAalto** [comment]
Yep, that's it. Thank you.

**Comment by alexyao2015** [comment]
@JanneAalto What tag did you have previously?

**Comment by JanneAalto** [comment]
I had diyhue/core:latest and if I remember correctly the latest experimental and master branches. 

I'm not sure which instance I had running when I took the logs.

**Comment by alexyao2015** [comment]
So with both the latest and experimental, you had issues with it?
