### ISSUE TITLE
Belkin Wemo or general IFTTT support would be great

### ISSUE THREAD

**Issue by eyekey** [diyhue/diyHue#56]
I have a Logitech Harmony remote. 
Sadly, the only devices supported are Philips Hue.
It would be great if diyHue would support "virtual lightbulbs". So you can connect these with on/off with IFTTT (via URL in json file).
This way you can add all kinds of devices...
Please consider this. Thanks.

**Comment by jannekayra** [comment]
One way to achieve this is to implement the diyHue native API in Node-RED.

I did this and now my livingroom 433Mhz Nexa receiver controlled (on/off) downlights are fully integrated to diyHue. Node-RED passes commands received from diyHue and gets light state updates back via MQTT. Light states are kept in a flow context variable in Node-RED and returned to diyHue when it requests them. (Then I have Docker container running another Node-RED instance + modified telldus daemon that acts as a bridge between MQTT and a Tellstick NET flashed with local control enabling FW  but that is another (long) story.. :)

So, with this kind of setup it is possible to integrate any light / device to diyHue that you can control with Node-RED.

There's one problem though that kept me busy for a while: I had to add the new lights to the config file manually. @mariusmotea is there any other way to add a light implementing the native API than manually editing the config file or autodiscovery? Should there be one?

To give you an idea of what is needed:
![image](https://user-images.githubusercontent.com/2945188/50729438-22bf8000-1142-11e9-8b5e-79654bce7ac8.png)

These had to be added manually to config.json:

```json
 "16": {
            "ip": "192.168.111.98:1880",
            "light_nr": "1",
            "mac": "00:17:88:05:04:c9",
            "protocol": "native"
        },
```

```json
 "16": {
            "capabilities": {
                "certified": true,
                "control": {
                    "ct": {
                        "max": 454,
                        "min": 153
                    },
                    "maxlumen": 250,
                    "mindimlevel": 1000
                },
                "streaming": {
                    "proxy": false,
                    "renderer": false
                }
            },
            "config": {
                "archetype": "spotbulb",
                "direction": "downwards",
                "function": "functional"
            },
            "manufacturername": "Philips",
            "modelid": "Bulb 01",
            "name": "Olohuone erkkeri",
            "productid": "Philips-LTW013-1-GU10CTv1",
            "productname": "Hue ambiance spot",
            "state": {
                "alert": "select",
                "bri": 247,
                "bri_inc": 25,
                "colormode": "ct",
                "ct": 260,
                "mode": "homeautomation",
                "on": false,
                "reachable": true
            },
            "swconfigid": "797DDD7C",
            "swupdate": {
                "lastinstall": null,
                "state": "noupdates"
            },
            "swversion": "1.29.0_r21169",
            "type": "Color temperature light",
            "uniqueid": "00:17:88:01:00:e6:c0:90-0b"
        },
```

I guess that most of the stuff in the second part is not needed but I had no idea how it should look for a native light so I just copied that from some other light. Seems to work :)

**Comment by cheesemarathon** [comment]
Hi, Thanks for your suggestion and thanks @jannekayra for the suggested fix with Node-Red! diyHue focuses solely on controlling non Hue lights within the Phillips Hue environment. Adding support for smart plugs and switches, although useful and could be used to control non Hue lights, is not the main focus of this project and will start introducing feature creep. I know we have added support for Hue dimmers and are working on ESP8266 based DIY dimmer switches but that is more to match current Phillips Hue control options. As such, this requested feature won't be implemented. However, if this is still something you're interested in, I suggest you look at (Home Assistant)[https://www.home-assistant.io/]. It does exactly what you want, allows you to connect multiple devices from many different systems to allow them to control each other, amongst some other things!

**Comment by jannekayra** [comment]
Can someone using native lights post their config.json?
