### ISSUE TITLE
Help with ESPHome and WS2812

### ISSUE THREAD

**Issue by andiaa734** [diyhue/diyHue#570]
**Describe the issue**

Can you please provide a working configuration for ESPHome and WS2812?
Sorry, but the Documentation regarding ESPHome is a mess. Nothing is working. I found no Documentation about which platform to use, which name has to be used and where. Even the given Examples are not working.
Light is detected but i'm not able to control it. Using Webinterface of ESP, i can switch on and off the light.
Also there is a bug. A white_led is always required from diyhueasyncudp.

**Steps you tried**

Current configuration:

esphome:
  name: ambilight1
  platform: ESP8266
  board: esp01_1m
  includes:
    - diyhue/AsyncUDP/diyhueasyncudp.h
    - diyhue/alertswitch.h
  libraries:
    - ESPAsyncUDP
  
  on_boot:
   then:
   - light.turn_on:
      id: color_led
      brightness: 50%

custom_component:
- lambda: |-
    auto diyhue = new diyhueudp();
    return {diyhue};

wifi:
  ssid: "MySSID"
  password: "MyPassword"
 
# Enable logging
logger:
# Enable Home Assistant API
api:
ota:

output:
  - platform: esp8266_pwm
    pin: GPIO5
    id: cold_white_gpio
    frequency: 4000 Hz
    inverted: False
    min_power: 0
    max_power: 1

  - platform: esp8266_pwm
    pin: GPIO12
    id: warm_white_gpio
    frequency: 4000 Hz
    inverted: False
    min_power: 0
    max_power: 1

light:

  - platform: fastled_clockless
    chipset: WS2812
    pin: GPIO2
    num_leds: 60
    id: color_led
    rgb_order: GRB
    name: "color_led"
    effects:
      - addressable_rainbow:
      - addressable_scan:
      - addressable_fireworks:
      - addressable_color_wipe:
      - addressable_flicker:
  
  - platform: cwww
    id: white_led
    name: "white_led"
    cold_white: cold_white_gpio
    warm_white: warm_white_gpio
    cold_white_color_temperature: 6500 K
    warm_white_color_temperature: 2000 K
    gamma_correct: 0.8
    default_transition_length: 0.4s

#  - platform: neopixelbus
#    id: color_led
#    type: grb
#    method: ESP8266_UART1

# methods:    
# ESP8266_DMA (default for ESP8266, only on pin GPIO3)
# ESP8266_UART0 (only on pin GPIO1)
# ESP8266_UART1 (only on pin GPIO2)
# ESP8266_ASYNC_UART0 (only on pin GPIO1)
# ESP8266_ASYNC_UART1 (only on pin GPIO2)
# ESP32_I2S_0
# ESP32_I2S_1 (default for ESP32)
# BIT_BANG (can flicker a bit)

 #   variant: ws2812
#    pin: GPIO2
#    num_leds: 60
#    name: "color_led"
#    default_transition_length: 0.5s
#    gamma_correct: 0
#    effects:
#      - random:
#          name: Random Effect With Custom Values
#          transition_length: 5s
#          update_interval: 3s

text_sensor:
  - platform: template
    name: "light_id"
    id: light_id
    lambda: |-
      char response[100];
      memset( response, 0, 100 );
      strcat( response, "esphome_diyhue_light;");
      strcat( response, WiFi.macAddress().c_str());
      strcat( response, ";");
      strcat( response, App.get_name().c_str());
      strcat( response, ";CT_BOOST;RGB_BOOST" ); // ;CT_BOOST;RGB_BOOST values go here; Replace with 0 to disable
      return { response };
    update_interval: 24h
    
switch:
  - platform: custom
    lambda: |-
        auto alertswitch = new alertSwitch();
        App.register_component(alertswitch);
        return {alertswitch};
    switches:
      name: alert
      id: alert
  
  - platform: template
    name: entertainment_switch
    id: entertainment_switch
    optimistic: true

    
web_server:
  port: 80

**How we can help**

Please provide a working config and extend the documentaion.

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128): No Docker, install.sh
 - OS (Ex: Windows 10, Ubuntu Buster): Buster
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): RPi4

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by alexyao2015** [comment]
Yes it is true that it always expects a white led. You can fake one by creating one on gpios not in use or just edit the code to remove it. Look at the fastled integration for help setting up the strip.

**Comment by AlexKusnezov** [comment]
@andiaa734 I actually struggled with that a while ago, so for Ws2812, ws2812b, ws2813 and apa102 I just left the white led and simply edited the config in diyhue to just a **color light** and not extended color light. This takes tje white led out of tje equation
![Screenshot_20210303-084413](https://user-images.githubusercontent.com/33514406/109771398-0bcf2800-7bfd-11eb-86e5-2aaf7f864387.jpg)

**Comment by ryancasler** [comment]
But that means you won't be able to set color temp for those LEDs.  Even if your strip only has RGB LEDs, you can still display CT white lights using the sketches in DIYHue.  The sketch will figure out the correct combination of R,G and B to get the CT you select.  And within the webconfig of the light itself you can apply multipliers to balance the colors if your strip doesn't show up quite with the tones/hues you are expecting.  There's no need to manually configure the light in DIYHue, it should work the way it is.

**Comment by AlexKusnezov** [comment]
@ryancasler exactly that will do it when you set it to color light. If your strip is rgb only it will work with ct, because if its set to extended color light the rgb strip will turn off on ct, since diyhue tries to address the white led, which you don't have. Just try it out

**Comment by ryancasler** [comment]
DIYHue doesn't control the individual pixels in the light.  It simply commands either the CT or the RGB value.  it is up to your sketch to determine how to turn on the individual pixel.  I have many ws2812b strips and they only have RGB leds but work fine in CT mode.  The firmware on the ESP8266 that you load converts the CT value you command into RGB values for your LEDs.  Works just fine.

**Comment by AlexKusnezov** [comment]
@ryancasler can you please share your esphome sketch? By default its recognized by dyhue as a hue lightstrip plus. When I select a ct value the strip shuts of, because its handed over to white led, which is not attached. How to deal with that?

**Comment by ryancasler** [comment]
If you are having a problem with a sketch, you should post in that repo.  If you're having a problem with ESP Home, you should post there.  If it's a problem with a the sketch located in the DIYHue Lights repo, you should post there.
