### ISSUE TITLE
ZLLSwitch (HueDimmerSwitch) requests without button parameter fail with KeyError.

### ISSUE THREAD

**Issue by panovvv** [diyhue/diyHue#578]
**Describe the bug**

I have a custom made ZLLSwitch (HueDimmerSwitch) remote made after [this one](https://github.com/diyhue/Devices/tree/master/HueDimmerSwitch).
When a button is pressed, it usually sends a request similar to this one:
`GET /switch?mac=48:3f:da:4f:c1:24&button=1000`. However, sometimes the request lacks the `button` parameter,
which breaks the handling code in this repo.
Relevant code piece from Arduino sketch for dimmer switch: [here](https://github.com/diyhue/Devices/blob/0c4b655e06570c3771856319abe5adf4278ee38a/HueDimmerSwitch/HueDimmerSwitch.ino#L144)
Traceback in diyHue:
```
----------------------------------------
Exception happened during processing of request from ('192.168.1.95', 62693)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/opt/hue-emulator/HueEmulator3.py", line 1478, in do_GET
    bridge_config["sensors"][sensorId]["state"].update({"buttonevent": int(get_parameters["button"][0]), "lastupdated": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")})
KeyError: 'button'
----------------------------------------
```
I'm not sure which side needs to be fixed - either the remote shouldn't send requests without the button parameter (registering device - what does it mean?) or the handling code needs to take into account button-less requests.

**Steps to Reproduce**

1. Have a ZLLSwitch remote with [this sketch](https://github.com/diyhue/Devices/blob/master/HueDimmerSwitch/HueDimmerSwitch.ino) flashed in it.
2. Smash the buttons repeatedly. Approximate frequency is more than once in 2 seconds.
3. Observe the traceback above.

**Expected behavior**

The request above is either processed or not sent at all

**Logs**

Example of normal button behavior:
```
192.168.1.95 - - [26/Jan/2021 18:32:19] "GET /switch?mac=48:3f:da:4f:c1:24&button=4000 HTTP/1.1" 200 -
127.0.0.1 - - [26/Jan/2021 18:32:19] "PUT /api/32c8a58a54e811eba1599059af62edba/groups/0/action HTTP/1.1" 200 -
```
Example of request w/o button param:
```
192.168.1.95 - - [26/Jan/2021 18:32:20] "GET /switch?devicetype=ZLLSwitch&mac=48:3f:da:4f:c1:24 HTTP/1.1" 200 -
----------------------------------------
Exception happened during processing of request from ('192.168.1.95', 50204)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/opt/hue-emulator/HueEmulator3.py", line 1478, in do_GET
    bridge_config["sensors"][sensorId]["state"].update({"buttonevent": int(get_parameters["button"][0]), "lastupdated": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")})
KeyError: 'button'
----------------------------------------
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): ARM
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Arch linux ARM
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): BeagleBone Black

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
I think this happen only when you press fast a button. The idea behind the schematic was to be as simple as possible (minimal components). Here the buttons have two functions, one is to wake up the esp from deep sleep and second is to pull down the gpio pin related to that button. The issue is that first step mai require 200ms - 400ms, so when you press and release fast a button and the esp boot, there is no gpio pin HIGH to read. This problem is on custom remote side and can be fixed using small caps that will hold the buttons state for longer time. Ror example replace R3 to R6 resistors with 100k values and place  in paralel with every resistor a capacitor (between 100nf - 1uF, this need to be fine tuned).

**Comment by panovvv** [comment]
Looking at the sketch code, this does not depend on the state of button GPIOs:
- Code that gets executed when a button is pressed (URL `/switch?mac=aa:bb:cc&button=123`): https://github.com/diyhue/Devices/blob/0c4b655e06570c3771856319abe5adf4278ee38a/HueDimmerSwitch/HueDimmerSwitch.ino#L76
- Code that get executed to register the remote (note the different parameters in URL: `/switch?devicetype=ZLLSwitch&mac=aa:bb:cc`): https://github.com/diyhue/Devices/blob/0c4b655e06570c3771856319abe5adf4278ee38a/HueDimmerSwitch/HueDimmerSwitch.ino#L140

When ESP wakes up and no button is pressed, it won't send /switch?mac=aa:bb:cc&button=123 requests at all.
However, also upon wakeup event, it will also send the latter request (`/switch?devicetype=ZLLSwitch&mac=aa:bb:cc`) if this condition is true: `if ((*rinfo).reason != REASON_DEEP_SLEEP_AWAKE)`. - no matter if the buttons are pressed or not.
The server receives this request and fails on it, because the processing code wrongly detects `/switch?devicetype=ZLLSwitch&mac=aa:bb:cc` as switch requests instead of register requests.:
https://github.com/diyhue/diyHue/blob/abd04406f1e8470368ad436e5c0b842d4a2d779c/BridgeEmulator/HueEmulator3.py#L1457

**Comment by panovvv** [comment]
I'll try and debug this further locally, but on the surface of it it seems the solution is to remove the second part of this condition:
```
if "devicetype" in get_parameters and get_parameters["mac"][0] not in bridge_config["emulator"]["sensors"]: #register device request
```

**Comment by mariusmotea** [comment]
This condition is correct. If a request with a mac address is not present then it means the device was never registered.

**Comment by panovvv** [comment]
> If a request with a mac address is not present then it means the device was never registered.
Are you saying that the registering the device request will only be processed when the device has already been registered? How does it get registered in the first place? I don't get it.
