### ISSUE TITLE
diyHue Bridge not found with official Hue App

### ISSUE THREAD

**Issue by neoaddix** [diyhue/diyHue#579]
**Describe the issue**
I'm trying to pair the diyHue Bridge with the Hue application but it never succeeds. I have tried multiple different things that were also advised in the documentation and in the github issues. I might be overlooking something but I need some help with figuring this out.

I'm running the software on a raspberry pi using Docker, starting it with the following command:
```
docker run -d --name "diyHue" --network="bridge" -v '/mnt/hue-emulator/export/':'/opt/hue-emulator/export/':'rw' -e 'MAC=dc:a6:32:b6:16:d6' -e 'IP=192.168.1.10' -e "DEBUG=true" -p 81:80/tcp -p 9243:443/tcp -p 1900:1900 -p 2100:2100/udp diyhue/core:latest
```
I can access the software on the configured IP address. I think I also succeeded in importing the lights form my original Hue Bridge once. But pairing the diyHue bridge in the official Hue App is not working 

**Steps you tried**

I have tried the following things
1. Install diyHue, access GUI, import lights from existing bridge, after that try to add the diyHue bridge in the app: sometimes it seems it finds something, but it always ends in nothing found
2. Reinstalled the Hue App and tried again, same
3. Removed docker container and files in /export folder, started new docker container and repeated step 1, same results
4. Reset existing Hue Brige, reinstalled diyHue, reinstalled app, same results it only finds the original Hue Bridge

I once had the situation where the app found 2 hue bridges (I have only 1 original so the second one must have been the diyHue) and when asked to continue setup it just fails to pickup the diyHue (I use the activate button in all situations btw)

**How we can help**

I would like to have some suggestions on what might go wrong in my setup. As mentioned, there were a few times the Hue App seemed to recognise that there was an additional bridge but the setup could never be completed and in my last tries it never finds the diyHue at all.

**Logs**

If needed I can provide logs for specific situation, I did not include anything yet since logs might be large and give less insights without context of user actions

**Docker Info (please complete the following information):**
 - Docker image version diyhue/core:latest
 - Raspberry Pi model 4 8GB
 - The Pi is also running pi-hole and ubiquity unifi controller

**Checklist**
- [X] I confirm that this is a help request
- [X] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by juanesf** [comment]
Can taste with diyhue/core:dev or diyhue/core:arm64-dev

**Comment by Mevel** [comment]
Your port mapping is wrong. Hue app need port 80 and 443. They just don't accept any other port. For more easy config we suggest hue essentials app for ios or Android.

**Comment by neoaddix** [comment]
Ah, perfect, yes that works way better. Thanks for the quick advise!
