### ISSUE TITLE
Hue Essentials and Windows Hue Sync App not connecting after upgrading to latest Docker Container

### ISSUE THREAD

**Issue by gibsonsowas** [diyhue/diyHue#581]
**Describe the bug**

When Connecting the Hue Essentials App to the HUE Emulator it states:
"Unerwartet Antwort der Bridge, Bitte versuchen Sie es später erneut"
"Expected an int but was 104.14 at path $.lights. 25.state.bri"

So it seems there is a type mismatch with the Data the Bridge reports back.

The Original Hue Android App is connecting flawless.

The Hue Sync App on Windows also cant connect to the diyHue Container.

**Steps to Reproduce**

**Expected behavior**

should connect as it does in older Versions
**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): amd64 running as Proxmox Container 
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Android
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Proxmox Hypervisor

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by gibsonsowas** [comment]
The reproduce part got lost. So here it is.
Steps to reproduce the behavior:
1. Go to Hue Essentials App on Android
2. Click on your Bridge Emualtor to connect
3. Push the Virtual Link Button
4. See error

**Comment by Thomas-Vos** [comment]
From the error message of Hue Essentials I can see that light 25 has a `bri` value of `104.14`. This is wrong as it should be an integer like `104`.

Could you share the config of your light with identifier 25? It would also be helpful to share what type of light this is as I think something could be going wrong with converting the bri value.

**Comment by gibsonsowas** [comment]
`"25": {
            "manufacturername": "Tasmota",
            "modelid": "Tasmota",
            "name": "tasmota_E70A02-2562",
            "state": {
                "alert": "none",
                "bri": 104.14,
                "colormode": "xy",
                "effect": "none",
                "hue": 0,
                "on": false,
                "reachable": true,
                "sat": 0,
                "xy": [
                    0.0,
                    0.0
                ]
            },
            "swversion": "1.46.13_r26312",
            "type": "Extended color light",
            "uniqueid": "4a:e0:ad:7f:cf:42-1"
        },`

It is a Tasmota flashed Teckin SB50
You were right, after removing the light the "Hue Essentials" app connected flawlessly. Thanks.

Sadly  the Windows Hue Sync App Problem wasn't fixed.

**Comment by Mevel** [comment]
Tasmota does not fully support entertainment function. It uses basic http update with some frame drop.

Our firmware or esphome support full speed (even slightly faster than original bulbs since it is on wifi)

Regarding sync I reference the following

[https://diyhue.discourse.group/t/setting-up-hue-sync-app-pc-with-diyhue/240](Hue Sync - diyhue)
