### ISSUE TITLE
New LIDL IAN341808 multiple switches 

### ISSUE THREAD

**Issue by aladin2000** [diyhue/diyHue#591]
4. Links
To create a hyperlink, type the [text you want to link](followed by the url in parenthesis)
-->

**Is your feature request related to a problem? Please describe.**

I bought one multiple plug device from LIDL ( IAN 341808)  
As hue app is not able to activate all the sub switches ( only first is detected and registered ) 

**Describe the feature that you would like to be added**

I wondered  if somebody was able to help me in activating such a device for all 3 switch/ON/OFF 

**Describe alternatives you've considered**

As I saw that there were possibility to register ZLLSwitch device with API and Mac adress   but did not succeded to let the device recognised at this moment. do you have a clue ? 

**Describe your use case for this feature**

Checklist**
- [x] I confirm that this is a feature request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

'''
http://dyiHueIP/switch?mac=xx:xx:xx:xx:xx:xx:xx:54-01&devicetype=ZLLSwitch
http://dyiHueIP/switch?mac=xx:xx:xx:xx:xx:xx:xx:54-02&devicetype=ZLLSwitch
http://dyiHueIP/switch?mac=xx:xx:xx:xx:xx:xx:xx:54-03&devicetype=ZLLSwitch
'''

**Comment by mariusmotea** [comment]
You are using the original hue bridge?

**Comment by aladin2000** [comment]
I have one original Hue V1 and I succeeded to register such  a lidl  device but with only the first  sub switch registered. 
So I tried the docker DiyHue to try to register such Lidl  device , but I cannot make it recognised as far as I tried

**Comment by mariusmotea** [comment]
DiyHue is something tottaly different from what you expect. ZigBee network communication is limited to Zigbee devices. DiyHue require 3rd party service for ZigBee communication.

**Comment by aladin2000** [comment]
As I have a Hue V1, then the device should be ok at least for the first plug ?

	"11": {
		"state": {
			"on": true,
			"alert": "select",
			"reachable": true
		},
		"type": "On/Off plug-in unit",
		"name": "On/Off plug 1",
		"modelid": "TS011F",
		"manufacturername": "_TZ3000_vzopcetz",
		"uniqueid": "xx:xx...:54-01",
		"swversion": ""
	}
}

**Comment by mariusmotea** [comment]
Will not work, the Hue Bridge is the master here and he expose just the first plug. Nothing can be done. You need something like ZigBee2MQTT or Deconz.

**Comment by aladin2000** [comment]
ok , thanks 

any clue/hack of V1 is possible to transform it ?

**Comment by mariusmotea** [comment]
You have no controll over this on the original bridge. uniquid field is read only
