### ISSUE TITLE
How to get this work on MacOS Mojave?

### ISSUE THREAD

**Issue by chrisdata** [diyhue/diyHue#6]
Hi, I'm a total newbie and I tried my very best to install but still failed.
Here's my log when I perform: `python3 HueEmultator3.py`

`MacBook-Pro:BridgeEmulator chrischua$ python3 HueEmulator3.py 
  File "/usr/local/bin/ip", line 39
    print 'Executing: %s' % cmd
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Executing: %s' % cmd)?
cat: /sys/class/net//address: No such file or directory
Traceback (most recent call last):
  File "HueEmulator3.py", line 61, in <module>
    dockerMAC = check_output("cat /sys/class/net/$(ip -o addr | grep " + HostIP + " | awk '{print $2}')/address", shell=True).decode('utf-8')[:-1]
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 389, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 481, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'cat /sys/class/net/$(ip -o addr | grep 192.168.0.134 | awk '{print $2}')/address' returned non-zero exit status 1.`

**Comment by mariusmotea** [comment]
Unfortunetly this require some small customization to run in on MacOS. I recommend to run it in docker container or ubuntu machine in virtual box

**Comment by chrisdata** [comment]
OK, I finally get it running succesfully on VirtualBox on Mac with Ubuntu.
Now it able to find the Emulator in Hue iOS app, but asking to press the Link button, I click on the Activate Web UI from diyhue but it nothing happened, what's wrong?

**Comment by mariusmotea** [comment]
Hmm, I hope you connect that Ubuntu VM directly to mac network adapter, because it needs his on mac + ip on your network. Try to wipe hue app data, maybe while you play it cache a certificate that need to be deleted.

**Comment by mariusmotea** [comment]
I forget, be sure you generate the certificate while the network is properly setup because the generated cert is based on mac address of the main interface. So better delete the cert in /opt/hue-emulator/cert.pem, run again the installation script and wipe the hue app data (on iPhone reinstall the app)

**Comment by mariusmotea** [comment]
yes, you may face one issue if hue entertainment broadcast remain on. Keep in mind that only ESP8266 are in realtime sync, for others you may see a 0.5 sec delay

**Comment by chrisdata** [comment]
Thanks, I get it all working now but after I reboot my system it seem failed to connect. Especially the link button things. Any easy solution? I'm actually bought several Yeelight V2 RGB bulbs, and few strip plus arriving tomorrow just to mimic Hue bridge so I can use those awesome Hue third-party app like DJLight etc.

**Comment by mariusmotea** [comment]
Can be multiple reasons, check if something else is listening on the ports used by hue-emulator. Perform the debugging specified in Wiki. Probably you can see what is the issue by executing:
`cd /opt/hue-emulator && sudo ./HueEmulator3.py`. Paste here the error if is not something you can understand.

**Comment by chrisdata** [comment]
I typed the cmd you list above and I get a lot of:
`"GET /api/config HTTP/1.1" 200 -`

I was trying use Ambee app on iOS to find the emu bridge, until it prompt me to press the link button, I press on the web UI "Activate" button but it can't add it, and it go back to the searching stage, why's that?

There's no any app using the port 80.

**Comment by mariusmotea** [comment]
I have no clue what happened but i believe is possible the mac address or something at vm network level changed. Try from you mac (not ubuntu vm) the command `curl https://{vm ip}/api/nouser/config -v -k` . The verbose will show the CN of the certificate. Check if the prefix and suffix is identical with the mac address of the VM. Also check if the ip from the command output json is the one that the vm is currently using.

**Comment by chrisdata** [comment]
I checked with the command curl thing on Mac and it all seem working fine. They both have the same MAC address and correct CN & IP no. (in my case which is 192.168.0.133)  Here's the verbose:

`*   Trying 192.168.0.133...
* TCP_NODELAY set
* Connected to 192.168.0.133 (192.168.0.133) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=NL; O=Philips Hue; CN=080027fffeac5611
*  start date: Dec 12 21:54:59 2018 GMT
*  expire date: Jan 11 21:54:59 2019 GMT
*  issuer: C=NL; O=Philips Hue; CN=080027fffeac5611
*  SSL certificate verify result: unable to get local issuer certificate (20), continuing anyway.
> GET /api/nouser/config HTTP/1.1
> Host: 192.168.0.133
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: nginx 
< Date: Thu, 13 Dec 2018 11:19:44 GMT
< Content-type: application/json
< Content-Length: 227
< 
* Connection #0 to host 192.168.0.133 left intact
{"name":"Philips hue","datastoreversion":70,"swversion":"1809121051","apiversion":"1.24.0","mac":"08:00:27:ac:56:11","bridgeid":"080027FFFEAC5611","factorynew":false,"replacesbridgeid":null,"modelid":"BSB002","starterkitid":""}MacBook-Pro:~ chMacMacMacBooMacBooMacBooMacMacBooMacMacMacMacMacMacMacMacMacMacMacMacMacMacBooMacMacMacMacMacMacMacMacMacMacMacMacBooMacBook-Pro:MacBook-PMacBook-PMacMacBooMacBooMacMacBooMacMacBook-PMacBook-Pro:~ chriMacBook-PMacBooMacBook-PMacBook-Pro:MacMacBook-PMacBooMacBooMacMacMacMacMacMacMacMacMacMac`

Now I able to get my Light DJ app working, but I can't connect with iControlHue app, it used to be fine before, what else can I try?

**Comment by chrisdata** [comment]
Also a newbie question, how to update the repo in Ubuntu? Thanks

**Comment by mariusmotea** [comment]
sudo apt update && sudo apt upgrade. For ios app's i cannot provide too much support because i don't use.

**Comment by chrisdata** [comment]
Sorry I may not say correctly, how to update diyhue repo ? 
I typed the code it seem update Ubuntu itself?

**Comment by cheesemarathon** [comment]
If you used the easy installer, Delete everything in the `/opt/hue-emulator` folder apart from `cert.pem` and the config file. Then re-run the easy install script. If you did a manual install. Delete your existing install, but backup your `cert.pem` and config. Then reinstall following the same steps you used to install it the first time. After that just replace `cert.pem` and the config with your backed up versions. For docker just stop the running container, pull the latest image and then container again with the same command you used to start it the first time.
