### ISSUE TITLE
Pairing with Hue Sync (Windows) not possible

### ISSUE THREAD

**Issue by bonkersGER** [diyhue/diyHue#600]
**Describe the bug**

I am unable to pair the windows Hue Sync programm with my diyHue 

The Programm does find the diyhue bridge and starts a pairing attemp but it wont work.

**Steps to Reproduce**

1. Start Hue Sync
2. Search for bridges
3. Hue Sync tells me to "Push" the Pairning button
4.  Pressing the pairing button in diyhue web interface
5. nothing happens in Hue Sync app

**Expected behavior**

**Logs**

[Pastebin Debuglog](https://pastebin.com/Q3J35yxT)

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): ARM
 - Docker image version (Ex: latest, arm-05f043b, 128): latest 
 - Host install: stable
 - OS (Ex: Windows 10, Ubuntu Buster): Pi OS lite
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry PI 4 4GB

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by Mevel** [comment]
https://diyhue.discourse.group/t/setting-up-hue-sync-app-pc-with-diyhue/240

Have a look over here

**Comment by Mevel** [comment]
can you show us a debug log output? manually start the emulator with `--debug=true` argument

**Comment by Mevel** [comment]
#602 has been added, you mitght want to check again.
The default "delete cert file and try again" was also a fix but now it should also work with already generated certifcate.
