### ISSUE TITLE
diyHue in separated networks / bind to multiple interfaces

### ISSUE THREAD

**Issue by vKnmnn** [diyhue/diyHue#615]
**Is your feature request related to a problem? Please describe.**

Hi Marius,
in my current home network i have two VLAN, where one is the main one for my personal devices and one for IOT devices like the wifi bulbs and such. 
Of course, Hue App discovery processes rely on broadcasting signals which are limited to their own broadcast domain, so if i want my TV and Android app to discover the diyHue bridge, i have to have the diyHue bridge listen on an IP in the main VLAN (the one my phone is in). 
Some of the discovery processes of lights equally rely on broadcast signals, so in order to be able to find the all the lights, the bridge needs to have an IP in the IOT-VLAN.

Currently, i solve this by having two instances run diyhue, one in each VLAN. this, of course, has it’s own limitations:

- after adding new lights, i need to re-import lights from IOT-bridge to main-bridge
- Entertainment-server trying to bind to 127.0.0.1:2101 of one of the bridges won’t start up, because the other bridge has already taken that port (Ambilight+Hue won’t work in some cases. I'll make an issue for later).
- cpu impact rises, because each action on main-bridge has to be relayed to IOT-brige

(I tried to work around the second issue, by changing the Address to 127.0.0.2, which succeeds to launch the server, but in the end doesn’t really work, as i can see with my tv.)

**Describe the feature that you would like to be added**

As to what i'd like to request:
- make diyHue able to bind to multiple interfaces, to serve the hue api there
- make diyHue able to scan the subnets on all interfaces (maybe configurable) to find lights on these subnets
(- make entertainment check, if 127.0.0.1:2101 is already taken and iterate the /8 net to find the next available address, in case some service is already bound to :2101 (may be optional)) see #616 

**Describe alternatives you've considered**

An alternative could be an improvement of a multi-instance-setup of diyhue:
 -  fix entertainment.py to serve both servers or agree on which instance needs to serve
 - make the iot-bridge push the changes in lights to the main bridge (active syncing)

**Describe your use case for this feature**
- Multi-vlan-setups
- syncing hue through broadcast domains (vpn or such?)

**Checklist**
- [x] I confirm that this is a feature request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
Hi,

The complexity of such setup is high, it was never made to be executed with multiple bind interfaces. I think the best is to keep the bridge in the VLAN with you mobile phones and have dedicated access sules to IoT VLAN to be able to control the lights. Also the scanning ip range can be manually specified with `--ip-range` parameter. Most hue apps work only in the same subnet because rely on SSDP to get the device ip.

**Comment by vKnmnn** [comment]
the --ip-range parameter takes a string of the form xxx-xxx, where xxx can be a number between 1 and 254, the latter is bigger than the former.

That means, that i can only limit the ip range in the subnet i'm already in (192.168.1. 100-200), but not extend that range to another subnet (192.168.100.X), or, if i had one subnet spanning a /23, i couldnt set the range to the second half of the subnet.

As such, you workaround could work for non-ssdp discovery, if --ip-range would take a CIDR notation instead of two numbers.

However, most of the issues i have wouldnt be adressed by this. 
Yes, i see that it adds a bit of complexity, but that’s why it is a feature request.
