### ISSUE TITLE
Launching 2nd Instance makes entertainment.py fail

### ISSUE THREAD

**Issue by vKnmnn** [diyhue/diyHue#616]
**Describe the bug**

**Steps to Reproduce**

entertainment.py should iterate over 127.0.0.1/8 and pick the next available IP:2101 to serve its content there.

**Logs**

```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator-things/functions/entertainment.py", line 11, in entertainmentService
    serverSocket.bind(('127.0.0.1', 2101))
OSError: [Errno 98] Address already in use

```

**Docker Info (please complete the following information):**
 - Architecture ARM
 - OS  latest Raspbian
 - Hardware Raspberry Pi 2 

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
In the next major release the entertainment will start listen on port 2101/udp only when the streaming is running. While it will not allow to stream on both instance, i think is very unlikely to use both at the same time.

**Comment by juanesf** [comment]
you can try this line of code.

https://github.com/juanesf/diyHue/blob/dev/BridgeEmulator/functions/entertainment.py#L8
