### ISSUE TITLE
Milight Bulb State seems always to fall back to "Off"

### ISSUE THREAD

**Issue by RudolfAchter** [diyhue/diyHue#639]
**Describe the bug**

The state of Milight Bulbs in my diyhue Installation alway fall back to off.

This is a problem when i use diyhue with OpenHab. OpenHab reads the actual State of the item after command is sent or when using in rules. When state of bulb is reportet as "off" instead of "on" as it should be this leads to problems in my whole setup.

**Steps to Reproduce**

- Switch on one Milight Bulb 
- After a few seconds (5 or so) Milight Bulb falls back to "off"

The same when openhab Uses the api. Openhab Sets Color on a Milight Bulb

```
PUT /api/a8dfee7e7f4d11eba991fdab23c3ce77/lights/8/state HTTP/1.1
...
{"hue":16708,"sat":184,"bri":254,"transitiontime":4}
```

diyhue confirms

```
HTTP/1.1 200 OK
...
[{"success":{"/lights/8/state/hue":16708}},{"success":{"/lights/8/state/sat":184}},{"success":{"/lights/8/state/bri":254}},{"success":{"/lights/8/state/transitiontime":4}}]
```

After some time OpenHab wants state of lights

```
GET /api/a8dfee7e7f4d11eba991fdab23c3ce77/lights HTTP/1.1
...
```

diyhue answers "light 8" is "off" ("on": false), but it should be "on"

```
HTTP/1.1 200 OK

	"8": {
...
		"state": {
			"alert": "select",
			"bri": 254,
			"colormode": "hs",
			"ct": 257,
			"effect": "none",
			"hue": 16708,
			"on": false,
			"reachable": false,
			"sat": 184,
			"transitiontime": 4,
			"xy": [
				0.0,
				0.0
			]
		},
...
	},

```

**Expected behavior**

I would expect the milight bulbs to behave (mostly) the same like Zigbee or Philips Hue Lights i also use (with Hue Bridge and Deconz/Conbee).

When i switch on a light, or i set brightness more than zero i expect the bulb to be "on". Diyhue should save the state of the last sent command to MiLight Bulbs. I know Milight Bulbs themselves do not return their actual state. But instead i would assume they have the state of the last command i sent.
Also DiyHue GROUPS seem to save the state of the last command

**Logs**

[diyhue_reporting_light_off.zip](https://github.com/diyhue/diyHue/files/6566283/diyhue_reporting_light_off.zip)

Here are Pcap Files where i captured Traffic while switching lights. You see diyhue Traffic in 2021-05-30_diyhue.pcap
You can Filter 2021-05-30_diyhue.pcap in Wireshark with these two filters to find information

Here i switched light 8
```
ip.host == 192.168.1.29 and http and (http.request.method == "PUT" and http.request.uri == "/api/a8dfee7e7f4d11eba991fdab23c3ce77/lights/8/state")

ip.host == 192.168.1.29 and http and ((http.request.method == "GET" and http.request.uri == "/api/100c70d6e3d711e9a7640242a4dd37b7/lights") or  http.response_for.uri == "http://diyhue.fritz.box/api/100c70d6e3d711e9a7640242a4dd37b7/lights")
```

For Reference i also attached 2021-05-30_deconz_hue.pcap
You can Filter here like this in Wireshark

on deconz / conbee i switched light 13

```
http.request.method == "PUT" and http.request.uri == "/api/85B28859B4/lights/13/state"

(http.request.method == "GET" and http.request.uri == "/api/85B28859B4/lights") or (http.response_for.uri == "http://192.168.1.68/api/85B28859B4/lights")
```

Here Light 13 is correctly reported as "on"

```
	"13": {
		"colorcapabilities": 0,
		"ctmax": 65279,
		"ctmin": 0,
		"etag": "3f8ff2b1579bde20971c078b145c5337",
		"hascolor": true,
		"lastannounced": "2021-05-30T12:30:58Z",
		"lastseen": "2021-05-30T12:36Z",
		"manufacturername": "innr",
		"modelid": "RS 230 C",
		"name": "EG_Flur_Strahler01",
		"state": {
			"alert": "none",
			"bri": 254,
			"colormode": "hs",
			"ct": 445,
			"effect": "0",
			"hue": 4756,
			"on": true,
			"reachable": true,
			"sat": 208,
			"xy": [
				0.4987,
				0.3168
			]
		},
		"swversion": "2.8",
		"type": "Extended color light",
		"uniqueid": "60:a4:23:ff:fe:b8:7d:4f-01"
```

I also looked at the diyhue Logs while Switching Ligts. It seems the milight bulbs fall back to "on":false when i get the unreachable Warnings.

```
192.168.1.35 - - [30/May/2021 14:06:35] "GET /api/a8dfee7e7f4d11eba991fdab23c3ce77/sensors HTTP/1.1" 200 -
WARNING:root:MiLight rgb_cct 0x0001 is unreachable: 'state'
WARNING:root:MiLight rgb_cct 0x0001 is unreachable: 'state'
WARNING:root:MiLight rgb_cct 0x0001 is unreachable: 'state'
WARNING:root:MiLight rgb_cct 0x0001 is unreachable: 'state'
192.168.1.24 - - [30/May/2021 14:06:35] "GET /api/100c70d6e3d711e9a7640242a4dd37b7/groups HTTP/1.1" 200 -
192.168.1.24 - - [30/May/2021 14:06:35] "GET /api/100c70d6e3d711e9a7640242a4dd37b7/lights HTTP/1.1" 200 -
WARNING:root:MiLight rgb_cct 0x0002 is unreachable: 'state'
WARNING:root:MiLight rgb_cct 0x0003 is unreachable: 'state'
WARNING:root:MiLight rgb_cct 0x0003 is unreachable: 'state'
WARNING:root:MiLight rgb_cct 0x0004 is unreachable: 'state'
WARNING:root:MiLight rgb_cct 0x005 is unreachable: 'state'
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM):  armhf
 - Docker image version (Ex: latest, arm-05f043b, 128): **diyhue/core:latest**
 - OS (Ex: Windows 10, Ubuntu Buster): Ubuntu Focal
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry Pi 4

**Checklist**
- [X] I confirm that this is a bug report
- [X] I confirm that I have completed this template to the best of my ability

**Additional context**

Could it be something with the ESP8266 i use for bridging to milight network?

I use an ESP8266 with this firmware https://github.com/sidoh/esp8266_milight_hub

Do you expect an answer for milight bulb state?
Or does WARNING:root:MiLight rgb_cct 0x0001 is unreachable: 'state' mean there is a connection issue to the esp8266?

**Comment by mariusmotea** [comment]
Can you tell me if the light in hue app is reported as unreachable? Because there is setting to mark unreachable lights as off and want to know if this is the case or something changed in MiLight hub api.

**Comment by RudolfAchter** [comment]
> Can you tell me if the light in hue app is reported as unreachable? Because there is setting to mark unreachable lights as off and want to know if this is the case or something changed in MiLight hub api.

I don't get diyhue working with the original Hue App. But i can connect it to Android Hue Essentials and Android Hue Dynamics. In Hue Essentials it indeed says "not reachable"

**Comment by RudolfAchter** [comment]
I did some network sniffing and searching in your python code (not good in programming, but i can read it).
I think it happens here in **functions/lightRequest.py**

```python
                elif addresses[light]["protocol"] == "milight":
                    light_data = json.loads(sendRequest("http://" + addresses[light]["ip"] + "/gateways/" + addresses[light]["device_id"] + "/" + addresses[light]["mode"] + "/" + str(addresses[light]["group"]), "GET", "{}"))
                    if light_data["state"] == "ON":
                        lights[light]["state"]["on"] = True
                    else:
                        lights[light]["state"]["on"] = False
```

lightRequest.py connects to esp url -> something like this http://esp-milight.fritz.box/gateways/0x0001/rgb_cct/1

its expecting some kind of state. Something like
```
{
  "state":"ON"
  "brightness":100
  "color_temp":100
  "bulb_mode":"color"
}
```

but instead **my esp delivers only this**

```
{"success":true}
```

`light_data["state"]` -> is not found so i think the "else" part is executed `lights[light]["state"]["on"] = False`. And this is regardless of the setting off_if_unreachable  it's not checked against this setting.

Which esp / nodemcu Firmware do you have? I think yours and mine behave differently

My Firmware is shown here

![image](https://user-images.githubusercontent.com/56109433/120234005-53df0480-c257-11eb-9331-e850b0ff0271.png)

**Comment by RudolfAchter** [comment]
I got it working i updated nodemcuv2 Firmware

![image](https://user-images.githubusercontent.com/56109433/120235043-7e31c180-c259-11eb-828e-06928c19dd19.png)

and i had to add some fields in the MQTT settings (im sure "hue" was missing)

![image](https://user-images.githubusercontent.com/56109433/120235227-de286800-c259-11eb-9b3f-e864b1f4059b.png)

Now my light state stays on and reflects the current state.
