### ISSUE TITLE
Hue App does not connect anymore to diyhue since app update

### ISSUE THREAD

**Issue by sascha777** [diyhue/diyHue#642]
**Describe the bug**
I updated my Hue App on IOs (Version 4.0.0 (8227)) and was prompted to update my bridge, too. It is now running on swversion 1945091050. 
Since the (app) update I can't connect anymore to the diyhue bridge. Controlling the origina Hue bridge from the diyhue web interface still works fine.

**Steps to Reproduce**
1. Update IOs app Version 4.0.0 (8227)
2. Try to connect to diyhue bridge

**Expected behavior**
Connection to diyhue bridge from original app is possible.

**Logs**
none

**Docker Info (please complete the following information):**
direct installation

**Checklist**
[x] I confirm that this is a bug report
[x] I confirm that I have completed this template to the best of my ability

**Additional context**
Thank you so much for this really awesome project!

**Comment by mariusmotea** [comment]
Hi, 

This is work in progress. Hue app v4.0 use both the original api and also a new api (with wired structure). This new api was implemented months ago in flask branch but it need to be updated again to work.
