### ISSUE TITLE
Tradfri Styrbar

### ISSUE THREAD

**Issue by Xorfee** [diyhue/diyHue#643]
**Is your feature request related to a problem? Please describe.**

**Describe the feature that you would like to be added**

Tradfri Styrbar Support for Remote Control

**Describe alternatives you've considered**

already have Tradfri remotes but this is very cheap and looking good

**Describe your use case for this feature**

**Checklist**
- [x] I confirm that this is a feature request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
I will add support in mqtt protocol for it when i will fix current issues.
