### ISSUE TITLE
Docker container keeps restarting after a while

### ISSUE THREAD

**Issue by Xorfee** [diyhue/diyHue#644]
**Describe the bug**

Basically I did nothing, woke up in the morning, docker container keeps restarting for no reason.
I had this issue before, and always did a fresh install afterwards, but I am sick of creating routines/behaviours and scenes for almost 50 lamps 

**Steps to Reproduce**

**Expected behavior**

sudo reboot (changed nothing)
docker rm -f diyHue + reinstall (did nothing)
docker stop other container (e.g. deconz homebridge  and then reinstall diyHue changed nothing)

**Logs**

 docker logs 5d9f5b70c89b
Host MAC given as ---------------------- (censored)
Docker Setup Initiated
SSL certificate found
Config file found
Docker Setup Complete
ERROR:root:CRITICAL! Config file was not loaded
Traceback (most recent call last):
  File "/opt/hue-emulator/HueEmulator3.py", line 191, in initialize
    bridge_config = load_config(path)
  File "/opt/hue-emulator/HueEmulator3.py", line 462, in load_config
    return json.load(fp)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): ARM64
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): raspian
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Pi4 1.2 b

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
I think you have a corrupted configuration file. Check the SD card integrity. Config corruption can occur only if the process is stopped when it write on disk the config, or if the disk (sd card on pi) has issues.

**Comment by Xorfee** [comment]
I did a scan, but everything seems to be fine .. Is there any sd card u recommend?

**Comment by mariusmotea** [comment]
you can restore a config made by weekly automatic backup taks to get ride of this issue. I had 2 failed sd cards in my PI in many iears. I know last one was an expensive one, so i think is a matter of luck.

**Comment by Xorfee** [comment]
How do I do this ? I did a fresh install instead of docker I used now host install.. I hope hue api allows backup soon.. no issue at all with homebridge and backups also with deconz

**Comment by brendanssound** [comment]
Exact same symptoms here. Did nothing.. just woke up one day and my diyhue didn't work.. Restarted pi & Reinstalled DiyHue.. No luck. I can see it start for about 2 seconds before it runs into a reboot loop using ssh

I also have home assistant installed with it might be worth mentioning is not having any such issues

**Comment by Xorfee** [comment]
Exactly this happened for me several times .. deconz and Homebridge working flawlessly.

but also not only in docker also when I install DiyHue as host . Just wondering if it is related with my sd card . Bought now 32 gig of SanDisk extreme pro .. and my pi was supplied by my router via usb, changed that to a 5v 3a supply .. been looking forward if this happens again after a few months 


> Exact same symptoms here. Did nothing.. just woke up one day and my diyhue didn't work.. Restarted pi & Reinstalled DiyHue.. No luck. I can see it start for about 2 seconds before it runs into a reboot loop using ssh
> 
> I also have home assistant installed with it might be worth mentioning is not having any such issues

**Comment by brendanssound** [comment]
Decided to delete my config file before I went down the new SD card install (id already purchased over the weekend) and found removing the config file (stop container, delete config, remove container) and fresh install did in fact work for me. I have to set everything back up and i still have no idea why my configuration got corrupted but it was not SD card related for me it seems

**Comment by Mevel** [comment]
success on this topic or does it need further investigation?

**Comment by brendanssound** [comment]
id say your safe to close this one. But I'm not the OP
