### ISSUE TITLE
Error connecting to Hue emulator after upgrading to home assistant 2021.6.0

### ISSUE THREAD

**Issue by obelix05** [diyhue/diyHue#645]
**Describe the bug**
After upgrading to 2021.6.0, the Hue integration for diyHue no longer works. It still works for the Hue Bridge v2. I've created a bug ticket in home assistant repo. The answer is that there is a problem with diyHue

**Steps to Reproduce**
1. Install Home assistant 2021.5.5
2. create integration Philips Hue with diyHue
3. update home assistant to 2021.6.*

**Expected behavior**
diyHue should act like a official Hue bridge and should work with home assistant too

**Logs**
```
192.168.178.124 - - [08/Jun/2021 08:27:16] "POST /api/ HTTP/1.1" 200 -
2021-06-08 08:27:16,210 - root - INFO - in post method
2021-06-08 08:27:16,211 - root - INFO - /api/
2021-06-08 08:27:16,211 - root - INFO - b'{"devicetype": "home-assistant#home"}'
192.168.178.42 - - [08/Jun/2021 08:27:18] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -
192.168.178.124 - - [08/Jun/2021 08:27:20] "POST /api/ HTTP/1.1" 200 -
2021-06-08 08:27:20,101 - root - INFO - in post method
2021-06-08 08:27:20,102 - root - INFO - /api/
2021-06-08 08:27:20,102 - root - INFO - b'{"devicetype": "home-assistant#home"}'
2021-06-08 08:27:20,103 - root - INFO - [
    {
        "success": {
            "username": "**********"


}
    }
]
192.168.178.124 - - [08/Jun/2021 08:27:20] "GET /api/**********/ HTTP/1.1" 200 -
192.168.178.124 - - [08/Jun/2021 08:27:20] "GET /clip/v2/resource HTTP/1.1" 200 -
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): amd64
 - Docker image version (Ex: latest, arm-05f043b, 128): latest, sha256:e22b1b47db67a023cd35290da35f974f0628d6e189a567f279d6412c0324eec2, created: 2021-06-01 19:17:57
 - OS (Ex: Windows 10, Ubuntu Buster): Linux
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Intel NUC 6

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**
[Home Assistant Issue #51611](https://github.com/home-assistant/core/issues/51611)

**Comment by Mevel** [comment]
success on this topic?

**Comment by jimmyeao** [comment]
no

**Comment by obelix05** [comment]
The issue is still there. Remove stale label

**Comment by mariusmotea** [comment]
I will take a look on this next days. The request `GET /clip/v2/resource ` show it use the new API and i hope you test with beta docker image where the new api is implemented.

**Comment by mariusmotea** [comment]
Please pull last beta docker image and try to pair. If fail please look in diyhue container logs and check it there was an error generated. On my first try the pair fail because of arch key error for Gradient Strip. I fix this and the pair was successfully.

**Comment by obelix05** [comment]
ok. for me the latest beta-version is working fine. Thanks @mariusmotea
