### ISSUE TITLE
How to remove diyHue

### ISSUE THREAD

**Issue by Furiousz23** [diyhue/diyHue#65]
Today i tried to install diyHue with the Automatic install. I got the message that another instance was using port 443 (this is my Domoticz). I stopped Domoticz and tried the automatic install again. This worked, got the diyHue running. But when i started Domoticz again the Hue app didnt connect to the brigde again. Also tried to connect the bridge again in the app but now it doenst connect anymore.

What i tried till now: cleared the Hue app chache, removed the cert.pem and started the automatic install again. Without result.

Can you help me to fix this? I would really love to control my Yeelights with my Harmony Elite :)

I`m using port 443 for Domoticz and Controlicz.

This is the output of command `curl https://127.0.0.1/api/nouser/config -k -v` 

```
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.2 (OUT), TLS header, Certificate Status (22):
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES256-GCM-SHA384
* ALPN, server did not agree to a protocol
* Server certificate:
*  subject: C=NL; ST=MyState; O=Domoticz; L=Domoticz; CN=*.domoticz.com; OU=Unit                                                                                                             51; emailAddress=your@email.com
*  start date: May 23 06:49:02 2015 GMT
*  expire date: May 20 06:49:02 2025 GMT
*  issuer: C=NL; ST=MyState; O=Domoticz; L=Domoticz; CN=*.domoticz.com; OU=Unit5                                                                                                             1; emailAddress=your@email.com
*  SSL certificate verify result: self signed certificate (18), continuing anywa                                                                                                             y.
> GET /api/nouser/config HTTP/1.1
> Host: 127.0.0.1
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Length: 85
< Content-Type: text/html;charset=UTF-8
< Last-Modified: Sun, 13 Jan 2019 20:31:06 GMT
<
* Curl_http_done: called premature == 0
* Connection #0 to host 127.0.0.1 left intact
<html><head><title>Not Found</title></head><body><h1>404 Not Found</h1></body></
```

**Comment by mariusmotea** [comment]
At the moment when you perform this curl command the domoticz was the application that listen on https port.
> subject: C=NL; ST=MyState; O=Domoticz; L=Domoticz; CN=*.domoticz.com; OU=Unit

**Comment by Furiousz23** [comment]
Ok, but how to solve the issue?

**Comment by mariusmotea** [comment]
deploy on different device or remove Domoticz, wipe hue app before just to be sure there is no cached certificate somewhere

**Comment by cheesemarathon** [comment]
Have the answers solved your issue @Furiousz23 ? Can this be closed?

**Comment by Furiousz23** [comment]
Not solved, but I understand off course! Is there a way to uninstall all of the installed software from diyHue?

**Comment by cheesemarathon** [comment]
Yes but there are several steps. I'll write a script now to make it a bit easier!

**Comment by cheesemarathon** [comment]
Run this:
```
curl -s https://raw.githubusercontent.com/diyhue/diyHue/master/BridgeEmulator/easy_uninstall.sh | sudo bash /dev/stdin
```

This will stop diyHue, uninstall the required astral python library, remove the diyHue files and remove the diyHue service. It leaves all installed packages in place in case they are used by other services. These are:

- unzip
- nmap
- python3
- python3-requests
- python3-ws4py
- python3-setuptools

Remove these at your own discretion

**Comment by Furiousz23** [comment]
Ok, thanx. Thinking about buying another RPi to run the diyHue (and some other stuff). That for the help
