### ISSUE TITLE
Problem pairing deconz with the diyHue beta branch

### ISSUE THREAD

**Issue by arneeichhorn** [diyhue/diyHue#659]
**Describe the issue**

I'm not sure whether this is a help request or bug report, because it is about the beta version.
My iDevices updated automatically to Hue 4 app, so im forced to use the beta branch but I can't get it to work.

My ZigBee Lights, switches and sensors are connected to Deconz/Phoscon via ConBee.

I tried to connect diyHue to deconz. Pairing is working fine. But no Lights are appearing.

Instead the following log output is displayed in docker logs.

**Steps you tried**

1. pulled latest image version: docker pull diyhue/core:beta
2. Started diyHue: docker run -d --name diyHueBeta --restart=unless-stopped --network=host -e MAC=b8:27:eb:4c:a6:aa -v /mnt/hue-emulator-beta/config:/opt/hue-emulator/config diyhue/core:beta
3. Went to Phoscon Web UI and enabled Pairing Mode
4. Went to diyHue Web UI Deconz put in IP address and Port, clicked Pair, Deconz User Appears.
5. Restarted docker container: docker restart diyHueBeta
6. Watched Log output: docker logs -f diyHueBeta

**How we can help**

Is this a known issue, or am I doing something wrong?
Currently im totally screwed, my whole light setup was based on diyHue and now I have nearly no possibility to control my lights anymore. The Hue Essentials app seems like no option to me, the user experience is not very good according to my opinion.

**Logs**

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/services/deconz.py", line 76, in websocketClient
    scanDeconz()
  File "/opt/hue-emulator/services/deconz.py", line 58, in scanDeconz
    if deconz_sensors[sensor]["type"] == "ZHALightLevel":
TypeError: unhashable type: 'dict'
```

```
2021-07-04 22:03:24,001 - lights.protocols.deconz - INFO - Error connecting to Deconz: can only concatenate str (not "int") to str
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): ARMv7
 - Docker image version (Ex: latest, arm-05f043b, 128): beta
 - OS (Ex: Windows 10, Ubuntu Buster): raspbian buster 10.8
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Raspberry Pi 3 Model B

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
Hi,

Are you able to provide me the output from deconz? The error is wired, i want to be sure that Deconz output is correct.

**Comment by arneeichhorn** [comment]
@mariusmotea how can I get the output from deconz?
docker logs -f deconz seems to have a too low log level?

**Comment by mariusmotea** [comment]
In the web interface where you insert the Deconz ip for pair must have now the username hash. Use curl or access in the browser:

http://{DECONZ_IP}/api/{USERNAME}

**Comment by arneeichhorn** [comment]
@mariusmotea Do I have to hide some information in this output like Mac addresses and device addresses or stuff, or is it only nonsensitive data?

**Comment by mariusmotea** [comment]
if you want truncate these, i don't need them anyway to debug this problem.

**Comment by arneeichhorn** [comment]
@mariusmotea 
https://pastebin.com/TXCKJWGq
don't know what these numbers like etag and uniqueids are for, but Xed them out.

**Comment by mariusmotea** [comment]
Ok, found the issue, I push an update, you can monitor image build process here:

https://github.com/diyhue/diyHue/actions/runs/1000333547

**Comment by arneeichhorn** [comment]
@mariusmotea 

now I get the following output after container startup:

```
2021-07-05 09:03:10,158 - services.deconz - INFO - register new Xiaomi motion sensor
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/services/deconz.py", line 76, in websocketClient
    scanDeconz()
  File "/opt/hue-emulator/services/deconz.py", line 52, in scanDeconz
    if not getObject("sensors", id):
  File "/opt/hue-emulator/services/deconz.py", line 26, in getObject
    if device.protocol == "deconz" and device.protocol_cfg["deconzId"] == id:
KeyError: 'deconzId'
```

When running search for lights in the web ui I still get:

```
2021-07-05 09:03:43,551 - lights.protocols.deconz - INFO - Error connecting to Deconz: can only concatenate str (not "int") to str
```

**Comment by mariusmotea** [comment]
So there is a deconz sensor with no `deconzId` key in protocol_cfg. Reading the code i found that emulated temperature sensor of the motion sensor lack this. I will push a commit to ensure that new sernsors will be added with `deconzId: "none"`. For you is better to fix this in configuration. Search in sensors.yaml for `protocol: deconz` and there you see protocol_cfg without deconzId key append `deconzId: none`. Save config and restart the service.

**Comment by arneeichhorn** [comment]
@mariusmotea 

in my sensors.yaml I only have this one entry:

```
'1':
  name: Daylight
  id_v1: '1'
  id_v2: c11cc5af-4986-490d-8acd-de22f79f4ecb
  state:
    daylight: null
    lastupdated: none
  config:
    'on': true
    configured: false
    sunriseoffset: 30
    sunsetoffset: -30
    reachable: true
  type: Daylight
  modelid: PHDL00
  manufacturername: Signify Netherlands B.V.
  uniqueid: null
  swversion: '1.0'
  protocol: none
  protocol_cfg: {}
```

**Comment by mariusmotea** [comment]
In this case monitor the image build process and try again:

https://github.com/diyhue/diyHue/actions/runs/1000403473

**Comment by arneeichhorn** [comment]
@mariusmotea 

first thank you for your quick help! I really appreciate it! :)

now I get following when starting the container:

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/hue-emulator/services/deconz.py", line 76, in websocketClient
    scanDeconz()
  File "/opt/hue-emulator/services/deconz.py", line 60, in scanDeconz
    lightSensor = {"name": "Hue ambient light " + name[:14], "id_v1": new_sensor_id, "protocol": "deconz", "modelid": "SML001", "type": "ZLLLightLevel", "protocol_cfg": {"deconzId": id}, "uniqueid": "00:17:88:01:02:" + sensor["uniqueid"][12:]}
NameError: name 'name' is not defined
```

and following on search new lights:

```
2021-07-05 10:19:21,516 - lights.protocols.deconz - INFO - Error connecting to Deconz: can only concatenate str (not "int") to str
```

**Comment by mariusmotea** [comment]
Give me 30 minutes to return to my PC. You can also join Slack channel for a more interactive debugging

**Comment by Schnux** [comment]
Hey,
I don't know if that helps, but I found out that in the deconz.py (under BridgeEmulator/lights/protocols/) the time library for the sleep function (line 26) is not imported. Also in line 38 the string cannot be concatenated, because the values, like the ip-address or the port, from the config get handled like a int

**Comment by mariusmotea** [comment]
Thanks, i will check these also

**Comment by arneeichhorn** [comment]
Problem is now fixed in current beta branch :)
