### ISSUE TITLE
Hue App asks to update the bridge.

### ISSUE THREAD

**Issue by nicrieser** [diyhue/diyHue#663]
**Describe the issue**

**Steps you tried**

**How we can help**

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): x86-64
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Ubuntu Server
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC

**Checklist**
- [x ] I confirm that this is a help request
- [x ] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
You need to manually update swversion key in config.json
