### ISSUE TITLE
WLED devices not discovered

### ISSUE THREAD

**Issue by muhackl** [diyhue/diyHue#665]
**Describe the issue**
Just 2 of 9 active WLED devices discovered in Hue Essentials App.

**Steps you tried**
1. Connect diyhue emulator to Hue Essentials App (working)
2. Search for lamps
3. 2 WLED devices are discovered and can be controlled
4. 7 other WLED devices are not discovered, although they are active in the network and can be found and controlled via the WLED app
5. Restart diyhue emulator
6. Search again for lamps - no success
7. Install WLED on another device (ESP32 WEMOS Lolin D32) and repeat step 5 and 6 - no success

**How we can help**
What else can I try/debug to get to know why the app / diyhue does not find my devices?

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): x86
 - Docker image version (Ex: latest, arm-05f043b, 128): Host automatic install, no Docker install
 - OS (Ex: Windows 10, Ubuntu Buster): Ubuntu 20.04
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC

**Checklist**
- [X] I confirm that this is a help request
- [X] I confirm that I have completed this template to the best of my ability

**Additional context**
First I thought, the app / diyhue just discovers devices of the type ESP32 WEMOS Lolin D32, because the 2 discovered ones where those. The other 7 devices are 8266 WEMOS D1 mini. But when I added another Lolin D32, it was not discovered either. I also checked the settings of WLED but they all resemble. I also tried to use the connect to hue bridge feature in the WLED interface but with no luck.

**Comment by mariusmotea** [comment]
Try to ping the WLED devices during light search. This way i expect them to respond faster. There is no reason why other 7 where not detected except the network latency. Probably WLED app wait longer for reply.
