### ISSUE TITLE
WLED devices not discovered properly

### ISSUE THREAD

**Issue by muhackl** [diyhue/diyHue#666]
**Describe the issue**

Just 2 of 9 active WLED devices discovered in Hue Essentials App.

**Steps you tried**

1. Connect diyhue emulator to Hue Essentials App (working)
2. Search for lamps
3. 2 WLED devices are discovered and can be controlled
4. 7 other WLED devices are not discovered, although they are active in the network and can be found and controlled via the WLED app
5. Restart diyhue emulator
6. Search again for lamps - no success
7. Install WLED on another device (ESP32 WEMOS Lolin D32) and repeat step 5 and 6 - no success

**How we can help**

What else can I try/debug to get to know why the app / diyhue does not find my devices?

**Logs**

No Logs available.

**Docker Info (please complete the following information):**
- Architecture (Ex: x86, ARM): x86
- Docker image version (Ex: latest, arm-05f043b, 128): Host automatic install, no Docker install
- OS (Ex: Windows 10, Ubuntu Buster): Ubuntu 20.04
- Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

First I thought, the app / diyhue just discovers devices of the type ESP32 WEMOS Lolin D32, because the 2 discovered ones where those. The other 7 devices are 8266 WEMOS D1 mini. But when I added another Lolin D32, it was not discovered either. I also checked the settings of WLED but they all resemble. I also tried to use the connect to hue bridge feature in the WLED interface but with no luck.

**Comment by muhackl** [comment]
Additional tries:
- Remove light in app, that was previously found and try to find again: Failed.
- Remove all lights and remove bridge/diyhue emulator in app. Add bridge again. Worked.
- Try to find lights again: Failed at first. 
- When I try to "search lamps" in the app, there is an error message, that sais approximately (translated from German): "Connection failed. Bridge is not reachable. Please check your internet connection." Although, the diyhue server and the Smartphone with the app is connected propery to Wifi and Internet.
- After that, the two former lights are found again. But still no other lights.
- When I ping a lamp that is not discoverable in the app while searching for new lamps, this unfortunately does not help either. Hoping, the app would not wait long enough for responding devices.

**Comment by juanesf** [comment]
The wled version are the same on all boards?

**Comment by muhackl** [comment]
Yes. All the same version.

**Comment by muhackl** [comment]
Today I set up another ESP32 Wemos Lolin D32 freshly with WLED 0.12.0. It was discovered perfectly - and now there are three lights detected by diyhue and you can see a pattern. Only the ESP32s are discovered. No 8266. 
I even set up a brand new 8266 D1 Mini - even used the latest Beta of WLED. But no chance. 
What is the difference? Is it hardware-related or is there something else in the code?

**Comment by juanesf** [comment]
How strange I have two esp8266 (we are d1 mini and nodemcu) both with wled and no problems. I am going to install diyhue on an x86 server with the host script and see if I find any problems. which branch did you use in the script? (master, dev, beta)

**Comment by muhackl** [comment]
Really strange. I used master and also tried beta. Dev did not work to start. I also tried to install it on a Raspberry Pi with Raspberry Os lite but no branch worked/ diyhue would not start. So I used Ubuntu Server on the Pi (3b) - diyhue worked. But also the 8266 D1 could not be discovered. What system do you use? I could try this as well.

**Comment by juanesf** [comment]
I have been reviewing the installation of the script and in the beta branch it fails due to the change in the folder structure. the only thing I can do is create a script to install the beta branch. or someone with more experience than me can correct the main script with the new folder structure in beta.

There are changes in the beta branch for wled that is not in dev or master, therefore I recommend that you use docker which has no problems.

@mariusmotea

**Comment by mariusmotea** [comment]
@juanesf the install.sh script will be changed to copy also the new folder structure. Hope to do it tomorrow.

**Comment by muhackl** [comment]
Thanks! I also tried docker (normal and bridge mode) on the same PC (Ubuntu 21.04) machine like the host install. Latest docker version of course. Both worked as far as Hue Essentials was able to find the bridge and finde the "usual suspects" - the three ESP32 WLED devices - but not the 8266 ones. 
What Raspberry Pi constellation do you recommend (Raspberry Pi 3 or 4? Raspberry OS full? Docker or Host install=) whare you are able to find the 8266?

**Comment by muhackl** [comment]
Now it's getting weird. Somehow, network issues seem to cause the trouble. I disconnected a repeater in my house and just left over the access point (Fritz Box). Suddenly, two further devices were found. All 8266s! NIce so far. But why won't the others be discoverable? One discovered device is in the same room as the diyhue server. One is even an another level of the house. Two further ones are in the same room then the server and are not discovered, even if I reboot them. I don't get it.

**Comment by mariusmotea** [comment]
for every protocol is required a time to discover or probe the lights ip. I still believe WLED  discovery with current timeout work fine if the network latency is below average. This protocol is scanned by default so every second will be added to total discovery time.

**Comment by AlexKusnezov** [comment]
Hey guys same here. Two of my ESP32 were discovered cerrectly, they are also connected to a repeater. One of the ESP8266, which is connected directly to the router was also discovered. However, the other five ESP8266, wich are connected through repeaters are not discovered. Can I add them somehow manually to the config.json?

**Comment by mariusmotea** [comment]
Better try to increase this value: 
https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/protocols/wled.py#L34

Now it wait 2 seconds. Maybe if you put  5 seconds it will detect all.

**Comment by AlexKusnezov** [comment]
@mariusmotea thanks, do you know how to adjust those when using the docker version?

**Comment by mariusmotea** [comment]
enter in the container with `docker exec -it diyHue bash` (hope the container name is diyHue), then `apt update && apt install nano`. Now with nano edit any file you want. At the end restart the container for the changes to take effect. Please tell me the minimum value you found to be working.

**Comment by AlexKusnezov** [comment]
@mariusmotea when I make the changes ``` sleep(2)``` -> ``` sleep(5)``` it won't stick after I restart the container

**Comment by mariusmotea** [comment]
maybe we need to switch to http based detection like all others http lights. I need to find a http path where WLED show some info to be sure is a WLED strip.

**Comment by mariusmotea** [comment]
Any idea what will be a similar http path on WLED with `/detect` used by our firmware?

**Comment by LPRM** [comment]
I have the same problem stated above. 
2 x ESP8266 running WLED 0.12.0 and diyHue running on a docker container. Hue app can't find any of the wled lights. 
I also tried to increase the sleep time up to 30 seconds with no success.
Is there a way to manually add the lights to diyHue?

**Comment by LPRM** [comment]
I tried to manually add one of the lights with success with the following lines:

lights inside emulator:
`"lights": {
            "0": {
                "name": "WLED-SOFA"
            }
        },`

lights after groups:
`"lights": {"0": {"state": {"on": 0, "bri": 200, "hue": 0, "sat": 0, "xy": [0.0, 0.0], "ct": 461, "alert": "none", "mode": "homeautomation", "effect": "none", "colormode": "ct", "reachable": 1},"type": "Extended color light", "name": "WLED-SOFA", "uniqueid": "4a:e0:ad:7f:cf:01", "modelid": "LCT015", "manufacturername": "Philips", "swversion": "1.46.13_r26312"}},
    "lights_address": {"0": {"ip": "192.168.1.90", "mdns_name": "WLED-SOFA", "protocol": "wled", "backlight": 0, "ledCount": 209, "name": "WLED-SOFA"}},`

I can now see it in diyHue, the only problem is that Bridge+Hue functions do not work, Checking the logs this appears: "entertain-srv: no process found". Maybe its something with my hardcoded configs.

**Comment by muhackl** [comment]
I am back to the original problem in the meanwhile. I set up DiyHUE again on a Raspberry PI 3 (host automatic install).
I installed DeCONZ and a ConBEE II USB Stick (deconz works really fine together with diyhue and Hue Essentials app).
BUT: Again not all WLED devices are discovered. This time, I can even see less pattern than the last time. It discovers some 8266s and a ESP32. But other 8266 and ESP32 are not discovered. I removed the repeater - what does not change a thing.
I set the sleep time in wled.py to 30 seconds. Did not help.
When I want to add a device "lamp" in Hue Essentials and press "Search for Lamps" ("Nach Lampen suchen" German version), I get the error message "Verbindungsaufbau fehlgeschlagen. Die Bridge ist nicht erreichbar. Bitte überprüfen Sie ihre Internetverbindung." (Translated: Connection failed. Bridge not reachable. Please check your internet connection.). But the bridge IS perfectly reachable and connected. I totally don't get it. Btw. same error message in iOS and Android app.
I'm out of ideas.

**Comment by AlexKusnezov** [comment]
@muhackl I think for now the way to get all wled into your config is doing it manually like @LPRM described above. I did this too with all my 8 wled devices

**Comment by muhackl** [comment]
@AlexKusnezov oh damn. Am I right when I assume I have to do this in the config.json file?
Does anybody know what causes this error message? It should not appear at all.

**Comment by AlexKusnezov** [comment]
@muhackl 
>Am I right when I assume I have to do this in the config.json file?

Yes

>Does anybody know what causes this error message? It should not appear at all.

Not sure, you could run diyhue in debug. I could be not related to wled.

Grüße aus Deutschland;)

**Comment by muhackl** [comment]
@AlexKusnezov Allright, I'll try that - though it's everything else than convenient.

Grüße zurück ;-)
