### ISSUE TITLE
Bridge Not found on 2.4GHz - Found on 5GHz - Need 2.4GHz for ESP8266 lights

### ISSUE THREAD

**Issue by charlescbullock** [diyhue/diyHue#67]
**Describe the bug**
Hello!

So, I have gotten the app to recognize the Raspberry Pi 3 b+ as a Hue Bridge!
But only when running the Pi on my 5GHz WiFi band.
I cannot get it to recognize the Pi when using 2.4GHz. 

I would assume I need to use the 2.4GHz band to control ESP8266 chips, as they utilize 2.4GHz. 

Anyways - I had originally installed the application when on the 5GHz band. 
Could that be the issue?

I have tried manually searching for the IP Address, with no luck as well.
On the 5GHz band, it automatically found the pi and recognized it as a Bridge.

I tried to run the log retrieval in terminal: 
"
      **Logs**
      If applicable, provide output logs. These can be obtained via manually running HueEmulator3.py with 
      `python3 HueEmulator3.py`.
"
And this is what I got: 
"
python3: can't open file 'HueEmulator3.py': [Errno 2] No such file or directory
"

Thanks for any help!!

**Comment by mariusmotea** [comment]
You should use wired connection on you pi, otherwise you can have lot of issues because of poor wifi implementation on raspberry.
