### ISSUE TITLE
Installer seems not to work with Beta Branch

### ISSUE THREAD

**Issue by bluenazgul** [diyhue/diyHue#673]
**Describe the bug**
Installer seems not to work with Beta Branch

**Steps to Reproduce**

**Expected behavior**
Installer should run without erros

**Logs**

**Docker Info (please complete the following information):**
 - Architecture x86: 
 - OS: Proxmox - CT: Debain 10
 - Hardware: Dell 7010 

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

![image](https://user-images.githubusercontent.com/171537/127992203-b0248102-89ee-43f3-b3ec-ccca1d695097.png)

**Comment by mariusmotea** [comment]
Hi,

I made a commit in order to fix this.

https://github.com/diyhue/diyHue/commit/920ba369de5145294c0220c7390f54347bd1d6ff

**Comment by bluenazgul** [comment]
thanks, but still seems not to work,

i grabed the raw file from your commit using wget and run it

![image](https://user-images.githubusercontent.com/171537/128041865-f44cd99d-c1fd-4e91-8bad-24cfa11edf03.png)

still getting the same error

**Comment by bluenazgul** [comment]
Thanks, installations seems to work with this file now

but even after restart the maschine i get an error using
`sudo systemctl status hue-emulator.service`

![image](https://user-images.githubusercontent.com/171537/128042860-2133d922-2fdc-47e4-87bc-da68f05aea47.png)

**Comment by mariusmotea** [comment]
What distro are you using? I test it again and for me it works.

```creating 'dist/zeroconf-0.28.6-py3.8.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing zeroconf-0.28.6-py3.8.egg
removing '/usr/local/lib/python3.8/dist-packages/zeroconf-0.28.6-py3.8.egg' (and everything under it)
creating /usr/local/lib/python3.8/dist-packages/zeroconf-0.28.6-py3.8.egg
Extracting zeroconf-0.28.6-py3.8.egg to /usr/local/lib/python3.8/dist-packages
zeroconf 0.28.6 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.8/dist-packages/zeroconf-0.28.6-py3.8.egg
Processing dependencies for zeroconf==0.28.6
Searching for ifaddr==0.1.7
Best match: ifaddr 0.1.7
Adding ifaddr 0.1.7 to easy-install.pth file

Using /usr/local/lib/python3.8/dist-packages
Finished processing dependencies for zeroconf==0.28.6
 Installing Hue Emulator.
ens18
Generating certificat for MAC 00:17:88:29:85:2e
If this is a diyhue reinstallation process then you will need to reinstall official Hue apps from PC and phone in order to wipe old certificate.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   671  100   671    0     0   2282      0 --:--:-- --:--:-- --:--:--  2282
Generating an EC private key
writing new private key to 'private.key'
-----
 Installation completed. Open Hue app and search for bridges.
marius@kde-neon:~/diyHue/BridgeEmulator$ 
```

**Comment by bluenazgul** [comment]
Iam running Debian 10 as this should be identical to raspbian as iam running it on proxmox

I get the Same install Result then you, only having the Screenshot issue dedicated to
`sudo systemctl status hue-emulator.service.`

**Comment by mariusmotea** [comment]
I made a new commit. The issue was caused by the fact that the certificate location is changed in beta branch in config folder. I made https://github.com/diyhue/diyHue/commit/ba387ad44fae32e318a5982e0c1c36c7d19317dd to fix it. Delete /opt/hue-emulator folder to not be detected.

**Comment by bluenazgul** [comment]
i used the uninstall script to make a clean setup

removed all old install.sh files, grabed the new `install.sh` using `wget`

installer seems to work

![image](https://user-images.githubusercontent.com/171537/128048718-b1e4117c-e288-485a-9745-56be2ea8873f.png)

but Hue Emulator Service still fails to load

![image](https://user-images.githubusercontent.com/171537/128048877-a4f85fb9-7d9b-4240-9f63-cd7a88877566.png)

**Comment by mariusmotea** [comment]
Please run manually:

`sudo /opt/hue-emulator/HueEmulator3.py`

and show here the logs. There must be an error.

**Comment by bluenazgul** [comment]
![image](https://user-images.githubusercontent.com/171537/128050746-e052dd5f-8445-48e8-82b0-8d76eed82f9c.png)

**Comment by bluenazgul** [comment]
Iam not sure, but I belive there is "flask" missing during the install Script for the Beta release

**Comment by bluenazgul** [comment]
got it fixed finaly (i hope so)

maybe this could help to improve the install.sh for beta release

`sudo apt install python3-venv python3-pip`
`sudo pip3 install flask`
`sudo pip3 install flask_cores`
`sudo pip3 install flask_restful`
`sudo pip3 install pyyaml`
`sudo pip3 install flask_login`
`sudo pip3 install flask_wtf`
`sudo pip3 install email_validator`

> root@diyHue:/opt/hue-emulator# sudo /opt/hue-emulator/HueEmulator3.py
2021-08-03 18:13:34,524 - configManager.argumentHandler - INFO - Using Host 192.168.178.16:80
2021-08-03 18:13:34,528 - configManager.argumentHandler - INFO - Host MAC given as xxxxxxxxxxxx
2021-08-03 18:13:34,529 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
2021-08-03 18:13:34,529 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
2021-08-03 18:13:34,529 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
2021-08-03 18:13:34,529 - configManager.argumentHandler - INFO - Debug logging disabled!
2021-08-03 18:13:34,530 - configManager.configHandler - INFO - Config loaded
Starting remote discovery
2021-08-03 18:13:34,960 - services.stateFetch - INFO - start lights sync
2021-08-03 18:13:34,961 - services.ssdp - INFO - starting ssdp...
2021-08-03 18:13:34,961 - services.ssdp - INFO - start ssdp broadcast
2021-08-03 18:13:34,961 - services.mdns - INFO - <MDNS> listener started
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.178.16:80/ (Press CTRL+C to quit)
 * Serving Flask app 'HueEmulator3' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on https://192.168.178.16:443/ (Press CTRL+C to quit)
192.168.178.152 - - [03/Aug/2021 18:13:36] "GET /description.xml HTTP/1.1" 200 -

**Comment by mariusmotea** [comment]
Sorry, i miss to install all packages from requirements.txt

**Comment by bluenazgul** [comment]
> Sorry, i miss to install all packages from requirements.txt

no problem, thats why it is called "Beta" - this needs the community to solve even small issues
