### ISSUE TITLE
diyHue as HUE RGB Receiver

### ISSUE THREAD

**Issue by Jhidzzo** [diyhue/diyHue#677]
**Describe the issue**

Is it possible to register a Raspberry Pi in the HUE Bridge as a RGB Light and execute custom Python code using the library?

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Comment by Mevel** [comment]
No. 
A regular Hue bridge can only register zigbee compatible bulbs / lights.

However: You can use diyhue (bridge emulator) in combination with the provided firmware for esp8266 microcontroller to make yourself a light that will become controllable via any 3rd party hue plug in.
