### ISSUE TITLE
Esp8266 motion not recognised in Hue App

### ISSUE THREAD

**Issue by betonishard** [diyhue/diyHue#68]
Hi all, first of all I would like to say thank you for this software. I use it for a long time now and I am really impressed. This software has a high WAF factor. Good job...

**Describe the bug**
Use the provided motion sensor esp8266 sketch on an esp8266 (wemos) in the HueApp. So I retrieved the latest sketch from the sensors repo. I uploaded this as is to a wemos board along with the lightlevel as well as the motion sensor. I know both work due to the fact that I have tested theses separately. The wemos board never gets recognized by the Hue app (add acessory, tap "led green light blinking", it starts searching (for minutes and minutes and still not find anything.

Time for debugging.
So started using curl commands, and check the json whether it get's updated with the mac address of the device. Tried others wel and they were added to the config.json as ZLLPresence.
http://<bridgeip>/switch?&mac=xx:xx:xx:xx:xx:xx&devicetype=ZLLprsesence
http://<bridgeip>/switch?&mac=xx:xx:xx:xx:xx:xx&lightlevel=46900&dark=true&daylight=true&presence=true
It appears in the config.json however not in the hue app. So stopped the service "service stop hue-emulator". Restarted with debug flag. All the communication arrives with 200 OK to the debug.

So I can conclude, it is present in the config.json, and it is reaching the bridge and responses with 200 OK.

Than I suspected my config file. I have an old config json, with lights dating back to LST001 (now it's LST002), lightstrip esp8266 with WS2812b ledstrip 5 pieces that work flawlessly.

So backup of config.json removed everything (rm -rf), reinstalled diyHue, removed app completely reinstalled app. Than I flashed one of my esp lights (from model LST001 to LST002) so it would be recognized by the app, launched the app, added the bridge and one light (the reflashed one was recognized). You can't continue if you don't add one light. Therefore I reflashed it. Now tried again with a brand new config.json. 

Same routinge as with the old config. So the sensor is added to the config.json with the correct mac address. I see traffic coming in. However no accessory detected (at least 10 minutes searching for a couple of times).

**To Reproduce**
Multiple ways as stated above. I just would like to have someone giving me the golden answer. Because it has been driving me crazy.

**Expected behavior**
ESP8266 motion detector recognized as an accesory in the app.

**Comment by betonishard** [comment]
If there is more information needed, please let me know.. 
Or if someone has a proper functioning motion sensor please let me know as well hoe to achieve this

**Comment by mariusmotea** [comment]
@betonishard there is a huge work made for sensors that need to be published soon. I still wait for some ESP-M2 modules for final test.

**Comment by betonishard** [comment]
@mariusmotea thank you for your reply, so basically what you're saying is don't bother it will be renewed anyway...

**Comment by cheesemarathon** [comment]
Yes @betonishard wait a couple of weeks and there will be some new much better hardware and software to match!
