### ISSUE TITLE
Missing HomeAssistant in Beta, and incompatible new Hue API with Master

### ISSUE THREAD

**Issue by RoboMagus** [diyhue/diyHue#687]
**Describe the issue**

I'm trying to get DiyHue up and running with my home assistant installation, mostly to be able to use the official Philips Hue app.
The problem is, that where the Beta has support for the latest app, for some reason it does not have HA support. And with the dev and master branches I get the HA support, but I would no longer be able to use it with the Hue app.

Questions:
- What's the reason for the deviation between supported protocols in beta vs the other branches?
- Is there any progress on the V4.0 app support, which had been implemented in Beta already some time ago: #642
  - Perhaps an e.t.a.?
- Is there a quick way to get this working, while the required features are combined from both development paths?

**Steps you tried**

Browsing the codebase to see what's missing in either branch that would provide support for both the features I require.

**How we can help**

Provide information about the differences between the versions, and a status update on the issues above.
(I also could not find a matching, up-to-date readme / manual that describes the configuration steps etc. for the Beta branch.)

**Logs**

None so far...

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): ARM
 - Docker image version (Ex: latest, arm-05f043b, 128):  diyhue/core:latest, diyhue/core:beta, diyhue/core:dev
 - OS (Ex: Windows 10, Ubuntu Buster): Raspbian
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): RPi4B

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by Mevel** [comment]
Hey!

The big challenge was to get the new api v2 reverse engineered. That is working so far, now the modules like home assistant is getting implemented in the v2 version.

**Comment by mariusmotea** [comment]
Is this issue still valid?

**Comment by RoboMagus** [comment]
I just checked with a fresh pull this morning, and now I can get the beta connected to my Home Assistant instance without issues. Thanks! :)
However for some reason I still cannot get it to propperly connect to the Hue app on android. (Home assistant links to it just fine though, which might cause issues with recursive light discovery). The app recognizes the DiyHue instance as a bridge, but upon pressing the link button nothing happens.

**Comment by mariusmotea** [comment]
If the Hue app has cached an old certificate it will not connect. Ensure the certificate MAC address is correct and the Hue app has no old certificate cached (better wipe the app data if Android or reinstall if is iPhone)

**Comment by RoboMagus** [comment]
After a complete reinstall of the Android app and a regeneration of the DiyHue certificate I got it up and running. Thanks for that advice.

Turns out in my case I also had a misconfiguration of the reverse proxy.  On TCP 443 it provided an incorrect certificate, instead of forwarding the one generated by DiyHue.

Thanks for helping me out @mariusmotea!
