### ISSUE TITLE
Fix security allerts

### ISSUE THREAD

**Issue by cheesemarathon** [diyhue/diyHue#69]
Hi Marius

I'm sure by now you have seen the security alerts [here](https://github.com/diyhue/diyHue/network/alerts).
Is there any reason why we can't fix the at least the two high severity ones?

I believe for the merge one we just need to change [this line](https://github.com/diyhue/diyHue/blob/565255de3da13fa20236ba6db3f61d7c3aa54a02/BridgeEmulator/web-ui-src/package-lock.json#L3556) to 1.2.1 or greater.

Similar thing for URL-parse but there are a few lines that need changing.

![image](https://user-images.githubusercontent.com/16329132/51240100-ede9cf00-1972-11e9-8ea0-e001f20b261c.png)

**Comment by mariusmotea** [comment]
@cheesemarathon i saw the alerts but as i'm not expert with react i ignore them...until today. I create a new vm just to compile the react code. I made a new commit, i hope all packages are now updates. As a bonus i added buttons for all internal links.

**Comment by mariusmotea** [comment]
I will try to compile this again

**Comment by mariusmotea** [comment]
made another commit. This time i change the package version manually to github recommendation because npm audit did not detect any security problem.

**Comment by cheesemarathon** [comment]
All fixed now!
![image](https://user-images.githubusercontent.com/16329132/51746725-fd69c600-209e-11e9-9643-7c7b24467e0f.png)
