### ISSUE TITLE
Cannot find the config.json on my mac

### ISSUE THREAD

**Issue by clementpeleman** [diyhue/diyHue#691]
**Describe the issue**

I got the bridge to work, but it gives me the update messsage. I know I can sole this if i change the config file. Ive searched all i could but i cannot find the file. Any idea on where it might be located on mac?

**Steps you tried**

**How we can help**

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128):  latest
 - OS (Ex: Windows 10, Ubuntu Buster):  mac os
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): macbook

**Checklist**
- [ x] I confirm that this is a help request
- [ x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
config.json file is located on your Mac depending you how you started the container. You must have a location mounted in the container at /opt/hue-emulator/export . In that location you have config.json file.
