### ISSUE TITLE
Call a user-script like bash, python

### ISSUE THREAD

**Issue by Luddi96** [diyhue/diyHue#700]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the feature that you would like to be added**

The user can create a light / device and specify the path to a bash / python script. When the light / device is changed by e.g. Alexa, the script is executed.

**Describe alternatives you've considered**

none

**Describe your use case for this feature**
I have my own UDP protocol to control all my devices (mainly lights). I do not want to reflash them. So I need a way to link "Hue Light" to "UDP packet sent". Easiest way would be to have diyHue call a script which then I can program to send my UDP packets.

**Checklist**
- [x] I confirm that this is a feature request
- [X] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
You need to create the protocol file for your lights. At this moment there is no "script execution" protocol implemented. If you know some programming language it is not that complicated since you have examples from other protocols.
