### ISSUE TITLE
Client protocols ['http-only', 'chat'] don’t overlap server-known ones

### ISSUE THREAD

**Issue by tetienne** [diyhue/diyHue#703]
**Describe the bug**

I have enable the home assistant import within the configuration file. I’m not able to see HA lights within diyHue interface.

**Steps to Reproduce**

```JSON
"homeassistant": {
            "enabled": true,
            "homeAssistantIncludeByDefault": true,
            "homeAssistantIp": "192.168.2.148",
            "homeAssistantPort": 8123,
            "homeAssistantToken": "xxxxx",
            "homeAssistantUseHttps": false
        },

```

**Expected behavior**

I want to see all my HA light within diyHue.

**Logs**

`WARNING:root:Home Assistant Web Socket Client disconnected trying to (re)connect`

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): x86
 - Docker image version (Ex: latest, arm-05f043b, 128): f1e13c02da65
 - OS (Ex: Windows 10, Ubuntu Buster): Ubuntu
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

Within Home Assistant 2021.9.7:
```

 Logger: aiohttp.websocket
Source: /usr/local/lib/python3.9/site-packages/aiohttp/web_ws.py:174
First occurred: 1:13:03 PM (1 occurrences)
Last logged: 1:13:03 PM
Client protocols ['http-only', 'chat'] don’t overlap server-known ones ()
```

**Comment by mariusmotea** [comment]
unfortunately the master version will receive only small updates, all efforts are on the `beta` branch

**Comment by tetienne** [comment]
OK so you suggest me to switch to the beta branch?

**Comment by mariusmotea** [comment]
Not yet. Beta stil miss the websocket implementation for home assistant.

**Comment by tetienne** [comment]
😞 Have you any workaround in mind? Can I help perhaps to patch the master branch?

**Comment by mariusmotea** [comment]
Master branch is currently a lot behind beta in terms of features. I spend few hours every day to have all features implemented and stable in this branch.

**Comment by tetienne** [comment]
That’s impressive. So I will be patient, thx for your amazing work.
