### ISSUE TITLE
bad check_updates.sh script

### ISSUE THREAD

**Issue by ynkblw** [diyhue/diyHue#706]
**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Checklist**
- [ ] I confirm that this is a bug report
- [ ] I confirm that I have completed this template to the best of my ability

**Additional context**

It's starting but only to the point where u are supposed to type in the Branch...

that's what I've got...
[1] Master Branch - most stable Release 
[2] Developer Branch - test latest features and fixes - Work in Progress!
Note: Please report any Bugs or Errors with Logs to our GitHub, Discourse or Slack. Thank you!
I go with Nr.: /dev/stdin: line 17: syntax error near unexpected token `)'
/dev/stdin: line 17: `        1)'

**Comment by mariusmotea** [comment]
Looking into this issue now.
