### ISSUE TITLE
Error when initializing HueEmulator.py

### ISSUE THREAD

**Issue by BarrMan** [diyhue/diyHue#709]
**Describe the issue**
When trying to run HueEmulator.py manually from my RaspberryPi, I get this error message:
```
Traceback (most recent call last):
  File "./HueEmulator3.py", line 29, in <module>
    from functions.entertainment import entertainmentService
  File "/opt/hue-emulator/functions/entertainment.py", line 5, in <module>
    from functions.lightRequest import sendLightRequest
  File "/opt/hue-emulator/functions/lightRequest.py", line 5, in <module>
    from protocols import protocols
  File "/opt/hue-emulator/protocols/__init__.py", line 1, in <module>
    from protocols import yeelight, tasmota, shelly, mi_box, native_single, native_multi, esphome, mqtt, hyperion, homeassistant_ws, wled
  File "/opt/hue-emulator/protocols/homeassistant_ws.py", line 157
    logging.info(f"Found {entity_id}")
                                    ^
SyntaxError: invalid syntax
```

**Steps you tried**
I manually installed diyHue emualtor on my RaspberryPI, in addition I made sure I have python3 as my default interpreter and manually installed the dependencies specified in the requirements.txt file. When running the service and trying to discover my newly flashed esp (connected to sk6812 leds), hue app is unable to find the leds.

**How we can help**
Help get diyHue Emulator running

**Logs**

**Docker Info (please complete the following information):**
 - Architecture: ARM 
 - OS: Raspbian: 
 - Hardware Raspberry Pi 3: 

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
What is exactly the python version, including minor version ?
