### ISSUE TITLE
DiyHue Beta: Scene "Nightlight" trows an error

### ISSUE THREAD

**Issue by PDekker** [diyhue/diyHue#722]
**Describe the bug**
Nightlight scene is not working. Lights do not respond.

**Steps to Reproduce**
1. Add Original Hue lights to zigbee2MQTT
2. Config DIYHUE Beta to imports lights from Homeassistant over web sockets
3. Setup works as expected
4. Open official Hue app. Latest version
4. Scene "nightlight" trows an error

**Expected behavior**
For this scene to work

**Logs**
```
diyHue            | 2021-10-31 15:35:37,726 - flaskUI.v2restapi - INFO - element not found!
diyHue            | [2021-10-31 15:35:37,728] ERROR in app: Exception on /clip/v2/resource/scene/cbe0d6ee-7d2d-4c78-a116-26c65b863c12 [PUT]
diyHue            | Traceback (most recent call last):
diyHue            |   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1950, in full_dispatch_request
diyHue            |     rv = self.dispatch_request()
diyHue            |   File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1936, in dispatch_request
diyHue            |     return self.view_functions[rule.endpoint](**req.view_args)
diyHue            |   File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 468, in wrapper
diyHue            |     resp = resource(*args, **kwargs)
diyHue            |   File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 89, in view
diyHue            |     return self.dispatch_request(*args, **kwargs)
diyHue            |   File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 583, in dispatch_request
diyHue            |     resp = meth(*args, **kwargs)
diyHue            |   File "/opt/hue-emulator/flaskUI/v2restapi.py", line 453, in put
diyHue            |     object.activate(putDict)
diyHue            | AttributeError: 'bool' object has no attribute 'activate'
diyHue            | 10.0.0.152 - - [31/Oct/2021 15:35:37] "PUT /clip/v2/resource/scene/cbe0d6ee-7d2d-4c78-a116-26c65b863c12 HTTP/1.1" 500 -
diyHue            | 10.0.0.152 - - [31/Oct/2021 15:35:38] "GET /clip/v2/resource/bridge HTTP/1.1" 200 -
diyHue            | 2021-10-31 15:35:39,140 - services.stateFetch - INFO - start lights sync
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): ARM
 - Docker image version (Ex: latest, arm-05f043b, 128): latest beta 
 - OS (Ex: Windows 10, Ubuntu Buster): Raspberry Pi OS
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Pi 4

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**
I'm running the Beta. Unsure if the English name is "Nightlight" in Dutch the scene is called "Nachtlampje"

**Comment by mariusmotea** [comment]
Hi,

Other scenes are working? It is possible that the Hue app to not be in sync with the emulator (ex: scene was deleted but is still displayed) and only a force close of the app will ensure that a full sync with diyhue bridge is done.  All other scenes are working fine?

**Comment by PDekker** [comment]
Solution was to clean sources with the Hue Essentials app
