### ISSUE TITLE
http_port and https_port does not work in beta (PR added)

### ISSUE THREAD

**Issue by heikkih** [diyhue/diyHue#726]
**Describe the bug**

It is not possible to use configurable http_port and https_port in the beta-branch.

I've added what is needed in PR #724 and #725 

I've verified with running diyhue on ports 8080 and 8443 with nginx proxy_pass for both http and https, and it works perfectly with both the official Hue app and Hue Essential.

Hope you can merge this so people running more stuff on the same servers can tune their configuration.

**Steps to Reproduce**

1. Start with one or both of --http-port 8080 and --https-port 8443 or 	-e HTTP_PORT=8080 -e HTTPS_PORT=8443 

**Expected behavior**

I really want this to work well :)

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): x86 
 - Docker image version (Ex: latest, arm-05f043b, 128): beta
 - OS (Ex: Windows 10, Ubuntu Buster): Debian
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by Mevel** [comment]
Thank you!

**Comment by heikkih** [comment]
Merged into beta in #724 and #725. Closing this.
