### ISSUE TITLE
transitionTime and transition colour

### ISSUE THREAD

**Issue by abneits** [diyhue/diyHue#735]
**Describe the bug**

First of all, my installation :
Diyhue 4.0 beta + Hue app essential + MQTT + ZigbeetoMQTT + Hyperion + Android grabber + 2 Hue play bar

My problem occur when i change colour from Hue App (and generally when Diyhue handle the request)
For example :
If i change from blue to yellow, there is some intermediate colour briefly apply. In my case blue -> white -> yellow.

Ohterwise if i do exactly the same thing from zigbeetomqtt interface, the change is made instantly without this intermediate colour.

It is annoying when my setup is in ambilight mode. That's create some lag and innacurate colour

**Steps to Reproduce**

1. Go to Hue APP Essential
2. Change colour from blue to yellow
3. Note that's white colour briefly display
4. Go to ZigbeetoMQTT
5. Change from blue to yellow
6. Change is made instantly

**Expected behavior**

Diyhue send the exact colour instantly without transition or intermediate colour

**Logs**

Nothing relevant

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PI 3B+

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
In Entertainment mode i made some tests and i saw is worst without a transition. I set different transition values for brightness change and color change. You can also try to optimize it by changing the transition from here:
https://github.com/diyhue/diyHue/blob/beta/BridgeEmulator/services/entertainment.py#L163
and here:
https://github.com/diyhue/diyHue/blob/beta/BridgeEmulator/services/entertainment.py#L164
