### ISSUE TITLE
Can't connect to diyhue bridge with Philipps Hue app 

### ISSUE THREAD

**Issue by oh-dee-bee** [diyhue/diyHue#736]
**Describe the issue**

**Steps you tried**

**How we can help**
Connection to diyhue bridge via Philips Hue app not possible: I can add the bridge (using the IP address), link successfully but afterwards when switching to the bridge the app tries to connect indefinitely.

Hue Essentials works just fine.

**Logs**
Running in debug mode, the only thing I see during app connection attempts is this (every second):

192.168.xyz.abc - - [04/Dec/2021 23:02:11] "GET /clip/v2/resource/bridge HTTP/1.1" 200 -

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM):  ARM
 - Docker image version (Ex: latest, arm-05f043b, 128):  latest
 - OS (Ex: Windows 10, Ubuntu Buster): (underlying) Raspian/Debian Bullseye
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero):  Raspi 3B+

**Checklist**
- [X] I confirm that this is a help request
- [X] I confirm that I have completed this template to the best of my ability

**Additional context**
Hue app version is 4.9.0 (9304). Diyhue is cleanly installed, 1 Hue bridge imported with 2 lights and 1 room. Changed swversion in config.json to 1948086000 (otherwise Philips app insists on updating, this is the current version my other bridges have - other versions don't work either)

**Comment by mariusmotea** [comment]
Just the beta version is working with Hue app v 4.x. Master version is working with Hue app 3.x only.

**Comment by tob1no** [comment]
Unfortunately not quite. The current App version (4.9) required a bridge version 1948086000, the beta branch is 1945091050. Is there already an ETA?

**Comment by oh-dee-bee** [comment]
Works fine using the official Docker container now, thank you!
