### ISSUE TITLE
Support for controlling / link of multiple Hue bridges

### ISSUE THREAD

**Issue by oh-dee-bee** [diyhue/diyHue#737]
**Is your feature request related to a problem? Please describe.**

Current Philips Hue bridge hardware only supports a (somewhat) limited amount of lights. From what I've gathered from Hue centric forums, the use of more than one bridge to cover large at home installations is not uncommon. Multiple bridges might also be in use to deal with Zigbee coverage problems.

**Describe the feature that you would like to be added**

If diyhue would support controlling multiple Hue bridges at the same time, it could be used to unify larger installations in a single exposed bridge.

**Describe alternatives you've considered**

None I am aware of.

**Describe your use case for this feature**
Control large Hue installation with a single exposed bridge.

**Checklist**
- [X] I confirm that this is a feature request
- [X] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
I think this may work currently, since once you import the lights from Hue Bridge it store bridge ip and the credentials. Then you can pair it to second bridge and import the lights from there. However i think you can have better success with a powerful zigbee controller supported by zigbee2mqtt to replace the original bridges.

**Comment by mariusmotea** [comment]
Never think there will be need to pair with multiple bridges, but i figure it may work once i saw the request. Indeed Philips added some additional features to zigbee communication like entertainment protocol witch is working better with the original bridge than Zigbee2Mqtt, but all other stuff (sensors/remotes) are working fine also on zigbee2mqtt.
