### ISSUE TITLE
Tradfri Setup - invalidate peer

### ISSUE THREAD

**Issue by HeikoB95** [diyhue/diyHue#738]
**Describe the bug**

Importing by Tradfri is not working.

**Steps to Reproduce**

From the main page I can switch to the Tradfri Setup and insert the IP and Security Code.
After pressing the save button the Internet Browser starts loading, but nothing happens. As of I  also have the problem, that the imported devices does not get displayed at the main page I only can check this in the Hue Essentials App, but I see only the Devices from the original Hue Gateway. Also the log of the diyHue/core docker container I get a problem (also copied down below in the logs)

**Expected behavior**

That importing Devices from Tradfri Gateway works.

**Logs**

192.168.178.33 - - [16/Dec/2021 10:56:08] "GET /tradfri?ip=192.168.178.109&code=XXXXXXXXXXXXXXXX HTTP/1.1" 200 -
Dec 16 10:56:08 ALRT 20 invalidate peer

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): x86_64
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Synology DSM7
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Synology Diskstation DS1520+

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
i recommend to switch to beta branch that provide error message in the web interface for the pair process

**Comment by HeikoB95** [comment]
Okay. What is meant by the Identity field for the Tradfri Setup in the beta?

**Comment by mariusmotea** [comment]
The username that will be created on the Tradfri gateway. From what i remember, there will be issues if this already exist, so endure you pick something unique.

**Comment by HeikoB95** [comment]
Okay. I get a error message at the button of my screen "timeout of 2000ms exceeded", after pressing the PAIR button and in the container log it has not been changed that much:

{'identity': 'sbafibaosfbkasbf',
'tradfriCode': 'XXXXXXXXXXXXXXXX',
 'tradfriGwIp': '192.168.178.109'}
Dec 17 09:46:50 ALRT 20 invalidate peer

**Comment by mariusmotea** [comment]
It means the bridge is unable to contact your Tradfri Gateway. Can you ping the ip of the Tradfri Gateway from the Diyhue host?

**Comment by HeikoB95** [comment]
If I connect via ssh to my NAS I can ping from there the Tradfri Gateway. As of I have to use Portainer I also tried to confirm, that this is also possible from inside the container. I tried to ping from the container console, but unfortunately the ping comment seems not to be available inside.

**Comment by mariusmotea** [comment]
Ensure the IP and the security code is correct, then try to pair with a new identity name. Not sure if IKEA did not made changes to the API.

**Comment by HeikoB95** [comment]
Thank you, I was pretty sure that the IP and Sec Code were correct, so I've scanned the QR code and copied the Sec Code and found out, that the supposed capitel letter i was and lower letter L.
