### ISSUE TITLE
Configured names and icons not saved

### ISSUE THREAD

**Issue by syphernl** [diyhue/diyHue#748]
**Describe the bug**
During configuration of the DiyHue Bridge lights in the Hue App you have the ability to select icons and name the bulb. 
I noticed that neither of these are saved.

**Steps to Reproduce**
* Pair DiyHue Bridge to your Hue App
* Configure new bulbs
* Give it a name and icon, other than the default Sultan icon.

**Expected behavior**
Bulb name + icon saved

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): amd64
 - Docker image version (Ex: latest, arm-05f043b, 128):  latest
 - OS (Ex: Windows 10, Ubuntu Buster): Alpine 3.15
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): LXC

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**
This might be related to https://github.com/diyhue/diyHue/issues/747

**Comment by mariusmotea** [comment]
Probably they changed this to the new api and i did not notice it. I will take a look in the next days.

**Comment by TRusselo** [comment]
having same issue

**Comment by mariusmotea** [comment]
I cannot replicate this issue. I rename a light and changed the icon to Christmas tree, it was working. Are you sure you use last beta version?
