### ISSUE TITLE
Cannot activate with Hue App or Hue Essentials

### ISSUE THREAD

**Issue by spower9991** [diyhue/diyHue#758]
**Describe the issue**
 My diyHue is up and running and I get to the linkbutton page fine. The Hue App and Hue Essentials app both pick up my Hub fine however when i click Activate the Hue App does nothing and the Hue Essentials app comes up with an error saying
"Error: The bridge cannot be reached. Please check your connection and try again". 

When i click the Activate button the below response is on Docker:

"172.17.0.1 - - [16/Jan/2022 23:01:56] "GET /hue/linkbutton?username=&password=&action=Activate HTTP/1.1" 200 -"

**Steps you tried**
 I've tried both Master version and 2.1 - currently running 2.1. I've also tried re-installing Docker. Also have made sure that my devices are on the same network and rebooted all my devices

**How we can help**
 Please could someone advise if this is a long known issue or if there is anything I'm doing wrong

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): x86
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - OS (Ex: Windows 10, Ubuntu Buster): Windows 10
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**
 thank you

**Comment by mariusmotea** [comment]
Switch to beta version and it must work.

**Comment by spower9991** [comment]
Just tried beta in host network config and the page continues to load but wont come up
Modified the bridge code for the beta and get a page with no pictures and the phrase 'Oops, there appears to be no lighting here'
- any advice?

**Comment by spower9991** [comment]
Below is Docker return minus the private information:

"2022-01-17 19:00:13,703 - configManager.argumentHandler - INFO - Using Host XXX.XXX.XX.X:80

2022-01-17 19:00:13,703 - configManager.argumentHandler - INFO - Host MAC given as XX-XX-XX-XX-XX-XX

2022-01-17 19:00:13,703 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255

2022-01-17 19:00:13,703 - configManager.argumentHandler - INFO - Deconz IP given as XXX.X.X.X

2022-01-17 19:00:13,703 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!

2022-01-17 19:00:13,704 - configManager.argumentHandler - INFO - Debug logging disabled!

2022-01-17 19:00:13,704 - configManager.configHandler - INFO - Config loaded

2022-01-17 19:00:13,799 - services.stateFetch - INFO - start lights sync

2022-01-17 19:00:13,800 - services.ssdp - INFO - start ssdp broadcast

2022-01-17 19:00:13,802 - services.ssdp - INFO - starting ssdp...

2022-01-17 19:00:13,802 - services.mdns - INFO - <MDNS> listener started

Exception in thread Thread-11:

Traceback (most recent call last):

  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner

    self.run()

  File "/usr/lib/python3.9/threading.py", line 892, in run

    self._target(*self._args, **self._kwargs)

  File "/opt/hue-emulator/HueEmulator3.py", line 93, in runHttps

    ctx.load_cert_chain(certfile="config/cert.pem")

ssl.SSLError: [SSL] PEM lib (_ssl.c:4022)

 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)

Starting remote discovery

 * Serving Flask app "HueEmulator3" (lazy loading)

 * Environment: production

   WARNING: This is a development server. Do not use it in a production deployment.

   Use a production WSGI server instead.

 * Debug mode: off"

**Comment by mariusmotea** [comment]
When you start the docker container is mandatory to specfy the MAC address as ENV variable with lowercase characters, otherwise the certificate generation process will fail. The error ssl.SSLError: [SSL] PEM lib (_ssl.c:4022) is probably caused by the lack of content in the cert.pem file.

**Comment by spower9991** [comment]
I had put the MAC address in lowercase, and how do i go about correcting the cert.perm file - sorry if it's obvious my mind is blank

**Comment by spower9991** [comment]
I'm using the Docker run cmd below, is there something wrong there?:

"docker run -d --name diyHue-beta --restart=always --network=host -e MAC=XX-XX-xX-XX-XX-xX -v /mnt/hue-emulator/config:/opt/hue-emulator/config diyhue/core:beta"

**Comment by mariusmotea** [comment]
`MAC=XX-XX-xX-XX-XX-xX` must be changed with the real mac address from the network interface.

Ex:
MAC=a2:fd:74:11:fc:c5

**Comment by spower9991** [comment]
Yes I’ve done this, I changed it on here to hide my MAC address but it’s absolutely correct and in lowercase

>

**Comment by mariusmotea** [comment]
Perform the HTTPs check from here: https://diyhue.readthedocs.io/en/latest/AddFuncts/debug.html?highlight=https#https-certificate-check

Very important, the Hue app cache the certificate. If you made tests/reinstallations you will need to reinstall the Hue app (iPhone) or wipe app data (Android).

**Comment by spower9991** [comment]
Thanks, I got the following from the HTTPs check:
"*   Trying 127.0.0.1:443...
* connect to 127.0.0.1 port 443 failed: Connection refused
* Failed to connect to 127.0.0.1 port 443 after 2022 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to 127.0.0.1 port 443 after 2022 ms: Connection refused"

I will uninstall the app and reinstall once the page is loading

**Comment by spower9991** [comment]
I also ran the code with the debug line added, same return as above, please see additional debug return:
"2022-01-18 21:29:03,788 - services.remoteDiscover - DEBUG - Discovery ping"

**Comment by mariusmotea** [comment]
`Trying 127.0.0.1:443.` you test this from the host where diyhue is running? If yes it means the https server was unable to start, as i said most likely the certificate is invalid

**Comment by spower9991** [comment]
Yes this is from the host where it is running. How can I fix the certificate?

**Comment by spower9991** [comment]
I saw a previous post saying that i can delete it from /mnt/hue-emulator/export/  and it should recreate it - sorry if im coming across stupid but i cannot find this anywhere

**Comment by spower9991** [comment]
Tried running "docker exec diyHue-beta rm -rf /mnt/hue-emulator/export/" to remove the cert, no luck and the curl has the same result

**Comment by martindinicolino** [comment]
same issue here, has there been any resolution?

**Comment by mariusmotea** [comment]
Please follow https debug step from the documentation. Most likely you have a bad setup.

**Comment by martindinicolino** [comment]
thanks for replying

after trying for about a day or so, i just got it to work, not 100% sure why, but i suspect the diyhue home assistant addon was restarting itself whilst i was deleting the `cert.pem` file, i turned off the watchdog whilst following this procedure and it eventually worked
 ```
Important After Install & before starting diyHue, edit the Config according to the Docs below. If you start diyHue with the default MAC or a wrong MAC the Certificate for Linking Official Apps is generated wrong and you get a error upon linking. In that case:

Stop diyHue
delete cert.pem in /config/diyhue dir
edit mac
restart diyHue
```

i‘m happy it‘s working now
