### ISSUE TITLE
Diyhue not connecting to the Hue App on Android

### ISSUE THREAD

**Issue by Toastyman17** [diyhue/diyHue#768]
**Describe the issue**

**Steps you tried**

**How we can help**

Hello all together,

I tried to install diyhue as a docker image on my RPI4.
Everything worked fine and the container is running without any error messages.
Unfortunately the connection to the hue app is not working. I am able to connect to the simulated bridge but the app stays in the "Connecting" state forever. Did anyone run into the same problem and can help me to resolve it?

Thank you in advance!

Cheers!

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): ARM-v7
 - Docker image version (Ex: latest, arm-05f043b, 128):  latest
 - OS (Ex: Windows 10, Ubuntu Buster):  Raspbian Lite
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero):  Raspberry-PI4

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
you need to use the beta image tag.

**Comment by juanesf** [comment]
I also think rpi4 is arm-v8 64-bit, and I don't know if the arm-v7 image would work.

**Comment by sjaks** [comment]
I am able to pair the `core:latest` with Hue Essentials app but not any image with official Hue 4.0 Android app. Tested `latest/master`, `dev` and `beta` - both Docker and host install on RPi 4. It's weird that it works on Hue Essentials.

**Comment by mariusmotea** [comment]
Hue app V4 works just with beta. In 90% of the cases you generated a wrong certificate, or changed the certificate without to wipe Hue app data. This check will help you:
https://diyhue.readthedocs.io/en/latest/AddFuncts/debug.html?highlight=https#https-certificate-check

**Comment by sjaks** [comment]
When making a fresh install of RPiOS on my RPi 4 and installing diyHue with
```
curl -fsSL https://get.diyhue.org -o install.sh
sudo bash install.sh
```

I can confirm that the certificates match. But offtopic to this issue, I cannot reach the activate button since no authentication window is prompted. All I see is:

![image](https://user-images.githubusercontent.com/44066308/151163300-6d142f51-f475-4e80-bff6-a907515cd77c.png)

I can get everything to work when checkout to `master` but this happens in `beta`.
