### ISSUE TITLE
DiyHue not passing Color Information to Home Assistant Lights

### ISSUE THREAD

**Issue by sojhinn** [diyhue/diyHue#770]
**Describe the issue**

I have diyhue running, I can connect to it with the Hue app and Hue Essentials no issues. I can see the lights, in both the gui for diy hue and any Hue app. I can change the color of the lights, brightness, and on/off in the official hue app. However, in both the diyhue group button or hue essentials, I can only turn off/on the light, and the color will not change. 

I also noticed that when I try to send through the hyperion data to the lights, that diyhue is updating the colors but its not being transferred to the lights. 

The lights are hosted on home assistant. 

**Steps you tried**

I have tried both branches. I have tried the home assistant beta build, as well as the docker beta image. Both are acting the same way. 

**How we can help**

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): x86
 - Docker image version (Ex: latest, arm-05f043b, 128): docker beta & home assistant add-on (beta)
 - OS (Ex: Windows 10, Ubuntu Buster): mac and home assistant
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): o2 droid and mac mini docker

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by sojhinn** [comment]
Anything I can try in the interim?

**Comment by mariusmotea** [comment]
Don't think so, but it will be helpful if you can provide more examples when is working and when not. Scenes are working from both apps?

**Comment by sojhinn** [comment]
Seems like a similar issue to this: https://github.com/diyhue/diyHue/issues/741#issue-1087942051

**Comment by ivancristina** [comment]
I have the same issue. Home Assistant light imported (Meross RGB Light Strip) both as LCT015 and LST002. DiyHue reads all the statuses perfectly and does turn on and off, but unfortunately SETTING color and brightness does not work. Tried with other Smart Lamps and emulating different models but unfortunately, the behavior is the same.

**Comment by mariusmotea** [comment]
This is on my list. I need to pair a light just with Home Assistant in order to import it also in DiyHue for testing
