### ISSUE TITLE
Support for Nanoleaf?

### ISSUE THREAD

**Issue by jditte** [diyhue/diyHue#772]
**Is your feature request related to a problem? Please describe.**

**Describe the feature that you would like to be added**

The beta version of diyHue supports an impressive list of light protocols, but I am surprised to see that such a major protocol as Nanoleaf is missing. Is anybody already working on supporting the protocol? If not, it might start looking into it, although the amount of time I can invest is limited. Is there a documentation of the interface between diyHue and code supporting light protocols? Or do I have to analyze the existing implementations as examples?

**Describe alternatives you've considered**

**Describe your use case for this feature**

**Checklist**
- [x] I confirm that this is a feature request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
Hi,

Unfortunately beta require more work on the core side, currently there is no easy way to change the default login password, etc. If you want to implement it i can show you how to start.

**Comment by jditte** [comment]
Thank you for the response. Just to make sure that I understand you correctly, are you saying that diyHue currently has limitations that do not allow supporting the Nanoleaf protocol just by adding code to the "lights" folder? In that case, I don't think that I am prepared to make any major changes to the diyHue core...

**Comment by mariusmotea** [comment]
You only need to create a protocol file in lights/protocols folder . Probably the best filename is nanoleaf.py in this file you need to have 3 functions, one that return the automatic discovered lights, one that fetch the lights status with a cron and update the diyhue bridge (in case 3rd party app change the lights status) and the mandatory function to set the light status. This convert the hue API values to destination device API values. If there is a nanoleaf python library (like yeelight has) the job will be even more simple.
