### ISSUE TITLE
Yeelight Quota Exceeded using Hue + Ambilight from TV

### ISSUE THREAD

**Issue by joaquinvacas** [diyhue/diyHue#781]
**Describe the bug**

**Steps to Reproduce**

**Expected behavior**

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Checklist**
- [ ] I confirm that this is a bug report
- [ ] I confirm that I have completed this template to the best of my ability

**Additional context**

Hi there! 👋 

Using diyHue with a Yeelight color bulb and a Philips TV (non Android TV) 

Everything is fine, works good, easy installation and so on.

The issue here is that works fine for at least half minute, because it shows the error "client quota exceeded" and AFAIK it's just an issue with the yeelight library (happened in python-yeelight, check https://gitlab.com/stavros/python-yeelight/-/issues/73 )  that's used for talking with the bulb.

Because the bulb can handle all of this when using the music mode and works fine with other projects using python-yeelight.

Using last version.

Tried beta but didn't change a thing.

The error was:

2022-02-14 15:50:45,526 - HueObjects - WARNING - piesalon light error, details: {'code': -1, 'message': 'client quota exceeded'}

**Comment by mariusmotea** [comment]
Hi,

We have different implementation of the yeelight for regular control (over http api) vs Entertainment protocol used to stream fast frames. I think your TV is like mine and don't know to use the entertainment mode, and for this reason the quota strike if there are too many requests.
