### ISSUE TITLE
How can I enable Hue Entertainment (DTLS server?) using Docker?

### ISSUE THREAD

**Issue by sofakng** [diyhue/diyHue#787]
**Describe the issue**
How can I enable Hue Entertainment (DTLS server?) using Docker?

**Steps you tried**
iLightShow app for iOS indicates my diyHue Bridge doesn't support Hue Entertainment Mode.  According to the [diyHue Documentation](https://diyhue.readthedocs.io/en/latest/AddFuncts/entertainment.html?highlight=entertainment#hue-entertainment), I need to download and compile a DTLS server but I'm not sure how to do this inside Docker.

**How we can help**
The docker image doesn't appear to include the DTLS server needed for Hue Entertainment.  Can this be included or instructions provided how to add it myself?

**Logs**
n/a

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM):  x86_64
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Debian
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): PC

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
Try the `beta` docker image tag. That has much better support and use openssl for DTLS offloading.

**Comment by sofakng** [comment]
Geez, I should have researched that more before asking.  That's great to hear it's already in the beta branch though.  I'll give it a try.  Thanks so much!
