### ISSUE TITLE
Deconz On Another Host?

### ISSUE THREAD

**Issue by cheesemarathon** [diyhue/diyHue#79]
**Is your feature request related to a problem? Please describe.**
I am running DIYHue in Docker, and due to the way it works (using default ports), I am having to run this on a separate VLAN to the rest of my Docker setup effectively creating a virtual host. Deconz currently sits in a different non-VLAN Docker network and needs to remain that way as it is linked to HomeAssistant. DIYHue appears to only look at the immediate local network to find Deconz.

**Describe the solution you'd like**
It would be great if I could specify the IP where Deconz resides - This would also have the added benefit of users being able to use Deconz on hosts separate from DIYHue

**Describe alternatives you've considered**
I've tried many different Docker network configurations to try and make all run nicely together but, nothing seems to work...

@danieledwardgeorgehitchcock

**Comment by cheesemarathon** [comment]
I look at adding support for an environment variable to provide doconz host ip

**Comment by cheesemarathon** [comment]
@mariusmotea are there any lines in HueEmulator3.py that contain the deconz IP other than these?
[Line 1112](https://github.com/diyhue/diyHue/blob/b5fa4971a7991b935ac70023fb401d33298c581d/BridgeEmulator/HueEmulator3.py#L1112)
[Line 1120](https://github.com/diyhue/diyHue/blob/b5fa4971a7991b935ac70023fb401d33298c581d/BridgeEmulator/HueEmulator3.py#L1120)
[Line 1124](https://github.com/diyhue/diyHue/blob/b5fa4971a7991b935ac70023fb401d33298c581d/BridgeEmulator/HueEmulator3.py#L1124)
[Line 1130](https://github.com/diyhue/diyHue/blob/b5fa4971a7991b935ac70023fb401d33298c581d/BridgeEmulator/HueEmulator3.py#L1130)
[Line 1134](https://github.com/diyhue/diyHue/blob/b5fa4971a7991b935ac70023fb401d33298c581d/BridgeEmulator/HueEmulator3.py#L1134)

**Comment by mariusmotea** [comment]
@cheesemarathon , yes, these are the only lines were deconz is hardcoded.

**Comment by joselito11** [comment]
How to connect Deconz on another maschine running on port 8081-Home assistant addon? Hace changed IP, but still nothing
