### ISSUE TITLE
Home Assistant Dimmer Switch?

### ISSUE THREAD

**Issue by CyrosX** [diyhue/diyHue#794]
**Describe the issue**

How can I add the Dimmer Switch? Added to Home Assistant with ZHA.

**Steps you tried**

**How we can help**

How to add Dimmer Switch

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
In order to configure the original behavior of the original switch with scenes selection on top button you need to use zigbee2mqtt or deconz and provide the access to this zigbee device directly, not via Home Assistant.
