### ISSUE TITLE
App icon

### ISSUE THREAD

**Issue by T-IOOO** [diyhue/diyHue#801]
**Is your feature request related to a problem? Please describe.**

**Describe the feature that you would like to be added**

Make a nice app icon for ios devices when putting the web ui as a shortcut.

**Describe alternatives you've considered**

**Describe your use case for this feature**

**Checklist**
- [x] I confirm that this is a feature request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by Mevel** [comment]
I think it is the favicon that is used. Will add it. And see if that does the trick.

**Comment by T-IOOO** [comment]
Actually it should be a 150x150 PNG image.

Maybe this will help?
https://github.com/nurikk/zigbee2mqtt-frontend/issues

**Comment by mariusmotea** [comment]
We made a new commit with lot of favicons. Can you test and confirm it is ok now?

Thanks @Fisico for support.

**Comment by T-IOOO** [comment]
Yes it works…

![9DEC17A2-B034-4CCA-8CB8-273D4EBB1F63](https://user-images.githubusercontent.com/59575587/161096770-dcfba20a-ad93-457f-8af8-dc880d6c1d5a.jpeg)

The icon looks really good. Maybe the logo should be a little bit smaller? Just my personal opinion 😊

**Comment by Fisico** [comment]
Yes it looks ugly... It seems like exported the icon without padding. 
I will send @mariusmotea a new version.

**Comment by mariusmotea** [comment]
Update pushed. @T-IOOO  can you update and check now?

**Comment by T-IOOO** [comment]
![F2836F46-E985-47D3-99EF-000EB7B1B5C4](https://user-images.githubusercontent.com/59575587/161117887-fa572417-2344-4515-a4e2-12716092ca5b.jpeg)

Perfect!

closing
