### ISSUE TITLE
No CLIP API Debugger after easy install

### ISSUE THREAD

**Issue by PapACutA** [diyhue/diyHue#82]
**Describe the bug**
After a newinstall with the easy automatic installation script as described in readthedocs the CLIP API Debugger under *http://\<bridge_ip_address>/debug/clip.html* is not reachable.

**To Reproduce**
1. Do a new install as described here https://diyhue.readthedocs.io/en/latest/getting_started.html#host-install
2. after succesfull install go to *http://\<bridge_ip_address>/debug/clip.html*
3. See error

**Expected behavior**
Expected to get shown the CLIP API Debugger that is located here *diyHue-master\BridgeEmulator\debug\clip.html*

**Additional context**
After manually saving the *clip.html* to */opt/hue-emulator* it works fine. So i think the *easy_install.sh* just do not copy it. Maybe adding *debug/clip.html* to the copy command on line 107 in the *easy_install.sh* script will fix it.

**Comment by cheesemarathon** [comment]
This should be fixed now. Try a fresh install just to make sure.

**Comment by PapACutA** [comment]
Fresh install on a RaspberryPi 3b+ and it works out of the box now. Thanks

**Comment by JorinL** [comment]
Hey there,
I get "ERR_EMPTY_RESPONSE" on http://192.168.0.7/debug/clip.html

I use the dockerimage: diyhue/core:latest

Is it something in my config or in that image?
