### ISSUE TITLE
ikea styrbar zigbee2mqtt

### ISSUE THREAD

**Issue by Xorfee** [diyhue/diyHue#820]
**Is your feature request related to a problem? Please describe.**

I am missing the ikea styrbar controlling feature, after switching from Deconz to Zigbee2mqtt.

**Describe the feature that you would like to be added**

https://www.zigbee2mqtt.io/devices/E2001_E2002.html#ikea-e2001%252Fe2002
I am not able to see that in diyHue also not in Hue Essentials, any way to add it, with the proper button events?

**Describe alternatives you've considered**

**Describe your use case for this feature**

**Checklist**
- [x] I confirm that this is a feature request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
Any idea what where the buttonevent codes for this in Deconz? I need to revert these to buttonevents

> Triggered action (e.g. a button click). Value can be found in the published state on the action property. It's not possible to read (/get) or write (/set) this value. The possible values are: on, off, brightness_move_up, brightness_move_down, brightness_stop, arrow_left_click, arrow_right_click, arrow_left_hold, arrow_right_hold, arrow_left_release, arrow_right_release.

[#](https://www.zigbee2mqtt.io/devices/E2001_E2002.html#linkquality-numeric)

**Comment by Xorfee** [comment]
> Any idea what where the buttonevent codes for this in Deconz? I need to revert these to buttonevents
> 
> 
> 
> > Triggered action (e.g. a button click). Value can be found in the published state on the action property. It's not possible to read (/get) or write (/set) this value. The possible values are: on, off, brightness_move_up, brightness_move_down, brightness_stop, arrow_left_click, arrow_right_click, arrow_left_hold, arrow_right_hold, arrow_left_release, arrow_right_release.
> 
> 
> 
> [#](https://www.zigbee2mqtt.io/devices/E2001_E2002.html#linkquality-numeric)

Afaik 

brightness_move_up, 1002

brightness_move_down, 2002

arrow_left_click, 3002

arrow_right_click 4002

I never used the other buttons,

**Comment by Xorfee** [comment]
1001, UP shoort
1002, UP long press
1003, UP long press release
2001, Down shoort
2002, Down long press
2003, Down long press release
3002, Shoort Left
4002 Shoort Right

this is what i get

**Comment by Xorfee** [comment]
I managed to get the clicks responded on zigbee2mqtt .. not able to see the N2 Control on diyHue interface,

any advice to see it?=

Cause afaik I was able to see the button on diyHue previously with deconz

**Comment by Xorfee** [comment]
Closing this, found out a workaround via homebridge to trigger and bind the buttons, legacy has to be actived via settings in order to map the buttons via homebridge .

**Comment by mariusmotea** [comment]
Hi,

I made a commit but i'm not sure about the modelid. Hope "Remote Control N2" is the correct one.

https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/services/mqtt.py#L40
