### ISSUE TITLE
Unable to create rooms using the Hue App

### ISSUE THREAD

**Issue by LarsHanegraaf** [diyhue/diyHue#821]
**Describe the bug**: When adding a bridge in the Hue app, I am obliged to add lights to a room. But addings lights to a room fails (without a clear error message in the Hue app).

**Steps to Reproduce**

1. Run diyHue using Docker Compose, run it with network mode `host`.
2. Click on the 'Link' button in the diyHue UI.
3. Open the Hue App on Android
4. Add the bridge
5. Try to add lights to a room
  i. Fail badly

**Expected behavior**

I expect that adding lights to a room will work 😛 .

**Logs**

In the Docker logs, I see the following error:
```
INFO:werkzeug:192.168.1.10 - - [12/May/2022 22:00:00] "GET /api/dfee0a2ad23211ecbc7a1c697a68b0fe/groups/0 HTTP/1.1" 200 -
ERROR:HueEmulator3:Exception on /clip/v2/resource/room [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/dist-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask/views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/opt/hue-emulator/flaskUI/v2restapi.py", line 405, in post
    "rid": newObject.id_v2,
AttributeError: 'NoneType' object has no attribute 'id_v2'
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): AMD64
 - Docker image version (Ex: latest, arm-05f043b, 128): both `latest` and `master`
 - OS (Ex: Windows 10, Ubuntu Buster): Ubuntu 20.04.1 LTS
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Intel Nuc

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

None, so far a great project and thanks for helping out! 😉

**Comment by mariusmotea** [comment]
Hi,

I push a new commit, please test now. It seams the new version of Hue api create now the rooms and the zones using the version2 api.

**Comment by LarsHanegraaf** [comment]
Hi, 

I pulled the container with tag `amd64-master-700a936cc9991a04987c53a89b216f7187c6703e` and that resolved the issue. Thanks!
