### ISSUE TITLE
Link to Light IP/Port from Light Configuration Page 

### ISSUE THREAD

**Issue by caribo** [diyhue/diyHue#827]
**Is your feature request related to a problem? Please describe.**

Not a problem, more a convenience.

**Describe the feature that you would like to be added**

When viewing the light configuration page I would like to be able to click the lights IP address and port number and have it launch in a new tab in order to configure the light directly.

**Describe alternatives you've considered**

Cut + paste of IP address and port number into new browser tab

**Describe your use case for this feature**
I can use this for navigation to the lights interface to configure the light name, led configuration and  upload new firmware
**Checklist**
- [x] I confirm that this is a feature request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

Click on IP link here ..
![Screenshot from 2022-06-01 17-39-19](https://user-images.githubusercontent.com/664999/171456433-fc8efc4e-3689-4f12-85fc-c9da591ed798.png)
launches ...
![Screenshot from 2022-06-01 17-41-46](https://user-images.githubusercontent.com/664999/171456548-1338c9c7-9cc8-4353-b774-5b7a989aac52.png)

**Comment by mariusmotea** [comment]
That is a good idea. When i will do the next web interface update i will try to implement also this one.

**Comment by mariusmotea** [comment]
This was implemented with last commits.
