### ISSUE TITLE
How do I continue after installation, unable to find in documentation where is Web Interface

### ISSUE THREAD

**Issue by lastrebel** [diyhue/diyHue#853]
**Describe the issue**
I cannot understand the documentaion. On configuration webpage it says use WebINterface but where can I find it. I have RaspberryPi Zero W, really wanted to try DiyHue. I have installed it successfully but there is no information where can I find Web Interface, or some clear example of steps. There is webpage for [Installation](https://diyhue.readthedocs.io/en/latest/getting_started.html#host-install) and one for [Configuration](https://diyhue.readthedocs.io/en/latest/configuration.html#), Installation was OK but Configuration page mentions WebInterface but not where can I find it? Now I catch some URL for that interface in one demo video but on that URL is no useful information just saying "Oops, there appears to be no lighting here". 

I tried these for web interface but no success:
<ip_adress>/hue
<ip_adress>/mnt/hue-emulator
<ip_adress:443>/mnt/hue-emulator (with port, again I just seen this somewhere, )

**Steps you tried**
1. I tried Docker, by installing it first on RaspberryPi via ssh, that was success, it threw back some container number. I did not know what to do with it at this point. I stopped and removed that container and abandoned this option. I dont wanna use Docker at this point, there is no more useful information for my level of knowledge.
2. I tried Host Automatic Install from this page https://diyhue.readthedocs.io/en/latest/getting_started.html perfect, output from terminal:  Installation completed. Open Hue app and search for bridges.
I went to Hue App, found the bridge and Hue app instructs me to press a button on that bridge. How do I press that button? I have red this page and it tells me about Web interface, where do I find it? https://diyhue.readthedocs.io/en/latest/configuration.html 
3. I read many pages on these websites but did not find how to continue after installation https://diyhue.readthedocs.io/ , https://diyhue.org/ , https://github.com/diyhue/diyHue/
4. I have red output from terminal after installation in Docker or Host Automatic install, there were no links or other useful instructions. After half of the day and starting hair loss I am turning to you.

**How we can help**
1. where can I find which URLs should I use for Web Interface. I belive one should be <ip>/hue , second I maybe <ip>/hue/linkbutton
2. how do I press Link Button on RaspberryPi.

**Logs**

**Docker Info (please complete the following information):**
- I used Host Automatic Installation, I dont wanna use Docker

**Checklist**
- [x ] I confirm that this is a help request
- [ x] I confirm that I have completed this template to the best of my ability

**Additional context**
 I have almost none technical knowledge so this might be easy for you but I spend way too much time and always hit wall.

**Comment by Mevel** [comment]
Hey!
Sorry for auto closing your issue.

Once the installation is complete either docker or host install, you navigate in your browser to the ip of you raspberry and find the web ui there.

Login with the credentials shown in the hint box.

There you can also find the link button.
