### ISSUE TITLE
issue with docker container start after adding lights + rooms (in HueEssential)

### ISSUE THREAD

**Issue by u20p17** [diyhue/diyHue#857]
**Describe the bug**

**Steps to Reproduce**

I installed the docker container from https://hub.docker.com/r/diyhue/core/tags on my unraid system and everything was working. Then I added MQTT + HA + all the lights and connected it to HueEssential + Hue App... In the Hue essentail app I made rooms and put the lights in the different rooms. after restarting the docker I get the error.

**Expected behavior**

docker container should start normally after all the changes mentioned above...

**Logs**

> 2022-10-04 19:18:07,022 - configManager.configHandler - ERROR - CRITICAL! Config file was not loaded
> Traceback (most recent call last):
>   File "/opt/hue-emulator/configManager/configHandler.py", line 142, in load_config
>     group = weakref.ref(self.yaml_config["groups"][data["group"]])
> KeyError: '1'
> CRITICAL! Config file was not loaded
> Exception ignored in: <function Group.__del__ at 0x153fbb2f61f0>
> Traceback (most recent call last):
>   File "/opt/hue-emulator/HueObjects/__init__.py", line 962, in __del__
> ImportError: sys.meta_path is None, Python is likely shutting down
> 2022-10-04 18:18:37,380 - configManager.configHandler - ERROR - CRITICAL! Config file was not loaded
> Traceback (most recent call last):
>   File "/opt/hue-emulator/configManager/configHandler.py", line 142, in load_config
>     group = weakref.ref(self.yaml_config["groups"][data["group"]])
> KeyError: '1'
> CRITICAL! Config file was not loaded
> Exception ignored in: <function Group.__del__ at 0x154bc75051f0>
> Traceback (most recent call last):
>   File "/opt/hue-emulator/HueObjects/__init__.py", line 962, in __del__
> ImportError: sys.meta_path is None, Python is likely shutting down
> 2022-10-04 18:32:00,063 - configManager.configHandler - ERROR - CRITICAL! Config file was not loaded
> Traceback (most recent call last):
>   File "/opt/hue-emulator/configManager/configHandler.py", line 134, in load_config
>     self.yaml_config["groups"][group].add_light(self.yaml_config["lights"][light])
> KeyError: '32'
> CRITICAL! Config file was not loaded
> Exception ignored in: <function Group.__del__ at 0x150ce99641f0>
> Traceback (most recent call last):
>   File "/opt/hue-emulator/HueObjects/__init__.py", line 962, in __del__
> ImportError: sys.meta_path is None, Python is likely shutting down
> Exception ignored in: <function Group.__del__ at 0x150ce99641f0>
> Traceback (most recent call last):
>   File "/opt/hue-emulator/HueObjects/__init__.py", line 962, in __del__
> ImportError: sys.meta_path is None, Python is likely shutting down
> 2022-10-04 18:32:20,382 - configManager.configHandler - ERROR - CRITICAL! Config file was not loaded
> Traceback (most recent call last):
>   File "/opt/hue-emulator/configManager/configHandler.py", line 134, in load_config
>     self.yaml_config["groups"][group].add_light(self.yaml_config["lights"][light])
> KeyError: '32'
> CRITICAL! Config file was not loaded
> Exception ignored in: <function Group.__del__ at 0x154266ec01f0>
> Traceback (most recent call last):
>   File "/opt/hue-emulator/HueObjects/__init__.py", line 962, in __del__
> ImportError: sys.meta_path is None, Python is likely shutting down
> Exception ignored in: <function Group.__del__ at 0x154266ec01f0>
> Traceback (most recent call last):
>   File "/opt/hue-emulator/HueObjects/__init__.py", line 962, in __del__
> ImportError: sys.meta_path is None, Python is likely shutting down
> 2022-10-04 19:18:06,908 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
> 2022-10-04 19:18:06,908 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
> 2022-10-04 19:18:06,908 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
> 2022-10-04 19:18:06,908 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
> 2022-10-04 19:18:06,908 - configManager.argumentHandler - INFO - Host MAC given as bc5ff4cdc619
> 2022-10-04 19:18:06,908 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
> 2022-10-04 19:18:06,908 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
> 2022-10-04 19:18:06,908 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
> 2022-10-04 19:18:06,909 - configManager.argumentHandler - INFO - Debug logging disabled!
> 2022-10-04 19:18:37,269 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
> 2022-10-04 19:18:37,269 - configManager.argumentHandler - INFO - Host MAC given as bc5ff4cdc619
> 2022-10-04 19:18:37,270 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
> 2022-10-04 19:18:37,270 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
> 2022-10-04 19:18:37,270 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
> 2022-10-04 19:18:37,270 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
> 2022-10-04 19:18:37,270 - configManager.argumentHandler - INFO - Host MAC given as bc5ff4cdc619
> 2022-10-04 19:18:37,270 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
> 2022-10-04 19:18:37,270 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
> 2022-10-04 19:18:37,270 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
> 2022-10-04 19:18:37,271 - configManager.argumentHandler - INFO - Debug logging disabled!
> 2022-10-04 19:32:00,035 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
> 2022-10-04 19:32:00,035 - configManager.argumentHandler - INFO - Host MAC given as bc5ff4cdc619
> 2022-10-04 19:32:00,035 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
> 2022-10-04 19:32:00,035 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
> 2022-10-04 19:32:00,035 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
> 2022-10-04 19:32:00,036 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
> 2022-10-04 19:32:00,036 - configManager.argumentHandler - INFO - Host MAC given as bc5ff4cdc619
> 2022-10-04 19:32:00,036 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
> 2022-10-04 19:32:00,037 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
> 2022-10-04 19:32:00,037 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
> 2022-10-04 19:32:00,037 - configManager.argumentHandler - INFO - Debug logging disabled!
> 2022-10-04 19:32:20,358 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
> 2022-10-04 19:32:20,358 - configManager.argumentHandler - INFO - Host MAC given as bc5ff4cdc619
> 2022-10-04 19:32:20,358 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
> 2022-10-04 19:32:20,358 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
> 2022-10-04 19:32:20,358 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
> 2022-10-04 19:32:20,359 - configManager.argumentHandler - INFO - Using Host 192.168.1.8:80
> 2022-10-04 19:32:20,359 - configManager.argumentHandler - INFO - Host MAC given as bc5ff4cdc619
> 2022-10-04 19:32:20,359 - configManager.argumentHandler - INFO - IP range for light discovery: 0-255
> 2022-10-04 19:32:20,359 - configManager.argumentHandler - INFO - Deconz IP given as 127.0.0.1
> 2022-10-04 19:32:20,359 - configManager.argumentHandler - INFO - Online Discovery/Remote API Enabled!
> 2022-10-04 19:32:20,359 - configManager.argumentHandler - INFO - Debug logging disabled!
> 
> ** Press ANY KEY to close this window ** 

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): Intel-Architektur der 11. Generation
 - Docker image version (Ex: latest, arm-05f043b, 128): latest ( from 01.10.2022)
 - OS (Ex: Windows 10, Ubuntu Buster):  UNRAID 6.11.0
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero):  Intel NUC11TNBi7

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by Mevel** [comment]
Your config is not saved and loaded correct.

Do you have the docker run command or compose file you use to start the container?

**Comment by u20p17** [comment]
Hi @Mevel,
the docker run command looks the following:

```
docker run
  -d
  --name='diyHue'
  --net='br0'
  --ip='192.168.0.8'
  -e TZ="Europe/Berlin"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="HomeServer"
  -e HOST_CONTAINERNAME="diyHue"
  -e 'TCP_PORT_80'='80'
  -e 'TCP_PORT_443'='443'
  -e 'UDP_PORT_1900'='1900'
  -e 'UDP_PORT_2100'='2100'
  -e 'MAC'='bc:5f:f4:cd:c6:19'
  -e 'IP'='192.168.1.8'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:80]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/cheesemarathon/docker-templates/master/images/diyhue.png'
  -v '/mnt/user/appdata/diyHue':'/opt/hue-emulator/config/':'rw' 'diyhue/core:latest'
abeecc86d7fb265c5c8b3d41277d81e6d1a52ad8ea51854994973ed72f16e096

The command finished successfully!
```

The config file is located at /mnt/user/appdata/diyHue (volume mapping App to Host: /opt/hue-emulator/config/ --> /mnt/user/appdata/diyHue). So the docker should find the config file.

Thanks in advance!

**Comment by u20p17** [comment]
solved the issue by removing the container, delete the config folder completely and make a fresh install...

**Comment by mariusmotea** [comment]
Such issues may occur if you restart the container after some config changes without to force a config dump from the web interface. Currently i don't know how we can detect the process kill so we can automatically dump the config before process to exit. The config is automatically saved every hour at minute 0 and when a new resource is created.
