### ISSUE TITLE
Home Assistant Auth not working 

### ISSUE THREAD

**Issue by Weltraumpenner** [diyhue/diyHue#862]
**Describe the bug**

I setted up the latest diyHue in Docker and tried to fetch lights from Home Assistant. Unfortunately the authorization is failing because an extra parameter "ID" is passed. 

**Steps to Reproduce**

Press "Scan for lights" in diyHue with latest Home Assistant (2022.10.3) configured. 

**Expected behavior**

Auth-Request should work.

**Logs**

diyHue-Log:
```
diyhue  | 2022-10-14 13:38:21,504 - services.homeAssistantWS - INFO - HomeAssistant WebSocket discovery called
diyhue  | 2022-10-14 13:38:21,504 - services.homeAssistantWS - WARNING - Home Assistant Web Socket Client disconnected trying to (re)connect
diyhue  | 2022-10-14 13:38:21,509 - services.homeAssistantWS - INFO - Home Assistant WebSocket Connection Opened
diyhue  | 2022-10-14 13:38:21,510 - services.homeAssistantWS - INFO - Home Assistant Web Socket Client connected
diyhue  | 2022-10-14 13:38:21,510 - services.homeAssistantWS - INFO - Home Assistant Web Socket Authorisation required
diyhue  | 2022-10-14 13:38:21,511 - services.homeAssistantWS - INFO - HomeAssistant WebSocket discovery waiting for devices
diyhue  | 2022-10-14 13:38:21,513 - services.homeAssistantWS - ERROR - Home Assistant Web Socket Authorisation invalid: {'type': 'auth_invalid', 'message': "Auth message incorrectly formatted: extra keys not allowed @ data['id']. Got 1\nnot a valid value for dictionary value @ data['type']. Got 'get_states'"}
diyhue  | 2022-10-14 13:38:21,514 - services.homeAssistantWS - INFO - Home Assistant WebSocket Connection Closed. Code: 1000 Reason b''
```

Home-Assistant-Log:
```
2022-10-14 14:02:35.704 WARNING (MainThread) [homeassistant.components.websocket_api.http.connection] [140541297405008] Auth message incorrectly formatted: extra keys not allowed @ data['id']. Got 1
not a valid value for dictionary value @ data['type']. Got 'get_states'
```

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM):  x86_64
 - Docker image version (Ex: latest, arm-05f043b, 128): latest
 - OS (Ex: Windows 10, Ubuntu Buster): Ubuntu 22.04.1 LTS

**Checklist**
- [x] I confirm that this is a bug report
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
I took a look in order to understand this issue but i did not find any `'id'` in the code: https://github.com/diyhue/diyHue/blob/master/BridgeEmulator/services/homeAssistantWS.py

**Comment by Weltraumpenner** [comment]
I guess it comes from there:
https://github.com/diyhue/diyHue/blob/0a631cc3950b647f96f1f7eda2f85e72b59b517b/BridgeEmulator/services/homeAssistantWS.py#L203
But I didn't have time to have a closer look.

**Comment by Weltraumpenner** [comment]
The latest docker-image solved this issue for me.
