### ISSUE TITLE
New Protocol - what should be done?

### ISSUE THREAD

**Issue by Paalap** [diyhue/diyHue#866]
Hi

I would like add a protocol to diyhue (quite strange one :) a light in a cooker hood). What should be done to get it to work, i.e. what should be adjusted except creation of the new protocol python script (and the lights in the config file as I would go without discovery).

Thank you in advance

**Describe the issue**

**Steps you tried**

**How we can help**

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM):  Raspberry
 - Docker image version (Ex: latest, arm-05f043b, 128):  host installation
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): Pi4

**Checklist**
- [ X] I confirm that this is a help request
- [X ] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by Mevel** [comment]
What type of light do you want to add?
What's the type of connection? Wifi? Zigbee?
Do you have some sort of api? Available documentation?
