### ISSUE TITLE
The New Hue Outdoor Motion Sensor

### ISSUE THREAD

**Issue by NedSin** [diyhue/diyHue#87]
Hey Guys, 
still Love this Project. 
After House is Full i start Outdoor and get the new HUE Outdoor Sensor Today. 

But i dont get him in the diyHUE Bridge.

I Try with Deconz and Raspbee but they dont find him. 
The HUE Bridge find him but after that, its not in the Emulated one.
When i try to connect him with the diyHUE bridge he (of course) dont find him to. 

Am i to Stupid or its just not Supported at the moment ? 

Update the diyHUE also change nothing and deconz is on the newest state ... 

Hope i dont have to send the sensor back ... 

Best Greetings 

Ned

**Comment by Mevel** [comment]
It needs to be supported by deconz and if it is listed in the sensor json it can be processed by diyhue. I think it needs to be implemented first.

**Comment by mariusmotea** [comment]
How is listed in Deconz (Phoscon)?

**Comment by NedSin** [comment]
i was not able to find it with deconz (phoscon)

**Comment by mariusmotea** [comment]
Deconz provide communication with zigbee sensors so it need support in Deconz first.

**Comment by NedSin** [comment]
Okay, i try my luck there. 

Post it here if i hear something new ...

**Comment by NedSin** [comment]
Looks like they working on it. 

Sadly my English is to Bad to Understand complete ...

**Comment by NedSin** [comment]
Hello together, 
the new Sensor is in Deconz: V2_05_59 implemented. 

Since i try to add him in deconz nothing works anymore with diyHUE. 

2 new installs, config backup not working. 

In the moment where i import deconz in the hue nothing works anymore. 

Hope the sensor get implemented soon. 

P.S.: The sensor is not shown in deconz, why ever, so i can not delete him ... 

best greetings 

Ned

**Comment by mariusmotea** [comment]
But the sensor must be displayed in Deconz if is supported.

**Comment by NedSin** [comment]
Hello again, yesterday i install the deconz plugin together with phoscon and diyHUE after that the sensor Was shown under sm002. I delete him and was now able to imort deconz without Problems in diyhue. After i try to add the sensor again in phoscon. He import him but is again Not showing in phoscon etc. 

The deconz App for raspberry dont Start on raspbian, why ever... 

I try today again to find him. 

I have a big New Problem and not Sure to open New issue or ask here... 😇 

After New install the diyhue my esp generic on/off and 433mhz devices are Not avalible. Not after reflash Not with /detect no way.

Switches and ws2811 where found.

Is there something changed in the diyhue bridge that i have to change in my Sketches?

Thank you. 
Ned

**Comment by mariusmotea** [comment]
Maybe you need to increase the timeout of detection?

**Comment by NedSin** [comment]
Hi, 
now i need to do Somethig, my Wife want to kill me because: Shutters, Doorbell, Aquarium Lights, etc. 
all Works normaly with diyHUE.

Now we have to do all with webservers. 

I have to fix this or (what i absolut not want) i have to change to mqtt/hasss combination :( ...

I changed the Line:

`
  server.on("/detect", []() {
    server.send(200, "text/plain", "{\"hue\": \"bulb\",\"lights\": " + String(devicesCount) + ",\"modelid\": \"Plug 01\",\"mac\": \"" + String(mac[5], HEX) + ":"  + String(mac[4], HEX) + ":" + String(mac[3], HEX) + ":" + String(mac[2], HEX) + ":" + String(mac[1], HEX) + ":" + String(mac[0], HEX) + "\"}");
  });
`

to this 
`
 server.on("/detect", []() {
    server.send(2000, "text/plain", "{\"hue\": \"bulb\",\"lights\": " + String(devicesCount) + ",\"modelid\": \"Plug 01\",\"mac\": \"" + String(mac[5], HEX) + ":"  + String(mac[4], HEX) + ":" + String(mac[3], HEX) + ":" + String(mac[2], HEX) + ":" + String(mac[1], HEX) + ":" + String(mac[0], HEX) + "\"}");
  });`

Still no result by Searching Lights even when i reload the /detect all 2 seconds ... 

I dont know what is the fu**** Problem ... 

An Ideas ? 

Thank you 
Ned

**Comment by NedSin** [comment]
Hi, 
now i need to do Somethig, my Wife want to kill me because: Shutters, Doorbell, Aquarium Lights, etc. 
all Works normaly with diyHUE.

Now we have to do all with webservers. 

I have to fix this or (what i absolut not want) i have to change to mqtt/hasss combination :( ...

I changed the Line:

`
  server.on("/detect", []() {
    server.send(200, "text/plain", "{\"hue\": \"bulb\",\"lights\": " + String(devicesCount) + ",\"modelid\": \"Plug 01\",\"mac\": \"" + String(mac[5], HEX) + ":"  + String(mac[4], HEX) + ":" + String(mac[3], HEX) + ":" + String(mac[2], HEX) + ":" + String(mac[1], HEX) + ":" + String(mac[0], HEX) + "\"}");
  });
`

to this 
`
 server.on("/detect", []() {
    server.send(2000, "text/plain", "{\"hue\": \"bulb\",\"lights\": " + String(devicesCount) + ",\"modelid\": \"Plug 01\",\"mac\": \"" + String(mac[5], HEX) + ":"  + String(mac[4], HEX) + ":" + String(mac[3], HEX) + ":" + String(mac[2], HEX) + ":" + String(mac[1], HEX) + ":" + String(mac[0], HEX) + "\"}");
  });`

Still no result by Searching Lights even when i reload the /detect all 2 seconds ... 

I dont know what is the fu**** Problem ... 

An Ideas ? 

Thank you 
Ned

**Comment by NedSin** [comment]
Hey Guys, 
realy nobody has an idea ?

**Comment by mariusmotea** [comment]
Hi,

Please flash the lights again, i made the commit https://github.com/diyhue/Lights/commit/a39deb07fac694d0f8726f8f012f57b598f93701

**Comment by NedSin** [comment]
My friend Marius, 
thank you a million time for this Fix ... 
Horror time over ... now i can use the half house again ;) ... 

No stress with the Outdoor Sensor but it would be nice when he works someday ... 

Thanks a lot again ...

**Comment by mariusmotea** [comment]
@NedSin That sensor is not touched by hue-emulator. If Deconz did the correct job and expose him exactly like the Hue Bridge, once imported the hue emulator must expose it the same, so hue app must see it and create the rules and scenes for it. You can check at what level this is hang to apply some corrections. Hue emulator is very flexible, you can change all sensor parameters from config.

**Comment by cheesemarathon** [comment]
@NedSin I'm closing this as the hue motion sensor working is not dependent on changes in this project. It only requires support by deconz, then diyHue should be able to work with it. I believe i have read a few issues over at the deconz repo that support is being worked on. Once deconz supports it, if your having issues still, open a new issue.
