### ISSUE TITLE
Change web server (web ui) listening port

### ISSUE THREAD

**Issue by eisengrau** [diyhue/diyHue#876]
**Describe the issue**

Hello,

It is possible to change the listening port of the internal web server (to something else than 80)? Either from a config file directly, or from an evironment directive for docker-compose? My user case wouild be to run it in a container with host network mode (instead of a bridged one, as I currently have issues with it) and I'm currently running another web service on port 80 on the host.

Thank You,

**Steps you tried**

Checked documentation.
Checked config.yaml

**How we can help**

Enable the possibility to change web ui port from within the docker container.

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

**Comment by mariusmotea** [comment]
I already replyed in #874

You can change the bind address, just look on the possible arguments of the docker container, but most likely you don't want to do this because no app will work.
