### ISSUE TITLE
How can i add a Arduino(esp8266) device?

### ISSUE THREAD

**Issue by cuban8IO** [diyhue/diyHue#88]
hi,
how can i connect your  diyhue/lights for esp8266? i have no idea. On the Hue Emulation page, i  cant see a menu point of adding the devices...

Thank you very much

**Comment by mariusmotea** [comment]
Flash the firmware in esp board, connect it to your wifi network and search for new lights from any hue application that is connected to hue emulator bridge

**Comment by cuban8IO** [comment]
yes, that i have tested, but the app has no found any devices..

**Comment by mariusmotea** [comment]
What sketch are you using? I made lot of changes in last period, maybe i introduce a bug. You can also start the script in debug mode to see if lights ip as founded.

**Comment by cuban8IO** [comment]
I use this sketch https://github.com/diyhue/Lights/tree/master/Arduino/Generic_RGBW_Light ...
I started the debug mode. But i can't choose the emulation bridge and the console shows Http response codes. The website works fine...

**Comment by mariusmotea** [comment]
add `--debug=true` to see debug messages. That is sketch is updated and for me is working. Maybe you need to increase the socket timeout. Hue emulator device is wifi connected?

**Comment by cuban8IO** [comment]
Yes, i can open the webpage. The emulator-bridge goes to online when the debug mode is off. How can i increase the socket timeout?

**Comment by mariusmotea** [comment]
Edit this line in HueEmulator3.py and restartbhue-emultor service

sock.settimeout(0.02) # Very short timeout. If scanning fails this could be increased



Put 0.1 just to be sure.

**Comment by cuban8IO** [comment]
yes, i have found any debug logs: 
2019-02-17 21:31:54,978 - root - INFO - ip 172.16.1.51 is unknow device, Expecti                                                                                                                                                             ng value: line 1 column 1 (char 0)
2019-02-17 21:31:55,079 - root - INFO - {
    "mac": "18:FE:34:E1:34:22",
    "modelid": "LCT015",
    "name": "New Hue RGBW light",
    "protocol": "native_single",
    "type": "rgbw",
    "version": 2
}
2019-02-17 21:31:55,080 - root - INFO - 172.16.1.109 is New Hue RGBW light
2019-02-17 21:31:55,081 - root - INFO - Add new light: New Hue RGBW light
2019-02-17 21:31:55,082 - root - INFO - ip 172.16.1.109 is unknow device, 'light                                                                                                                                                             s'
2019-02-17 21:31:55,157 - root - INFO - registration fail, is the link button pr                                                                                                                                                             essed?
172.16.1.108 - - [17/Feb/2019 21:32:03] "GET /api/a7161538be80d40b3de98dece6e91f                                                                                                                                                             90/config HTTP/1.1" 200 -
172.16.1.108 - - [17/Feb/2019 21:32:03] "GET /api/a7161538be80d40b3de98dece6e91f                                                                                                                                                             90 HTTP/1.1" 200 -

I have activated the link-button over "/hue/linkbutton?username=&password=&action=Activate" ...

**Comment by mariusmotea** [comment]
I found a bug, give me 2 minutes

**Comment by cuban8IO** [comment]
ah cool.... great. i hope, it helps me - no problem ...

**Comment by mariusmotea** [comment]
https://github.com/diyhue/diyHue/commit/5b94a937c6d7adc181a0018c000a2852f54ce732 must fix this. Just download again the HueEmulator3.py file.

**Comment by cuban8IO** [comment]
yeesss.. works fine! thank you!! :)

**Comment by mariusmotea** [comment]
Is good that this issue was reported now as some users may lose lot of time to fix this.
