### ISSUE TITLE
Bluetooth hue bulb

### ISSUE THREAD

**Issue by Leon135** [diyhue/diyHue#884]
**Describe the issue**

Cannot connect a hue bluetooh bulb with the hue emulator

**Steps you tried**

1. Open Hue application
2. Add a light bulb
3. Add a bridge
4. Transfer
5. And error

**How we can help**

I know that there is a hue_bl library but it just doesnt work

**Logs**

**Docker Info (please complete the following information):**
 - Architecture (Ex: x86, ARM): 
 - x64
 - Docker image version (Ex: latest, arm-05f043b, 128): 
 - latest
 - OS (Ex: Windows 10, Ubuntu Buster): 
 - Windows 10, Lubunto 21.10
 - Hardware (Ex: PC, Raspberry Pi 1/2/3/Zero): 
 - PC

**Checklist**
- [x] I confirm that this is a help request
- [x] I confirm that I have completed this template to the best of my ability

**Additional context**

I have no idea what the cause of this would be. I think the scan light option doesnt have scanning for bluetooth lights so thats propably why i couldn't connect any.

**Comment by Mevel** [comment]
Bluetooth bulbs are not supported at this  moment.

**Comment by Leon135** [comment]
Are they planned to be supported in the future?

**Comment by mariusmotea** [comment]
There was some progress made, look at https://github.com/diyhue/diyHue/issues/692. If you have some coding skills you can find the issue quickly.
