### ISSUE TITLE
Question: Does Spotify Sync work?

### ISSUE THREAD

**Issue by Shadow505** [diyhue/diyHue#885]
Hey,

does the feature from the official Hue app work, that allows you to connect your  Spotify account to hue and then allows you to sync the light to the music you're listening to via Spotify (live) and also provides various ways to customize the experience (colors, lights, etc). If so, is it fully local or are there still remote servers from Hue involved?

Thanks

**Comment by mariusmotea** [comment]
That is a cloud based service, diyhue cannot use Hue cloud services since is not a genuine bridge.
