### ISSUE TITLE
Cant find DIY esp8266 light

### ISSUE THREAD

**Issue by m50008** [diyhue/diyHue#9]
I connected the hue app successful with the raspberry pi but i cant find my esp8266 board.
I use the Node Mcu 1.0 and can connect to its ip and set the state and everything but the Hue app doesnt find it. The nmap package is also installed.

**Comment by mariusmotea** [comment]
Hi,

When you run this in debug mode during light search the output from nmap will be displayed. Please check if the ip of your Node Mcu is displayed. Try to disable all protection futures on your router.

**Comment by ryancasler** [comment]
Did you power-cycle your lights before searching?  With my ESP DIY's, I found that unless I recently power-cycled the Hue app wouldn't find them.  Dunno why but it worked.

**Comment by ghiagio** [comment]
Hello,

I am in the same situation as m50008. Nmap is installed and running. I looked into the HueEmulator3.py to see how it was used (in the scanForLights function) and if I run 

_nmap 192.168.1.113/24 -p80 --open -n | grep report | cut -d ' ' -f5_

I correctly have the results
_192.168.1.1
192.168.1.113
192.168.1.153  
192.168.1.228_

192.168.1.153 being the IP adress of the NodeMcu. But if I run the script & service in debug mode, this is  what I have

_2018-12-15 19:17:16,362 - root - INFO - b'{}'
2018-12-15 19:17:22,453 - root - INFO - [
    "192.168.1.1",
    "192.168.1.228",
    "192.168.1.113"
]
2018-12-15 19:17:22,511 - root - INFO - registration fail, is the link button pressed?_

Do you have any why the light cannot be detected ?

Thanks

**Comment by ghiagio** [comment]
I keep trying auite often (every 10 minutes). I also tried to run the bit of code in python 

_device_ips = check_output("nmap  192.168.1.113/24 -p80 --open -n | grep report | cut -d ' ' -f5", shell=True).decode('utf-8').rstrip("\n").split("\n")_

and got the list with the light

**Comment by cheesemarathon** [comment]
Are we still having issues with this @ghiagio @m50008 ?

**Comment by m50008** [comment]
Yes, the Hue App still doesnt find the Lamp. I cant add the in the Hue App because the lamp is not found.

**Comment by m50008** [comment]
> Hi,
> 
> When you run this in debug mode during light search the output from nmap will be displayed. Please check if the ip of your Node Mcu is displayed. Try to disable all protection futures on your router.

How can i run this in debug mode?

**Comment by mariusmotea** [comment]
```sudo systemctl stop hue-emulator
cd /opt/hue-emulator
sudo ./HueEmulator3.py --debug=true
```

**Comment by mariusmotea** [comment]
LST001 is legacy, update the light firmware, it must expose now LST002.

**Comment by m50008** [comment]
Okay thank you, that worked, now i connected the esp with the hue app. But after updating the nodemcu, when turning on or of the ledstrip, the led strip starts flickering in all colors. With the LST001 the was a smooth dimming that is now gone.

**Comment by mariusmotea** [comment]
Can you show here the variables set in sketch header? I have no issues with current version

**Comment by m50008** [comment]
#define light_name "WS2812Fenster" //default light name
#define lightsCount 1
#define pixelCount 150
#define transitionLeds 6 // must be even number

#define button1_pin 4 // on and bri up
#define button2_pin 5 // off and bri down
#define use_hardware_switch false // on/off state and brightness can b

**Comment by m50008** [comment]
Thank you for the help, everything works now. Flashed the sketch again and now everything works!
