### ISSUE TITLE
Fail to start? KeyError: 'Type' #64 still persists

### ISSUE THREAD

**Issue by morphygee** [diyhue/diyHue#90]
Hi.

the problem of bug #64 still persists.
it works as long as I add some routines. such as "wake up"
after the first service restart I am getting this error:
`Traceback (most recent call last):
  File "./HueEmulator3.py", line 1847, in <module>
    updateConfig()
  File "./HueEmulator3.py", line 147, in updateConfig
    if bridge_config["groups"][group]["type"] == "Entertainment":
KeyError: 'type'`

installed on raspberry 3 via automatic host install (https://diyhue.readthedocs.io/en/latest/getting_started.html#automatic-install)

**Comment by mariusmotea** [comment]
yes, probably somebody undo the fix from mistake. I will fix it again in few minutes.

**Comment by mariusmotea** [comment]
I fix this with last commit. Please test and reopen in case you still face problems.
