### ISSUE TITLE
WLED multiple segments (I turn off one, all turn off)

### ISSUE THREAD

**Issue by Aaroneisele55** [diyhue/diyHue#900]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Install Script

### Home Assistant related?

No

### Description

When I turn off one segment of my WLED light in the Hue Essentials App (connected to my diyHUE bridge), all segments turn off.
Changing the color or dimming works as expected, turning on one segment will akso turn off the whole light.

### Errorlog:

I don't have a log

### Steps to reproduce

1 Create multiple segments in WLED
2 Try to turn one of them off in the Hue Essentials App
3 All segments turn off

### Please enter your operating system details here

Linux 5.15.84+ armv6l

### What DiyHue version(branch) are you using?

master (latest)

**Comment by mariusmotea** [comment]
I think most likely this is WLED default behaviour, it don't allow individual segments to be powered off/on.
