### ISSUE TITLE
Cannot add a reinstalled diyHue instance to Hue App

### ISSUE THREAD

**Issue by robotica72** [diyhue/diyHue#91]
Description: Cannot add a reinstalled diyHue instance to Hue App...

I have had this a few times and my quick fix has been to use a different IP address, but I was hoping there was a better fix.    If I remove a diyHue bridge from the Hue App and try to add it back after I reinstall the Hue bridge on the same IP/Hardware/Docker Container I cant add it back into the App.

The App will see it for a second during the seach but then it flips to no bridges found.   If I tap on the search button like a madman I can click the found 1 bridge quick enough to enter the link phase in the App, but it never links up that way.

If I change the IP address, I can add it without any issues.

I assume that the Hue app is the issue, but with a bridge I never had this issue - only with the diyHue bridge...  

Any potential ideas?

**Comment by mariusmotea** [comment]
Wipe Hue application data because it cache the previews generated certificate and will not accept new one. On iphone you need to reinstall the hue app

**Comment by robotica72** [comment]
I thought that might be the issue - thanks for the clarification.

Cleared the cache and had no issues adding both hubs back in.

**Comment by cheesemarathon** [comment]
Issue fixed so closing
