### ISSUE TITLE
Synology, Docker (in macvlan) cannot identify lights from DeConz in another container

### ISSUE THREAD

**Issue by steffensammet** [diyhue/diyHue#917]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

No

### Description

Hello,

as Philips hue requires Port 80, I set up a Docker in MACVLAN in my network (Synology Host is 192.168.178.3; MACVLAN is 192.168.178.210; Router is 192.168.178.1)

Accessing to diyHue via Hue app works like charm! I can pair the diyhue to Deconz, which is running in another docker on host and it connects, creates a user etc.
![image](https://github.com/diyhue/diyHue/assets/38013126/5d9a2c28-5492-4f7a-bf5e-6f939a4870d5)

However, when I like add lights from deconz, nothing happens. In the log, I found this statement
`<html>
<body>

2023/07/18 12:09:32 | stdout | 2023-07-18 12:09:32,164 - lights.protocols.deconz - INFO - Error connecting to Deconz: HTTPConnectionPool(host='192.168.178.3', port=8085): Max retries exceeded with url: /api/6FD763C51E/lights (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f2ee43c4100>, 'Connection to 192.168.178.3 timed out. (connect timeout=3)'))
-- | -- | --

</body>
</html>`

When trying to access http://[192.168.178.3:8085/api/6FD763C51E/lights](http://192.168.178.3:8085/api/6FD763C51E/lights as it is indicated above using my browser, it works like charm. Wha is wrong - a mistake by the user or problem in the software.

Lights coming from the "normal" hue bridge work like charm !

### Errorlog:

```
Please paste the full error log here
```

### Steps to reproduce

see description

### Please enter your operating system details here

Synology Docker

### What DiyHue version(branch) are you using?

master (latest)

**Comment by Flashlab2** [comment]
Could you share how you run the diyhue container on your Synology? I can't get the certificate to work with 127.0.0.1, the Synology IP or the Macvlan IP. I tried the Synology MAC, the Macvlan MAC address.

**Comment by steffensammet** [comment]
in the meantime, I found that in Docker, macvlan networks are not able to talk to host networks and vice versa.

**Comment by Flashlab2** [comment]
But you do have a working certificate with the official Hue app?
