### ISSUE TITLE
IKEA DIRIGERA Pairing is not working

### ISSUE THREAD

**Issue by adiac** [diyhue/diyHue#919]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

No

### Description

I'm having issues to pair the IKEA DIRIGERA Hub, to a point where I'm guessing it's not really supported, since it may differ from the original IKEA Tradfri Gateway. But anyway...

### Errorlog:

```
timeout of 2000ms exceeded
```

### Steps to reproduce

I just set up the new Hub, set a custom IP on my network via DHCP, restarted the Hub, then tried to pair it. The required security code was a first problem, because on the new Hub it is not labeled as such, but it seems from research that the 8 digit number is the security code, which is included in the left barcode (see this [image](https://bilbotruke.net/58782-thickbox_default/hub-para-ikea-home-smart-ikea-dirigera.jpg)). For testing I just put some random characters into the Identity field.

Anyway I just get an `timeout of 2000ms exceeded` error and that's it. Can you help me in any way on this?

### Please enter your operating system details here

Linux 6.1.21-v7+ armv7l  
Raspbian GNU/Linux 11 (bullseye)

### What DiyHue version(branch) are you using?

master (latest)

**Comment by ryancasler** [comment]
The DIRIGERA  uses a completely different API model than the Tradfri did.  So, someone would have to implement this as a totally new interface.  I would classify this more as a feature request than a bug.

**Comment by adiac** [comment]
Thank you for this information. It was not clear for me that the DIRIGERA Hub is not supportet.
