### ISSUE TITLE
Special Character in Room Names

### ISSUE THREAD

**Issue by n3PH1lim** [diyhue/diyHue#93]
If you add a Room with an Umlaut tested with ü in Küche.
You are not able to change a Room after this.

With every new Room or old Room you want to change the app says the name already exists.

**To Reproduce**
Create a Room with an Umlaut in the Name in the official Hue App.

**Expected behavior**
Room Name should also work with Country specific Letters.

**Additional context**
Only tested with the official Hue App.

**Comment by mariusmotea** [comment]
This is related to https://github.com/mariusmotea/diyHue/issues/238. I guess changing the json library encoding can fix this. I never test it, i don't have special characters on my keyboard.
https://stackoverflow.com/questions/11977935/how-to-convert-a-string-with-umlauts-back-to-json

**Comment by n3PH1lim** [comment]
After a bit googling and fiddling I think I fixed it.

I created a pull requests.
[https://github.com/diyhue/diyHue/pull/94](url)
