### ISSUE TITLE
Entertainment segment in Hue app stopped working

### ISSUE THREAD

**Issue by Justdigit** [diyhue/diyHue#935]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

No

### Description

Since the new API and new versions its not possible to create an entertainment room for a PC monitor.

The lights that have been aded are not visiable when  you are going to create a room.

### Errorlog:

```
Please paste the full error log here
```

### Steps to reproduce

Go in the Hue app and try to create an entertainment room.

### Please enter your operating system details here

Docker Android Hue app

### What DiyHue version(branch) are you using?

master (latest)

EDIT:
The enttertainment mode works with on Older Android App 4.36 for instance

**Comment by igorcv88** [comment]
I have that same issue… it’s been happening for almost a month now

**Comment by mariusmotea** [comment]
This is an api change that need to be investigated. Do you have any output from a gradient request using last Hue app version?

**Comment by igorcv88** [comment]
I’m sorry but I don’t get what you mean by a Gradient Request using the Hue App… do you mean using it to control my gradient strip? I do have a WS2812B but I didn’t know the Hue App could control it that way

**Comment by mariusmotea** [comment]
i made a commit 10 minutes ago to add some new entertainment keys that were missing from the api.

**Comment by igorcv88** [comment]
Solved!
