### ISSUE TITLE
Typo in Webinterface

### ISSUE THREAD

**Issue by Tederean** [diyhue/diyHue#96]
**Describe the bug**
Typo in Webinterface, when using RGB lights. It says Brghtness instead of Brightness. 

![typo](https://user-images.githubusercontent.com/2964600/53445557-14d6fe80-3a11-11e9-905c-edefd570f022.png)

I can find the typo in the following files:

BridgeEmulator/web-ui-src/build/static/js/main.b1024bd8.chunk.js.map
BridgeEmulator/web-ui-src/build/static/js/main.b1024bd8.chunk.js
BridgeEmulator/web-ui-src/src/Room.js
BridgeEmulator/web-ui/static/js/main.b1024bd8.chunk.js.map
BridgeEmulator/web-ui/static/js/main.b1024bd8.chunk.js

**Comment by cheesemarathon** [comment]
@mariusmotea #97 should fix this, if you could just review it

**Comment by mariusmotea** [comment]
The issue was fixed with the commit made 10 minutes ago
