### ISSUE TITLE
No Lamps showing up in Entertaiment Area Creation

### ISSUE THREAD

**Issue by Schwarz-F** [diyhue/diyHue#963]
### Issue does not already exist?

No, I did not search

### Select Environment

Docker

### Home Assistant related?

No

### Description

If I try to create an Entertainment Area, no Lamps are shown, which I could add to the Area.  Although an LED Lightstrip is paired (see pictures), which works fine on the original bridge. The LED - Strip is connected via zigbee2mqtt, and yes I know that the transmition will not be in real time, but still good enough for my needs. The lightstrip is also controllable with the "normal" Hue app.
![grafik](https://github.com/diyhue/diyHue/assets/102516859/7a8dab81-6082-481c-99ff-7e135853b18b)
![grafik](https://github.com/diyhue/diyHue/assets/102516859/229f7b3f-54af-4361-a817-8a5a291ac0ff)

### Errorlog:

No direct error message, just the images.

### Steps to reproduce

1. Add a lightstrip via zigbee2mqtt to your diyhue instance
2. Select LST002 as the Modell
3. Try adopting it into an entertainment area

### Please enter your operating system details here

Docker Container on Truenas Scale

### What DiyHue version(branch) are you using?

master (latest)

**Comment by kimukao1** [comment]
Same problem here. Pairing of the Hue Sync Box with Deconz DIYHUE successful. But creating an entertainment zone doesn‘t work: there are no lamps shown, although I have plenty of original hue color lamps connected to the DIYHUE. Would be grateful for helpful advice.

**Comment by mariusmotea** [comment]
I think the creation of entertainment areas from Hue Essentials app was not impacted by the api changes.

**Comment by Schwarz-F** [comment]
Do you think that the Issue with the Api is fixable in with in the near future or do i need to buy the Hue Essentials Premium Version to use the Entertainment Area Features?

**Comment by mariusmotea** [comment]
i think i fix it already with today commits.
