### ISSUE TITLE
DIYHue in HomeAssistant - W in RGBW not working

### ISSUE THREAD

**Issue by wasp100** [diyhue/diyHue#99]
**Describe the bug**
Hi,
First of all, thanks for the amazing piece of software.

I have installed the DIY Hue software along with a RGBW strip light (using Generic_SK6812_Strip arduino code). I managed to successfully pair the strip light with the Hue App, and it works perfectly in the app.

I've exposed the DIY Hue to Home Assistant by adding the following to the configuration.yaml:
hue:
  bridges:
    - host: DIYHUE_IP_ADDRESS

It shows up fine in Home Assistant, however the W in the RGBW in not controllable. It seems like it is not sending the White LED info to Home Assistant.
I can comfortably control all the other colors though.

Can you please indicate how I can get access to the White LED in the RGBW through Home Assistant?

**Expected behavior**
Be able to control the W led in the RGBW strip

**Comment by mariusmotea** [comment]
The white led is used just in color temperature mode. I believe home assistant send only hue or xy values.

**Comment by wasp100** [comment]
Is there any way to expose the white led for color temperature to Home Assistant? That's exactly what I want to do in Home Assistant so that I can get similar colors as the scenes Relax, Read, Concentrate, Bright, etc.
It would be greatly appreciated.

**Comment by wasp100** [comment]
@mariusmotea 
It seems like Home Assistant does indeed support color temperature, where the values were based on Philips Hue. See link below:
https://github.com/home-assistant/home-assistant/pull/559

**Comment by mariusmotea** [comment]
if you start the HueEmulator3.py script manually you will see what home assistant sent. If if send "ct" values then the issue is on our side, if not on homeassistant side. I personally don't believe home assistant sent the CT values.

**Comment by wasp100** [comment]
I am not using the hue emulator component in home assistant. I am using the Philips hue component...
https://www.home-assistant.io/components/hue/
How do I verify if the ct values are sent/received?

**Comment by cheesemarathon** [comment]
Follow the instructions [here](https://diyhue.readthedocs.io/en/latest/AddFuncts/debug.html) to enable debug mode. Then, using home assistant, change the color of the bulb. Then just paste the output of debug mode here.

**Comment by wasp100** [comment]
I think I may have figured it out...
in the config.json file, the Generic_**SK6812**_Strip shows up as:

            "swversion": "1.46.13_r26312",
            "type": "Color light",

I think that's why it's not exposing the ct values to HA.

Should it not be **"type": "Extended color light", ???**

How do I change this on my side to test if this works? I tried editing the config.json file, but it made the light non responsive.

**Comment by wasp100** [comment]
@mariusmotea 
In HA, attributes for Hue SK6812 Light when scene is set to "read": (There are no CT values sent for this scene)
```
brightness: 254
supported_features: 61
effect_list: colorloop,random
effect: none
friendly_name: Hue strip
```


When scene is set to "tropical twilight":
```
brightness: 123
rgb_color: 255,159,77
effect: none
supported_features: 61
effect_list: colorloop,random
xy_color: 0.542,0.385
hs_color: 27.458,69.412
friendly_name: Hue strip
```

**Comment by mariusmotea** [comment]
Tropical twilight is a color scene. Ct scenes are: Read, Relax, Bright, Energize...

**Comment by mariusmotea** [comment]
You can change in config.json but find a modelid that really use extended light color.

**Comment by wasp100** [comment]
@mariusmotea
Which one would you recommend I test with?
As I said before, editing the config file made the light unresponsive. 
What the best way to go about this? Re-flash the esp with a different Arduino code? If so, which one?

**Comment by mariusmotea** [comment]
Stop hue-emulator service before any changes in config.json. Put light modelid `LCT001` and type `Extended color light`. This must fix the issue

**Comment by wasp100** [comment]
@mariusmotea 
It works! Thanks... Can you incorporate this change in your code?

Now when a scene is set to "read", in HA:
```
friendly_name: Hue strip
brightness: 254
supported_features: 63
effect_list: colorloop,random
effect: none
color_temp: 346
min_mireds: 153
max_mireds: 500
```

When scene is set to "tropical twilight":
```
friendly_name: Hue strip
brightness: 123
supported_features: 63
rgb_color: 201,167,255
effect: none
min_mireds: 153
effect_list: colorloop,random
xy_color: 0.291,0.225
max_mireds: 500
hs_color: 263.448,34.118
```

Thanks again for the awesome code.

**Comment by mariusmotea** [comment]
there is one issue, in the past we emulated the modelid `LCT001` but somebody discovered that we have a big lack of colors that can be simply solved by replacing the modelid with another one. Hue App is tuned for Philips bulbs.

**Comment by wasp100** [comment]
@mariusmotea
Is there no way that you can change the characteristics of the LST002 to be an extended color light?

**Comment by mariusmotea** [comment]
LST002 is hue strip with no CT leds. But looking now to the code, the previews bulb is extended color light so i suppose here is an issue with Home Assistant.

Default Hue Emulator light values:
```
"LCT015": {"state": {"on": False, "bri": 200, "hue": 0, "sat": 0, "xy": [0.0, 0.0], "ct": 461, "alert": "none", "effect": "none", "colormode": "ct", "reachable": True}, "type": "Extended color light", "swversion": "1.46.13_r26312"}, 
            "LST002": {"state": {"on": False, "bri": 200, "hue": 0, "sat": 0, "xy": [0.0, 0.0], "ct": 461, "alert": "none", "effect": "none", "colormode": "ct", "reachable": True}, "type": "Color light", "swversion": "1.46.13_r26312"},

```
