### ISSUE TITLE
Hue App says No Bridge Found. 

### ISSUE THREAD

**Issue by Talha771** [diyhue/diyHue#994]
### Issue does not already exist?

I have searched and found no existing issue

### Select Environment

Docker

### Home Assistant related?

No

### Description

I have diyhue, and everything works fine and dandy, when I try to add the bridge in the official app, without logging into the phillips hue account, it recognizes the bridge, connects and everything works perfectly. However, when I login to a phillips hue account and add the bridge, it finds the bridge, and as soon as I connect the bridge, it then reverts and then says, no bridge found. 

The Hue Essential app works perfectly 

### Errorlog:

N/A 

### Steps to reproduce

Login to phillips hue account in app and then try to pair

### Please enter your operating system details here

Ubuntu 20.04 LTS, Docker 

### What DiyHue version(branch) are you using?

master (latest)

**Comment by mariusmotea** [comment]
Since this is not a genuine bridge you cannot use any cloud service. Is like you have an offline bridge.

**Comment by Talha771** [comment]
Okay, that makes sense. Closing this now.
